### ISSUE TITLE
Get AI assistance for auto insights - "ASK COPILOT" Option not available

### ISSUE THREAD

**Issue by kcodeg123** [MicrosoftDocs/visualstudio-docs#10136]
In this section, https://learn.microsoft.com/en-us/visualstudio/debugger/debug-with-copilot?view=vs-2022#get-ai-assistance-for-auto-insights, the "Ask Copilot" button is not available by default. I have GitHub Copilot enabled and have been using it a lot so there's no issue with the GitHub Copilot extension on Visual Studio 2022 itself. However, I believe there needs to be some additional activation step for this to appear? Otherwise not sure if there is a bug.

Current:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/3813135/07b0c696-594f-48b9-8460-603047df201d)

Expected:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/3813135/b922a9bc-3bd3-4a66-a99d-460feff899cd)

**Comment by Mikejo5000** [comment]
@kcodeg123 A couple questions: Do you have the [Copilot Chat extension](https://learn.microsoft.com/en-us/visualstudio/ide/visual-studio-github-copilot-chat?view=vs-2022#install-the-visual-studio-extension) installed as well as Copilot? Are you seeing any insights show up in the Top Insights view? If the profiler doesn't report any Top Insights in the report, you won't see the Ask Copilot button to help with insights.

**Comment by Mikejo5000** [comment]
@kcodeg123 If the issue is not one of the issues I mentioned previously, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
