### ISSUE TITLE
"証明書フォルダ－" on localized document 

### ISSUE THREAD

**Issue by mutsun** [MicrosoftDocs/visualstudio-docs#102]
"証明書フォルダー” should be "certificates フォルダー" because this word identify the folder which contain certificate files that are downloading to local folder when user creates offline-installation image with "--layout" option. 

https://docs.microsoft.com/ja-jp/visualstudio/install/create-an-offline-installation-of-visual-studio 

1.証明書をインストールします (これらはレイアウト フォルダーの証明書フォルダーにあります。 インストールするには、それぞれを単に右クリックします)。

Expected:
1.証明書をインストールします (これらはレイアウト フォルダーの certificates フォルダーにあります。 インストールするには、それぞれを単に右クリックします)。

**Comment by ghogen** [comment]
@nokura Nobuko, can you check this?

**Comment by gewarren** [comment]
@mutsun thank you for reporting this, and sorry for the delay. Hopefully our localization team can look at this soon.

**Comment by gewarren** [comment]
@nokura or @CeciAc could one of you take a look at this? Should it be moved to the Japanese repo's issues page?

**Comment by CeciAc** [comment]
Hello, @mutsun,

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/39

Kind regards,
Microsoft DOCS International Team

@gewarren #please-close this issue

**Comment by gewarren** [comment]
@CeciAc Thank you so much for moving the issue. I'm sure it will get more attention over there.
