### ISSUE TITLE
Create an Offline Installer for Visual Studio for Mac - Visual Studio for Mac

### ISSUE THREAD

**Issue by oopsaleem** [MicrosoftDocs/visualstudio-docs#1024]
and lovely VS is available for mac os. What a surprise!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd139e6-bbd6-4c1a-1b40-5abd63031a9a
* Version Independent ID: bc91c619-c340-40e6-9c55-8c496eb24da5
* Content: [Create an Offline Installer for Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-offline-installer)
* Content Source: [mac/create-offline-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-offline-installer.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by oopsaleem** [comment]
Not a big deal.

**Comment by built2order** [comment]
+1

**Comment by gyk** [comment]
It's not difficult to make the offline installer yourself: <https://developercommunity.visualstudio.com/comments/519542/view.html>.

For those who cannot install due to poor Internet connection: Just launch the installer, open `/Users/$USER/Library/Caches/VisualStudioInstaller/downloads/InstallationManifest.json`, you will see the metadata of each package and can download them respectively. The only exception is Android SDK, the components of which are listed in `/Users/$USER/Library/Caches/VisualStudioInstaller/downloads/xamarin-manifest.xml`. You basically need the following to complete the installation
(taking VS for Mac 8.4.6.36 as an example):

- 3534162-studio.sdk-patcher.zip
- build-tools_r28.0.3-macosx.zip
- emulator-darwin-5889189.zip
- platform-28_r06.zip
- platform-tools_r29.0.4-darwin.zip
- sdk-tools-darwin-4333796.zip

On my network the official installer could download at < 30 kB/s, and the timeout error kept occurring so it seemingly took forever to finish. In contrast, each file can be downloaded directly at 5 MB/s. Please don't tell me it was developed in VS for Mac itself :P
