### ISSUE TITLE
Decompiler engine

### ISSUE THREAD

**Issue by rolandh** [MicrosoftDocs/visualstudio-docs#1050]
How does this compare to DotPeek etc? What are the advantages and disadvantages? It appears it uses ILSpy like the others on the market.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f28ec7e-9069-4d36-632c-e195e7f6b21b
* Version Independent ID: ebe0a750-17c5-dfa7-f0c2-b35ebfdd45f6
* Content: [Viewing type definitions in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/go-to-and-peek-definition#feedback)
* Content Source: [docs/ide/go-to-and-peek-definition.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/go-to-and-peek-definition.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@rolandh I assume you're talking about the View metadata as source feature? @kuhlenh can you answer Roland's questions? Thanks!

**Comment by TerryGLee** [comment]
Thanks for your question. We appreciate your interest in Visual Studio. 

Because this venue is meant specifically for documentation feedback, your question might best be asked in one of the following venues, instead:​

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

(Also, we apologize for the delay in responding to your inquiry.)

Thanks,
~ Terry

**Comment by rolandh** [comment]
How is this not documentation feedback? The documentation could be improved to explain this.

**Comment by AliBayatGH** [comment]
When I then look at  the decompiled source for any referenced class in the .NET framework, all I can see for every method's body is throw null
