### ISSUE TITLE
mr 

### ISSUE THREAD

**Issue by steveowen** [MicrosoftDocs/visualstudio-docs#1076]
Not an error just a wish list asks
Just a note to say it would be amazing to have a visual designer for Xamarin cross platform apps like the Xamarin android designer and of course the amazing windows universal app designer .  I had to go to Xamarin android designer to position buttons on my android phone app.
so I have to go to the windows designer for my universal apps. would be good to have  a cross platform visual button designer.

And last wish please please please could you add a colour fill routine for canvas apps  like the old ExtFloodFill in mfc
to fill boundary of lines with a color.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to report a problem with Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@steveowen It looks like you have a product feature request rather than an issue with documentation. To that end, this venue isn't the correct place for such requests. Instead, please share your product feature requests and suggestions with us on [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide).

As an FYI, these alternative means of contacting us are documented in the "Reporting alternatives" section of the [How to report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#reporting-alternatives-a-namealternatereportinga) page, and in the "I want to make a suggestion about Visual Studio features" section of the [Talk to us](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us#i-want-to-make-a-suggestion-about-visual-studio-features) page.

Thanks,
~ Terry
