### ISSUE TITLE
There are no screenshots showing examples of the different kinds of extension points

### ISSUE THREAD

**Issue by tg73** [MicrosoftDocs/visualstudio-docs#1099]
Generally in this section it would be helpful to have more screenshot examples of the different extension points. It would be great to have a couple of overview screenshots annotated to identify those extension points that have visible effect. Right now I'm trying to find out how to add to the codelens stuff above a method signature, and it's quite hard to work out what kind of extension point this is without visual examples.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2529758f-dcd8-bd40-2030-206d9e96e2fc
* Version Independent ID: 2cf819fd-ffba-3f3a-3fa3-5c730918c179
* Content: [Extending the Editor and Language Services - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/extensibility/extending-the-editor-and-language-services)
* Content Source: [docs/extensibility/extending-the-editor-and-language-services.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-the-editor-and-language-services.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
