### ISSUE TITLE
needs proof-reading

### ISSUE THREAD

**Issue by odyxanthi** [MicrosoftDocs/visualstudio-docs#1157]
It looks like this tutorial needs proof-reading. There seem to be gaps in the instruction.

E.g. it says "In the FirstToolWindowCommand class, add the following code at the end of the ShowToolWindow() method. "   but when wast this method defined in the first place?

Also it suggests adding a button handler method 
"private void ButtonHandler(object sender, EventArgs arguments)" but how it is invoked?

I have done all steps required but I only get a gui with some dummy search button that doesn't do anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554db2bb-c0c2-d694-be77-44cb0fd311f8
* Version Independent ID: e7a691ea-7540-f6c4-46e4-66abdbd07c37
* Content: [Adding a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window)
* Content Source: [docs/extensibility/adding-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-tool-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by CmdrBeavis** [comment]
Agreed! Thankfully, we get the two methods that haven't been created yet [when we're told to change or add them] later in the text.  Weird.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by odalet** [comment]
It's been 4y since the initial issue and 2y since the last reply... Any chance the documentation will be updated? If not, it may be better to have it completely removed as it's useless at the moment!
