### ISSUE TITLE
Managing security

### ISSUE THREAD

**Issue by xenalite** [MicrosoftDocs/visualstudio-docs#1165]
A number of undesirable AAD identities have access to add / edit our cloud subscriptions.
I looked at subscription security. No identities have User Access Administrator role assigned, and yet they have access.
One identity is a Reader only on the subscription. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ff3400-d8b9-eeaa-c785-3859c0b8e40e
* Version Independent ID: e01d9d35-733c-d892-e1e8-19e5f2553ebf
* Content: [Setting Up Administrators for Cloud Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/cloud-admin)
* Content Source: [subscriptions/cloud-admin.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/cloud-admin.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@xenalite Thanks for your feedback; @evanwindom @lankaim FYI.

**Comment by TerryGLee** [comment]
@prrana FYI on this.

**Comment by Juanpanaya** [comment]
Hello @xenalite 

Thank you for submitting this and I'll be more than glad to assist.

For future cases, quickest way to contact support is to create a support ticket via the following link: 

- https://visualstudio.microsoft.com/subscriptions/support/

From my understanding, users which do not have administrator roles are still able to add/edit your purchased cloud subscriptions. In order to provide you with an accurate response and solution to your issue please provide me with the following information: 

- Example of users which have no User Access Administrator role assigned, and yet have access to manage the Cloud subscription.
- Cloud subscription GUID.

We'll need this to further investigate and please, feel free to add additional information that may be helpful.

Thanks,

**Juan Anaya**
**Visual Studio Subscriptions Tier 3 Support
Microsoft**

**Comment by xenalite** [comment]
@Juanpanaya 
Cloud subscription GUID: 3ab753c1-6a9b-4b5e-8a53-b2591fb06b80
Non-Admin user UPN: oskar.mamrzynski@towerswatson.com

**Comment by Juanpanaya** [comment]
Hello, @xenalite 

Thank you for the response. 

In this case after further investigation, I am able to see the email you provided as one of the emails that can manage the cloud subscription within the Manage portal. 

In order to provide you with a better context as to why the user may be able the manage the subscription is due to one of the following reasons: 

- The user has admin rights in the Azure subscription used to purchase the cloud subscriptions, this will make him have admin rights in the cloud subscriptions.
- The user has a owner, contributor, service admin, or co-admin role within the Azure subscription.

If you'd like to learn more about the roles, please visit: 

- https://docs.microsoft.com/vsts/billing/add-backup-billing-managers?view=vsts

Thanks,

**Juan Anaya
Visual Studio Subscriptions Tier 3 Support
Microsoft**

**Comment by Juanpanaya** [comment]
Hello, @xenalite 

Thank you for the response.

In regards to this case, please create a ticket with the Azure support team as they can further assist with the feedback you provided.

In order to create a ticket with them, please follow the next link: 

- https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview 

Kind regards,

Juan Anaya
Visual Studio Subscriptions Tier 3 Support
Microsoft
