### ISSUE TITLE
SolutionFolder

### ISSUE THREAD

**Issue by habibcs** [MicrosoftDocs/visualstudio-docs#1179]
I want to add custom items inside a solution folder created inside a solution - meaning I do not wish to add projects but some other usual directory with certain files.
Or say, I want to add a .nuget solution level folder which should also be present in the directory structure.
How to do that? It should have been specified on this page too, I suppose.

Thanks, Habib

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b16f65fa-87db-b0da-e314-609f32229cea
* Version Independent ID: 6ba5748d-af76-75fe-d341-f8edc9f27280
* Content: [SolutionFolder Element (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/solutionfolder-element-visual-studio-templates)
* Content Source: [docs/extensibility/solutionfolder-element-visual-studio-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/solutionfolder-element-visual-studio-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Have you tried a Miscellaneous Files project?

https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/miscellaneous-files-project?view=vs-2019

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
