### ISSUE TITLE
Map of images/icons to their image IDs?

### ISSUE THREAD

**Issue by tgriff** [MicrosoftDocs/visualstudio-docs#1184]
I wish there was a map of images/icons to their image IDs so I can easily find the ID for the image/icon I want rather than having to do some trial and error until I find the right ID. If there is such a map, put a link to it on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c747e6f-61b3-430c-3432-133febdfbe37
* Version Independent ID: 8e44ba72-b136-7e9c-0ee0-1fb49fcfa6da
* Content: [Image Service and Catalog - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/image-service-and-catalog)
* Content Source: [docs/extensibility/image-service-and-catalog.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/image-service-and-catalog.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by madskristensen** [comment]
You can see the list of images on http://glyphlist.azurewebsites.net/knownmonikers/ and get the [KnownMonikers Explorer](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.KnownMonikersExplorer) extension for an in-VS experience with added features

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
