### ISSUE TITLE
How can I link my VS Enterprise subscriber account to a local AD user?

### ISSUE THREAD

**Issue by nde-agridea** [MicrosoftDocs/visualstudio-docs#1195]
This article explains how to add an alternate account to a VS subscription, but only Azure AD is supported. How can I do the same with a local AD ? This is needed so that I can add more concurrent pipelines to my on premise TFS (one per Entreprise subscription as explained in this article https://docs.microsoft.com/en-us/vsts/pipelines/licensing/concurrent-pipelines-tfs?view=tfs-2018&viewFallbackFrom=vsts)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e967e1-0b8e-a6b5-13ef-bd206ca6d13a
* Version Independent ID: 612623f5-6252-6353-8c7c-c1be43bd8801
* Content: [Identities for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity?view=vsts)
* Content Source: [subscriptions/vs-alternate-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-alternate-identity.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@evanwindom @lankain FYI. Is this something we can clarify further in the documentation?

**Comment by evanwindom** [comment]
@nde-agridea Thanks for reaching out.  An alternate identity provides a way to sign in to a your subscription with two different identities, but it doesn't duplicate or expand any of the benefits.  If your subscription allows you one pipeline, for example, using an alternate identity doesn't not provide an opportunity to use additional pipelines since that is dependent on the subscription, and not the identity.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for answering the inquiry. I'll close this issue, in that what's being asked for is a scenario that's not supported.
