### ISSUE TITLE
Conflicts between different versions of Microsoft.CSharp

### ISSUE THREAD

**Issue by Conway-Tse** [MicrosoftDocs/visualstudio-docs#1196]
Using Visual Studio 2017. Build fails with message: 
Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved. 
It happens after step 8 of Write shared data service code in Learn app-building basics with Xamarin.Forms in Visual Studio.
I have tried to install all the version available, the results are:
version 4.0.0 The package may not be fully compatible with the project.
Other version: warning MSB3277: Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved. 
I should appreciate your help to find out why.

**Comment by gewarren** [comment]
@Conway-Tse Sorry that you are seeing that error. This issues page is not meant for product issues, it's for documentation issues. The best way to get help with your issue is to report the problem through VS, where it will be logged to Developer Community. See https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017.

**Comment by Conway-Tse** [comment]
@gewarren Thanks a lot for pointing me to the right place.
