### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by Stephan500** [MicrosoftDocs/visualstudio-docs#1210]
I just had a lot of headache about custom templates. It seems that the export of templates in VS 2017 does not create this tag. And if it is missing no files are created. So the default is obviously not "true".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1184788d-0428-d0df-fe5b-5fd3b482773e
* Version Independent ID: 691fc116-3713-3fba-72a4-afec1a2d79dc
* Content: [CreateInPlace (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/createinplace-visual-studio-templates)
* Content Source: [docs/extensibility/createinplace-visual-studio-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/createinplace-visual-studio-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
