### ISSUE TITLE
Sample command line invocation

### ISSUE THREAD

**Issue by fbrier** [MicrosoftDocs/visualstudio-docs#1216]
Because the CreatePkgDef utility is invoked by the VSiX compiler as part of the build process, no examples seem to exist on the Internet. There are several articles or blog posts that mention the CreatePkgDef utility, none have an example of it being invoked from a command window. As Visual Studio is reporting, "The specified task executable "CreatePkgDef.exe" could not be run. Access is denied", I was attempting to reproduce the error on a command line and perhaps determine the source of the problem. It works fine on Windows 10, but not on Windows 7. However, the rejects the /out: parameter with the message, "CreatePkgDef : error : ArgumentException: Invalid Parameter 'out:dummy.pkgdef'" I 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6453dc4e-0412-8550-a459-65c99a67526e
* Version Independent ID: b18674ec-3c78-d05b-b4cf-7a11d1f887ff
* Content: [CreatePkgDef Utility - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/createpkgdef-utility)
* Content Source: [docs/extensibility/internals/createpkgdef-utility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/createpkgdef-utility.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
