### ISSUE TITLE
Document the new terms added in 15.x timeframe

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#1219]
This page is missing some of the new terms that were added in 15.x timeframes:

```
ActiveProjectOutputType
ActiveProjectBuildProperty
SolutionHasProjectBuildProperty
ProjectAddedItem
```

Also, it would be helpful with more examples of expressions - both as values of the terms, and usage within the "expression" argument. For example, it's not clear that you can write the following expression:

```
CSharpProjectContext & !(NETCore | NETStandard)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9786c88-8bd3-8d62-5132-743e44b41dda
* Version Independent ID: 0bd057a1-b51c-b617-ca99-3979b4729f26
* Content: [How to: Use Rule-based UI Context for Visual Studio Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions)
* Content Source: [docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@madskristensen Do you want to take a look at this feedback?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
