### ISSUE TITLE
Qualify GetService() call

### ISSUE THREAD

**Issue by solvingj** [MicrosoftDocs/visualstudio-docs#1277]
It's not clear where GetService() comes from.  Snippit could provide the necessary using statement, or make it a fully qualified function call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72794642-353e-46e5-c822-f471b5ef65b4
* Version Independent ID: 391aac5d-2695-9344-828e-8d5e8b9a334b
* Content: [How to: Use the Activity Log - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log)
* Content Source: [docs/extensibility/how-to-use-the-activity-log.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-the-activity-log.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
