### ISSUE TITLE
Inconsistent page title between content and the title on the TOC section (on the left)

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/visualstudio-docs#1290]
The page title on the content is "Visual Studio 2017 build numbers and release dates", but the title on the left TOC is "Visual Studio 2017 build numbers and release dates".
Based on the actual TOC on the left, I assume that _I expect to get_ or I will get the list of Visual Studio build numbers and release dates, not just Visual Studio 2017. But the actual content has this title: "Visual Studio 2017 build numbers and release dates".

Please confirm that this is intentional or not. It is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio 2017 build numbers and release dates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates#feedback)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by eriawan** [comment]
This is the follow up screen capture:

![image](https://user-images.githubusercontent.com/8773147/43187116-d4395f8a-901a-11e8-9edb-4adc2b5fb1e1.png)

**Comment by TerryGLee** [comment]
@eriawan Thanks for your inquiry! This is by design. We purposefully shorten titles in the TOC and then add more detail to the page names. We do this for several reasons: 
1) Everything in the TOC refers to the most current version of Visual Studio (unless it's labeled specifically as belonging to a previous version) so there is no need to include the version number, 
2) We want the shortest labels as possible in the TOC so that the TOC is not unwieldy to view in different form factors (i.e. a cell phone, for example), and, 
3) Our research shows that more people use a search engine to find our content than they do our TOC, so we add more detail to our titles so that a search engine can more effectively present correct results from customer search queries.
Again, thanks for your inquiry; we appreciate your taking the time to provide us with feedback. 
~ Terry

**Comment by TerryGLee** [comment]
I'd like to add also that [Visual Studio 2017 build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates)  was a new page idea for Visual Studio 2017, and we do not typically add new pages for previous versions.
