### ISSUE TITLE
Using R.net with C# from Visual Studio error The program '[11012] tryR.exe' has exited with code 2 (0x2). 

### ISSUE THREAD

**Issue by sessler** [MicrosoftDocs/visualstudio-docs#1301]
I have Visual Studio 2017, RdotNet version v4.0.30319, R version 3.4.1

Tried to create the example program:

using RDotNet;
namespace tryR
{
    class Program
    {
        static void Main(string[] args)
        {
            string result;
            string input;
            REngine engine;
            REngine.SetEnvironmentVariables(rPath:"P:\\Program Files\\R-3.4.1\\bin\\i386", rHome:"P:\\Program Files\\R-3.4.1");
            engine = REngine.GetInstance();
            engine.Initialize();

            //input
            Console.WriteLine("Please enter the calculation");
            input = Console.ReadLine();

            //calculate
            CharacterVector vector = engine.Evaluate(input).AsCharacter();
            result = vector[0];

            //clean up
            engine.Dispose();

            //output
            Console.WriteLine("");
            Console.WriteLine("Result: '{0}'", result);
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }
    }
}
 and when running the code, I got the error message: The program '[11012] tryR.exe' has exited with code 2 (0x2). when executing the REngine.GetInstance(); statement

(I tried to launch R from the above directory and it started correctly).

Thanks for any advice

**Comment by kraigb** [comment]
@sessler It looks like your issue is with R.NET specifically, and not Visual Studio or the R Tools for Visual Studio (RTVS) (and especially not the documentation for VS/RTVS, which is what the present repo is for). 

I suggest you should pursue the matter through https://github.com/jmp75/rdotnet/issues. If you think it is an RTVS issue specifically, then use https://github.com/Microsoft/rtvs/issues. In the meantime, I'm closing the issue here in the docs repo.
