### ISSUE TITLE
Our company's internet firewall blocked us from install Visual Studio using web installer 

### ISSUE THREAD

**Issue by longtth** [MicrosoftDocs/visualstudio-docs#1324]
Our company (and many others) has firewall that block massively downloaded files, and it's very hard to get Visual Studio downloaded and install to PC, 
It would be very nice for us to have a simple ISO that we could request IT Dept to download, save on server and we only need to copy down, then install. 
Please consider bring ISO back!
Many thanks.

**Comment by TerryGLee** [comment]
@longtth Thanks for your feedback. We do have a page that might help you mitigate firewall issues: [Install and use Visual Studio and Azure Services behind a firewall or proxy server](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server). 

As for providing an ISO, we do not do so for the following reasons:

1. Visual Studio 2017 is a huge product that supports many types of development: from Android to UWP to C++ to Unity to Linux. If we were to still offer a 'full' install, it would come in at over 50GB. That's one huge ISO image!
1. We surveyed hundreds of people during the previews and RCs, and people told us that they had historically used an ISO for two reasons:
(i) because they wanted to download once and create a network install for enterprise deployment;
(ii) because they had a shaky internet connection and wanted to be sure they'd downloaded successfully before installing. A single monolithic ISO isn't the best solution for either of those scenarios - it's just the one that people are habituated to over all these years.
1. For the former (enterprise deployment), we have a full administrators' guide that provides detailed guidance on how to deploy the product: https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-administrator-guide. This includes PowerShell scripts, examples of using the installer to create and update a network cache, descriptions of how to deploy Visual Studio in a fully offline environment, and so on.
1. For the latter, we've worked really hard to improve the robustness of the installer. The componentization work we've done means that the smallest install is one-tenth the size of Visual Studio 2015, making it far more likely to succeed. And other typical installs are smaller too. We download VS in small packages that are more likely to succeed, and we use multiple ways (WebClient, BITS, WinInet) to download those files to minimize problems with AV and proxy software. If you want to download first then install, you can cache the components locally and then install from there.
1. Because of the nature of our product (rapidly updating, lots of third-party components), an ISO is problematic. We don't have the rights to redistribute several large components (including Android), and others update on a rapid cadence that often includes critical security fixes, meaning an ISO image is incomplete, often outdated, and potentially not secure.
