### ISSUE TITLE
.requiredModifiers does not specify behavior of multiple values

### ISSUE THREAD

**Issue by henrygab** [MicrosoftDocs/visualstudio-docs#1349]
The document indicates that .requiredModifiers can specify multiple values.  However, it does not indicate which of the following behaviors is followed:

A. It requires ALL the listed modifiers to exist to match
B. It requires AT LEAST ONE OF the listed modifiers to exist to match

The first is expected, but the second is how the .applicable_accessibilities aspect is handled.  Can you clarify the documentation here?

Thanks you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kendrahavens Can you clarify how multiple required modifiers are used in a naming convention?

**Comment by kendrahavens** [comment]
I'm not sure on this one. Asking @sharwell

**Comment by sharwell** [comment]
* The **Symbol modifiers** section should be updated to state that a naming rule will only match signatures that have _all_ modifiers specified in `required_modifiers`. If this property is omitted, the default is an empty list, meaning there are no specific modifier requirements in order for the rule to apply.
* It does not seem like the **Accessibility levels of symbols** section needs to be updated because symbols can only have one declared accessibility (i.e. it is trivial to infer that a signature will match if _any_ of items in the list match it).

**Comment by tonyhallett** [comment]
Not true. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected
