### ISSUE TITLE
Two additions - Build apps with native UI using Xamarin in Visual Studio

### ISSUE THREAD

**Issue by Babster** [MicrosoftDocs/visualstudio-docs#1377]
Maybe it's worth to add information which can be useful for beginners
1. When you add NuGet packages to your solution, some errors appears across code within the projects' code. For example, LoadApplication(new App()); - Couldn't find App(). Building process returned success, but for novice developers (me) it was a serious issue. After IDE restart all errors disappeared
2. The main issue was: I used to programme WPF solutions so when I press "Start" button the application immediately starts. But for this solution type, it looks like the system completely doesn't work because only the black screen appears. I thought it's because the compiler doesn't load App() class.

p.s. instead of this two issues, everything else works perfect, thanks!

**Comment by gewarren** [comment]
@Babster Thanks for leaving this feedback. Can you let us know which article/tutorial this is in regards to so we can address it?

**Comment by Babster** [comment]
Sure! It's about this tutorial:
https://msdn.microsoft.com/en-us/library/dn879698.aspx

**Comment by gewarren** [comment]
@charlespetzold Charles, can you take a look at these suggestions?

**Comment by gewarren** [comment]
@Babster The MSDN topic has been revised at https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio. You were probably seeing errors in your project because the MSDN topic is out of date. Sorry for the inconvenience this caused you. I'm closing the issue, but if you feel the newer topic needs to be updated, please comment and I'll reopen.
