### ISSUE TITLE
无法打开源文件"stdafx.h"

### ISSUE THREAD

**Issue by gosali** [MicrosoftDocs/visualstudio-docs#1408]
@IamDead commented on [Sat Aug 18 2018](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/32)

按照文中所述步骤创建“C++ Windows 控制台应用程序”后，在编辑代码过程中提示“无法打开源文件"stdafx.h"”，并且默认使用的是“#include "pch.h"”，是文中内容有误还是我需要更改设置？
——VS2017社区版15.8.1

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89847656-bea8-b9a7-a50a-3d7e75e14ff6
* Version Independent ID: 9f6c1029-6d5b-1d41-10dd-65863848c2e5
* Content: [Visual Studio 中的 C++ 入门](https://docs.microsoft.com/zh-cn/visualstudio/ide/getting-started-with-cpp-in-visual-studio)
* Content Source: [docs/ide/getting-started-with-cpp-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/getting-started-with-cpp-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **tglee**

**Comment by gosali** [comment]
Back Translation:
After creating the "C++ Windows Console Application" as described in the article, during the editing process, the message "Unable to open the source file "stdafx.h"" is displayed, and the default is "#include "pch.h"". Is the content in the text incorrect or do I need to change the settings?
——VS2017 Community Edition 15.8.1

Could you please check Documentation?

Microsoft DOCS International Team

**Comment by IamDead** [comment]
OK, i find it, : [https://msdn.microsoft.com/en-us/library/hh419385.aspx?f=255&MSPPError=-2147217396#projectRef](url) following the "To link the tests to the object or library files" instructions

**Comment by gewarren** [comment]
@corob-msft Do we need to update this topic a bit?

**Comment by corob-msft** [comment]
@gewarren Yes, several of the new project templates changed with 15.8, and the name of the precompiled header was one of the things changed in this one.

**Comment by BCSZhang** [comment]
@corob-msft You mean "pch.h" plays the same role as "stdafx.h" ? So with "pch.h" I do not need "stdafx.h" anymore? And what is the difference between "stdafx.h" and "pch.h" ? Thank you!

**Comment by corob-msft** [comment]
@BCSZhang The precompiled header file name is arbitrary; it can have any name you like. For many years, the new project templates have used the name "stdafx.h". The precompiled header option was first used by MFC, which was code-named "afx" internally, so the header was named "stdafx". Ever since then, the name has been confusing people. Some of the new project templates in VS 2017 version 15.8 now use "pch.h" because it's easier to understand that it means "precompiled header". In Visual Studio, you can change the name in the project's **Property Pages** dialog. Open **Configuration Properties** > **C/C++** > **Precompiled Headers** and change the name in the **Precompiled Header File** property.

**Comment by BCSZhang** [comment]
@corob-msft Thank you very much for your relpy. It does great help to me!
