### ISSUE TITLE
Offline installation fails

### ISSUE THREAD

**Issue by Tieho** [MicrosoftDocs/visualstudio-docs#1413]
I downloaded everything to a local cache with the layout command, and then tried to install VS2017 15.8.1 in an offline environment. First of all the instructions to install certificates for 15.8 Preview 2 or later are wrong, because the certificate filenames found in the local cache do not match the instructions. I installed the three certificates found in the 'certificates' folder.

Then when I try to update my previous VS2017 installation to 15.8.1, I get an download error of file: https://download.visualstudio.microsoft.com/download/pr/e2f7e3f3-3e44-43b6-a79e-7c2c44aefb3c/5cb3e0df23808182a154f0ad2e3d0d69/payload.vsix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Tieho Thanks for your feedback. We'll take a look at the page content. Meanwhile, please file a bug directly though the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool. And FYI, we also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues.

**Comment by tydunkel** [comment]
@Tieho Thank you for your feedback. As Terry suggested, providing feedback through the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool is the best way to resolve issues like this. That will allow us to privately collect file logs to diagnose the issue.

In the meantime, have you verified that everything you are trying to install exists in the offline layout? You can run the [--verify](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-verify-a-layout) option to verify the layout is correct. If anything is missing, it can be fixed by the [--fix](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-fix-a-layout) command.
