### ISSUE TITLE
How to access from UI?

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/visualstudio-docs#1415]
Maybe there should be a See Also section linking to the Visual Studio users guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43077cf8-4083-61bb-a86c-f13cb2701b4d
* Version Independent ID: b5a3c4c8-0bec-bd1f-852d-afb7e192340f
* Content: [Workspaces in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/workspaces)
* Content Source: [docs/extensibility/workspaces.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/workspaces.md)
* Product: **visual-studio-dev15**
* GitHub Login: @vukelich
* Microsoft Alias: **svukel**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
