### ISSUE TITLE
Electron (Atom Shell)

### ISSUE THREAD

**Issue by JimmyMac6996** [MicrosoftDocs/visualstudio-docs#1420]
Can CodedUI be used to test an Electron Application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30d3429-0f9c-c67f-62d2-806f366aaccb
* Version Independent ID: 5f44a758-23cc-d3e7-e523-dc9c1d85c5fd
* Content: [Configurations and Platforms for Coded UI Tests in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/supported-configurations-and-platforms-for-coded-ui-tests-and-action-recordings)
* Content Source: [docs/test/supported-configurations-and-platforms-for-coded-ui-tests-and-action-recordings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/supported-configurations-and-platforms-for-coded-ui-tests-and-action-recordings.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PBoraMSFT Can you answer this?

**Comment by PBoraMSFT** [comment]
@JimmyMac6996 - No, Coded UI cannot be used for testing Electron based apps. The supported apps and technologies is mentioned in the doc you refered to above.
Please also note that we have deprecated Coded UI and VS 2019 will be the last release - https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#test-tools 

We do not recommend that any new customers onboard Coded UI.

@gewarren - can you please close the issue? I don't seem to have the permissions for that.

**Comment by gewarren** [comment]
@ypinhas Since this issue is closed, could you open a new issue with your question? Thanks.

**Comment by PBoraMSFT** [comment]
@ypinhas - I have already responded to your email. 
Including the same information here for anyone else that may have a similar question:


While no new features will be added given that we are deprecating, Coded UI test in VS 2019 will continue to be supported for any issues that may arise during the support lifecycle of the product. Please refer the product lifecycle and servicing docs – VS releases are supported for 5 years (mainstream) + 5 years (extended support).

Different Visual Studio versions can be installed side by side. This means that developers can continue to use VS 2019 to maintain any existing Coded UI test assets, while being able to use the new VS version when it becomes available in the future for other development needs. 
The same side-by-side installation on Pipeline agents allows for CI/CD pipelines to run smoothly without any interruptions. This is because when Coded UI tests run as part of a CI/CD pipeline in the Azure DevOps Server (or the Azure DevOps service), tests are run against a particular VS version installed on the agent machine/VM or a particular version of test platform. We will continue to support running tests against VS 2019 or its associated test platform in newer versions of Azure DevOps Server until the support life cycle of VS 2019 ends. This means that you do not need to maintain two different Azure DevOps server (TFS) versions to be able to keep existing Coded UI tests running.
