### ISSUE TITLE
Systems Engineer

### ISSUE THREAD

**Issue by DRussell555** [MicrosoftDocs/visualstudio-docs#1423]
Hi, although this document covers 32/64 bit Office applications, it fails to describe settings for 64/32 Bit Operating Systems. It is also very dated in that it describes a Hotfix for Office 2007 which is irrelevant given the document was supposedly created in 2017. I think it is important that dates are included so readers ascertain the relevance of the information provided. Not mentioning the Registry differences for the 64/32 bit OS is just plain dumb. Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c26ff2bd-2b95-2a91-2479-69fc63c07239
* Version Independent ID: 738a7001-8809-4bbf-73fa-8c45ab56534a
* Content: [Registry entries for VSTO Add-ins - Visual Studio](https://docs.microsoft.com/en-nz/visualstudio/vsto/registry-entries-for-vsto-add-ins)
* Content Source: [docs/vsto/registry-entries-for-vsto-add-ins.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/registry-entries-for-vsto-add-ins.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@DRussell555 Thanks for your feedback! Yes, we're aware that this page needs updating. It's on our backlog to fix.

**Comment by John-Hart** [comment]
@DRussell555 the article does mention the Wow6432Node for 64bit OS's.  It's not clear to what you believe is missing. Could you please give an example?  The article may have been written a while ago but the article should still be relevant.

**Comment by danielstefanescu** [comment]
@DRussell555 Any updates?

**Comment by hm442** [comment]
Hi,

IMHO the information of the registry entries is incomplete because there are 3 and not just 2 cases and wrong because the Configuration Path is mixed up. I guess it should be like this:

1. OS version 32 bit + Office version 32 bit: Root\Software\Microsoft\Office\application name\Addins\add-in ID
2. OS version 64 bit + Office version 32 bit: Root\Software\Wow6432Node\Microsoft\Office\application name\Addins\add-in ID
3. OS version 64 bit + Office version 64 bit: Root\Software\Microsoft\Office\application name\Addins\add-in ID

The same for Visio accordingly.

Please verify and correct when indicated,
Thank you

**Comment by John-Hart** [comment]
The document has been updated to mention installing on 64-Bit Windows Thanks for the feedback.
