### ISSUE TITLE
error CS1061: 'IAsyncServiceProvider' does not contain a definition for 'GetService' ...

### ISSUE THREAD

**Issue by CmdrBeavis** [MicrosoftDocs/visualstudio-docs#1470]
So, I followed the above instructions to the letter, well, except where I had to jump ahead and get the `ShowToolWindow()` code, which did not get created when the project was initially spun up, nor were we given any code for said method above the point at which we were told to change it, and I'm getting the following exception:

FirstToolWindowCommand.cs(124,35,124,45): error CS1061: 'IAsyncServiceProvider' does not contain a definition for 'GetService' and no accessible extension method 'GetService' accepting a first argument of type 'IAsyncServiceProvider' could be found (are you missing a using directive or an assembly reference?)

Now, I'd love to try and fix this myself, but since I'm taking a tutorial and all, and thus don't yet know how these things work, that would be difficult at best. :(  

-sigh-

Any help appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554db2bb-c0c2-d694-be77-44cb0fd311f8
* Version Independent ID: e7a691ea-7540-f6c4-46e4-66abdbd07c37
* Content: [Adding a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window?view=vs-2017)
* Content Source: [docs/extensibility/adding-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-tool-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by tpatel11** [comment]
If you look at the property called ServiceProvider in your command class, that returns the package of type AsyncPackage. If you want to use the derived version (async version), you can use GetServiceAsync instead of GetService. Reason for your issue is, AsyncPackage implements IAsyncServiceProvider interface and that is being returned as service provider but if you look at class AsyncPackage, it also derives from Package class. This Package class has method called GetService. So, as a solution, you may need to add another property as something like below. You would still be able to use the same package object just casting as the base class type instead of interface type of derived class. Once you have this, you can call GetService method on SVCProvider.

private IServiceProvider SVCProvider
        {
            get
            {
                return this.package;
            }
        }

**Comment by gewarren** [comment]
This is similar to #1277.

**Comment by craigcaseyMSFT** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!
