### ISSUE TITLE
How to debug View code

### ISSUE THREAD

**Issue by andre-ss6** [MicrosoftDocs/visualstudio-docs#1474]
I'm trying to remote debug the code in my _Layout.cshtml file but I get the 'No symbols have been loaded for this document' warning. I'm able to debug normal files just fine. Is this supported? 

I'm using Visual Studio 15.8.1. My app is a ASP.NET Core 2.0 Web app running on Windows Server 2016 under IIS and .Net Core 2.0, using the Visual Studio 2017 Remote Debugger version 15.0.28010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4215ecb-721f-9b0b-66ae-042ffd7c9842
* Version Independent ID: 0d58ec46-8b09-f184-24f3-ac53ac0d1b50
* Content: [Remote Debug ASP.NET Core on a Remote IIS Computer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2017)
* Content Source: [docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
If you run locally instead of on the remote machine, can you hit a breakpoint on the same code in the .cshtml file?

I believe for cshtml you need to debug inside a script block. See this post and let me know if it applies.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/f735dc0d-584c-4872-8458-116fa9611926/debugging-of-cshtml-file-in-vs2013

**Comment by andre-ss6** [comment]
I'm not trying to debug javascript. I was trying to debug C# code inside a View. And yes, I'm able to do that locally, but not remotely.

**Comment by andre-ss6** [comment]
Yes, they are exactly the same version. Please note that I'm fully able to debug .cs files remotely just fine. Only the .cshtml files didn't work. I fear this might not even be supported. The documentation doesn't state nothing about that, however.

**Comment by Mikejo5000** [comment]
I believe it should work, but I will ask about it.

**Comment by andre-ss6** [comment]
I'm not sure you know what I'm talking about... These are not script files. They are view files, which contain plain, old, regular C# code inside them. The only difference is that ASP.NET generates a hidden class to run that code and emits an HTML file upon request.

**Comment by Mikejo5000** [comment]
Yes, sorry, forgot again. I deal with a lot of script docs on a regular basis.

**Comment by Mikejo5000** [comment]
Would you report the issue via Send Feedback link at the top of VS (choose "Report a Problem")? Thanks.

**Comment by neustupa** [comment]
Hello. I am trying to remotely debug an ASP :NET Core 2.1 web application but with no success. I have done everything as mentioned in the article (except the Core version). The problem is I don't see any dotnet.exe processes in the Attach to Process dialog box in Visual Studio. I am using VS 2017 15.8.6, both my computer and the server has .NET Core Runtime 2.1.5 and SDK 2.1.403. The version of remote debugger is 15.0.28010.0 and the server is running on WS 2016 Datacenter Version 1607 (OS Build 14393.693), IIS 10.0.14393.0. Can anyone help me with the problem please?

**Comment by Mikejo5000** [comment]
@neustupa Is the app running on IIS? Make sure that it's running first. In the Attach to Process dialog, check "Show processes from all users", in case its running under a different user account. Make sure the Connection Target is correct also. What do you mean by "except the Core version"?

**Comment by neustupa** [comment]
Hi. Thank you for the response. Yes the the app is running on IIS. I am showing processes from all users. The connection target is correct, I just double checked everyrhing. By "except the Core version" I meant that I created the ASP .NET Core Web application on .NET Core 2.1 not 2.0.

**Comment by neustupa** [comment]
Ok. Problem solved. But actually I don't know how. I installed all updates of WS 2016, updates of .NET Core Runtime and also SDK and it is working. Sorry for bothering you and thank you again for response.

**Comment by Mikejo5000** [comment]
NP, glad it's working for you now!
