### ISSUE TITLE
The installation command does not work with no internet connection

### ISSUE THREAD

**Issue by Shawn1874** [MicrosoftDocs/visualstudio-docs#1485]
The command given within the instructions do not work.
 `c:\vs2017layout\vs_community.exe --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Component.GitHub.VisualStudio --includeOptional `

If I need to use the internet then it defeats the purpose of an offline installer.  If I am connected to the internet then it just ignores the options and downloads the latest version of the web installer, ignoring the options on the command line.  There is something wrong in those instructions.
![image](https://user-images.githubusercontent.com/18298395/45107305-fa6d3980-b0ed-11e8-894c-1f6f3014c6bc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by Shawn1874** [comment]
Evidently, simply executing the command 'vs_enterprise.exe' works and opens up the GUI if I run that from the directory where there cached files are stored.  The instructions on the web page say to repeat all of the --add parameters that were used to create the layout.  Trying to install exactly as instructed does not appear to work.  

By the way, I am using vs_enterprise not the community version so I did run the command with the correct executable name.  The problem report is just repeating the command given within the instructions so that you know what part of the page I am talking about.

**Comment by TerryGLee** [comment]
@Shawn1874 Thanks for your feedback; we appreciate it! We'll investigate and make updates to the page as necessary.

**Comment by moh-hassan** [comment]
@Shawn1874
>The instructions on the web page say to repeat all of the --add parameters that were used to create the layout. Trying to install exactly as instructed does not appear to work.

It works in installation.
The --add option parameter in the command-line, auto select (check) these workload or components in GUI. So you need not to check it again.
BTW, the command  you provided is working with me (i don't use --includeOptional)

**Comment by vbjay** [comment]
To be clear.  This page contains instructions to download an offline installer.  This allows you to install on computers that have no internet.  You can make an iso or file share or what have you to get the files from the computer you ran the command on to the place you want to install.  They don't provide ISO's.  This allows you to download once and install as needed.

**Comment by tydunkel** [comment]
@Shawn1874 Thank you for reporting this issue. From your screenshot, it appears that the command line passed to the installer was malformed. What you posted as your command line appears correct, but the installer received something different. Did you perhaps include a space accidentally somewhere in the command line passed to the installer? It seems that ```--a``` was given instead of ```--add```.

For future issues, please report through the [Report a Problem](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio-2017%3Fview%3Dvs-2017&data=02%7C01%7Ctydunkel%40microsoft.com%7C35450f5b6dbf462a894808d65c7f586c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636798099344837625&sdata=SLtwpjns2nDqbJcTGVMHOoDNsykZ9zYrdc48sRKcNP4%3D&reserved=0) tool included in the installer. That will post feedback to the [Developer Community](https://developercommunity.visualstudio.com) which is actively monitored for issues and will create bugs directly on the product team.
