### ISSUE TITLE
Can't get ShowToolWindow to trigger in VS2017, plus how to dive into Configuration-hives etc.

### ISSUE THREAD

**Issue by rvoith** [MicrosoftDocs/visualstudio-docs#1490]
I have just tried to create a test-project as described in this post. However, I can't get the ShowToolWindow method to trigger. My workaround (just to see how to enumerate properties) was to *not* remove the click-handler and rather put my code inside the handler. Then I could at least do some work :-)

The example above only shows how to loop the top-hive property names, and nothing about how to get to the property-values. Doing so will quickly reveal that the many property-values are of type System.__ComObject. I would love to see some samples on how to properly extract the values too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc47f17-30eb-8b33-be7d-501c6c9270b4
* Version Independent ID: 95c97b42-04e2-e743-d390-61733f76a17f
* Content: [Getting Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-project-properties?view=vs-2017)
* Content Source: [docs/extensibility/getting-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/getting-project-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
