### ISSUE TITLE
32 vs 64 bit

### ISSUE THREAD

**Issue by davedoug1970** [MicrosoftDocs/visualstudio-docs#1492]
Getting the error: Message: The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see "Troubleshooting Data-Driven Unit Tests" (http://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library. Error details: ERROR [IM014] [Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d4d170-fcf4-6caf-da44-dfe6e194a257
* Version Independent ID: c980b0f6-ed24-9c4a-0b2e-77962aafc81d
* Content: [Walkthrough: Using a Configuration File to Define a Data Source in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source?view=vs-2017)
* Content Source: [docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks for your feedback; we appreciate it (and sorry for the delay in responding). To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
