### ISSUE TITLE
Reporting issues when you can't log in

### ISSUE THREAD

**Issue by mausch** [MicrosoftDocs/visualstudio-docs#1493]
I can't log in to VS (getting an ArgumentNullException when trying to), I don't see any way to report that here since I can't launch VS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to report a problem with Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@mausch Thanks for letting us know; I've forwarded this issue to the appropriate parties for a response.

**Comment by mariaghiondea** [comment]
Hi,
Looks like you are running into a Sign In issue. We use the Visual Studio sign in and those issues are tracked through support. I apologize for making you jump through hoops to get this fixed!
Please visit https://www.visualstudio.com/subscriptions/support/ and select “Account, Subscription & Billing Support” under the “Contact Us!” heading. Follow the prompts that will connect you to a support agent who can help troubleshoot this issue with your account. You can set Issue to “Subscription sign in support” for issues signing into the product
For logging Visual Studio issues from Developer Community, please see https://developercommunity.visualstudio.com/content/problem/7588/theres-no-mechanism-for-reporting-feedback-other-t.html for more details. We don't have any plans to do this yet, since we feel like Visual Studio reports bring us a lot of diagnostics and actionability value, but we are aware of the corner case scenarios we are missing.
Thanks,
Maria Ghiondea
Visual Studio Feedback Systems
