### ISSUE TITLE
VS2017 Offline Installer can no longer be created since version 15.8 using these instructions

### ISSUE THREAD

**Issue by Tiohkatrah** [MicrosoftDocs/visualstudio-docs#1510]
I tried to create a layout using
vs_enterprise.exe --layout c:\download\vs2017 --lang en-US de-DE --includeOptional
This worked for VS2017 Version 15.7
I tried to get a working layout for version 15.8 (for offline installation) for weeks now - several attempts failed - the layout is always incomplete. 

There are lots of errors shown during the download, like:
```
Failed to load from stream: Das angeforderte Objekt wurde nicht gefunden.

Failed to get signer for 'C:\Users\Tioh\AppData\Local\Temp\f2m4kxru\AndroidPlatf
orm19.Private.F072D1E001B4438432E5\android-19_r04.zip'
Download of 'https://go.microsoft.com/fwlink/?linkid=841556' succeeded using eng
ine 'WebClient'
Layout progress: 59,12%
Layout progress: 59,12%
Layout progress: 59,13%
Failed to load from stream: Das angeforderte Objekt wurde nicht gefunden.

Failed to get signer for 'C:\Users\Tioh\AppData\Local\Temp\f2m4kxru\AndroidPlatf
orm19.Private.F072D1E001B4438432E5\android-19_r04.zip'
```
The resulting layout is not complete and cannot be used for an offline installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by nschonni** [comment]
15.1-15.8 support dropped with 15.9 https://blogs.msdn.microsoft.com/visualstudio/2018/10/05/visual-studio-2017-and-visual-studio-for-mac-support-updates/

**Comment by tristanbarcelon** [comment]
Thanks @nschonni. It's not the news I wanted to hear unfortunately. I suspect they archived it sooner due to the VS2019 effort. This forces me to update the offline release we install to 15.9. I used to actually spend the time burning a full download of each and every edition and major.minor.path to an ISO but the effort took too much time and storage. For environments that need reproducible builds, this pattern of forced upgrades is not going to be good enough.

**Comment by tydunkel** [comment]
@Tiohkatrah The signer messages are simply warnings and not the root cause of the download failures. Are you still experiencing this issue? If so, can you file feedback using the [Report a Problem](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio-2017%3Fview%3Dvs-2017&data=02%7C01%7Ctydunkel%40microsoft.com%7C35450f5b6dbf462a894808d65c7f586c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636798099344837625&sdata=SLtwpjns2nDqbJcTGVMHOoDNsykZ9zYrdc48sRKcNP4%3D&reserved=0) tool? This will allow us to follow up and get the diagnostics we need.
