### ISSUE TITLE
Deploying from a network installation

### ISSUE THREAD

**Issue by ruslangaripov** [MicrosoftDocs/visualstudio-docs#1531]
My "response" to you below relates to your article \`\`Create a network installation of Visual Studio 2017''[1]

> A complete Visual Studio 2017 layout requires at least 35 GB of disk space

No, guys, your 15.8.4 complete set snapshot takes up to 43 GB (!) because you put there everything you could imagined.

But that was not a problem. The **real issue** is:

> Deploying from a network installation
>
> Users can install by running: 
> `\\server\products\VS2017\vs_enterprise.exe`

**No!!!** :rage: **User can not**!!! I have downloaded f## 43 GB, moved that s##t to an offline machine and run `vs_community.exe` there. And what do you think has happened? Your f### installer decided to download something more from the Internet! Of course it failed and installation terminated. :rage: And don't tell me about your dummy option `--noWeb`! It does not change anything.

I wonder who has made that stuff? Did you test that itself, on offline machines? :angry: Time passes, but you, MSFT, does not change. All you can do is draining other people's resources. I really tired of you. You can ban me here, on almost your "service", I don't give a s##t anymore. :rage:

[1]: https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by eico1013** [comment]
Same problem here. Download 50 Gb for offline installation but vs installer still tries to load packages from web. Need help

**Comment by ruslangaripov** [comment]
@eico1013 

> Download 50 Gb

:finnadie: I thought it's unable to beat my "record" of 43 GB!

> but vs installer still tries to load packages from web

In my cases VS 2017 was installed first from the Internet (online installer); that is it appeared on a PC when that machine has Internet connection. It was a long time ago -- when VS 2017 got its first release. After that the machine became completely offline system. When I had tried to update that instance of VS from the offline snapshot, I failed. Because the offline installer tried to get packages from the Internet (I believe because VS instance was firstly "built" from ``online'' packages). To be able to update/install VS 2017 from offline snapshot, I had to uninstall VS 2017 first, and then install it from the snapshot. **But MSFT doc does not say anything about such "scenario"**. :rage3:

Hope this can help you. G'luck!

**Comment by DylanQuitsGum** [comment]
We ran into this same problem on my team.  There is a folder in the layout that says some along the lines of certificates or vscertificates. (Sorry, I'm not at work and don't have the files in front of me).  Install the certificates in that folder to the local store and the installation should work fine.

**Comment by ruslangaripov** [comment]
@TerryGLee  Well, this is how msft works? They just silently close tickets giving no explanations. Well done, msft, well done! :+1: :kissing:

**Comment by akochepasov** [comment]
The offline installer doesn't work for community and enterprise edition on Nov 20.

I tried python only layout:
```
vs_community.exe --layout vs2017offline.python.15.8    ^
 --add Microsoft.VisualStudio.Workload.CoreEditor      ^
 --add Microsoft.VisualStudio.Workload.Python          ^
 --includeRecommended --passive --norestart --wait     ^
 --lang en-US 

```
and
`vs_community.exe --noWeb
`
It didn't work as it tries to download packages.

The C++/C# layout have the same issue:
```
vs_enterprise.exe --layout vs2017offline.15.8          ^
 --add Microsoft.VisualStudio.Workload.ManagedDesktop  ^
 --add Microsoft.VisualStudio.Workload.NativeDesktop   ^
 --add Microsoft.VisualStudio.Workload.NetCoreTools    ^
 --add Microsoft.VisualStudio.Workload.MSBuildTools    ^
 --add Microsoft.VisualStudio.Workload.Python          ^
 --add Microsoft.VisualStudio.Workload.VCTools         ^
 --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools ^
 --add Microsoft.VisualStudio.Component.VC.ClangC2              ^
 --add Microsoft.VisualStudio.Component.VC.ATLMFC               ^
 --add Microsoft.VisualStudio.Component.VC.CLI.Support          ^
 --add Microsoft.VisualStudio.Component.VC.140                  ^
 --add Microsoft.Component.NetFX.Core.Runtime                   ^
 --includeOptional --includeRecommended --norestart             ^
 --lang en-US --wait

```
with 
`vs_enterprise.exe --noWeb
`
Both don't work. It would be nice if you guys unplug one machine from the network and try to test the offline install. It doesn't seem a really complex test setup.

**Comment by tydunkel** [comment]
@ruslangaripov and @akochepasov Sorry for all of the inconvenience. Just to verify, are you both running the ```vs_community.exe``` that is being saved in the offline layout?

e.g.
```vs_community.exe --layout C:\layout --add Microsoft.VisualStudio.Workload.CoreEditor```
```C:\layout\vs_community.exe --noWeb```

The ```vs_community.exe``` saved in the layout will instruct the installer to install from the layout. Without running that the installer will run without knowing there is a layout on the system, attempting to download from the web.

If this is still an issue, please file an issue using the [Report a Problem](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fide%2Fhow-to-report-a-problem-with-visual-studio-2017%3Fview%3Dvs-2017&data=02%7C01%7Ctydunkel%40microsoft.com%7C35450f5b6dbf462a894808d65c7f586c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636798099344837625&sdata=SLtwpjns2nDqbJcTGVMHOoDNsykZ9zYrdc48sRKcNP4%3D&reserved=0) tool from the installer. This will allow us to track the issue and get further diagnostic information to accurately diagnose the root cause.

**Comment by akochepasov** [comment]
Hi Tyler, 

> @ruslangaripov and @akochepasov Sorry for all of the inconvenience. Just to verify, are you both running the `vs_community.exe` that is being saved in the offline layout?
> 
> e.g.
> `vs_community.exe --layout C:\layout --add Microsoft.VisualStudio.Workload.CoreEditor`
> `C:\layout\vs_community.exe --noWeb`
> 

Yes, I run the binary, saved inside the layout. I didn't think it may be useful to copy the layout over and copy vs_community.exe additionally.

**Comment by bjmacdonald** [comment]
Install from offline layouts simply don't work anymore.  This is extremely frustrating.  I did a completely fresh layout to a network share and tried installing from that share using the same path on a freshly installed Windows 10 machine.   Same result as my other machines - with the --noWeb option the installer craps out complaining about downloading a manifest and without noWeb it ignores the local layout and downloads everything from the web.  Again.

**Comment by akochepasov** [comment]
Very frustrating installation issue. I removed my offline VS2017 as it didn't work and didn't allow to update itself to a version with an apparent offline installation fix. After uninstalling, Windows died completely to the blue screen with 0xc0000145 error code. I had to reinstall all the Windows, programs and settings.

**Comment by gregnorz** [comment]
It appears that the bootstrappers are no longer acknowledging the **`response.json`** when accessed via a UNC path. I have a specific partial layout created to ease install for our team with a slightly customized **`response.json`** to passively install the required components. This is not picked up when launching the bootstrapper from File Explorer via a UNC share.

If I copy the offline layout down to the machine I'm installing on, launching the bootstrapper works as expected by picking up the **`response.json`**.

Perhaps this is similar to what others are seeing.

**Comment by tobyhu87** [comment]
Hi @gregnorz ,

Thanks for reporting this issue.  Can you please 'Report a problem' in our Developer Community website? (https://developercommunity.visualstudio.com/) 

We can help you with this issue there.

thanks
toby

**Comment by tobyhu87** [comment]
Hi @akochepasov 

Thanks for reporting this issue. Can you please 'Report a problem' in our Developer Community website? (https://developercommunity.visualstudio.com/)

We can help you with this issue there.

thanks
toby

**Comment by tobyhu87** [comment]
Hi @bjmacdonald 

Thanks for reporting this issue. Can you please 'Report a problem' in our Developer Community website? (https://developercommunity.visualstudio.com/)

We can help you with this issue there.

thanks
toby

**Comment by verzada** [comment]
Wow. Wish I had read this thread before attempting this at all. 
Even created a post on StackOverFlow ... 

https://stackoverflow.com/questions/55024224/visual-studio-2017-create-an-installation-through-network-share-and-ansible

Since Microsoft chose to not provide an ISO, but instead have an offline installer for VS2017, this is a rather huge problem. I understand now that I'm not far off with my setup, but the problem is that it's not currently possible to do an installation from a network share.

**Comment by gregnorz** [comment]
Replying here before logging an official issue just in case someone stumbles upon this (or others in this thread have interest)...

I finally got around to performing some testing with different permutations of a network installation. The bottom line is that I can't, under **ANY** circumstances, get a network-based installation of VS2017 installed using a layout with a custom **`response.json`**. I've tried a VM **not** on a domain, a VM on a domain, UNC paths, mapped network drives, and installation via File Explorer as well as command line. The only way a layout will install with the **`response.json`** is if I copy the layout folder locally and run the bootstrapper from within the VM. 

I am seeing this error in the bootstrapper's log file:

`VisualStudio Bootstrapper:3/13/2019 11:59:28 AM: Caught Exception: Type = CampaignTrackingParseException, Message = Failed to parse id from parent process, StackTrace =    at Microsoft.VisualStudio.Setup.Bootstrapper.Telemetry.CampaignTracking.GetCampaignId(String parentProcessPath, String& exeName, String& parentProductVersion, String& campaignId)
   at Microsoft.VisualStudio.Setup.Bootstrapper.Program.Parse(String[] args, IServiceProvider serviceProvider, String entryAssemblyProcessName, String entryAssemblyProcessFullName)
InnerException:Type = FileNotFoundException, Message = V:\vs_setup.exe, StackTrace =    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Microsoft.VisualStudio.Setup.Bootstrapper.Telemetry.CampaignTracking.GetCampaignId(String parentProcessPath, String& exeName, String& parentProductVersion, String& campaignId)
VisualStudio Bootstrapper:3/13/2019 11:59:28 AM: Failed parsing the campaign ID.`

Somehow these lines of code don't like working with a network drive or UNC share. This error appears regardless of how the machine itself is configured; if the layout is over the network, the bootstrapper throws this exception.

I will also report this on the Developer Community with my log files. Hopefully that will get someone what they need to fix this.

**Comment by jefmes** [comment]
I just wanted to say thank you to those comment prior to now - I'm just about to take a stab at setting this up, and it looks like it's essentially broken. I'll see what happens for us and report back one way or another.

**Comment by gregnorz** [comment]
For those interested, here is my thread over on Developer Community:

[https://developercommunity.visualstudio.com/content/problem/488652/vs-2017-bootstrapper-will-not-use-responsejson-whe.html](https://developercommunity.visualstudio.com/content/problem/488652/vs-2017-bootstrapper-will-not-use-responsejson-whe.html)

**Comment by TASlavens** [comment]
@ruslangaripov

With respect to the size of a full layout, https://github.com/MicrosoftDocs/visualstudio-docs/issues/1555 is the closed issue I had raised last year, pointing out that "at least 35GB" is a less than useful figure.  It was closed, apparently based on the fact that "at least 35GB" is pedantically correct, because 41.5GB is greater than 35GB.  By that reasoning, "at least 1 byte" is also correct, although obviously an even less useful figure.

Now, it's a minimum of 43.3GB for an English-only full layout of Ent. 15.9.10, and 43.2GB for the corresponding Pro. layout.  Anyone who has a 64GB memory stick with 38GB free, and is thinking, "Good, there is plenty of space for a full layout plus a couple of non-English localizations", is in for a rude surprise.

Upon reading that response from @TerryGLee, I simply gave up attempting to offer anything beyond necessary corrections to the TFS areas of MS online docs.

**Comment by ruslangaripov** [comment]
@TASlavens  Of course, I agree with you -- size of the installation set is too much big.  Too much.  And reaction of Microsoft to your ticket just makes me speachless.  @TerryGLee must be removed from Microsoft support just for such answers and for that strange "habit" to close a ticket without having any reason for that.

It's sad to know that one has to download and store almost 45 GB of the installation set.  But what's the real pain is a need to copy that huge set to a target client machine to be able to install Visual Studio 2017.  I believe that Microsoft will **not** fix either the documentation set (#1555), or this issue.  Sooner or later @TerryGLee will close this PR **again without having any explanation** for that.

**Comment by TASlavens** [comment]
@ruslangaripov

To be clear, my complaint was only about the documented minimum size of layouts.  I'm OK with the size of the download itself - the product supports a huge set of capabilities.

I just read through all of the comments, and it's clear several individuals have had problems which I have not experienced.  I have recently performed two clean installations of VS 2017 15.9.9 Ent. from a mapped network drive, and two updates of existing installations which had been originally installed from the web.  In the latter cases, I believe the existing installations were 15.8.2, but I don't recall now.  In all cases, the installation targets were Win2012R2 VMs which host TFS agents.  We also perform clean installations from layouts I occasionally put on a few USB sticks for new developers/laptops - it's faster than the web installation here due to bandwidth limitations in the office.  So, I have a few suggestions:

0.)  If the layout size is a problem, consider specifying only the workloads you need (especially skip the mobile development workload, which includes huge emulators, if you can) and specifying only the languages you need (the difference between just en-US and all languages is several GBs).  You could do it at component granularity, too, but there are a lot of them.  I've done this to produce a layout which includes only the components necessary for profiling (plus the shell; it seems we can't get away from that), so I know it works.  That layout is only 619MB, though about 25% more on disk due to file system allocation unit size.

1.)  Always download the most recent bootstrapper EXEs from the links above.  The VS Com. link is missing starting with 15.9.11, but you can copy one of the other links and modify it appropriately.  Why do this every time?  Back around 15.4.x, I noticed that an "old enough" bootstrapper would often produce a broken layout, or fail partway through.  Maybe that has been fixed more recently, but I always get the latest one to avoid wasting time.  Be careful about downloading these from other pages; the links for VS 2019 on at least one other MS page still point to the RCs.

2.)  Unfortunately, you need to create a separate layout for each edition (Ent., Pro., or Com.) you want to install.  You can't drop vs_Professional.exe into a layout created with the vs_Enterprise.exe bootstrapper and expect it to work.  Ask me how I know...

3.)  As @DylanQuitsGum noted, if you don't acquire the necessary certificates, the installer will download those at installation time.  There is (or was) documentation for that somewhere around here, but I cannot find it now.  If you have them available in the layout and specify the arguments in the next note, the installer will not attempt to download them.

4.)  In addition to acquiring the certs, you also need to specify both --noWeb and --noUpdateInstaller.  The former prevents downloading updated workloads, components, and so on.  The latter prevents the installer from self-updating from the web.

5.)  If you do a test installation on a disposable VM and install the minimum set of workloads and components you need, you can subsequently use the VSSetup PowerShell module to retrieve the list of workload and component IDs, and then transform them into the "add" section of a custom Response.json file.  Put that file into your layout (overwrite or rename the default Response.json), so the installation/update can use it.  Also a bit of a warning:  If you're selecting specific components within that initial installation used to generate a custom Response.json, closely review the component tree on the right-hand side.  Some components selected in the main list don't always end up selected in the component tree, and you don't want to go through all of that more than once - trust me.  What does this get you?  Your own standard installation for build servers or a baseline which can reduce how much additional customization (if any) your devs need to do for their specific work needs.  Oh, and another warning:  Beware of Unicode vs. ASCII encoding of the Response.json file, depending on what your preferred editor does with it.  Only Notepad is available on our servers, and I didn't notice that it had changed the encoding, which had me banging my head against a wall trying to determine why things were not working.

A few caveats about the prior notes:  First, all of that applies only to VS 2017; I haven't tried a VS 2019 layout yet (maybe this Friday).  Second, I limit updates to our TFS agent VMs for stability, and sometimes VS updates come very quickly, so I have not deployed every patch of VS 2017 from layouts, maybe only half.  You might be unlucky enough to have created layouts from a patch versions which are broken.  Third, client installations here have always been clean (the devs use the web to keep up to date), and only on Win7 and Win10 laptops - there is no Win8.x here for devs.  Finally, the server installations/upgrades I do have only been on Win2012R2 and Win2016.

Perhaps some of this will be of help to you and others who might come looking.  Good luck!

**Comment by cremor** [comment]
@gregnorz Microsoft closed your bug report as an external (Windows) problem 😞 

I've created a batch script that allows the installation from a network share. You can find it here: https://gist.github.com/cremor/ff21d9f3f4cf7da36eef1558e714c90b

**Comment by atloiaco** [comment]
Has anyone found a workaround for this yet? We just tried to create a network installation of 2019 and when we go to install it on the clients. I pops up with the verifying files window for about a minute before the windows disappears and thats the end of it. We created multiple layouts and haven't been able to install any of them.

**Comment by cremor** [comment]
I have no problems with the script that I linked in my last comment. I'm using it for each VS2019 update.

**Comment by atloiaco** [comment]
@cremor thank you for replying. For your script is it for installation after the network installation layouts have been created? If so I tried your script and had the same issue with the different layouts we have.

**Comment by cremor** [comment]
Yes, the script installs an previously downloaded layout.

I've never encountered the problem you describe. The problem discussed in this issue is that the network layout just isn't used (and everything is downloaded again during the setup). If the installer doesn't even start, there is something else wrong with it.

**Comment by atloiaco** [comment]
The installer starts and I get the screen that has "Just a moment ... fetching your files" and under it is Verifying and Installing. The verifying bar is at 100% and installing just stays at 0%. Then the window just closes. I am able to install this same layout from the network share on a Virtual Box that is connected to the internet so it would seem that the layout is not the issue, it is just trying to connect to the internet to verify the files when it shouldn't need to.

**Comment by ojutan** [comment]
I guess the documentation is wrong. I also downloaded the complete vs enterprise "layout" just for nothing and I am not amused..

**Comment by Procastin8or** [comment]
I skimmed through the comments and didn't notice that the following was noted. The following is how I install it from an offline source on a non-internet connected computer. I believe you need the "--noweb" and "--noUpdateInstaller". From my understanding the "--noweb" is not truely needed for the install to work. It is for disabling the automatic update check once it is installed. The "--layout" option is only needed for the initial download from the internet. Obviously add whatever Workloads or Components that you need [().]https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?vs-2019&view=vs-2019 This is also without modifying the .json files. I also use "--quiet", but left that out below.

1) In powershell, I CD to the directory where the vs_professional.exe is located. 
2) Install the certificates located in the "Certificates" folder
3) .\vs_professional.exe --productkey <product key here> --norestart **--noUpdateInstaller --noweb** --add Microsoft.VisualStudio.Workload.CoreEditor --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.NativeCrossPlat --add Microsoft.VisualStudio.Component.VC.CLI.Support --add Microsoft.VisualStudio.Component.VC.140 --includeRecommended

**Comment by TerryGLee** [comment]
Thanks to all who have participated in this discussion! Based on your feedback, over the preceding months we've expanded the documentation with a [network install troubleshooting guide](https://docs.microsoft.com/visualstudio/install/troubleshooting-network-related-errors-in-visual-studio), we’ve improved the guidance on [creating a local install cache](https://docs.microsoft.com/visualstudio/install/create-an-offline-installation-of-visual-studio), and we’ve updated this page, [**Create a network installation of Visual Studio**](https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio), with improved information about:

- download size
- `--noWeb` command-line parameter
- how to modify the response.json file

For those who want download and then install on the same computer, we added a [“Download, then install” feature](https://docs.microsoft.com/visualstudio/install/create-an-offline-installation-of-visual-studio). In addition, we’re working on additional features to ease deployment in enterprise scenarios, including the ability to update a local cache with updated packages. When we release those features, we’ll announce them on the [Visual Studio Blog](https://devblogs.microsoft.com/visualstudio/) and in the [release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes). So again, thank you for your feedback to improve the documentation, and Visual Studio.

If you encounter further issues when installing or using Visual Studio, please use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio), which provides our development team with setup and other logs needed to diagnose your issue. If you find an error in the documentation, please use the feedback link at the bottom of a Docs page to report the issue. You can also submit a pull request with a suggested documentation fix by using the edit button at the top of a Docs page.

In addition, we’d like provide some context to a few issues raised in this thread.

**Why don’t we provide an ISO?** Quite simply, it’s become too big. It’s too big to burn on a DVD, and too big to reliably download.  Instead, the best solution if someone is looking for an ISO is for them to just create their own offline layout.

**How large is a local cache of Visual Studio?** For version 16.7 (the latest version as of writing, a local cache for the Community edition in en-US is about 32 GB and Enterprise is 42 GB. Including additional locales increases the size by about half a GB per locale.

**Why is a Visual Studio local install cache so large?** Visual Studio supports a lot of different development scenarios. One of our goals is to make it easier for developers to get started with development without needing to search for the tools, SDKs, and other resources they need to be productive. However, each SDK, each development language we support adds to the size of Visual Studio. This doesn’t mean you need to download all of these tools, nor even install them. We’ve constructed the Installer to give you control over how many, or how few of these SDKs and tools you want to install along with Visual Studio. As some examples, amongst other tools and SDKs, a full local cache of the latest Visual Studio includes:

- 8 .NET SDKs, plus additional targeting packs
- SQL Data Tools
- Clang Compiler
- 8 C++ toolsets, for x86/X64, ARM, and ARM64, and MFC and ATL tools for these toolsets
- 2 versions of Python, in 32-bit and 64-bit
- Google Android Emulator
- Android SDK
- 5 Windows SDKs
- Language packs for all of our tools and SDKs so that you can use Visual Studio in the language of your choice

**How can I reduce the size of the local cache or my install?** Download or install just the tools, SDKs, and resources that you’ll use. For example, If you aren’t planning to use the C++ v141 toolset or .NET Framework 3.5, there’s no need to include it in the local cache, or install it. You can always modify your cache or install to include it later. The [Command-line parameter page](https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio) will help you restrict the cache to just those workloads and components you need.

**Why does Visual Studio setup sometimes attempt to install components from the web even though I’m using a local cache?** A few of the tools and SDKs you can install by using Visual Studio aren’t in the local cache because they include third-party packages. So while Visual Studio Installer will download the third-party installer into the local cache on your behalf, we are unable to also download the third-party packages referenced by those installers.

Finally, we’d like to note our [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/) page, which outlines the expectations for community interactions for [docs.microsoft.com](https://docs.microsoft.com) and is designed to help us provide a welcoming and inspiring community for all.

**Comment by rra88** [comment]
I've followed [https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022#install-visual-studio-onto-a-client-machine-from-a-network-installation](url) to create a layout that I've xcopy'ed over to a network location on a network not connected to internet. I used `vs_Community.exe --layout C:\VSLayout --add Microsoft.VisualStudio.Component.CoreEditor --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.DataScience --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.Python --includeRecommended --includeOptional --lang en-US` to create the layout. On a client on the network, I want to install from the layout, so I ran `\\server\products\VS\vs_enterprise.exe --noweb`. I added the --noweb option here, and not in the command for creating the layout as the --noweb option was introduced in the chapter "Install Visual Studio onto a client machine from a network installation" in the documentation (after all the info about creating a layout). The installation quit after some minutes with an error message about not having internet connection. Did I read the documentation wrong? Should the --noweb option be added when creating the layout?

**Comment by TerryGLee** [comment]
@rra88 This issue is closed; please consider creating a new issue or using one of the following resources for help:

* We offer an [installation chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
* Report product issues to us via the [Report a Problem](../../ide/how-to-report-a-problem-with-visual-studio.md) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE. If you're an IT Administrator and don't have Visual Studio installed, you can submit [IT Admin feedback here](https://aka.ms/vs/admin/feedback). 
* Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://aka.ms/feedback/suggest?space=8).
