### ISSUE TITLE
VS 2017 - Access stored font and color settings - Docs out of date? 

### ISSUE THREAD

**Issue by mrworkman** [MicrosoftDocs/visualstudio-docs#1541]
Is this still valid when speaking about Visual Studio 2017? The referenced registry key does not exist - so no font/colour info is available there. It *is* available in `C:\Users\user\AppData\Local\Microsoft\VisualStudio\15.0_f92f921eExp\Settings\Exp\CurrentSettings-2018-08-25.vssettings` though. What's the correct way to do this nowadays?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9bc03c-1d5b-e956-7868-645a9c18d923
* Version Independent ID: 2b890743-a5fe-b6fb-7632-a5c2baec6f59
* Content: [Accessing Stored Font and Color Settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/accessing-stored-font-and-color-settings?view=vs-2017)
* Content Source: [docs/extensibility/accessing-stored-font-and-color-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/accessing-stored-font-and-color-settings.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by bchavez** [comment]
Hello,

I'm going to share what I found for others following in my footsteps.

I recently had a problem with VS 2019 settings interfering with my VS 2017 settings. [Specifically, my color settings are getting all tangled up between both VS 2017 and VS 2019.](https://developercommunity.visualstudio.com/content/problem/516365/visual-studio-fonts-and-color-settings-are-not-iso.html)

Unfortunately, the `CurrentSettings.vssettings` file isn't the only place where settings are stored in Visual Studio. This is especially true for the newer versions of VS, like 2017 and 2019.

It is a pain trying to figure out *the actual* settings storage location for fonts and colors because Visual Studio aggressively caches everything ***everywhere***. Also, don't forget, Visual Studio requires you to sign into your Visual Studio account which can also synchronize settings. This "remote config" adds an extra layer of complexity in determining where and what settings are being applied.

The **effective** settings storage location for fonts and colors that Visual Studio uses is located at the following location:

`%userprofile%\appdata\local\Microsoft\VisualStudio\vshub\Settings`

The folder is essentially a mix of XML and SQL lite database files. This is the effective location where **fonts and colors** are stored in Visual Studio. In fact, there's a dedicated process `ServiceHub.SettingsHost.exe` launched with `devenv.exe` that interacts with this folder.

Other suspected and cached (but less effective) locations for fonts and colors include the following locations:

* `%userprofile%\appdata\local\Microsoft\VisualStudio\16.0_2a8eeedb\ApplicationPrivateSettings.xml`
* `%userprofile%\appdata\local\Microsoft\VisualStudio\16.0_2a8eeedb\privateregistry.bin`  
   Visual Studio's Private Appliation Registry Hive loaded via [`RegLoadAppKey`](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/filtering-registry-operations-on-application-hives)

(where `16.0_2a8eeedb` is your VS version installed)

So, if you're looking for an xcopy, restore file, or "recover from backup", way of restoring your Visual Studio Fonts and Color settings the paths listed above are the files and folders you want to look at to restore your "fonts and colors" in Visual Studio.

Hope that helps.  
-Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
