### ISSUE TITLE
Is MenuButton/SplitDropDown Ever Supported?

### ISSUE THREAD

**Issue by weifenluo** [MicrosoftDocs/visualstudio-docs#1544]
I can never get a Button with type of "MenuButton" or "SplitDropDown"  to work in a tool window toolbar. 

This Stackoverflow post:
https://stackoverflow.com/questions/14285622/how-to-define-a-splitdropdown-or-menubutton-for-a-toolbar-in-a-vsct-file
also says "It seams that the SplitDropDown and MenuButton types are no longer supported by the Visual Studio IDE". I searched the internet with no luck to find any example of using "MenuButton" or "SplitDropDown" in a .vsct file.

So my question is:

1. Is "MenuButton" or "SplitDropDown" ever supported in .vsct file?

2. If yes, please kindly provide a small working example (VS2017) to show a MenuButton in a tool window toolbar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10f35553-7713-7c2c-1f8b-0735810df31d
* Version Independent ID: 27bb3f2c-c2c8-d565-499c-98f562795c71
* Content: [Button Element - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/button-element?view=vs-2017)
* Content Source: [docs/extensibility/button-element.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/button-element.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
