### ISSUE TITLE
Why can't I see the GUI editor?

### ISSUE THREAD

**Issue by shehackspurple** [MicrosoftDocs/visualstudio-docs#1551]
This line"This file corresponds to a page that's named About in the web app." is followed with an image of the gui, yet...  I don't see how in the editor that we got there.  I expand that page and I see code.  I can't drag and drop things onto the form.  How do we get there?  And could you add a step here to show it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 026ec5bc-2e15-2dea-caaf-ef3fe810a387
* Version Independent ID: e0db4893-129d-80d2-2e6d-bb9f7c04b85e
* Content: [Use Visual Studio to create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017)
* Content Source: [docs/ide/quickstart-aspnet-core.experimental.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.experimental.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@shehackspurple Thanks for your feedback! So, this isn't something that you can drag onto a form, but I can make the procedure a little clearer. Stay tuned!

**Comment by TerryGLee** [comment]
@shehackspurple I've made a few changes to the page that should make it clearer how to create a web app in Visual Studio with C# and ASP.NET. Hopefully, the additional screenshot and descriptive text in the "Create and run the app" section is helpful. Let us know if not! Otherwise, we'll close this issue in the next 24-48 hours. (And thanks again for your comments that precipitated the changes.)

**Comment by TerryGLee** [comment]
@shehackspurple We'll close this issue now; thanks again for your feedback.
