### ISSUE TITLE
Treeview example

### ISSUE THREAD

**Issue by Allann** [MicrosoftDocs/visualstudio-docs#1557]
Whilst this article outlines many styles and "rules",  it would be nice to link to an example or tutorial on how to get these items right and allow developers to hit the ground running.  For example, an article that outlines the  boilerplate code for any WPF tree view extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae232be6-a9f6-0942-521f-c7f96ab3473d
* Version Independent ID: cac23f6e-b781-37ea-b199-d114b3a6d2ed
* Content: [Common Control Patterns for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/common-control-patterns-for-visual-studio?view=vs-2017#BKMK_TreeViews)
* Content Source: [docs/extensibility/ux-guidelines/common-control-patterns-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/common-control-patterns-for-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
