### ISSUE TITLE
SpecificSolutionName not working

### ISSUE THREAD

**Issue by AerikAwesome** [MicrosoftDocs/visualstudio-docs#1567]
[TemplateTestSolution.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/2411232/TemplateTestSolution.zip)
The reserved parameter SpecificSolutionName does not seem to be working. Tested using a class library project in Visual Studio 2017. 

Also tried the variants specificsolutionname, SpecifiedSolutionName and specifiedsolutionname, with only the last one returning anything (the project name, not the solution name, unfortunately).

Edit - Attached zip file with example solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Visual Studio project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2017)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@AerikAwesome Thanks for letting us know. Do you know if you had "Create solution directory" checked when you created the project? If not, SpecificSolutionName is blank, according to the article.

![image](https://user-images.githubusercontent.com/24882762/45966530-3eae7400-bfe0-11e8-8a90-72493310f66d.png)

**Comment by AerikAwesome** [comment]
@gewarren Yes, the "Create directory for solution" option was checked.

**Comment by hargrave81** [comment]
I too am experiencing this same Issue.  Is there an easier mechanism to achieve this goal:
Create a multiproject solution template
Acme
Acme.Models
Acme.Tools
$projectsafename$ is Acme but as each project is created the projectsafename is unique per-project (e.g. MyCustom.Models so if MyCustom.Models references Acme.Tools it really points to MyCustom.Models.Tools rather than MyCustom.Tools)

**Comment by JeffRausch** [comment]
I'm also getting this error.  I tried all lowercase since this is the only param that's camal cased [(Param List)](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2017) but that didn't work either.  
It would really be nice to be able to access the solution name even when adding a project to an existing solution.  We organize project output by Solution\Project so now our users still have to manually edit output paths every time.

**Comment by gewarren** [comment]
Since it sounds like this is an issue with the product, it'd be best to log the issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) by choosing Help > Send Feedback > Report a Problem. You'll get better traction from the product team there. I'll close this once somebody confirms they've opened an issue on Developer Community.

**Comment by JeffRausch** [comment]
I opened this issue on the Developer Community site.
[VS Template SpecificSolutionName does not work](https://developercommunity.visualstudio.com/content/problem/444531/vs-template-specificsolutionname-does-not-work.html)

**Comment by gewarren** [comment]
@JeffRausch Thank you Jeff!

**Comment by keivaan** [comment]
you must in document **MyTemplate.vstemplate** in root **ProjectTemplateLink** add attribute **CopyParameters="true"**
`
      <ProjectTemplateLink ProjectName="$projectname$.Core" CopyParameters="true">
		DPKSchema.Core\MyTemplate.vstemplate
	  </ProjectTemplateLink>
`
and you can access name solution in the document .cs by this code
`
     $ext_projectname$
`
