### ISSUE TITLE
Expand on best practices

### ISSUE THREAD

**Issue by chm-tm** [MicrosoftDocs/visualstudio-docs#1578]
You have done a great job, guys, to document MSBuild.

However, I still find it quite difficult to engineer a build system when a couple of include files come into play. Property and item evaluation order is easy to get wrong.

The tooling to debug these type of issues is great.

However, any guidance of how to tackle this complexity the right way, conceptually, is highly appreciated. You have enough help about the different concepts. But how to do actual build engineering with this tool on a mid to large scale basis?

Granted, we have a great working sample with the C# project system. But do we have some prose?
 I'd expect that on this page. Links to such info provided in Wikis, blogs or books would also be OK.

For an idea of what I talk about, have a look at [this issue](https://github.com/NuGet/Home/issues/7084).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3640922f-bdb4-dfee-6b1c-7342e0a89ed2
* Version Independent ID: d33c6cb1-fe9b-656a-ade4-5d488143a898
* Content: [MSBuild Best Practices - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-best-practices?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-best-practices.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-best-practices.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by chm-tm** [comment]
You could refer to https://devblogs.microsoft.com/dotnet/the-evolving-infrastructure-of-net-core/.

**Comment by stevenbrix** [comment]
@chm-tm thanks for sharing that doc, there is a ton of good information int here. In my opinion that doc is too high level to try and understand any best practices for a single project.

I'll give an example below that I think is a best practice. I'll only refer to props files, but it applies equally to targets as well.

As the order inclusion is a serious issue and headache to get right, I've seen many projects run into the issue that I call "MSBuild Spaghetti" [pretty clever, huh ;)].  What I've seen happen is that instead of relying on props inclusion to come from Directory.Build.props, project files (either .csproj or .props) will import specific props, and all try to import them in the same order. Even if every project does import them in the same order, it's very easy for this to diverge and become costly to maintain.

In order to combat this, props files should be simple and single-purpose, and *props should not include other props*.

The only exception to this is Directory.Build.props.

Since you can never escape the ordering dependency of MSBuild, having a single place to include props from ensures that you only have one place to figure this out. If you ever come across an issue that smells like an ordering issue (properites/items not set that you think should be) you know exactly where to start investigating, and don't have to worry about creating ordering issues elsewhere in the tree.

**Comment by chm-tm** [comment]
@stevenbrix wow this is helpful advice!

I maintain projects predating MSBuild 15 so they [couldn't initially rely upon `Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets).

Consider including @stevenbrix in this page.

**Comment by ghogen** [comment]
We plan to update this topic as we identify new best practices. If you have any suggestions, you can drop them here for now.  Thanks for your ideas!

**Comment by ghogen** [comment]
We're going to go ahead and close this issue, because we have other documentation that helps with MSBuild. Having already implemented a few concrete suggestions on this, we want to close old, open-ended issues to keep a manageable backlog.
