### ISSUE TITLE
Native C++ package support

### ISSUE THREAD

**Issue by annajayne** [MicrosoftDocs/visualstudio-docs#1599]
This topic assumes that VSIX packages are always implemented using managed code, which is not necessarily the case.

How does this relate to native C++ packages created using the Wizard (which use VSL::IVsPackageImpl) etc.?

As VS2017 is the second version of Visual Studio to support AsyncPackages, the documentation, VSL implementation and samples should really support asynchronously loaded native C++ packages by now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126cb7b6-69ed-c50d-5b1b-b4b94948bf96
* Version Independent ID: f666821f-3bd5-282d-6bd6-4550fafa2872
* Content: [How to: Use AsyncPackage to Load VSPackages in the Background - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2017)
* Content Source: [docs/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by mlevis** [comment]
Yes Native C++ support needs to be added. You can still create a C++ vspackage in VS 2019. I have a very extensive extension that has been around since VS6. Converting all of that to C# is not an option.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by oold** [comment]
The documentation still doesn't mention how to do this for a C++ package. I need to convert an important in-house extension here and I neither know how to modify the extension to load asynchronously nor do I know much about native VS extensions at all. We keep having issues with developers accidentally disabling the extension due to the warnings issued by VS. Please provide proper documentation for this.
