### ISSUE TITLE
The VSPROPID values are missing in this document

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/visualstudio-docs#1622]
I see:

__VSPROPID4: var returns true if a batch of projects is currently being loaded synchronously as a result of a user command or other explicit load, otherwise false.

__VSPROPID2: var returns true if the solution is currently being closed, otherwise false.

__VSPROPID: var returns true if a solution is currently being opened, otherwise false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fb5c11-0f77-a25a-14ce-678091ca4c75
* Version Independent ID: bd16946d-a82b-9bad-13d8-ee9161728f8d
* Content: [Managing Project Loading in a Solution - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/managing-project-loading-in-a-solution?view=vs-2017)
* Content Source: [docs/extensibility/managing-project-loading-in-a-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/managing-project-loading-in-a-solution.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
