### ISSUE TITLE
Don't use "using namespace std;"

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/visualstudio-docs#1655]
Using namespace std is a bad example, consider replacing it with using std::cout;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89847656-bea8-b9a7-a50a-3d7e75e14ff6
* Version Independent ID: 9f6c1029-6d5b-1d41-10dd-65863848c2e5
* Content: [Get started with C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/getting-started-with-cpp-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/getting-started-with-cpp-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **tglee**

**Comment by corob-msft** [comment]
@Arush-Agarampur There are certainly places where a **using namespace std;** is not appropriate, such as a header file, but in a source file that has no conflicting namespaces, this usage is both reasonable and common, and has many proponents who consider it good engineering practice. Since we don't usually take sides in what amount to religious wars over acceptable engineering, you'll find many of our examples do explicitly scope identifiers from the std namespace. This is ultimately a matter of user preferences, and not something we would dictate.
