### ISSUE TITLE
Light bulb suggestions not work

### ISSUE THREAD

**Issue by tunguyen305** [MicrosoftDocs/visualstudio-docs#1675]
Hi

I'm follow the [Walkthrough: Display light bulb suggestions](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-light-bulb-suggestions?view=vs-2017)

But there are 2 issues with it:
- Firstly, when I use that VSIX file, and open a *.cshtml file (in my MVC project), each time the light bulb show, it display 2 or more command like:
Convert 'abc' to upper
Convert 'abc' to upper

- Secondly, when I also add a custom command that allow show a item in contextmenu when user rightclick to *.cshtml file. In this case, just custom command is display, the light bulb will NOT display

[VSIXProject2.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/2467690/VSIXProject2.zip)

Please help me check them

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
