### ISSUE TITLE
Where should the .vsz file be placed?

### ISSUE THREAD

**Issue by sketch34** [MicrosoftDocs/visualstudio-docs#1695]
This documentation always feels like it isn't written from the perspective of a developer actually trying to do things. So hard to find the answers to the basic questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d15a44-760b-bed4-5dc3-415f183c19e8
* Version Independent ID: 1e257d1d-026d-e6d9-5500-5a49dffb3e7c
* Content: [Wizards - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/wizards?view=vs-2017)
* Content Source: [docs/extensibility/internals/wizards.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/wizards.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
