### ISSUE TITLE
VS 2017 uses 8-char hex suffix

### ISSUE THREAD

**Issue by drewnoakes** [MicrosoftDocs/visualstudio-docs#1701]
I think a note such as this might be worth adding for VS2017:

&gt; [!NOTE]
&gt; In Visual Studio 2017 it's possible to have multiple experimental instances, and each is identified by an eight character hexidecimal suffix. For example `15.0_26954a82`

A subject expert should validate this is correct. I'm just reporting behaviour I've observed.

---

It'd also be useful to report the file system path where VSPackages are copied in case they need to be manually removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f518d4-58fd-baa0-677a-dc77e31ff1dc
* Version Independent ID: e521bc58-c8bd-b742-e525-acdaf8004baa
* Content: [The Experimental Instance - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/the-experimental-instance?view=vs-2017)
* Content Source: [docs/extensibility/the-experimental-instance.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/the-experimental-instance.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by drewnoakes** [comment]
Hives are found under path `%LOCALAPPDATA%\Microsoft\VisualStudio`.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
