### ISSUE TITLE
Design UI for iOS

### ISSUE THREAD

**Issue by RyanFromIT** [MicrosoftDocs/visualstudio-docs#1726]
In the "Set up your solution", #2 is to target iOS.  However, you don't have a "Design UI for iOS like you two for the other two platforms/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* Content: [Build apps with native UI using Xamarin in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio?view=vs-2017#solution)
* Content Source: [docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @RyanFromIT, although it has been updated for technical correctness since, this document was first written before Xamarin supported editing the iOS projects in Visual Studio! You'll notice right near the start of the article, it says "Next steps, which include designing an iOS user interface" which links to [these brief notes](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio?view=vs-2017#next-steps) and the [link to the finished code](https://github.com/xamarin/mobile-samples/tree/master/Weather).

Adding more detail on iOS is definitely something for us to consider adding here in future, thanks for the suggestion.

Until then, please refer to the [Xamarin.iOS docs](https://docs.microsoft.com/xamarin/ios/) and in particular the [user-interface pages](https://docs.microsoft.com/xamarin/ios/user-interface/) for more information.
