### ISSUE TITLE
But how to use snippet shortcut

### ISSUE THREAD

**Issue by tomeks666** [MicrosoftDocs/visualstudio-docs#1792]
I am trying to Ctrl-K Ctrl-S and then I type shortcut name for the snippet, but I still have to navigate thorough categories and select the snippet with keyboard or mouse. Basically my defined shorcut in .snipped file does nothing. All I want to is to insert {} around a block with a single keystroke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0360876b-37ed-53ac-5b8a-5964574ee41a
* Version Independent ID: 27d1ddfd-0ec9-a6ac-b0f1-34b1f33f004b
* Content: [How to use surround-with code snippets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-use-surround-with-code-snippets?view=vs-2017)
* Content Source: [docs/ide/how-to-use-surround-with-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-use-surround-with-code-snippets.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tomeks666 Thanks for your feedback; we appreciate it. One thing I'm wondering is if your defined shortcut conflicts with an existing shortcut. But if not, to make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
