### ISSUE TITLE
Visual Studio Offline Setup failed to download some components.

### ISSUE THREAD

**Issue by YuilTheLion** [MicrosoftDocs/visualstudio-docs#180]
While doing the setup with the `--layout` parameter, it was mentioned that the components failed to download.
Will those components get downloaded by the end of process?
I am currently trying to download Visual Studio Enterprise 2017. **(not the RC release)**
And I really mean for those red-marked components:
![image](https://user-images.githubusercontent.com/28005756/27667249-46d07328-5c99-11e7-8df2-9091e546d0c3.png)

**Comment by TerryGLee** [comment]
We appreciate your contacting us! So that we can investigate further, we invite you to post this issue to our Developer Community website at https://developercommunity.visualstudio.com/. 
Note: You might be asked to provide a setup log file; here's how:  
1) Download collect.exe from http://aka.ms/vscollect, and run it
2) Attach %temp%\vslogs.zip to the problem report on https://developercommunity.visualstudio.com/
Thanks,
Terry

**Comment by YuilTheLion** [comment]
Can you please help me how to report the issue there?
It only redirects me to "Report an issue" tool inside Visual Studio.
I haven't installed it yet!

**Comment by TerryGLee** [comment]
Thanks for the follow-up. Here's an answer to your initial inquiry; perhaps it will help you complete your installation so that you can then post the issue to the Developer Community. 

When you create a layout and a download fails, Setup will try to download the file(s) several times. However, if Setup still can’t successfully acquire the file(s) after several retries, Setup displays an error message, as shown in your screenshot, where the missing files are indicated in red text. You can try re-running the same --layout command later to try to get the missing files. When you re-run the command, it will not re-download the files that already exist locally in the layout folder. So, if only a few files failed to download the first time, it shouldn’t take as long the second time.

Thanks,
~ Terry
