### ISSUE TITLE
just now i verified two files 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/visualstudio-docs#1832]
Just now  i verified the contents  of  the  layout.json and response.json using notepad.exe.
In both the files , i found all the contents are same .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee82e78-02d5-bfe3-eb67-c69bdad01fa8
* Version Independent ID: 72f8b130-354d-a164-cb37-3d9b0b7cff19
* Content: [Automate Visual Studio installation with a response file - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/install/automated-installation-with-response-file?view=vs-2017)
* Content Source: [docs/install/automated-installation-with-response-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automated-installation-with-response-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@RAJU2529 It looks like you might have identified a product problem; please use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) tool. When you do so, your report becomes a work item for the product team, which allows you to engage directly with that team so that such problems can be addressed and fixed.
