### ISSUE TITLE
Trouble updating VS 2013 license

### ISSUE THREAD

**Issue by eadebeus** [MicrosoftDocs/visualstudio-docs#1883]
I hope you can help me with this.
I am trying to update the license for Visual Studio 2013, and I have run into
a problem. VS didn't recognize my password, so I tried resetting my password,
but after I went through the captcha, it announced that my user ID doesn't exist.
But if I try to create a new account with my email address, it says that I can't
because it does exist already. Can my uid both exist and not exist at the same time?
Is there any way to reset it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff48e07-208e-a8b1-0855-3f677cdf788b
* Version Independent ID: 0fd3926f-d997-c744-3f48-85568a2d462e
* Content: [Sign in to Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/signing-in-to-visual-studio?view=vs-2017)
* Content Source: [docs/ide/signing-in-to-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/signing-in-to-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@eadebeus It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:
- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/), or utilize one of the [Subscriptions support forums](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-priority-support).
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.
- If you do not have a subscription, consider connecting with using either our [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
