### ISSUE TITLE
[Template parameters] Date?

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/visualstudio-docs#1887]
Can we have date as well (i.e. $time$ without the time section - just DD/MM/YYYY)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Visual Studio project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2017)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@sp-stuart-harrison -- Stuart, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
