### ISSUE TITLE
Topological Sort

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/visualstudio-docs#1906]
How to implement a topological sort on the projects references, for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c6b3cd-fc32-1501-68a6-1da597bfd33b
* Version Independent ID: 499fd553-6e2e-aefe-aefd-2711c01e39e0
* Content: [Code maps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2017)
* Content Source: [docs/modeling/map-dependencies-across-your-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/map-dependencies-across-your-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@baruchiro -- Baruch, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
