### ISSUE TITLE
No "Show Derived Types" in Class View settings

### ISSUE THREAD

**Issue by fairjm** [MicrosoftDocs/visualstudio-docs#1934]
Is it removed or need some conditions to active it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960c4e0-ac54-9e65-6397-44d7a5750764
* Version Independent ID: 224d2c57-b542-8030-6b77-ce8a7889b466
* Content: [View code structure using class view, call hierarchy, object browser, and code definition window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/viewing-the-structure-of-code?view=vs-2017#feedback)
* Content Source: [docs/ide/viewing-the-structure-of-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/viewing-the-structure-of-code.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@fairjm -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
