### ISSUE TITLE
No longer works in Visual Studio 2017

### ISSUE THREAD

**Issue by lucidmikeb** [MicrosoftDocs/visualstudio-docs#1945]
The second example on this page no longer works with Visual Studio 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f603718-773f-1c7b-894b-2e77a7b213da
* Version Independent ID: 64a041be-c330-15a3-256b-94d2f85b8624
* Content: [Creating and Managing Modal Dialog Boxes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-and-managing-modal-dialog-boxes?view=vs-2017)
* Content Source: [docs/extensibility/creating-and-managing-modal-dialog-boxes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-and-managing-modal-dialog-boxes.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
@lucidmikeb The line of code to retrieve IVsUIShell needs to be moved to the OpenDialog InitializeAsync method and needs to changed to use GetServiceAsync. You can put the IVsUIShell pointer into a property for use in the Execute method later.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
