### ISSUE TITLE
Unable to import SQL snippet

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/visualstudio-docs#1967]
This documentation states "SQL" is valid for the Code element's Lanquage attribute.

I created a TSQL snippet and imported it into SSMS. But when attempting to import it into Visual Studio 2017, I receive the error "the snippet files chosen were not valid".

Also, I noticed when authoring the snippet in Visual Studio 2017, Intellisense only offers VB,C#,J#,and XML for the Code element's Lanquage attribute.

VB snippets import fine.  I can also reproduce the error when using the sample at https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2017 and changing the Language to "SQL"

**Comment by gewarren** [comment]
@dialedin2014 Thanks, I'll add this investigation to our backlog.

**Comment by gewarren** [comment]
Invesigating...

Section in question is here: https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2017#attributes

**Comment by gewarren** [comment]
@dialedin2014 I contacted the engineering team and it sounds like this is a product issue. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool in Visual Studio. When you do this, your report becomes part of the work items that are tracked on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
