### ISSUE TITLE
Creating and debugging Outlook 2016 add-in on Visual studio 2010

### ISSUE THREAD

**Issue by jwphrijk** [MicrosoftDocs/visualstudio-docs#1968]
Ask Question 

 

 
up vote

0

down vote

favorite

Hello,

I want to create a Outlook Add-in with VS2010 but when I want to debug this I get the error "You cannot run or debug this project because the required version of Office is not installed". Googling this error It looks like It can be solved by referring the dll installed with the office 2016, another solution I found said to specifie the Outlook.exe in the debug menu as external program. But this doesn't seem to register the add-in.

Is it possible to create a Outlook 2016 add-in with VS2010?

Thank in advance for your advice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c81ef68-355f-a059-91fa-904a7979ae48
* Version Independent ID: 777a14e8-58e0-f08a-116f-315f8f1aa86f
* Content: [Run solutions in different versions of Microsoft Office - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/running-solutions-in-different-versions-of-microsoft-office?view=vs-2017#feedback)
* Content Source: [docs/vsto/running-solutions-in-different-versions-of-microsoft-office.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/running-solutions-in-different-versions-of-microsoft-office.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jwphrijk The page you reference seems to indicate that the answer to your inquiry is "yes, you can." I'm sorry to learn that you are experiencing difficulties doing so. For a support request of this nature, I'd now typically point you to another venue such as StackOverflow to pursue your answer. However, I see that either you or someone else asked the same question on [StackOverflow](https://stackoverflow.com/questions/53471060/create-office-2016-add-in-with-visual-studio-2010) already. Perhaps the answer you seek will surface via that venue. 

(@John-Hart, FYI.)

**Comment by John-Hart** [comment]
I believe the page you're referring to is talking about Running solutions built with different versions of Visual Studio in different versions of Office.  In your case, I believe you're asking if you can create an Add-in with Visual Studio 2010 that targets Office 2016.  This is a little bit different in that Visual Studio may not support creating new projects that target a particular version of Office directly.  Which is true with Visual Studio 2010. It cannot create projects that target Office 2016 directly. In order to do this you would need to create an Office 2010 project with Office 2010 installed on the machine and then follow the instructions on the page you referred to on how to run the addin with Office 2016.  The better solution would be to download the Community edition of Visual Studio 2017 and create an a new project using the Office 2013 and 2016 project templates.  You can download the Community edition from: https://visualstudio.microsoft.com/downloads/
