### ISSUE TITLE
support for hexfloat notation

### ISSUE THREAD

**Issue by louis-langholtz** [MicrosoftDocs/visualstudio-docs#1997]
I'd love to see support for C++ std::hexfloat style formatted floating point numbers. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c135d-ace1-1f09-041a-13411c054ff3
* Version Independent ID: 083fc572-d877-2216-19a9-326636c1d8e6
* Content: [Format specifiers in the debugger (C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2017)
* Content Source: [docs/debugger/format-specifiers-in-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-cpp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TerryGLee** [comment]
@louis-langholtz It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
