### ISSUE TITLE
Where to put the pkgdef file?

### ISSUE THREAD

**Issue by arihannu** [MicrosoftDocs/visualstudio-docs#2009]
There are no instructions where to put the pkgdef file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e45c1ad-ec51-d4ac-e312-aa3f00d1aa17
* Version Independent ID: ddf8b9a6-f8d9-2642-be36-0856e639ac85
* Content: [How to: Manage a Private Gallery By Using Registry Settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings?view=vs-2017)
* Content Source: [docs/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by madskristensen** [comment]
Anywhere in the VSIX Project. Just make sure the .pkgfile ends up somewhere inside the .vsix file and that you add it as an `<Asset>` in the .vsixmanifest file

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
