### ISSUE TITLE
Es fehlt eine Information

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#2013]
@ojutan commented on [Tue Dec 04 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/28)

Man kann den Download für die Offlineinstallation nur auf Sytemen durchführen, auf denen noch kein Visual Studio installiert ist. Das sollte auf alle Fälle mit aufgenommen werden, denn wenn schon ein VS auf dem System vorhanden ist, dann landet man in einem schwer zu diagnostizierenden Zustand, daß der Bootstrap Installer OHNE FEHLERCODE sich beendet (errorlevel = 0) aber trotzdem nichts herunterlädt.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Erstellen einer Offlineinstallation von Visual Studio - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tydunkel** [comment]
@ojutan Thank you for filing this issue! If an installation is from the web it cannot be updated from an offline layout. If the installer detects that the same SKU of Visual Studio is already on the system, it will attempt to either modify or update the installation. If there is not update and nothing to modify, it will exit with a return code of 0 since there were no errors. The log should contain more information on why the installer closed without installing anything.
