### ISSUE TITLE
Add the content type to an editor export, unclear

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/visualstudio-docs#2055]
Its says you should add attributes to a class, but you have created 5 classes up to that point? so which one is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80c84be-4fae-ea57-4ce3-1b3c62cae593
* Version Independent ID: 3261010a-d0ba-b2c0-ef2d-aba46e101ad6
* Content: [Walkthrough: Linking a Content Type to a File Name Extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-linking-a-content-type-to-a-file-name-extension?view=vs-2017#add-the-content-type-to-an-editor-export)
* Content Source: [docs/extensibility/walkthrough-linking-a-content-type-to-a-file-name-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-linking-a-content-type-to-a-file-name-extension.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
