### ISSUE TITLE
Tool window internal command is being set up in the command to show the window

### ISSUE THREAD

**Issue by dkrikun** [MicrosoftDocs/visualstudio-docs#2056]
The command to play the media which belongs to the tool window itself, is being set up in the same code that sets up the command to find and show the tool window in the first place. Two problems:
1. It feels like it would be better to separate these concerns, by moving the code to set up the tool window commands etc. into the tool window code (FirstToolWindow.cs). It's not clear how one could do this because it is not clear how to obtain the command service inside `ToolWindowPane` children constructor.
2. If you close then reopen the tool window, an exception is thrown because the command service already has the media open command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554db2bb-c0c2-d694-be77-44cb0fd311f8
* Version Independent ID: e7a691ea-7540-f6c4-46e4-66abdbd07c37
* Content: [Adding a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window?view=vs-2017)
* Content Source: [docs/extensibility/adding-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-tool-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
