### ISSUE TITLE
Incorrect version download for MPF

### ISSUE THREAD

**Issue by dulazhere** [MicrosoftDocs/visualstudio-docs#2086]
The link provided for MPF is for Visual Studio 2010-2013 but this is listed under Visual Studio 2017. I came here from "https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1?view=vs-2017#test-the-template-registration" where they ask to download MPF and look for a file called ProjectBase.files which does not exist in the download from this link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 616affe3-8417-fab8-4a92-15a71dde6646
* Version Independent ID: a8aafe78-e9ae-ee89-0a9a-e80c3e0ba939
* Content: [Using Managed Package Framework for a Project Type (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/using-the-managed-package-framework-to-implement-a-project-type-csharp?view=vs-2017)
* Content Source: [docs/extensibility/internals/using-the-managed-package-framework-to-implement-a-project-type-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/using-the-managed-package-framework-to-implement-a-project-type-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by Silthrim** [comment]
Did you find a solution?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
