### ISSUE TITLE
missing example for "IVsProjectUpgrade"

### ISSUE THREAD

**Issue by cbries** [MicrosoftDocs/visualstudio-docs#2201]
In the documentation
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/upgrading-projects.md
the following is stated:

>> For a sample implementation of xref:Microsoft.VisualStudio.Shell.Interop.IVsProjectUpgrade, see VSSDK Samples.

But fact is there absolutly no example provided, sad.

Search "IVSProjectUpgradeViaFactory" (0 hits in 0 files)
Search "ProjectUpgrade" (0 hits in 0 files)
Search "IVsProjectUpgrade" (0 hits in 0 files)

**Comment by gewarren** [comment]
This is the section with the link: https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/upgrading-projects?view=vs-2017#upgrading-custom-projects

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
