### ISSUE TITLE
Generate Code Map For Solution - Unable to Connect to the Specified Database

### ISSUE THREAD

**Issue by user905** [MicrosoftDocs/visualstudio-docs#2232]
Using Windows 7, sp1, Visual Studio 2017 Enterprise throws the following error when attempting to generate a code map:

Unable to connect to the specified database.

An exception occurred attempting to connect to a database using the following connection string:
  Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=;Initial Catalog=master;Integrated Security=True;Enlist=False;Asynchronous Processing=True;MultipleActiveResultSets=True;Connect Timeout=30.

Check that the specified SQL Server instance exists and the service is running.

This is for an app that uses SQL Server 2012. SQL Server 2016 is not installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c6b3cd-fc32-1501-68a6-1da597bfd33b
* Version Independent ID: 499fd553-6e2e-aefe-aefd-2711c01e39e0
* Content: [Code maps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2017)
* Content Source: [docs/modeling/map-dependencies-across-your-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/map-dependencies-across-your-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by user905** [comment]
More details here: https://stackoverflow.com/questions/54246967/generate-code-map-for-solution-unable-to-connect-to-the-specified-database

**Comment by WilliamAntonRohm** [comment]
@user905 Apologies for the lateness of this reply, and thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
