### ISSUE TITLE
Set up without typescript

### ISSUE THREAD

**Issue by coch110149** [MicrosoftDocs/visualstudio-docs#2245]
Can this doc be updated to how to set this up without typescript. Whenever I use a .jsx I get syntax errors. I am not sure which loader I should use.

**Comment by coch110149** [comment]
Content: Create a Node.js and React app - Visual Studio
Content Source: docs/javascript/tutorial-nodejs-with-react-and-jsx.md

**Comment by Mikejo5000** [comment]
@coch110149 You can do the same app with babel as the specified compiler in the webpack configuration file instead of the TypeScript compiler (loader: 'ts-loader' would need to be changed). I have made the app work with JS and babel in the past, but we didn't want two separate documents. You are seeing syntax errors in VS when adding more JSX code? Or you see errors when transpiling the JSX code from the command line? Did the exact steps in the tutorials work for you as-is?

**Comment by Mikejo5000** [comment]
Closing this as it is a nice-to-have doc addition, but would complicate the existing doc to show both methods.
