### ISSUE TITLE
COMFileReference details

### ISSUE THREAD

**Issue by DaveInCaz** [MicrosoftDocs/visualstudio-docs#2265]
Perhaps the remarks about COMFileReference could be expanded. Things that I have read elsewhere:

* The point of this project items seems to be that you can use it to compile .NET code that references COM components without the COM components being registered on the build server (instead of COMReference). But this isn't really explained.

* The COM dll doesn't need to be registered on the machine for this to work.

* Each COMFileReference item can also have a WrapperTool attribute

* The EmbedInteropTypes attribute is not documented as being applicable to COMFileReference, but it seems to work as intended.

* Since Visual Studio provides no designer support for COMFileReference, you must edit the project/build file by hand.

* During a build, MSBuild extracts the type library information from the COM DLL and creates an interop assembly that can be either standalone or embedded in the calling .NET assembly.

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e663f7-3bac-61af-28bb-f0e471dcdca6
* Version Independent ID: 97985f56-e0ac-a03d-f651-b86cc2b85804
* Content: [Common MSBuild Project Items - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#comfilereference)
* Content Source: [docs/msbuild/common-msbuild-project-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-items.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Would you recommend adding these items to the section on COMFileReference?

**Comment by Mikejo5000** [comment]
@rainersigwald Does this doc seem like a good place to put this info? The descriptions are mostly short descriptions, so it doesn't match the doc pattern too well.

**Comment by rainersigwald** [comment]
I agree that we should probably not put _all_ of this info in this doc, but that it could be clearer. Some of this applies to `COMReference`, too.

Maybe:
1. "Represents a list of type libraries that are passed to the `TypeLibFiles` parameter of the [`ResolveComReference` task](https://docs.microsoft.com/en-ca/visualstudio/msbuild/resolvecomreference-task)." instead of "that feed into the ResolvedComreference target" which is both misspelled and not useful.
1. A brief "this item applies only to managed projects" note.

Some of this probably belongs on the task input doc which is better suited to detail:
* "doesn't need to be registered"
* `EmbedInteropTypes` metadata (also applies to `COMReference`/the `TypeLibNames` input

cc @AaronRobinsonMSFT for more COMReference domain knowledge.

**Comment by AaronRobinsonMSFT** [comment]
@rainersigwald 's comments are spot on.

>2. A brief "this item applies only to managed projects" note.

I would make it clear both of these items are for only for .NET projects.

**&lt;rant&gt;**
Both the `COMReference` and `COMFileReference` items are incredibly confusing and boarder on seemingly designed to breed confusion in COM scenarios. When I hit issues, I often need to dig through the targets file to understand what is happening and even then don't always understand why.
**&lt;/rant&gt;**

**Comment by pvvl** [comment]
Maybe it is also worthwhile mentioning that the usage of COMFileReference without EmbedInteropTypes=true is vulnerable to race conditions if two assemblies try to generate the same interop on the same folder quasi-simultaneously. We ran into this problem several times and ended up generating the Interops in a separate build step to circumvent such collisions.
