### ISSUE TITLE
Compiling IronPython to DLL

### ISSUE THREAD

**Issue by boustrephon** [MicrosoftDocs/visualstudio-docs#2269]
It would be great to see something about compiling IronPython to DLLs. I know we can do it using pyc, but it is not clear whether this is available in PythonTools for VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59f61b3-8cae-f461-e85e-5c159a56e7c4
* Version Independent ID: 80d076a4-12f3-e0b2-7793-33e8d8f1840a
* Content: [Manage Python application projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-projects-in-visual-studio?view=vs-2017)
* Content Source: [docs/python/managing-python-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@boustrephon Thanks for filing the issue. The Python Tools for Visual Studio don't provide the capability of compiling to a DLL, which is why you don't see anything about it in the documentation. Are you expecting to at least see a note regarding the possibility with pyc? Generally speaking, the VS docs aren't the place to go into details on this, so I wanted to clarify with you what would be most helpful in terms of mentioning the possibility.

By the way, if this is a kind of feature that you'd like to see in VS, then file an issue at https://github.com/Microsoft/ptvs/issues.

**Comment by kraigb** [comment]
Closing due to lack of response. Feel free to reopen if needed.

**Comment by boustrephon** [comment]
Hi kraigb, sorry about the slow response on my part. 

Obviously my preference would be for there to be a tool/template for compiling to pyd/dll, but failing that, I think it would be helpful to see a note that says that Visual Studio does not provide this with a link to the repository that contains pyc.py.

I have added an issue as suggested. https://github.com/Microsoft/PTVS/issues/5071
