### ISSUE TITLE
Screenshots with code?

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/visualstudio-docs#2270]
It would be great to have snippets of code that can be copied rather than screenshots of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2017)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by NickCraver** [comment]
It's worth noting the screenshots (I'm pretty sure) are also wrong in the `pathSegment` case. This barrier greatly ups the cost of fixing the documentation. If it weren't for the screenshots (diff theme, matching prefs, etc.) I'd submit a PR instead of this comment :)

The `pathSegment` is missing the actual rule to apply, it has:
```json
  "dependentFileProviders": {
    "add": {
      "pathSegment": {}
    }
  }
```
when you really need a rule, like this:
```json
  "dependentFileProviders": {
    "add": {
      "pathSegment": {
        "add": {
          "ExtensionMethods.*": [ ".cs" ]
        }
      }
    }
  }
```
I hit he same thing as another user and had to find how to make it work a bit haphazardly: https://stackoverflow.com/a/55145320/13249. Alternatively, it's magic in ways neither of us understand that should probably be better documented.

**Comment by gewarren** [comment]
@AngelosP Can you take a look at this feedback?

**Comment by AngelosP** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/3877

**Comment by NickCraver** [comment]
@AngelosP please note from my comment above - the example in one screenshot was also wrong :) The conversion is much appreciated!

**Comment by AngelosP** [comment]
Oops, I'm sorry @NickCraver I missed your fix in my original PR. I've updated it as per your feedback https://github.com/MicrosoftDocs/visualstudio-docs/pull/3929. Thank you!
