### ISSUE TITLE
VS2017 Core 2.2 correct project template ?

### ISSUE THREAD

**Issue by edikaufmann** [MicrosoftDocs/visualstudio-docs#2292]
when creating in VS2017 15.9.6 --&gt; Visual C# --&gt; Web --&gt; .Net Core --&gt;
'ASP.NET Core Web Application --&gt;

when choosing the project template from ASP.NET Core 2.2 'Web Application'
Source: indicates SDK 2.2.103:

Now, when the project is built it seems that a wrong template has been picked. 
I.e I do NOT see in the pages e.g. the 'About.cshtml'  in the Pges folder nor do I see any other
'elements' when running the project!
PS: this according to the tutorial in:
https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017

Question what I'm possibly missing here?

thanks for your time and help, ed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@edikaufmann Thanks for letting us know; we'll investigate and report back.

**Comment by TerryGLee** [comment]
@edikaufmann Unfortunately, I cannot reproduce your results; I followed the instructions in the procedure on the [Quickstart: Use Visual Studio to create your first ASP.NET Core web app](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017) page, and when I opened a new project by using the ASP.NET Core Web Application template in Visual Studio 2017 version 15.9.6, I verified that there is a Pages folder that includes the About.cshtml file.

Is it possible that per Step 5 of the [Create a project](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017#create-a-project) section of the page, perhaps you accidentally chose an option other that "Web Application"? That might produce the results that you describe. Also, can you verify the version of the ASP.NET Core template that you are seeing? I noted that the current version of the Web Application template is ASP.NET Core 2.1 (instead of 2.2).

**Comment by edikaufmann** [comment]
@TerryGLee  …. I created a new project and definitely have chosen 'Web Application' ; same issue!

your Quote:
"Also, can you verify the version of the ASP.NET Core template that you are seeing"

??? how/where would I find that info? ????
As said in the previous msg is have seen in VS2017:
- ASP.NET Core 2.2 'Web Application'
- SDK 2.2.103:
Attached what I see in the Solution explorer "MyCoreApp.png"! Might be you know which template have been chosen!
PS: In fact the app is running; just (eg) no 'About' page in the Navbar'
<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div> 
I'm pretty sure I miss something stupid!? Or have a mismatch of libraries!?!?
thanks ed
![mycoreapp](https://user-images.githubusercontent.com/6625322/52072885-5e553a80-2586-11e9-976e-6d614a9e090e.PNG)

**Comment by TerryGLee** [comment]
@edikaufmann Today, we published an updated [Quickstart: Use Visual Studio to create your first ASP.NET Core web app](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017) page that includes refreshed screenshots and information that reflects the current experience in version 15.9.6 of Visual Studio 2017. 

If you'll please take a look at Step 5 of the [Create a project](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2017#create-a-project) section of the page again, you'll see that when you create a new project, the version of the Web Application template is ASP.NET Core 2.1, and that the SDK is version 2.1.503. I realize that this doesn't match what you've reported, but I am at a loss to determine how that happened (even in our Preview version of Visual Studio 2019, the ASP.NET Core 'Web Application' version is still 2.1, although the SDK is version 2.1.600-preview-009472).

However, because this GitHub Issues venue is for solving problems with documentation, and because the documentation is correct and current, I'm not able to help you further with your support request, so I am closing this GitHub Issue.

However, if you'd like to pursue this further, you might consider asking your question on [Stack Overflow](https://stackoverflow.com/search?q=Visual+Studio+2017+ASP.NET+Core). To help you get to the most relevant result, the link I've added goes to a query that includes "Visual Studio 2017" and "ASP.NET Core".    

Alternatively, if you think that this is a product problem that you'd like to see our software engineers resolve, please use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by edikaufmann** [comment]
@TerryGLee thanks for your time. Yes, with 2.1 it works ... I had a special 'project' where I wanted to test 2.2... will postpone it for some time!
