### ISSUE TITLE
Why the StartNode icon is not the same whenshown in Rehosted Designer and Visual Studio ?

### ISSUE THREAD

**Issue by yanbingms** [MicrosoftDocs/visualstudio-docs#2298]
I want to know how to customize the StartNode icon of the Workflow.
If we can‘t customize the StartNode icon,  we prefer using the icon shown in Visual Studio, but we don't know how to do it.

The icon shown in Rehosted Designer:
<img width="320" alt="in-rehosted-designer" src="https://user-images.githubusercontent.com/5501981/52036431-7b7f0e80-2570-11e9-8848-521b3c385e94.png">

The icon shown in Visual Studio:
<img width="388" alt="in-visualstduio" src="https://user-images.githubusercontent.com/5501981/52036432-7c17a500-2570-11e9-94d5-e5df1119b73a.png">

Highly appreciated if somebody can tell me how to do.

**Comment by WilliamAntonRohm** [comment]
@yanbingms  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
