### ISSUE TITLE
RtlZeroMemory?

### ISSUE THREAD

**Issue by szalkerous** [MicrosoftDocs/visualstudio-docs#2317]
Why does RtlZeroMemory() not qualify as "zero termination" for this analysis rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a60d6b-9b4b-d1e8-3fca-0df426cac2b0
* Version Independent ID: b1ca7b58-be37-8da4-7133-c6f0d33ac284
* Content: [C6054 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c6054?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C6054)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/code-quality/c6054.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c6054.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by WilliamAntonRohm** [comment]
@szalkerous  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
