### ISSUE TITLE
How can I lock the latest and "N" version of vs_buildtools.exe in building my Docker image?

### ISSUE THREAD

**Issue by nelsonjchen** [MicrosoftDocs/visualstudio-docs#2354]
This is from the Dockerfile in the document [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017)

```
# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
```

Doesn't "https://aka.ms/vs/15/release/vs_buildtools.exe" change? If a new version of the VS build tools are released, it will install that new version. 

If that's the case, I'm uncomfortable with this. If I run `docker build .` today, I should be able to run again it in 5 months and get the same image. Is there a link to a bootstrapper that's bound to the latest version of the build tools?

I understand and fully appreciate that only the latest versions of VS are supported but I struggle with my DevOps side with an image where the dependencies aren't locked and aren't reproducible.

I found a page for [N-1 (15.8.9) versions and below of the build tools but it's N-1 ](https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017). How can I link to N (15.9.6) in my Dockerfile? Would the only way to make a reproducible Docker image be to use those unsupported "N-1" versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
You need to create a network layout as described in https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio. But why are you building a new container image each time anyway? The immutable nature of images (and typically tags should follow, except for the ubiquitous `:latest` tag) are how you retain a fixed image. Not even in typical Linux-based container images using, say, apt-get, create an immutable image across machines because one or more of those packages may change. The best way to lock to a specific version to tag and push that image for use across your network.

**Comment by nelsonjchen** [comment]
I'm interested in keeping the Docker image generally reproducible from the Dockerfile without doing a network installation ahead of time. If I miss a component in a previous build or some other change needs to be made to the image, I would like to be able to reinstall an exact version of Visual Studio in the image. If I was building an image at 15.9.2, I would like to be able to rebuild the image at 15.9.2 later. Am I SOL in creating a VS Build Image at 15.9.2 if I missed creating a network installation of 15.9.2 at this time? 

As for the typical Linux-based container images, with `apt-get`, I can specify versions and lock down as much as I want.  I could do `apt-get install foobar=1.6.0`. It will install foobar@1.60 today and it will install it 5 months from now if I rebuild the image. Package resolution could result in different packages, while meeting the requirements, being installed but I can lock it down more package versions. This just doesn't seem to be a possibility with the bootstrapper.

**Comment by nelsonjchen** [comment]
To put it another way. I can lock `clang` to the latest and currently released version in a Linux container if I do something like `apt-get install clang=x.x.x`. If I rebuild that container 4 months from now, I can still get that exact version. I can't see how to do that with VS without a network installation.

**Comment by heaths** [comment]
We do currently not support that because many updates contain regular security fixes. You don't need to create an entire network layout, however. You can use the first part of the instructions to save the channel and pass that to both the `--installChannelUri` and `--channelUri` to always install that version without downloading all the payloads. Save that file with your Dockerfile and you can keep it all together in source control.

**Comment by nelsonjchen** [comment]
OK, that works for my needs. I wish there was a list of ChannelUris but this is good enough.
