### ISSUE TITLE
When to use .editorconfig versus .NET Analyzers?

### ISSUE THREAD

**Issue by nbarbettini** [MicrosoftDocs/visualstudio-docs#2382]
I'm a big fan of Roslyn analyzers like https://github.com/DotNetAnalyzers/StyleCopAnalyzers. It looks like there is some overlap here in enforcing code style (naming conventions, formatting conventions).

Should I think of .editorconfig as a built-in way to enforce this, and Roslyn analyzers as the "advanced" case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani or @kendrahavens could you comment on this question?

**Comment by mavasani** [comment]
@nbarbettini I think you are confusing couple of completely different, but complementary aspects - _analyzers_ and _analyzer configuration_:
1. Analyzers: Extensions that analyze source code and report violations. Some analyzers are built-into VS (like the IDE analyzers that report style issues) and some are third party ones which can be installed (like StyleCopyAnalyzers, FxCopAnalyzers, etc.)
2. Analyzer configuration: Configuration file(s) to allow end users to control the behavior of each analyzer and severity of reported diagnostics. This may be via an editorconfig or a ruleset file (see https://github.com/dotnet/roslyn-analyzers/issues/1844 for clarification of differences between these) or even completely custom format specific to the third party analyzer package.

IDE analyzers support configuration via editorconfig, see [here](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) for available options and semantics.
StyleCop analyzers do not support editorconfig based configuration, but use their own stylecop.json with their own custom format, that end users can provide in their project for configuration of stylecop analyzers.

Hope that clarifies things.

------------

PS: @gewarren - Now even the FxCop analyzers supports editorconfig based configuration - see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md), which was added very recently to FxCop. We should actually document FxCop analyzer configuration via editorconfig somewhere, with possible links from configurable CA rule documentation pages, which clearly states legacy FxCop does not support such a configuration.

**Comment by mavasani** [comment]
@nbarbettini Leaving aside the analyzer configuration aspect, and just discussing the overlap between IDE analyzers and StyleCop analyzers, you are correct that there is indeed an overlap here, but there are subtle differences (@kendrahavens please correct me if I am wrong or missing something here):

1. VS IDE built in rules are a hybrid of code style and code quality rules to help improve your code base for better maintenance and use of new language features. These rules are enhanced with every VS release or new C#/VB language version release to recommend using new language features that came in the release.
2. StyleCop analyzers is a third party implementation of _only_ code style rules, and mostly a port of an older StyleCop tool which had a different implementation. These rules allow you to configure certain coding styles over others, neither of which might be superior to other, but generally help enforce certain style preferences of a repo.

**Comment by mavasani** [comment]
@gewarren Given this issue and https://github.com/dotnet/roslyn-analyzers/issues/1844, and numerous other prior queries that I have received in this area, we probably need to document the differences between the following somewhere:

1. IDE analyzers vs. third party analyzers, especially StyleCop analyzers given the built-in VS IDE rules are mostly code style rules.
2. Analyzers vs Analyzer Configuration - almost every one seems to view that `editorconfig = VS IDE code style` , `ruleset = legacy FxCop or CA rules` and StyleCop analyzers is a superset of IDE code style, primarily because it has lot more style rules and configuration options and can also be enforced on CI. All of these are incorrect assumptions that confuse/intermix complimentary aspects.
3. [EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017) vs [Ruleset file](https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2017) vs [Additional file](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md) - All of these are different end user _configuration mechanisms_ for analyzers, and they can all co-exist.

Also tagging @jinujoseph and @vatsalyaagrawal as an FYI - once we have such a documentation page, we should point all users confused between these aspects to this page.

**Comment by gewarren** [comment]
Thanks Manish @mavasani. I've created two work items to cover the necessary documentation. I'll send it over for review sometime in March.

**Comment by gewarren** [comment]
The [analyzers FAQ](https://docs.microsoft.com/visualstudio/code-quality/analyzers-faq?view=vs-2017) page is live now. Let me know if there's anything else I should add.
