### ISSUE TITLE
Highlighting functionality for SQL Server 2017

### ISSUE THREAD

**Issue by norbertjohn** [MicrosoftDocs/visualstudio-docs#2502]
Great article and I implemented successfully in Visual Studio 2017. I have a requirement to implement the same in SQL 2017 but the same code is not working there? Is it feasible and if yes, what are the additional steps I should consider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9b97b4-5893-dbc1-c40d-2e3511f2db8b
* Version Independent ID: 40d09c59-7697-ded6-c912-375c98ad2f54
* Content: [Walkthrough: Highlighting Text - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-highlighting-text?view=vs-2017)
* Content Source: [docs/extensibility/walkthrough-highlighting-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-highlighting-text.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@stevestein Do you have an extensibility expert on board?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
