### ISSUE TITLE
The python app created in visual studio cannot be published?

### ISSUE THREAD

**Issue by imeya** [MicrosoftDocs/visualstudio-docs#2586]
just want to confirm, when use visual studio to create a python web app -&gt; then publish it(not iis, just web app), then the web does not work? I published a python web app, and get the page "Your App Service app is up and running".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a03cb3-5472-d3bc-3b4b-7eda41f2e22e
* Version Independent ID: dd54b123-53a5-e328-ea74-54fab50a6e6c
* Content: [Publish a Python app to Azure App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/publishing-python-web-applications-to-azure-from-visual-studio?view=vs-2017)
* Content Source: [docs/python/publishing-python-web-applications-to-azure-from-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/publishing-python-web-applications-to-azure-from-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Hi @imeya. Currently, Python is officially supported only on Azure App Service for Linux. However, publishing from Visual Studio directly to Azure App Service on Linux using the "Publish" command is _not_ presently supported. That's why the doc page here instructs you to use Git deploy or Containers instead, which are the necessary routes

Python does still work on Azure App Service on Windows, and you can publish from Visual Studio in that case. However, you must do some configuration on App Service first, however, and create the appropriate web.config file. Instructions are on https://docs.microsoft.com/en-us/visualstudio/python/publish-to-app-service-windows?view=vs-2017. (This link is given at in a callout at the top of the article you refer to here.)

The message you're seeing on App Service is the default page that indicates you haven't actually deployed any custom code. Again, more work is necessary to publish from VS to App Service on Windows, or you need to publish using a different mechanism for App Service on Linux.
