### ISSUE TITLE
Visual Studio Example Solution VB

### ISSUE THREAD

**Issue by pmg1963** [MicrosoftDocs/visualstudio-docs#2614]
I am having difficulty getting the vb code to work.  Why cant you have a link to a properly working solution file that can be downloaded and run in VS, like they do on Code Project Pages, see for example https://www.codeproject.com/Articles/1004699/VB-NET-runtime-control-designer-for-windows-forms?msg=5594985#xx5594985xx.    Near the top of the article is "Download the VB.NET sample project ControlDesigner_Demo_VS2012.zip - 171.7 KB".  You should provide that for all your example code, saves us time in having to type everything.  Is there any simpler example of Intellisense that I could see? I am making my own code editor and want to include intellisense feature

**Comment by gewarren** [comment]
@pmg1963 Sorry that the VB code isn't working. Is this the article you're referring to? https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-creating-a-core-editor-and-registering-an-editor-file-type?view=vs-2017

**Comment by pmg1963** [comment]
No I was trying the [https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-statement-completion?view=vs-2017](url) example.

Can I have a link to a working VB example?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
