### ISSUE TITLE
Must Select Project, Not Solution

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/visualstudio-docs#2732]
In steps 1 and 2 under the "Publishing an existing project" section, it refers to selecting the Solution and not the Project. However, it is the other way around. The Project must be selected and not the Solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* Content: [Setting up a Git Repository - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository#publishing-an-existing-project)
* Content Source: [mac/set-up-git-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/set-up-git-repository.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by jmatthiesen** [comment]
Thanks for the feedback, using the latest version (8.1) of Visual Studio for Mac, I’m seeing that the Publish option works whether the Solution or Project is selected. If you’re seeing this isn’t the case, please report the issue using the Help > Report a Problem menu, since it would be a product issue.
