### ISSUE TITLE
Can I comment out a section in the sln file?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/visualstudio-docs#2766]
Can I comment out some rows in `sln` file?
The `#` does not really comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* Content: [Solution (.Sln) File - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2017)
* Content Source: [docs/extensibility/internals/solution-dot-sln-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-dot-sln-file.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by tom-corwin** [comment]
I opened an issue in the MSBuild repository a month ago about this, so It's at least on the backlog. 
See: https://github.com/microsoft/msbuild/issues/4328

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
