### ISSUE TITLE
What about running Java code?

### ISSUE THREAD

**Issue by erelsgl** [MicrosoftDocs/visualstudio-docs#2767]
Is it possible to run Java code from Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970f0d59-b2b4-7082-1c2c-a468c93571ef
* Version Independent ID: a3135966-c343-5a6b-cd97-772a0c34fd93
* Content: [Develop code without projects or solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions?view=vs-2017)
* Content Source: [docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by chrishoen** [comment]
never run java code ever

**Comment by WilliamAntonRohm** [comment]
@erelsgl Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
