### ISSUE TITLE
A Quick Review section does not work

### ISSUE THREAD

**Issue by dulazhere** [MicrosoftDocs/visualstudio-docs#2772]
This section directly contradicts with what's in https://docs.microsoft.com/en-us/visualstudio/extensibility/upgrading-custom-project-and-item-templates-for-visual-studio-2017?view=vs-2017. In there under Template Scanning it says starting Visual Studio "scanning is performed only for the user-level location. The default user-level location is %USERPROFILE%\Documents\&lt;Visual Studio version&gt;\Templates\. " So please make your documentation consistent.

Furthermore, I tried the steps described in the "A Quick Review" section and it doesn't work. I don't see a new MyProjectNode project type as shown in the picture. The picture is also from an older version of Visual Studio. Please update documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f6a71-101a-044c-d1bb-f4710bd360bf
* Version Independent ID: bbeb5949-b533-c48d-ef2f-87a89689f118
* Content: [New Project Generation: Under the Hood, Part One - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/new-project-generation-under-the-hood-part-one?view=vs-2017)
* Content Source: [docs/extensibility/internals/new-project-generation-under-the-hood-part-one.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/new-project-generation-under-the-hood-part-one.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
