### ISSUE TITLE
VSPackage not in the project

### ISSUE THREAD

**Issue by mevanecek** [MicrosoftDocs/visualstudio-docs#2782]
When creating the SimpleProject as a VSIX project, there is no VSPackage nor SimpleProjectPackage in the project. Where do those come from? The code snippet implies that SimpleProjectPackage should have other code in the class, but there's no indication how to create the file. Using Visual Studio 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8135def2-30e0-d9e4-af54-5a8d3a073c63
* Version Independent ID: fea902ab-e883-51bd-c291-04d1988f37f6
* Content: [Creating a Basic Project System, Part 1 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1?view=vs-2017#create-a-basic-project-type)
* Content Source: [docs/extensibility/creating-a-basic-project-system-part-1.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-basic-project-system-part-1.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
