### ISSUE TITLE
Needs Updated for VSTU 3.9.x, Unity 2018.x

### ISSUE THREAD

**Issue by DanVicarel** [MicrosoftDocs/visualstudio-docs#2807]
Unity now supports .NET Standard, so we no longer need to use "Unity 3.5 .net Subset Base Class Libraries"  for the target framework.  The screenshot in the `Unity debugging` section should be updated to reflect this.  

Also, Unity 2018.2+ now supports debugging via .pdb files directly, without a .mdb file.  It would be nice to see some updated documentation about this, as I have been unable to debug a managed plugin using only the .pdb so far (full setup is Visual Studio 15.9.7, VSTU 3.9.0.3, Unity 2018.3.6f1, managed .dll and .pdb side-by-side in the `Assets/Plugins` folder, but still cannot debug.  Also no .mdb file is being generated, even though I shouldn't need it.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56378a75-b639-d64b-d7fb-00a7eafa20b5
* Version Independent ID: c66870c5-4153-7b42-7aad-fc454c39f9cd
* Content: [Using Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019#unity-debugging)
* Content Source: [docs/cross-platform/using-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/using-visual-studio-tools-for-unity.md)
* Product: **visual-studio-windows**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by sailro** [comment]
Hello @DanVicarel 

Yes Unity supports .NET standard, but you can still target the legacy runtime. That's why we keep 3.5 profiles so far.

If you are targeting the new runtime, you should be able to debug using a PDB, but you have to make sure that this PDB is a portable-pdb. It will not work with legacy PDB files.

Indeed we have to update the documentation regarding this.

Thank you!

cc @therealjohn

**Comment by DanVicarel** [comment]
@sailro Thanks for the reply!

How do I know if I'm using a portable-pdb, or generate one if I'm not?  Also, if I use a portal-pdb, will Unity still generate the mdb? If possible, I'd like to turn off that behavior so the mdbs aren't taking up space in my repository.

**Comment by sailro** [comment]
A PDB is a portable-PDB if the first 4 bytes are 'BSJB'. You can make sure you are generating Portable-PDB by checking your project properties in Visual Studio:

Project/Properties, select the Advanced button.
In the Debugging information list, choose Portable (instead of Full or Pdb-only).

Regarding Unity and VSTU, starting with VSTU 3.8.0.0, if your project is targeting the new runtime and the PDB file is a portable-PDB, we will not convert the PDB file to MDB.

**Comment by DanVicarel** [comment]
@sailro Sorry for the late reply, and thanks for the explanations.  Your solution worked!  Not sure if this Issue should be marked closed until the documentation is updated, but for my purposes, the Issue is resolved.

**Comment by sailro** [comment]
Great. Thank you I updated the documentation accordingly.
