### ISSUE TITLE
IDebugMemoryContext2 == NULL

### ISSUE THREAD

**Issue by silverfrost** [MicrosoftDocs/visualstudio-docs#2808]
Under what circumstances can this function return S_OK and yet pContext is set to NULL (it does happen)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28f6a3c-455b-40de-54c3-8eb595ae06cd
* Version Independent ID: 92adc886-3a77-961c-fc83-008bcac4242f
* Content: [IDebugObject::GetMemoryContext - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/idebugobject-getmemorycontext?view=vs-2017#feedback)
* Content Source: [docs/extensibility/debugger/reference/idebugobject-getmemorycontext.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/debugger/reference/idebugobject-getmemorycontext.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
