### ISSUE TITLE
How to include items from "Show all" list, in your toolbox?

### ISSUE THREAD

**Issue by MortInfinite** [MicrosoftDocs/visualstudio-docs#2813]
I'm trying to figure out how to add items, which are shown in the "Show all" list of toolbox items, to my general list of toolbox items - But haven't found this subject described anywhere.

The "Show all" list contains elements I'm interested in seeing in my toolbox, but there doesn't seem to be any way for me to include those items. Clicking "Choose items" will open a dialog which will allow me to select between 5 different categories of components, to add to the toolbox, but these do not include the same items as are displayed in the "Show all" list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f92855d-5247-0ffa-ef6f-cb654d7b26a7
* Version Independent ID: 54b3a6ba-badb-29c0-f3b4-f013414263aa
* Content: [Toolbox window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/toolbox?view=vs-2017#feedback)
* Content Source: [docs/ide/reference/toolbox.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/toolbox.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I'm guessing that this is a product design flaw. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
