### ISSUE TITLE
Wizard instructions don't work without assembly codebase

### ISSUE THREAD

**Issue by mcurland** [MicrosoftDocs/visualstudio-docs#2816]
The ProvideCodeBase attribute on the assembly pointing to the dll in the package folder (or the equivalent [$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{NEW GUID}] entry in the .pkgdef file) are absolutely required to make this work. This may be added automatically in newer project types, but is definitely not there in older ones (my wizard builds in the same project for all 8 VS versions from 2005 to 2019). VS2017, however, is the first time I've tried an MSI and GAC-free installation, so this may not apply to earlier versions.

As far as I can tell, the Assembly Asset tag in the vsixmanifest has no affect. You must provide a codebase to the assembly to see it from an item template in VS2017.

This article is incomplete and even harmful without this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* Content: [How to: Use Wizards with Project Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2017#feedback)
* Content Source: [docs/extensibility/how-to-use-wizards-with-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
