### ISSUE TITLE
No explaination of the ProvideCodeGenerator & ProvideCodeGeneratorExtension Attributes and the new way of registering Single File Generators

### ISSUE THREAD

**Issue by NoRelect** [MicrosoftDocs/visualstudio-docs#2818]
It would be great if you would explain the concepts behind the ProvideCodeGeneratorExtension and ProvideCodeGenerator Attributes, as they seem to be the new way of registering Single File Generators, no more Registry hacking needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffe0e292-13f2-0d70-1759-7d750d840c3a
* Version Independent ID: 1f92ed1b-94fb-092e-c604-d891fe22c8d5
* Content: [Registering Single File Generators - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators?view=vs-2019)
* Content Source: [docs/extensibility/internals/registering-single-file-generators.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/registering-single-file-generators.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by BrunoJuchli** [comment]
For managed, is the following still the must current solution:?
https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/SingleFileGenerator

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
