### ISSUE TITLE
Suggested Refinement

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/visualstudio-docs#2828]
If your target overrides the one that has an empty definition in an imported targets list, as does this one, the override must appear last, or the predefined target overwrites it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a060d-7dc1-5826-8beb-f47097d0928f
* Version Independent ID: cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7
* Content: [Copy Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2017)
* Content Source: [docs/msbuild/copy-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/copy-task.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@txwizard. So, it looks like the proposal is to add the text to the example section, after the first sample code? Can you clarify the suggestion below:
"If your target overrides another target that has an empty definition in an imported targets list, as in the preceding example, the override must appear last, or the predefined target overwrites it."
I don't see an imported targets list, so that confuses me a bit. @rainersigwald for comment

**Comment by rainersigwald** [comment]
In this case, there's no override of targets because these minimal example projects don't have any imported targets. But we should indeed mention the last-one-wins nature of targets in more places; the only one I found was in [How to: Extend the Visual Studio build process](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019#override-predefined-targets), but it would be relevant in [the Targets overview](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets) and the [Target element](https://docs.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?view=vs-2019).

**Comment by Mikejo5000** [comment]
OK, thanks, I'll plan to update.
