### ISSUE TITLE
Standalone Program with finshed DSL AND graphical Interface?

### ISSUE THREAD

**Issue by fuzzifikation** [MicrosoftDocs/visualstudio-docs#2835]
Hello,

I'm trying to deploy my own DSL into a standalone program that many people can use. Here, unfortunately, "You can use Windows Forms to display the state of a domain-specific language (DSL) model, instead of using a DSL diagram."

Well.. I'd like to do just this other thing.. namely implement the DSL and its graphical designer into a standalone program (wpf of something like it). How can I do that? Is such a feature planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211cc693-f42f-c8a6-1a94-698c20d32e57
* Version Independent ID: 8dd135d0-0dca-17af-0961-e2da4e545bf4
* Content: [Creating a Windows Forms-Based Domain-Specific Language - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/creating-a-windows-forms-based-domain-specific-language?view=vs-2017)
* Content Source: [docs/modeling/creating-a-windows-forms-based-domain-specific-language.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/creating-a-windows-forms-based-domain-specific-language.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@fuzzifikation  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
