### ISSUE TITLE
What is this .SDF Magic you speak of....

### ISSUE THREAD

**Issue by CheetahChrome** [MicrosoftDocs/visualstudio-docs#2843]
How does one create a SQL Compact database, exactly in VS 2019? For this article to be relevant, that information needs to be linked or accurately presented, because SDF database files were dropped in what...VS 2015? Correct me if I am wrong. :-/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1351cc8-f703-27a2-32c7-904256cb9e82
* Version Independent ID: 7a6912ef-da8d-6690-6da9-cc741fd5acde
* Content: [Create Data-Driven Unit Tests - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2019#create-a-data-source)
* Content Source: [docs/test/how-to-create-a-data-driven-unit-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-data-driven-unit-test.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@CheetahChrome Thanks for the feedback. We should update this page.

**Comment by CheetahChrome** [comment]
Thank you, I know your all work hard on this and in re-reading my words, it was a touch, well flippant. To that I apologize if taken wrong.

**Comment by gewarren** [comment]
@CheetahChrome No offense taken! It's very helpful to get direct feedback about what exactly is out of date.

**Comment by JimInWA** [comment]
**Short answer**

You need to download and install an extension.  The link indicates that you should be able to use it in VS2019
- https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox

**Longer answer**

I think the last version of Visual Studio that included direct support (no need for extension) for creating SQL Compact Database (SDF files) was Visual Studio 2012.

SQL Compact Database is deprecated.  There **was** a Connect article about that but since Connect was turned off it is redirecting to rather useless Docs page:
- https://connect.microsoft.com/SQLServer/feedback/details/776328/port-sql-compact-to-windows-rt
- https://docs.microsoft.com/en-us/collaborate/connect-redirect

Here is a link that has the relevant text from the Connect article as its answer:
- https://superuser.com/questions/1218648/creating-a-sql-server-compact-edition-database-file-in-microsoft-visual-studio-2

**Follow-up question**

Considering the fact that SQL Server Compact has been deprecated and support will end in 2021, could this documentation be updated to provide an alternative approach that is supported beyond that timeframe?

**Comment by gewarren** [comment]
@AbhitejJohn What's the currently recommended way to create a data source for data-driven tests?

**Comment by AbhitejJohn** [comment]
@gewarren : [This](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2019#specify-the-datasourceattribute) should be helpful. @cltshivash would be able to help with examples perhaps.(Just can't seem to tag him on this repo - perhaps he isn't a member here yet).

**Comment by gewarren** [comment]
@AbhitejJohn The [Unit test basics Q&A](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019#qa) shows an example that uses an Access database. Would it be appropriate to change the example in the Create data-driven tests article to use an Access database instead of SQL Compact?

**Comment by AbhitejJohn** [comment]
@gewarren: perhaps. @cltshivash would be the right contact for that though.
