### ISSUE TITLE
no quick info displayed

### ISSUE THREAD

**Issue by AdrianPistoleanu** [MicrosoftDocs/visualstudio-docs#2866]
Hi guys, can you check this again, please ? Looks like it triggers the quick info (hits the "m_session = m_provider.QuickInfoBroker.TriggerQuickInfo(m_textView, triggerPoint, true);" line) but nothing happens afterwards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28863dd2-b54a-4733-ebc7-57d0235bfc95
* Version Independent ID: b9062a5a-ac9a-d8c5-00d9-204a6bd98d30
* Content: [Walkthrough: Displaying QuickInfo Tooltips - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-quickinfo-tooltips?view=vs-2017#feedback)
* Content Source: [docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by Barina** [comment]
Doesn't work for me either. I had to change obsoleted references to their Async version though..

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
