### ISSUE TITLE
MIssing information: How to create an SDK

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/visualstudio-docs#2886]
There's info about using SDKs (they're a great simplification!). but I'm not finding any information on how to create your own SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 911666fa-55ac-cbc1-ce79-66c058859ad9
* Version Independent ID: 571eec5d-8fb9-2401-fc4c-8a7896723eb7
* Content: [MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2017)
* Content Source: [docs/msbuild/msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Paul-Dempsey There is a topic on how to reference a project SDK:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017

**Comment by Paul-Dempsey** [comment]
The question is NOT how to reference an SDK, it is how to CREATE one.

________________________________

**Comment by gregvanl** [comment]
@Paul-Dempsey Would this be what you're looking for? https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-software-development-kit?view=vs-2019

**Comment by Paul-Dempsey** [comment]
Yes, that is what I was looking for. I didn’t find this when searching for MSBuild SDK (or net core SDK.) The problem is that this is under Visual Studio, not with MSBuild where I expect information on MSBuild project formats.  I expect stuff under Visual Studio to be related to Visual Studio IDE. The docs under MSBuild that talk about the new SDK project format and how to reference SDKs should at least have a link to SDK construction, but I didn’t find any.

________________________________

**Comment by Paul-Dempsey** [comment]
Actually now that I read that topic, I’m not so sure that is what I’m looking for. What I’m talking about is the new msbuild SDK project style, for example:

<Project Sdk=“Microsoft.Build.Traversal”>

The question is how to create one of these.

________________________________

**Comment by Mikejo5000** [comment]
@Paul-Dempsey Unfortunately, I don't think there is a current doc on that. @rainersigwald in case he has a suggestion here.

**Comment by rainersigwald** [comment]
I don't think we do. @jeffkl, can you think of anything?

The important thing to remember when authoring an SDK is that it's just a top/bottom import. Anything in `Sdk.props` will be the first thing imported, and anything in `Sdk.targets` will be the last thing. Otherwise, they're standard import files.

Other guidelines:

* If it's possible to implement what you need as a standard NuGet package that delivers build logic, you should do so.
* Minimize the size of the SDK--put only the bare minimum logic you need in it, and use it to add a NuGet package reference if you need tasks or other payload.
* Where possible, allow the user to to set properties in the body of the project--don't set properties unconditionally in `Sdk.targets` or its imports.

There are several examples that you can learn from at https://github.com/Microsoft/MSBuildSdks.

**Comment by Paul-Dempsey** [comment]
I don’t like reverse-engineering. I like to read documentation, so I know what the rules are (at least a clue what they’re supposed to be), and that everything relevant is covered – no single sample or an instance covers all the applicable ground.

Thanks for the info. I hope to see a page soon on creating your own MSBuild SDK, including specifics on the nuget packaging. I think this is a better way of creating and managing build features I need to share across repos – way better than managing git submodules.

:- P

**Comment by jeffkl** [comment]
We did not officially document how to create them, only consume them.  Rough draft:

Has to have an `Sdk` folder with an `Sdk.props` and `Sdk.targets`
Only ship an MSBuild project SDK if:
  1. You need to extend the NuGet Restore logic (because NuGet packages aren't on disk when restoring)
  2. You need to define a custom project type like Traversal or NoTargets.
  3. You want to extend a project type that doesn't support PackageReference (.vcxproj, .ccproj, .sfproj, and .nuproj).  

Keep them very very small.  Depending on the project type, when resolving the SDK in Visual Studio the UI is blocked.  If the SDK is large this can cause customer pain.

**Comment by ghogen** [comment]
The scope of the documentation doesn't include creating MSBuild SDKs, only consuming them. This could be a good project for a whitepaper or third-party blog.

**Comment by ghogen** [comment]
https://github.com/dotnet/docs/issues/18977
related issue
