### ISSUE TITLE
Please provide more guidance.

### ISSUE THREAD

**Issue by MariusMyburg** [MicrosoftDocs/visualstudio-docs#2909]
I love the fact that the C++ Core Guidelines are part of Visual Studio now.

However, in at least this case, this page does not provide guidance; it is more of a comment, which is useless. I got this warning in my code, and I pressed F1 on the warning to find a suggested solution to the problem. Instead of a solution, I find a page stating only "don't do this". I'd like to note here that that is not very helpful. 

The statement:

"Never return (either formal return or out parameter) any pointer from a function."

Is all well and good, but what exactly should I return then? 

I added a null-check before my return statement, but the code analysed seems to not know that I have thereby ensured that I cannot return a null pointer, and the warning remained.

I changed my code to return a reference instead, but my code still gives the same warning.

I would like for the MSDN documentation to not just vaguely say "Don't do this.", but to be more practically useful by showing how returning pointers should in fact be eliminated. I.e. if the preferred method is to return a shared_ptr instead, then that should be stated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f0eb39-d71b-dfe8-30da-dcd2c0bd9e15
* Version Independent ID: d778b17f-bfa2-ee82-ab27-08735a91f04c
* Content: [C26487 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26487?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C26487)%26rd%3Dtrue&view=vs-2017#feedback)
* Content Source: [docs/code-quality/C26487.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26487.md)
* Product: **visual-studio-windows**
* GitHub Login: @kylereedmsft
* Microsoft Alias: **kylereed**

**Comment by corob-msft** [comment]
@MariusMyburg 
The rule could be expanded to "Never return (either by a return statement or an out parameter) any pointer *to a local variable or parameter* from a function." That makes the reason obvious, because what it points at is going to go out of scope when the function returns. In that case, it doesn't matter if you check whether the pointer is null or not, or make it a `shared_ptr`, or turn it into a reference. It points at something that's about to disappear. If you're lucky, your code will crash immediately when you dereference the pointer. More likely, you'll be accessing and possibly trashing some random stack location, and causing difficult to diagnose problems that surface later on.

If you must return a pointer instead of a value, the way to resolve this warning is to return a pointer to something that outlives the function call. To fix the issue, you can either return a pointer to memory that was passed in to the function, or a pointer to a static variable, or you can allocate memory and return a pointer to it (along with ownership). A `shared_ptr` is fine for that, though not required.

**Comment by MariusMyburg** [comment]
@corob-msft Hi Colin. I like your suggestion; the text that you added in italics is really critical to describing what the suggestion is really all about. More than making the reason for the warning obvious, it makes the reason correct, as without this text, it actually seems to be saying to never return any pointer from any function whatsoever. So yes, I like it, your proposed change to the wording would have made it clear :) Thanks for your feedback.

**Comment by corob-msft** [comment]
This update should get published later today, or possibly Monday if it missed the cutoff.
