### ISSUE TITLE
Clarification - Microsoft.VisualStudio.Component.SQL.SSDTBuildSku-SQL Server Data Tools - Build Tools

### ISSUE THREAD

**Issue by patware** [MicrosoftDocs/visualstudio-docs#2919]
What is included in Microsoft.VisualStudio.Component.SQL.SSDTBuildSku	SQL Server Data Tools - Build Tools.

Does it include SSAS, SSIS, SSRS build/compile ?  (*.dtproj)  

If so, please add the information in the "Name" column above, and in the description (hover text in the Visual Studio Build Tools 2017 Installer).

If not, what is needed to build a SSAS, SSIS, SSRS build/compile ?  (*.dtproj)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@patware Thanks for the suggestion; at this time, we cannot modify the page as you describe for the following reasons:

1. It's an automated pull of data from the product manifest itself and because of the frequency in which we update the page, it's not feasible to manually modify it to provide the additional information that you seek. 
1. We choose not to offer product information in a "hover over" format, as that presents accessibility issues.

That being said, I will inquire to see if I can find the information you seek, but my reply will most likely be delayed. If you need an immediate answer, another alternative that you can pursue is asking your question on [Stackoverflow](https://stackoverflow.com/search?q=visual+studio+build+tools+2017+SQL+Server+Data+Tools) (the URL includes the following search string elements: "visual studio build tools 2017" and "SQL Server Data Tools".) 

Thanks,
~ Terry

p.s. Another source of information that might be useful to you is the [SQL Server Data Tools Team Blog](https://devblogs.microsoft.com/ssdt/).

**Comment by TerryGLee** [comment]
@patware This page might also be useful to you: [Download and install SQL Server Data Tools (SSDT) for Visual Studio](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017).

**Comment by TerryGLee** [comment]
@patware The answers you seek are best found in the link I previously listed:  [Download and install SQL Server Data Tools (SSDT) for Visual Studio](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017).

Also, this page might prove useful, too: [Project migration and upgrade reference for Visual Studio](https://docs.microsoft.com/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects). 

And if you cannot find what you're looking for on those two pages, you could also ask a question or search for answers to similar questions on the [MSDN forums](https://social.msdn.microsoft.com/Forums/home).

Otherwise, for reasons previously posted, we cannot change the referenced page to include the information you're asking for. Therefore, I am closing this issue.
