### ISSUE TITLE
Inadequate - most of what you put is obvious

### ISSUE THREAD

**Issue by dotfield** [MicrosoftDocs/visualstudio-docs#2933]
Firstly what is PreBuildEvent.bat you mentioned? You put the events into the dialog and it appears in the makefile.
I note if you have two if doesn't create a different &lt;PreBuildEvent&gt; tag for it but puts them in the same one.
How do I make it conditional to targets being up to date?
How do I have a custom "clean" to remove the files generated by this step?

A lot of pre-build is code generation. csproj is not very good at that, C++ project files are better but even then doesn't really work that well other than manually editing the project files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e9cb58-9d4b-7b53-40c0-3c9c232a27bd
* Version Independent ID: 92405b1b-7ec7-51d2-ddd2-c2fd47d167b0
* Content: [How to: Specify build events (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-build-events-csharp?view=vs-2017#feedback)
* Content Source: [docs/ide/how-to-specify-build-events-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-specify-build-events-csharp.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by ghogen** [comment]
I'm not sure this is possible in the IDE, but we should add guidance on how to modify the project file to support this.  

You can create a target element and specify a condition:
https://docs.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?view=vs-2019

You can use the BeforeClean and AfterClean tasks to extend the clean functionality so that you could remove those auto-generated files:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019

In general, it seems we should provide more guidance in the VS docs for extending and customizing the build process. This could range from more references to the MSBuild docs to providing tutorials and examples of common build extension tasks.
