### ISSUE TITLE
Pictures of code

### ISSUE THREAD

**Issue by maryob77062** [MicrosoftDocs/visualstudio-docs#3014]
Please don't use pictures of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36a7fc54-584b-4ae2-ad71-6343ad8e2801
* Version Independent ID: 0784bf12-f389-3660-ae7a-1641a82d3e46
* Content: [Convert foreach loop to LINQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019)
* Content Source: [docs/ide/reference/convert-foreach-linq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/convert-foreach-linq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by kendrahavens** [comment]
Could you let me know why? Are you wanting to copy the code and try out the codefix for yourself or is there another reason? I could definitely add the triggering code to this doc:

```csharp
var greetings = new List<string>()
    { "hi", "yo", "hello", "howdy" };

IEnumerable<string> enumerable()
{
    foreach(var greet in greetings)
    {
        if(greet.Length < 3)
        {
            yield return greet;
        }
    }

    yield break;
}
```

I use pictures so that it is obvious where the cursor is that triggers the refactoring and what the refactoring menu should look like. Thanks for your help on this!

**Comment by maryob77062** [comment]
Same as at Stack Overflow. Need to copy a bit or the whole thing. Pictures of code are not acceptable.
