### ISSUE TITLE
Create Unit Tests restricted?

### ISSUE THREAD

**Issue by kaimikael** [MicrosoftDocs/visualstudio-docs#3020]
I have looked in Visual Studio Community 2017 and 2019 for Windows as well as Visual Studio for Mac Community 8 and none of them have the menu option “Create Unit Tests” shown in the section “Generate unit test project and unit test stubs”.  Is this a feature restricted to the Pro/Enterprise versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66fe9e04-c830-3350-3ff9-9a3ecb7cfe5e
* Version Independent ID: e1063d2e-aace-86b2-a4b4-6378c45c55a0
* Content: [Unit Test Basics - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2017)
* Content Source: [docs/test/unit-test-basics.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-test-basics.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@kaimikael Thanks for your inquiry. The documentation per the page that you referenced is correct in that it says "Running unit tests after every build is supported only in Visual Studio Enterprise." It also mentions Visual Studio Enterprise a few other times on the page. So, if you are running the Community edition instead of the Enterprise edition, that's why you aren't seeing the **Create Unit Tests** option in the context menu.

**Comment by gewarren** [comment]
@kaimikael The [Create Unit Tests](https://docs.microsoft.com/en-us/visualstudio/test/create-unit-tests-menu?view=vs-2017) menu command is only available for managed code that targets the .NET Framework (but not .NET Core). Does that help to explain why you're not seeing the command?
