### ISSUE TITLE
"Suppress violations from the Error List" only works when file is open

### ISSUE THREAD

**Issue by inthemedium** [MicrosoftDocs/visualstudio-docs#3029]
1. Create a new .net core project in vs 2019
2. PackageReference Microsoft.CodeAnalysis.FxCopAnalyzers, version 2.9.1
3. Change code to have an analyzer issue
4. Close file, close solution.
5. Reopen solution
6. Build
7. Right-click on the analyzer issue

Expected:
  The suppression sub-menu
![image](https://user-images.githubusercontent.com/510739/55757502-958f0e80-5a43-11e9-995b-ea94eaa61bf1.png)

Actual:
  No suppression sub-menu. Note that opening the file where that issue is located will bring up the suppression sub-menu.
![image](https://user-images.githubusercontent.com/510739/55757639-f4ed1e80-5a43-11e9-93df-3b1951f506de.png)

Is this by-design or a bug? If it is by-design, please document it!

-Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Is the suppression menu in the Error List only available when the file with the warning is open, or is this a bug? If bug, should it be logged at Developer Community?

**Comment by gewarren** [comment]
@inthemedium Manish pointed out that the error you're seeing is likely coming from static code analysis. These errors can't be suppressed from the Error List because the code might have been changed since you last built. To only see errors from FxCop analyzers, change the filter in the Error List from "Build + IntelliSense" to "IntelliSense Only". Another option might be to enable full solution analysis, which allows FxCop analyzers to run on closed files too (note that buliding is not required for FxCop analyzers).

For reference, see [this section in the docs](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#suppress-violations-from-the-error-list).
