### ISSUE TITLE
will Microsoft.VisualStudio.Workload.NativeDesktop contain all the listed sub components?

### ISSUE THREAD

**Issue by yingang** [MicrosoftDocs/visualstudio-docs#3031]
I've used the following command to create an offline installation:

vs_professional.exe --layout e:\vs2017lite --lang en-US --add Microsoft.VisualStudio.Workload.NativeDesktop

and the result folder (e:\vs2017lite) is about 1.03GB.

Then I run the vs_setup.exe in the folder and select the "Desktop development with C++" to install. But the installer still prompts me that there are about 1.61GB to be downloaded. Why?

Update: if I don't specify any workload, the offline folder would be about 40.6GB and it won't prompt to download anything before installing "Desktop development with C++".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe411145-ff47-dfe5-1e57-db8d54671b58
* Version Independent ID: 4dac6d72-8c3c-dec8-d473-a2902e4e1fb9
* Content: [Visual Studio Professional workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2017#desktop-development-with-c)
* Content Source: [docs/install/workload-component-id-vs-professional.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-professional.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@yingang Thanks for your inquiry @tydunkel FYI

**Comment by tydunkel** [comment]
@yingang When adding workloads to a layout the recommended and optional components are not included by default. When selecting a workload manually in the VS Installer, recommended components are included by default. The extra downloads needed likely comes from these recommended workloads.

When creating the layout, recommended components can be included with `--includeRecommended`. Otherwise, if they are not wanted, you can deselect all of the components that appear under the "Desktop development with C++" node in the "Installation details" of the installer.

See [Customize a layout](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017#customize-the-network-layout) for more details.

**Comment by yingang** [comment]
@tydunkel, thanks for your elaborate explanation.
