### ISSUE TITLE
Why no reusable offline Cache via GUI

### ISSUE THREAD

**Issue by bernd5** [MicrosoftDocs/visualstudio-docs#3040]
In the past I was not able to create an working offline cache which does not require a working network connection.

The installer is still checking something even if I downloaded it via Layout cmd.

What I would really like is to have a GUI (as you have) wich stores the required files in a cusomizable location to create a reusable offline installer of Visual Studio.
What is so difficult to do that?

**Comment by TerryGLee** [comment]
@bernd5 It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
