### ISSUE TITLE
The Short Explanation Cover more details about R. But i Would Suggest one Thing Please Add Module about how to Integrate with SQL And Asp.Net Website. 

### ISSUE THREAD

**Issue by hariomsharma151** [MicrosoftDocs/visualstudio-docs#3057]
[Enter feedback here]

---
The Short Explanation Cover more details about R.
But i Would Suggest one Thing Please Add Module about how to Integrate with SQL And Asp.Net Website. 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde63717-000d-d97c-0898-36c005d8541f
* Version Independent ID: 4c63fc76-7fac-4e58-cca7-e8476cb1248f
* Content: [Getting started with R Tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/getting-started-with-r?view=vs-2017)
* Content Source: [docs/rtvs/getting-started-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/getting-started-with-r.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the suggestion. However, because R Tools for Visual Studio is no longer supported in Visual Studio 2019 (in favor of Azure Notebooks), the R docs for Visual Studio 2017 are no longer being actively updated or improved except for critical fixes. I'm sorry to bear such news, because I appreciate the suggestion, but the reality is that we won't be following up with this issue further.
