### ISSUE TITLE
toggle live analysis

### ISSUE THREAD

**Issue by Caleb-D** [MicrosoftDocs/visualstudio-docs#3064]
We have custom Roslyn analyzers and a huge solution.  The combination is slow.  Laggy text editing.  Frequent pauses of the UI.  Could a toggle for ALL live analysis in all projects be added?  I really like the live code analysis rules, but would like it only to run during a build (like the static code analysis).

I know there is a toggle for Full Solution Analysis, but this doesn't help.  I also have the experimental, separate process option selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36455e6f-5542-5223-b242-9cddf6df267c
* Version Independent ID: 946abcdb-7e41-b5b5-e062-9cd8c914fbd3
* Content: [Code analysis using Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019#feedback)
* Content Source: [docs/code-quality/roslyn-analyzers-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/roslyn-analyzers-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@Caleb-D It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

**Comment by Caleb-D** [comment]
Actually, there is a submission there already.  Didn't realize this was only for documentation.
