### ISSUE TITLE
Filter on Write do not work for VB.net 2019

### ISSUE THREAD

**Issue by Jean-Georges** [MicrosoftDocs/visualstudio-docs#3073]
I installer version 2019 to finally get a filter for my variable on the Write action and it still does not work. 
I got 1 Blank for the definition and 518 Read, no write !
Jean-Georges Marcotte

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ff86d8-c851-8bfa-3357-09350f76bd95
* Version Independent ID: af88c525-6027-4e0e-7417-23e16f386f21
* Content: [Finding references in your code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-references?view=vs-2019&viewFallbackFrom=vs-2015#feedback)
* Content Source: [docs/ide/finding-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Jean-Georges Thanks for your feedback; we appreciate it. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
