### ISSUE TITLE
define question

### ISSUE THREAD

**Issue by SashaSenichkin** [MicrosoftDocs/visualstudio-docs#3079]
how can i manage define elements from code? can i assosiate it with project constants or complication symbols?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c201c2-b5d4-0d8a-22b0-1d6bc2604a9c
* Version Independent ID: 43b6d5e7-0635-e279-a607-de70ba35a9b0
* Content: [Define Element - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/define-element?view=vs-2019)
* Content Source: [docs/extensibility/define-element.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/define-element.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
