### ISSUE TITLE
Accessing Docker via browser failed 

### ISSUE THREAD

**Issue by sergejkaiser** [MicrosoftDocs/visualstudio-docs#3084]
I tried to run this docker image on a local machine but I keep on being unable to open the container in the browser. 

docker run -v $pwd:/home/sergej -p 6056:5444 --name my-rtvs-container my-rtvs-image:latest rtvsd

fail: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionFilter.OnConnection
System.AggregateException: One or more errors occurred. (A call to SSPI failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3

**Comment by WilliamAntonRohm** [comment]
@sergejkaiser  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
