### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by nurbles** [MicrosoftDocs/visualstudio-docs#3086]
"user options" is far too generic unless every single setting a user can manipulate is stored in this file on a per-project basis.  Since I know this is untrue, this page is missing critical information.  When I need to decide how important the .suo file is to me, I need to know the specific options or at least option groups that are stored in this file.  This article provides neither a hint about the necessary info nor a link to a page that does document what specific options may be stored in the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f6ddb0-af89-71ec-024e-fcb25a55e75f
* Version Independent ID: 69c03fac-d6c4-c41c-6cfe-47e5b5ae2e42
* Content: [Solution User Options (.Suo) File - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-user-options-dot-suo-file?view=vs-2019#see-also)
* Content Source: [docs/extensibility/internals/solution-user-options-dot-suo-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-user-options-dot-suo-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
