### ISSUE TITLE
Automate deletion of branches for merged PRs

### ISSUE THREAD

**Issue by SimonCropp** [MicrosoftDocs/visualstudio-docs#3096]
![image](https://user-images.githubusercontent.com/122666/56262568-90f0e700-6122-11e9-9b29-ba66e3982251.png)

**Comment by TerryGLee** [comment]
@gewarren FYI

**Comment by gewarren** [comment]
@SimonCropp Thanks, I've deleted those branches now. Can you suggest automation for deleting them automatically? For the masterxxxxxxxxx branches, those are generally deleted automatically when they are merged, but due to a glitch in our system that has since been fixed, those PRs had to be manually merged and then they branch wasn't automatically deleted.

**Comment by nschonni** [comment]
This might work (if you have access to Actions) https://github.com/jessfraz/branch-cleanup-action

**Comment by gewarren** [comment]
We discussed this and decided not to pursue it at this time. Only a few contributors have write perms to the repo, so in most cases there would be no branch to delete as it would be in the user's fork, not the main repo. The one exception is the masterxxxxx branches that get created as part of our private-public sync, but when things are working properly, those seem to be deleted automatically, for example in this [PR](https://github.com/MicrosoftDocs/visualstudio-docs/pull/3097):

![image](https://user-images.githubusercontent.com/24882762/56319621-0e165f00-6117-11e9-9bf6-272f28dd92ed.png)

(It shows that I merged/deleted, but in fact that was done for me by some automation.)

**Comment by SimonCropp** [comment]
thanks peoples
