### ISSUE TITLE
Promote flag

### ISSUE THREAD

**Issue by isaac-a-pendergrass** [MicrosoftDocs/visualstudio-docs#3141]
Just a note that there is no mention of the promote flag here. I assume most people would be creating the service to be accessible outside of the package it is registered in. A quick mention would be great. May save someone needless headaches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4999b84e-a7f2-1ffc-6d02-d439ff0330de
* Version Independent ID: 7755af16-b4f5-e3b8-798f-35ea143ad306
* Content: [How to: Provide an Asynchronous Visual Studio Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-provide-an-asynchronous-visual-studio-service?view=vs-2017#feedback)
* Content Source: [docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @isaac-a-pendergrass Thanks for the suggestion. PRs welcome.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
