### ISSUE TITLE
ActiveProjectFlavor:<projectTypeGuid> and SolutionHasProjectFlavor:<projectTypeGuid>

### ISSUE THREAD

**Issue by Emdot** [MicrosoftDocs/visualstudio-docs#3168]
For a list of possible &lt;projectTypeGuid&gt; values, see https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs and https://www.mztools.com/articles/2008/MZ2008017.aspx. These lists aren't necessarily complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9786c88-8bd3-8d62-5132-743e44b41dda
* Version Independent ID: 0bd057a1-b51c-b617-ca99-3979b4729f26
* Content: [How to: Use Rule-based UI Context for Visual Studio Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions?view=vs-2019#feedback)
* Content Source: [docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
