### ISSUE TITLE
VisibilityConstraints Context?

### ISSUE THREAD

**Issue by kdawg1406** [MicrosoftDocs/visualstudio-docs#3186]
The topic would be much better if you have VisibilityConstraints in context with where it is in the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1723bf1-2209-4ea2-2072-8ea949a0585b
* Version Independent ID: 3cc58555-77e6-f50e-bb73-fdfb547b5d54
* Content: [Making Commands Available - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/making-commands-available?view=vs-2019)
* Content Source: [docs/extensibility/internals/making-commands-available.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/making-commands-available.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
