### ISSUE TITLE
Target build order doc is incorrectly worded / confusing

### ISSUE THREAD

**Issue by tmat** [MicrosoftDocs/visualstudio-docs#3189]
https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2019#determine-the-target-build-order

> 4. Before a target is executed **or skipped**, if its `Condition` attribute was absent or did not evaluate to false, its DependsOnTargets targets are run.

I don't think "or skipped" should be in the sentence. Either the target condition is true/absent and then targets in DependsOnTargets as well as the target itself are executed, or is false and then it's skipped and DependsOnTargets are not run.

> 3. The Condition attribute of the target is evaluated. 

It would be useful to clarify exactly when is the condition evaluated. In evaluation phase, thus changes in the values of properties the condition reads that happen after evaluation phase have no effect?

**Comment by tmat** [comment]
@rainersigwald

**Comment by rainersigwald** [comment]
I'm not sure how to concisely explain these, hopefully @Mikejo5000 has some ideas. As it stands the document is correct (but not necessarily _clear_).

The "or skipped" line is referring to an incrementally-up-to-date target (that has a condition that does not evaluate to `false`). It's conveying that MSBuild will ensure that its `DependsOnTargets` will run before deciding whether or not the tasks in the target will run (due to incrementality).

💭 Maybe say "Before a target is executed (or skipped if it's up to date)", possibly with a link to [the incremental-build doc](https://docs.microsoft.com/en-us/visualstudio/msbuild/incremental-builds?view=vs-2019)?

The condition is evaluated at execution time, using the state of property values set at the time of step 3 of the order for that target: after any already-mentioned targets have run, but before `DependsOnTargets` is handled.

**Comment by Mikejo5000** [comment]
I like your suggestion here, Rainer. I'll update it.

**Comment by tmat** [comment]
AH, that makes more sense. I'd define what "skipped" means before "MSBuild determines the target build order as follows:". Something like "A target is considered _skipped_ if it is not executed because it's outputs are up-to-date wrt its inputs (see incremental build).".

Then the point 4: "Before a target is executed or _skipped_ its DependsOnTargets targets are run, unless the `Condition` attribute is applied to the target and evaluates to _false_."

**Comment by tmat** [comment]
> The condition is evaluated at execution time, using the state of property values set at the time of step 3 of the order for that target: after any already-mentioned targets have run, but before DependsOnTargets is handled.

That makes it very clear. Thanks!

**Comment by Mikejo5000** [comment]
Updating the PR. I'd prefer to define "skipped" after first mention, otherwise reader will not have much context for it.

**Comment by tmat** [comment]
@Mikejo5000 As you see fit. I'm used to specifications that define terms they use upfront.
