### ISSUE TITLE
How to guide on creating new solution templates in Visual Studio for Mac

### ISSUE THREAD

**Issue by jbachelor** [MicrosoftDocs/visualstudio-docs#3233]
What I've been trying to find in the documentation is how to create a new solution template. I have certain boilerplate code and project structures I like to use, and would like to be able to share those with my team and others I am trying to help learn. Is there any such guide you could link to here, possibly a new entry under "See also":  "Creating new templates in Visual Studio 2019 for Mac"? Would really love this... Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776b3956-55f3-6f3e-640c-d322203a8395
* Version Independent ID: 700a8e79-12a9-d4b9-7984-980e1cb9ed7f
* Content: [Creating new Projects and Solutions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-new-projects?view=vsmac-2019#feedback)
* Content Source: [mac/create-new-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-new-projects.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @jbachelor this is not supported in Visual Studio for Mac right now. 

Since there is some shared code with the open source project MonoDevelop, you might find some of its documentation helpful https://www.monodevelop.com/developers/articles/project-templates/ although this has not been tested.

Thanks for your feedback - it's helpful for us to know this is something you'd use.

**Comment by jbachelor** [comment]
Thanks so much for getting back to me, @conceptdev. I hope it is something that will eventually be supported. It would be super helpful!
