### ISSUE TITLE
File names are important.

### ISSUE THREAD

**Issue by johnholliday** [MicrosoftDocs/visualstudio-docs#3238]
It should be stressed in the walk-through that Visual Studio employs a strict naming convention for files and other resources.  As an example, in the section entitled "Creating a basic project template", the reader is instructed to create a Templates/Projects/SimpleProject folder structure containing 4 files.  It would be helpful to point out that during template registration, the base name of the icon file must match the base name of the ".myproj" file.  If it does not match exactly, then the icon will not be associated with the project type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8135def2-30e0-d9e4-af54-5a8d3a073c63
* Version Independent ID: fea902ab-e883-51bd-c291-04d1988f37f6
* Content: [Creating a Basic Project System, Part 1 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1?view=vs-2019)
* Content Source: [docs/extensibility/creating-a-basic-project-system-part-1.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-basic-project-system-part-1.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
