### ISSUE TITLE
Can I get my code to be called when the debugger stops/resumes?

### ISSUE THREAD

**Issue by daveyostcom** [MicrosoftDocs/visualstudio-docs#3258]
See [this](http://github.com/daveyostcom/DateTimeDebug).

I would like the debugger to call `DateTimeDebug.Running = false` when it stops, and `DateTimeDebug.Running = true` when it resumes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9dcc5d-ade9-c88a-76f6-538231671b0b
* Version Independent ID: 6d86c444-dba6-8d0e-4b2c-a4cc57c11365
* Content: [First look at the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2019)
* Content Source: [docs/debugger/debugger-feature-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debugger-feature-tour.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@daveyostcom  It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.

**Comment by daveyostcom** [comment]
[Posted feedback here](https://developercommunity.visualstudio.com/idea/572935/i-need-my-code-to-be-called-when-the-debugger-stop.html)
