### ISSUE TITLE
AKS publishing tools for VS2019

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/visualstudio-docs#3259]
Hi, please add more info how to get installation for VS2019. Or how to get similar functionality from VS2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2017)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This topic was updated for VS 2019, but the manual Publish to AKS action is not supported in VS 2019, so that part is not in the VS 2019 version of the topic.   Instead, Azure Dev Spaces can be used for the development lifecycle and the CLI command such as 'azds up' can be used in place of the Publish to AKS procedure during the dev lifecycle.  For production deployment, Azure Pipelines can be used to handle publishing automatically for Kubernetes development.

**Comment by jjindrich** [comment]
Will be greate to add this information to plugin homepage. It's confusing for VS17 -> VS19.
