### ISSUE TITLE
Download fail?

### ISSUE THREAD

**Issue by tedneward** [MicrosoftDocs/visualstudio-docs#3280]
Three times I've tried to do a complete offline cache-download, and all three times I'm getting this failure:

Error: Package 'Cocos2dv1,version=1.5.2' failed to download from 'https://go.microsoft.com/fwlink/?linkid=854219'. WebClient download failed: The decryption operation failed, see inner exception.. Bits download failed: Error context: BG_ERROR_CONTEXT_REMOTE_FILE, Error code: -2145844843. WinInet download failed: Authenticode verification returned 0x800b0100 for path: CocosCreator.exe., Signature: PackageId=Cocos2dv1;PackageAction=DownloadPackage;ReturnCode=0x80131500

Not sure how to diagnose or fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@tedneward Thanks for letting us know, and we're sorry to learn that you're having a problem with your offline cache. Because this venue is for documentation issues, here are some other options to obtain a solution for the installation problem that you're experiencing:

- Contact us via a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
- Use your [GitHub](https://github.com/) account to contact us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

If all else fails, please use the Visual Studio Installer to report the problem to us in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). For more information, see the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) page.

**Comment by armanforghani** [comment]
I have the same problem with VS2017 and VS2019.

```
Error: Package 'Cocos2dv1,version=1.5.2' failed to download from 'https://go.microsoft.com/fwlink/?linkid=854219'. WebClient download failed: The remote server returned an error: (403) Forbidden.. Bits download failed: File not found.. WinInet download failed: Function: HttpQueryInfo-ResponseCode, HR: -2147024493, Message: Url 'https://cocos2d-x.org/filedown/CocosCreator_v1.5.2_win', Signature: PackageId=Cocos2dv1;PackageAction=DownloadPackage;ReturnCode=0x80131500
```
