### ISSUE TITLE
Where is RunTmChk.lib?

### ISSUE THREAD

**Issue by yoelhalb** [MicrosoftDocs/visualstudio-docs#3286]
Where is RunTmChk.lib in VS 2019?
The linker can't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f337c29-9b49-e0bd-1191-a42c2952ce25
* Version Independent ID: 79390d0b-7584-bdf8-a6af-d91d0bbf5d17
* Content: [Using Run-Time Checks Without the C Run-Time Library - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-run-time-checks-without-the-c-run-time-library?view=vs-2019#feedback)
* Content Source: [docs/debugger/using-run-time-checks-without-the-c-run-time-library.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-run-time-checks-without-the-c-run-time-library.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@yoelhalb -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

My apologies for the delay in responding.

**Comment by Mikejo5000** [comment]
Doc is likely out of date and needs an update. Apparently, RunTmChk.lib is removed.
https://github.com/fo40225/Win32Lab/tree/master/DynamicLinkSystemBuiltinCRT
Doc might need to be removed if there's not a workaround.

**Comment by Mikejo5000** [comment]
Removing the doc. The scenario doesn't appear to be supported anymore.
