### ISSUE TITLE
Sync autoloads deprecated

### ISSUE THREAD

**Issue by sinand99** [MicrosoftDocs/visualstudio-docs#3288]
[ProvideAutoLoad(UIContextGuids80.SolutionExists)] attribute causes following error in VS2019 16.1:
"Synchronous auto loads will be deprecated in future versions, consider using BackgroundLoad flag and AsyncPackage base class."
Please update documentation for version 16.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7aca15b-bfa6-33ac-8f45-78d5d6c4ffc0
* Version Independent ID: c3dc31a4-cf7a-4b25-8e39-91cb19565203
* Content: [Creating an Extension with a VSPackage - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-an-extension-with-a-vspackage?view=vs-2019)
* Content Source: [docs/extensibility/creating-an-extension-with-a-vspackage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-an-extension-with-a-vspackage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
