### ISSUE TITLE
'Report a problem' does not work in VS 16.1.0

### ISSUE THREAD

**Issue by bradleyscollins** [MicrosoftDocs/visualstudio-docs#3289]
I'd love to report a problem via the instructions here: https://developercommunity.visualstudio.com/content/problem/post.html?space=8

But the "Report a Problem ..." dialog appears and immediately disappears. Yes, I've tried turning it off & on again. And you provide me no other avenue for reporting *this* bug. Which brings me to how I found this bug—*another* bug: 

Since upgrading to VS 16.1.0 yesterday, I get the following error every single time I open VS 2019:

"Unfortunately, a process used by Visual Studio has encountered an unrecoverable error. We recommend saving your work, and then closing and restarting Visual Studio."

This appears sometimes upon startup. Other times, it appears when I enter a period, and IntelliSense attempts to engage. Other times, it's some other action that appears to trigger the error. (Forgive me: I have not noted every singe occurrence.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by mariaghiondea** [comment]
It sounds like your installation/upgrade wasn't successful. 
Are you able to launch the Visual Studio Installer? If yes, can you please try a repair? Does the Feedback Tool launch from there? That is another place to report feedback from, especially installer feedback.

**Comment by bryanfarrell** [comment]
I'd love to report a similar problem I'm having in 16.1.1.  I click on the link to report the problem and then it fails to authenticate me no matter how many times I try.  It tells me to log into visual studio but the thing is I am successfully logged into Visual Studio.  It appears to be defaulting to Internet Explorer (not Edge or the OS default browser) to go to the report page.  Really need to fix this as I'd like to report issues with Visual Studio 2017/2019 but can't at the moment.

The issues I do want to report are 1, in Visual Studio 2019, when it launches and opens a solution, and the active document in that solution is inside the quick view tab, it throws this error (sorry to report it here hopefully you can move it to correct project: 

System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))at EnvDTE._DTE.get_ActiveDocument()at ReasonCodeExample.XPathTools.ActiveDocument.get_Current() in C:\projects\xpathinformation\ReasonCodeExample.XPathTools\ActiveDocument.cs:line 14at ReasonCodeExample.XPathTools.VisualStudioIntegration.XmlTextViewCreationListener.TextViewCreated(IWpfTextView textView) in C:\projects\xpathinformation\ReasonCodeExample.XPathTools\VisualStudioIntegration\XmlTextViewCreationListener.cs:line 38at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<>c__DisplayClass254_0.<BindContentTypeSpecificAssets>b__1()at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

#2) In both Visual Studio 2017/2019 when using a .NET Standard project, I am getting a yellow triangle with exclamation point on the Dependencies node in the project explorer.  The thing is the project compiles fine and I get not warning that would indicate what the potential problem could be.  It's possible this is being displayed because of a bug when having the project target both .NET 4.5 and Standard 2.0, or also possibly because it's .NET Core project referencing Microsoft.Windows.Compatibility but either way when I drill down through all of the dependencies there are none marked indicating there is a problem.  Only the high level Dependencies node is marked with the warning symbol.  As I said it compiles but if there is an issue a warning of some sort would be great or if it's a bug it should be fixed as it's concerning that something could be wrong with the dependency tree.

Again sorry to put the issues here but until you fix the report a problem page (or also let us do it directly from the website after logging in) I really didn't have a choice but to mention them here in the hopes you will create them in the proper place in the VS bug tracker site.

**Comment by gewarren** [comment]
@bradleyscollins @bryanfarrell Are you still having problems with Report a Problem?

**Comment by bradleyscollins** [comment]
I'm afraid I am. I have done repairs, reinstallations, and version upgrades, but nothing seems to fix it.

When I click **Help > Send Feedback > Report a Problem ...**, a window starts to appear and then immediately disappears.

**Comment by gewarren** [comment]
@bradleyscollins Have you been able to report the "Report a Problem" issue using the report a problem feature in Visual Studio Installer?

![image](https://user-images.githubusercontent.com/24882762/66066555-9ab6ad00-e4fe-11e9-8f72-55ead56c02e3.png)

**Comment by m-pollack** [comment]
I have the same issue 

I have seen this recently 

vs_installershell.exe exception processing message ......

PERHAPS MICROSOFT SHOULD ALLOW US TO REPORT THE PROBLEMS IN A WEB PAGE INSTEAD OF A PAGE THAT TELLS US HOW TO DO IT IN A APPLICATION THAT KEEPS BREAKING 

ON THE OTHER HAND, I AM SURE THE TEAM DOES NOT WANT TO HEAR ABOUT THE ISSUES 
THERE ARE SO MANY THEY MIGHT GET THEIR FEELINGS HURT

**Comment by grimreaper38uk** [comment]
I think it's too late for their feelings.  MS haven't had any for at least a decade.
Same problem here to - authentication error when signing in, despite being signed in in VS.
No way to report the other myriad of errors that have cropped up this morning.

**Comment by m-pollack** [comment]
to make it work take VS out of admin mode

**Comment by WilliamAntonRohm** [comment]
@seaniyer -- Sean, please look into this issue.

**Comment by mariaghiondea** [comment]
For any sign in errors and when you can't submit or have issues with the Feedback Tool in Visual Studio, please email us at vsfeedback at microsoft dot com. You can also post from the C++/.NET spaces on https://developercommunity.visualstudio.com. Those are our avenues for reporting issues and suggestions.
Maria Ghiondea
Visual Studio Feedback System Team
