### ISSUE TITLE
Problems in walkthrough: Creating an SDK using C++

### ISSUE THREAD

**Issue by phraemer** [MicrosoftDocs/visualstudio-docs#331]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-creating-an-sdk-using-cpp.md

* The `Prerequisites` element is missing from the `.vsixmanifest`
* Wrong pri file name. Should be `NativeMathWRT.pri` instead of `SimpleMath.pri`
* Incorrect path in the props file. Should be `DesignTime\Debug\x86` instead of `DesignTime\Retail\x86` (Or the example should work with a Release build)
* In step 11 the paths are formatted incorrectly without back slashes

### InstallationTarget for VS 2017

Properties will not be imported (I only tried in VS2017, maybe it works elsewhere)
The problem is `<InstallationTarget Id="Microsoft.ExtensionSDK" TargetPlatformIdentifier="Windows" TargetPlatformVersion="v8.0"...` will install the extension at `C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0\ExtensionSDKs\` and not `C:\Program Files (x86)\Microsoft SDKs\UAP\v0.8.0.0\ExtensionSDKs\` where a sample UWP app made with VS2017 expects them to be.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
