### ISSUE TITLE
What do I do with this information?

### ISSUE THREAD

**Issue by m-mitchell** [MicrosoftDocs/visualstudio-docs#3335]
I've opened the template log and it has the templates I'm trying to load listed, but the Visual Studio project dialog isn't seeing them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8bdeeea-18b8-cbc5-4b07-69059f185b50
* Version Independent ID: 5eefca01-d41a-d4d3-a74d-2d78724ed2bf
* Content: [Troubleshoot template discovery in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/troubleshooting-template-discovery?view=vs-2019#feedback)
* Content Source: [docs/extensibility/troubleshooting-template-discovery.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/troubleshooting-template-discovery.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by onerob2000** [comment]
Hellloooo?  Anyone?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
