### ISSUE TITLE
VS2019 Offline installer - how to use for Preview versions

### ISSUE THREAD

**Issue by cmjchrisjones** [MicrosoftDocs/visualstudio-docs#3351]
This works great for creating an offline installer for the RC versions, however how can we do the same for the Preview versions, I don't see any mention of it in the docs unfortunately...

**Comment by TerryGLee** [comment]
@cmjchrisjones Thanks for your feedback. We typically do not provide documentation for preview releases other than in the [release notes](https://docs.microsoft.com/visualstudio/releases/2019/release-notes-preview?view=vs-2019) and in [blog posts](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-1-generally-available-and-16-2-preview-1/), mostly because such content can prove difficult to keep updated in a timely fashion, and also because preview releases aren't recommended for a production environment. However, I've inquired with the engineering team regarding your question, and will report back when I have an answer for you.

**Comment by cmjchrisjones** [comment]
Thanks @terryglee

**Comment by TerryGLee** [comment]
@cmjchrisjones The answer from the engineering team is: You should be able to create an offline installer for a Preview edition. In other words, how setup works is identical between Preview and Release versions.  However, there is always a possibility that you might see a new Setup feature in a Preview release, and if so, any documentation for it will be in the in the [release notes](https://docs.microsoft.com/visualstudio/releases/2019/release-notes-preview?view=vs-2019) only.
