### ISSUE TITLE
The latest vs 2019 editor, an error occurred while loading the number of references.

### ISSUE THREAD

**Issue by Dogwei** [MicrosoftDocs/visualstudio-docs#3373]
![QQ截图20190604135837](https://user-images.githubusercontent.com/14845492/58854963-5a226080-86d1-11e9-9902-cf293b08676b.png)

![QQ截图20190604135857](https://user-images.githubusercontent.com/14845492/58854801-eda76180-86d0-11e9-9f06-124a54e13656.png)

And the previous Chinese the number of references as "引用", now become "references".

**Comment by gewarren** [comment]
@dogwei Thank you for letting us know about this error. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
