### ISSUE TITLE
Definition of common location is unclear.

### ISSUE THREAD

**Issue by JimBobSquarePants** [MicrosoftDocs/visualstudio-docs#3409]
There seem to be limitations. It does not appear to be possible to place a shared .editorconfig file in a location that is not a direct root of the child projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b086b-cda0-2741-2b2b-b2d7e87d0ac9
* Version Independent ID: 29465605-4eda-76c5-4254-8976bc17ca37
* Content: [Configure FxCop analyzers using editorconfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/configure-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/configure-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you take a look at this feedback? Are there limitations on where a shared .editorconfig file can live?

**Comment by dchaib** [comment]
I can confirm the issue. I cannot get this to work if the file is not placed in a parent folder of the project. For information, my goal is to share the .editorconfig file across different solutions/repos in my company using a NuGet package.

**Comment by mavasani** [comment]
@JimBobSquarePants @dchaib Are you talking about the approach number 2. mentioned here: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#enabling-editorconfig-based-configuration-for-a-project? Can you please clarify your repro steps and what does not work for you?

**Comment by dchaib** [comment]
Thanks for your quick reply. Yes, that's the one I'm mentioning.
Repro steps:
* create a ConsoleApp (I'm using .Net 4.7.2) in a folder, say c:\Projects\MyApp\
* create an editor config file in a folder that is not a parent, say c:\Projects\Config\, with an `ident_size` of `1`
* create a props file as described in the documentation
* reference it at the top of the csproj
* reformat the code in `Program.cs`

Expected result: the indentation is updated
Actual result: nothing changes

Of course, if I move this `.editorconfig` file to c:\Projects and update the `props` file accordingly, it works. But that is more to do the folder hierarchy than the configuration in the `props` file as suggested by the following test:

* create an .editorconfig with `indent_size = 1` and place it c:\projects
* update the props file accordingly
* create an .editorconfig with `indent_size = 10` and place it in c:\projects\MyApp
* reformat `Program.cs`

Expected result: an indentation of 1, as this the configuration referenced in the project
Actual result: an indentation of 10 (probably because this is the first file up the folder structure)

**Comment by mavasani** [comment]
@dchaib The setup steps mentioned in the above configuration steps are only applicable for FxCop analyzer editorconfig settings mentioned at https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019, not for all the editorconfig settings. All other settings are still directory based.

**Comment by dchaib** [comment]
Thanks for the quick reply @mavasani. This thing between EditorConfig and FxCop is getting really confusing sometimes :)
So I guess, I should be better off copying the editorconfig file from my NuGet package to the root folder of my project. It should then work for both use cases.

**Comment by mavasani** [comment]
Yes, editorconfig implementation in Roslyn compiler and IDE is primarily implicit directory based and has been chosen as the primary analyzer configuration format. We have a feature request [here](https://github.com/dotnet/roslyn/issues/38042), especially the last part in listed items in it, to enable explicit and non-directory based configuration, similar to the way you can specify rulesets from arbitrary directories, to give users more flexibility. The non-directory based editorconfig configuration support for FxCop analyzers rules is just a temporary workaround until the Roslyn feature request is implemented for all analyzer configuration.

**Comment by dchaib** [comment]
I have not been able to copy the file from my NuGet package to the root of the project so I'll be waiting for this feature request then! Thanks again for your help!
