### ISSUE TITLE
How to upgrade VS Enterprise Edition from 2017 to 2019 version?

### ISSUE THREAD

**Issue by KiroHikaru** [MicrosoftDocs/visualstudio-docs#3430]
The Installer did not display the 2019 upgrade option, how to fix this?

![image](https://user-images.githubusercontent.com/30339493/59511356-3be20f00-8ee0-11e9-9e66-50c7332c4299.png)

**Comment by TerryGLee** [comment]
@KiroHikaru Thanks for your interest in our newest version, Visual Studio 2019! Unfortunately, the Visual Studio Installer only updates a previously installed version of Visual Studio. However, you can download Visual Studio 2019 from this page: https://visualstudio.microsoft.com/downloads/.

**Comment by TerryGLee** [comment]
@KiroHikaru I've updated the [Update Visual Studio](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2017) page with information about how to get the newest version of Visual Studio. Because this venue is meant for documentation feedback instead of product feedback (and it sounds like you'd like this information to appear in the product UI itself; specifically, in the Visual Studio Installer), please use our [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) tool to do so. Meanwhile, thanks for helping us improve our documentation!
