### ISSUE TITLE
How do you revert to last commit in Mac VS community.

### ISSUE THREAD

**Issue by rshermanfl** [MicrosoftDocs/visualstudio-docs#3440]
I'm thinking the only way to revert to last commit (or any commit) is console? I mean is that really the case in this day and age? I can't imagine how to cherry pick or anything else in the way of beyond the basics for a code repository...I know, you will say this is free product, a "free" IDE...it's just that several "free" IDEs handle this as a core competency. Jetbrains and even Xcode (but many other examples exist NetBeans, Eclipse, ZenStudio, etc...) Not everyone wants an outside app like Sourcetree...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1ebf72-a4ef-3b5f-99d5-95a0a83973d9
* Version Independent ID: b839d4b7-e42d-758c-2762-8fc7a93551e9
* Content: [Working with Git - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/working-with-git?view=vsmac-2019#feedback)
* Content Source: [mac/working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/working-with-git.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by TerryGLee** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by rshermanfl** [comment]
It seems like maybe this feature does exist? I can't find it in the UI but
there are menmtions about it in the developer blog. Maybe just the page is
missing information.
