### ISSUE TITLE
[Improvement] Page: Writing to the User Settings Store

### ISSUE THREAD

**Issue by TobiasSekan** [MicrosoftDocs/visualstudio-docs#3444]
On this page, i was confused, how can I get the `ServiceProvider` , so you should add
```csharp
[Import]
internal SVsServiceProvider ServiceProvider = null;
```
to the code example and a note box with link to the import page
https://docs.microsoft.com/de-de/visualstudio/extensibility/editor-imports

the same should be added to the pages
* https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-service-information-from-the-settings-store
* https://docs.microsoft.com/en-us/visualstudio/extensibility/using-the-settings-store

happy coding

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda15bb6-a9d7-fbc7-fa47-c75ac51ccc88
* Version Independent ID: f0c858f7-c1fa-4c06-c394-d0de661ed7ee
* Content: [Writing to the User Settings Store - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/writing-to-the-user-settings-store?view=vs-2019#feedback)
* Content Source: [docs/extensibility/writing-to-the-user-settings-store.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/writing-to-the-user-settings-store.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
