### ISSUE TITLE
 Data collector 'Code Coverage" message: Cannot find codecoverage.exe for VS 2019 Professional

### ISSUE THREAD

**Issue by gremlm** [MicrosoftDocs/visualstudio-docs#3514]
I have installed VS 2019 Professional on the build server.
When I am trying to use "vstest.console.exe MyTestAssembly.dll /EnableCodeCoverage" I have the following message: "Data collector 'Code Coverage" message: Cannot find codecoverage.exe". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#feedback)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gremlm From [this conversation](https://developercommunity.visualstudio.com/content/problem/205336/data-collector-code-coverage-message-cannot-find-c.html), it sounds like you need to install Visual Studio Enterprise edition on the build server.

**Comment by TerryGLee** [comment]
@gewarren Thanks for your response. We'll close this GitHub Issue now.

**Comment by gremlm** [comment]
"Provided" answer is not related to this question! 
This question is about Visual Studio 2019 Professional which includes code coverage. I can run it from IDE. but can't run it from command line on the same machine.  "Provided" answer is about Visual Studio 2017, which does not include code coverage.

**Comment by TerryGLee** [comment]
@gremlm Thanks for the further clarification. To make sure that this issue is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by gewarren** [comment]
The [official guidance](https://visualstudio.microsoft.com/vs/compare/) shows that code coverage is only supported on VS 2019 Enterprise edition:

![image](https://user-images.githubusercontent.com/24882762/60045391-a1b95e00-9679-11e9-8ae9-4c8f9ccc40de.png)

@AbhitejJohn Could you comment on why code coverage can be run from the VS 2019 IDE when it shows as not supported?

**Comment by AbhitejJohn** [comment]
@gremlm : Thanks for letting us know. We are only aware of the Code Coverage window showing in SKUs other than Enterprise which is a bug that we've addressed in the latest previews of VS 2019 update-2. A user would **not** be able to invoke code coverage either from the Test menu or from the Test Explorer in non-Enterprise SKUs though. Is that what you are seeing too?
/cc: @gewarren

**Comment by gewarren** [comment]
Reclosing this issue as code coverage is not supported for VS 2019 Professional.

**Comment by gremlm** [comment]
Question: what tools set should be installed for using code coverage from command line on build server, without IDE at all?
I have seen the following : 
- Visual Studio Build Tools
- Visual Studio Test Agent
- Visual Studio Test Controller
but, according to description none of this three has CodeCoverage for using from command line.
By the way, codeCoverage is available as nuget package but where/how to install it?
[nuget](https://www.nuget.org/packages/Microsoft.CodeCoverage/16.1.1)

**Comment by WilliamAntonRohm** [comment]
@gremlm Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by eliassal** [comment]
@rangler2 I did exactly the same thing but always getting 

> Data collector 'Code Coverage' message: Cannot find CodeCoverage.exe..
in azure devops pipeline
Thanks for your help

**Comment by rangler2** [comment]
@eliassal  sorry I don't think I can help much as we have since upgraded to Azure Devops Server 2020.  My suggestion probably only works for the specific version of TFS (2017) when VS2017 Community is installed. I don't remember how I worked out the location to copy the files into... it must have been based on the location where VS2017 had installed into.
