### ISSUE TITLE
visual studio 2019 some of sql processes not working. then i use 2017 edition.

### ISSUE THREAD

**Issue by oshada97** [MicrosoftDocs/visualstudio-docs#3518]

**Comment by TerryGLee** [comment]
@oshada97 Thanks for your feedback; we appreciate it. It looks like you're experiencing a problem with the product, rather than the documentation. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
