### ISSUE TITLE
Building behind Corporate Firewall

### ISSUE THREAD

**Issue by schreibubi** [MicrosoftDocs/visualstudio-docs#3522]
Hi,

I'm trying to build this docker container while being behind a corporate firewall. vs_buildtools.exe fails because it cannot download the required install packages. I tried to specify the proxy in the docker container using environment variables, the netsh command or setting the proxy registry keys, but nothing works. Any idea on how to fix this?

Thanks,

Joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@schreibubi Thanks for writing to us. Please note that this venue is meant for documentation-specific feedback rather than for support-related problems or product-related questions.

For support-related problems, please note that we offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​
 
Here are a few more support options for product-related feedback:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

And here are a few places where you can get answers to general questions from the community:

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by ledettwy** [comment]
Then the documentation should include at least a snippet about how to do this correctly, since it is likely a common use-case, and it is not obvious from existing documentation.
