### ISSUE TITLE
about error rectification

### ISSUE THREAD

**Issue by heshma4357** [MicrosoftDocs/visualstudio-docs#3533]
iam getting the error below even after installing visual studio while createing a chatbox using django.sooo please mail the modify settings to phanigna4357@gmail.com.iam able to see visua studio in my search bar.
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "C:\Users\DELL\Desktop\dj\chatbox\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-ij0fqsag\\twisted\\setup.py
';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DELL\AppData\Local\Temp\pip-reco
rd-dui25rqx\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\DELL\Desktop\dj\chatbox\venv\include\site\python3.7\twisted" failed with error code 1
 in C:\Users\DELL\AppData\Local\Temp\pip-install-ij0fqsag\twisted\

**Comment by msebolt** [comment]
@heshma4357 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
