### ISSUE TITLE
What tools set should be installed for using  Visual Studio 2019 code coverage from command line on build server, without IDE at all?

### ISSUE THREAD

**Issue by gremlm** [MicrosoftDocs/visualstudio-docs#3535]
What tools set should be installed for using  Visual Studio 2019 code coverage from command line on build server, without IDE at all?
I have seen the following  redistributable packages:
- Visual Studio Build Tools
- Visual Studio Test Agent
- Visual Studio Test Controller

but which one of them or other one has  none of them has code coverage for using in command line on build server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#feedback)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@gremlm  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
