### ISSUE TITLE
Are these benefits applicable to any existing MSDN Subscriber?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/visualstudio-docs#3551]
I have been noticing bit of a confusion out in the field about difference between MSDN subscription benefits and Visual Studio Subscription benefits. 

As per my knowledge MSDN Subscription is now called as Visual Studio Subscription. Is there any documentation available that states that the MSDN Subscription is the same as Visual Studio Standard Subscription? 

So are these subscriber benefits applicable to both Visual Studio and MSDN subscriber ? And if so can we add some verbiage or note in that regard somewhere in this documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c83add-3638-8dd7-6f4a-3537aa6adff6
* Version Independent ID: fb37fe41-88ed-e7e1-f701-456625e81adb
* Content: [Visual Studio Subscriptions - Subscriber Benefits](https://docs.microsoft.com/en-us/visualstudio/subscriptions/subscriber-benefits)
* Content Source: [subscriptions/subscriber-benefits.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/subscriber-benefits.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@WilliamAntonRohm - Thanks for reaching out.  MSDN subscriptions became Visual Studio subscriptions about two years ago, so effectively MSDN subscriptions no longer exist.  At about that time we switched over from the old MSDN portal to the new Visual Studio subscriptions portal at https://my.visualstudio.com which provides subscribers with a better experience.   People still call the subscriptions "MSDN" quite a bit because they were called that for a long time.  Over time we should see less use of that term, though, as it no longer applies.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your response to the inquiry; we'll close this issue now.
