### ISSUE TITLE
Analyzing code coverage from the command line is useless  if there is no possibility to specify location and name of the result .coverage file!

### ISSUE THREAD

**Issue by gremlm** [MicrosoftDocs/visualstudio-docs#3553]
Analyzing code coverage from the command line is useless  if there is no possibility to specify location and name of the result .coverage file!
vstest.console.exe ***.dll /EnableCodeCoverage  -and where result, .coverage file is generated? some "default" directory based on the time schema?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@gremlm Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
