### ISSUE TITLE
Download Error in vs_enterprise.exe --layout 

### ISSUE THREAD

**Issue by surviveplus** [MicrosoftDocs/visualstudio-docs#3559]
I want to install Visual Studio 2019 in the limited network .

I read "Install Visual Studio" section of this page and made our network team to open "Microsoft domains".
Then I did "vs_enterprise.exe --layout" command. 

vs_enterprise.exe --layout c:\folder --lang ja-JP

But some errors were shown in downloading.
When I click a prompt window of errors, it was closed.
So I could not get text of errors.

Should we open other URLs?

I know this URL might be used to download in manual from marketplace web site .
https://*.gallerycdn.vsassets.io

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019#feedback)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@surviveplus Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by TerryGLee** [comment]
@surviveplus Here are also a few more options to consider for installation issues:

- We offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
- You can use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers about installation-related issues in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by surviveplus** [comment]
Thank you for your reply.
I will use these supports.

If I solved this issue, I am going to feedback here.
