### ISSUE TITLE
how to use full list while batching? and another question

### ISSUE THREAD

**Issue by wangzimei** [MicrosoftDocs/visualstudio-docs#3560]
q1. in first example, `<Message Text="Number: %(ExampColl.Number) -- Items in ExampColl: @(ExampColl)" />` outputs
```
Number: 1 -- Items in ExampColl: Item1;Item4
Number: 2 -- Items in ExampColl: Item2;Item5
Number: 3 -- Items in ExampColl: Item3;Item6
```
what should i do if i want to output the following in %-caused batching?
```
Number: 1 -- Items in ExampColl: Item1;Item2;Item3;Item4;Item5;Item6
Number: 2 -- Items in ExampColl: Item1;Item2;Item3;Item4;Item5;Item6
Number: 3 -- Items in ExampColl: Item1;Item2;Item3;Item4;Item5;Item6
```

q2. if i write
```
<ItemGroup>
    <ClCompile Include="$(cpp)">
        <ObjectFileName>$(IntDir)%(ClCompile.Identity).obj</ObjectFileName>
    </ClCompile>
    <ClCompile Include="x2.cpp">
        <ObjectFileName>$(IntDir)%(ClCompile.Identity).obj</ObjectFileName>
    </ClCompile>
</ItemGroup>
```
is it same as
```
<ItemGroup>
    <ClCompile Include="$(cpp)">
        <ObjectFileName>$(IntDir)$(cpp).obj</ObjectFileName>
        <ObjectFileName>$(IntDir)x2.cpp.obj</ObjectFileName>
    </ClCompile>
    <ClCompile Include="x2.cpp">
        <ObjectFileName>$(IntDir)$(cpp).obj</ObjectFileName>
        <ObjectFileName>$(IntDir)x2.cpp.obj</ObjectFileName>
    </ClCompile>
</ItemGroup>
```
? here i just want to use the metadata of each item, do not want any batching

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17d417b-9aa2-b39e-53a9-169d8148bf38
* Version Independent ID: e5c51cbf-c4fb-264d-e465-af914ff703f6
* Content: [Item Metadata in Task Batching - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-metadata-in-task-batching?view=vs-2019#feedback)
* Content Source: [docs/msbuild/item-metadata-in-task-batching.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/item-metadata-in-task-batching.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@wangzimei Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by wangzimei** [comment]
@WilliamAntonRohm thank you

i think the doc fails to explain how to use a list reliably, it shows the meaning of @(ExampColl) can change based on the presence of %(ExampColl.Number) or just %(Number)

i tend to believe it's doc bug but "you decide" 😊
