### ISSUE TITLE
What IAM role is required for publish profile?

### ISSUE THREAD

**Issue by shawnstl** [MicrosoftDocs/visualstudio-docs#3561]
What IAM role is required to download the publish profile?  Our development team has this greyed out in the portal.  Is there a specific action that can be granted in a custom role to allow this level of access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d91844e-d0d6-362a-eae7-575a0b03505f
* Version Independent ID: dc6bc695-7c25-8cb2-f4bd-12a866587bb2
* Content: [Publish to Azure App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-azure?view=vs-2019#feedback)
* Content Source: [docs/deployment/quickstart-deploy-to-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/quickstart-deploy-to-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@shawnstl Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
