### ISSUE TITLE
How can i change the Visual Studio 2019 IDE Navigator window size

### ISSUE THREAD

**Issue by serdarsen** [MicrosoftDocs/visualstudio-docs#3567]
I just want to read full name of an active file without dots. Is this possible to change default window size bigger then this?

![2019-07-03 09_09_07-Greenshot](https://user-images.githubusercontent.com/26231317/60567387-8e417d80-9d72-11e9-93fb-41d51d4e7bd7.png)

My environment font size is 14

![image](https://user-images.githubusercontent.com/26231317/60567703-7fa79600-9d73-11e9-95c2-ccfd338bd7d8.png)

**Comment by msebolt** [comment]
@serdarsen It looks like you have product feedback rather than documentation feedback. 

If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. 

For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by serdarsen** [comment]
ok thank you @msebolt i'll do that way than.
