### ISSUE TITLE
How to add MLNET Model Builder extension to MacOS VisualStudio 2019 ?

### ISSUE THREAD

**Issue by luto65** [MicrosoftDocs/visualstudio-docs#3577]
Currently it is not possible to add the .vsix MLNET Model Builder extension in Mac OS.
Can you please fix this  and provide detailed examples on how to achieve this.
The lack of support of .vsix for MacOS is preventing the use of MLNET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81fd881-9387-165a-846c-37025ccf433b
* Version Independent ID: a0bfdf42-fc87-0b73-8cdb-fb935434be70
* Content: [Extending Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac?view=vsmac-2019#feedback)
* Content Source: [mac/extending-visual-studio-mac.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-sdk**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by msebolt** [comment]
@luto65 It looks like you have product feedback rather than documentation feedback. 

If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. 

For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
