### ISSUE TITLE
How do I isolate all of the settings in Visual Studio 2017 from Visual Studio 2019?

### ISSUE THREAD

**Issue by Brandon-Gui123** [MicrosoftDocs/visualstudio-docs#3579]
Currently, I've been facing a lot of issues with the syntax highlighting in Visual Studio 2017 and 2019. As far as I've seen, Visual Studio 2019 offers more fine-tuned syntax highlighting options (one example would be the ability to colour C# methods like "User Types - Methods" in 2019 as opposed to 2017 where you must change the colour for "Identifiers"). If for whatever reason I were to save my settings in 2017, the new settings in 2019 would revert back to it's original (except for the ones that existed in 2017).

I've tried resetting my settings and followed the instructions on the Visual Studio Docs page (https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio) but it just doesn't seem to work. I've even turned off "Synchronize settings across devices when signed into Visual Studio" but it still won't work.

Is there a way to **completely isolate** Visual Studio 2017's settings from Visual Studio 2019? I need Visual Studio 2017's settings to be **fully** independent of 2019 and vice versa.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f452163a-5b45-243c-9601-585359deec53
* Version Independent ID: 881229c0-dfb7-6e68-00ae-868abd0c6687
* Content: [Synchronize settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/synchronized-settings-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/synchronized-settings-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@Brandon-Gui123  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
