### ISSUE TITLE
invalid with C#8 nullable reference types?

### ISSUE THREAD

**Issue by collinbarrett** [MicrosoftDocs/visualstudio-docs#3588]
Will this warning be invalid on non-nullable reference types when C# 8's nullable reference types feature is released?

I am authoring some new code using C#8 while in beta. When I see CA1062 flagged on a non-nullable reference parameter, is it safe to just ignore it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@collinbarrett Thanks for your questions. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your questions:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
