### ISSUE TITLE
this. vs _

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/visualstudio-docs#3596]
Could you please give a short link to the article describing how to make VS using underscore instead of this. for the field name is this is possible. Doing that every time manually is really annoying

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b64e74-c447-e671-06f0-c28834e604dc
* Version Independent ID: 988170ed-2cc0-d90d-06e4-d7603bd8f9e7
* Content: [Refactor a field to a property - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/encapsulate-field?view=vs-2019)
* Content Source: [docs/ide/reference/encapsulate-field.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/encapsulate-field.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@yahorsi Thank you for your suggestion!

The issue is more of a coding preference than language feature, though please consider suggesting the idea [here](https://social.msdn.microsoft.com/Forums/home?forum=csharplanguage).

Alternatively, you can add **this** to your [keyboard shortcuts](https://docs.microsoft.com/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2019) and/or create a [custom build step](https://docs.microsoft.com/en-us/cpp/build/understanding-custom-build-steps-and-build-events?view=vs-2019) to replace the underscores before compilation.

**Comment by yahorsi** [comment]
The issue is about documentation, docs does not tell me where/how I could change it.

**Comment by gewarren** [comment]
I'm not aware of any way to do that automatically using a built-in feature. You can set a preference for use of `this` versus not at all in C#/VB, but not versus an underscore.

![image](https://user-images.githubusercontent.com/24882762/61019251-588e2d00-a34e-11e9-9660-b3f6e2e042c0.png)
