### ISSUE TITLE
TEE CLC is no longer maintained (according to its Github project) so what is its replacement?

### ISSUE THREAD

**Issue by scastria** [MicrosoftDocs/visualstudio-docs#3597]
Surely Microsoft has a solution for TFS from the command line to support CI/CD solutions that do NOT run on Windows??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [Team Foundation Version Control (TFVC) - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control?view=vsmac-2019#feedback)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by justinpark01** [comment]
Seriously, why doesn't Microsoft support its own versioning control, this is ridiculous

**Comment by jmatthiesen** [comment]
Hi, all, I'm sorry I don't have anything to add to this conversation. In Visual Studio for Mac we don't have plans to work on Team Foundation Version Control and the other projects like TEE-CLC aren't owned by our team. I can update our documentation to not refer to TEE-CLC anymore, but obviously that won't help with the issue you have. I know that's not helpful and sorry I don't have more to offer up.

You can submit to the Azure DevOps team a new suggestion for a command line tool, here: https://developercommunity.visualstudio.com/spaces/22/tfs.html?type=idea

I'll leave our docs alone for now, so that the legacy support of the TEE-CLC tool is at least still provided as a workaround.

#please-close
