### ISSUE TITLE
Please update for VS2017 and higher

### ISSUE THREAD

**Issue by karenpayneoregon** [MicrosoftDocs/visualstudio-docs#3600]
This page could use an update to how to disable security warning for VS2017 and higher as the current page does not support newer releases of Visual Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13df8304-e6f6-6998-0378-65cb03bb81c4
* Version Independent ID: 1acfc047-cf95-dc15-94b8-0f476dffead7
* Content: [Security Warning: Attaching to a process owned by an untrusted user can be dangerous. If the following information looks suspicious or you are unsure, do not attach to this process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/security-warning-attaching-to-a-process-owned-by-an-untrusted-user?view=vs-2019)
* Content Source: [docs/debugger/security-warning-attaching-to-a-process-owned-by-an-untrusted-user.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/security-warning-attaching-to-a-process-owned-by-an-untrusted-user.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by BramvRiel** [comment]
I'd just like to add that I encountered this problem when I assigned a custom application pool user in IIS. When I then debug an application that uses the service on that application pool, I get this warning because the custom application pool user is "untrusted".
The reason I assign custom application pool user is to simulate the production environment.

**Comment by Mikejo5000** [comment]
Updating this doc. Fix should be live by end of day, 1/15/21
