### ISSUE TITLE
VS2019: Choose - When  Condition=" '$(Configuration)'=='MyConfig' " not working anymore

### ISSUE THREAD

**Issue by Linus62** [MicrosoftDocs/visualstudio-docs#3617]
I have a configuration named "local". This configuration compiles and links all my custom libraries with my application. 
With other configurations ("test", "production") these libraries are referenced by Nuget with the inversed condition:
    &lt;Reference ...  Condition="'$(Configuration)' != 'Local'"&gt;
      .....
    &lt;/Reference&gt;

With Visual Studio 2019 it takes always the NuGet reference instead of the project ref. I noticed it when I am trying to debug. The debugger issues a "Just My Code Warning": "You are debugging a Release buld of xxx.dll. Using Just My Code with Release builds using compiler optimizations results in a degrades debugging experience (e.g. breakpoints will not be hit)"
With Visual Studio 2017 the same project works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9555b2e3-0394-0e64-e7a2-4e1adc5e99bf
* Version Independent ID: ed70f624-65ad-556c-25c3-08e00415f6cd
* Content: [MSBuild Conditional Constructs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-conditional-constructs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditional-constructs.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Linus62 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
