### ISSUE TITLE
Turn off "quick fix"

### ISSUE THREAD

**Issue by EddieRich** [MicrosoftDocs/visualstudio-docs#3618]
How do you disable this "feature" so neither ever appear again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c0395a-7b86-46ca-9ede-f7cf361f2844
* Version Independent ID: 2ef2a75f-77e5-0192-3a64-a555178f02e3
* Content: [Quick Actions, light bulbs, and screwdrivers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quick-actions?view=vs-2019#feedback)
* Content Source: [docs/ide/quick-actions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quick-actions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@EddieRich  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by joeparzel** [comment]
How is this an acceptable answer?  If I went to my mechanic and asked them how to turn off my car, they would be wrong to assume that I only wanted my car turned off because I'm having an issue driving it.  That being said, YES, people want to turn this feature off because it is causing issues, namely, distraction and resource consumption.  The capability to turn it off either exists or it does not; your documentation is incomplete.
