### ISSUE TITLE
What is the default mime type for this file?

### ISSUE THREAD

**Issue by johnnyasantoss** [MicrosoftDocs/visualstudio-docs#3625]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* Content: [Solution (.Sln) file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019#feedback)
* Content Source: [docs/extensibility/internals/solution-dot-sln-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-dot-sln-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@johnnyasantoss  `text/plain` should work, since it is a text-based config file.

Please comment below if there are issues.

**Comment by aolszowka** [comment]
FWIW it appears that you need the UTF-8 BOM as well as a Newline otherwise the overlay will not work. Some tooling (such as the `dotnet sln` tool) will insert the UTF-8 BOM when you use it to modify solutions. However if you are missing the newline you will not get the same overlay as you would had you created this file via Visual Studio. See https://github.com/dotnet/cli/pull/8199
