### ISSUE TITLE
Is this deprecated by MSIX?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/visualstudio-docs#3645]
As the title says.  Is this packaging process deprecated by MSIX?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85eb697-fd62-62d1-cc5a-24b4f7f18017
* Version Independent ID: 715fa2ac-cc41-596b-bb07-38b6be492fe7
* Content: [ClickOnce Security and Deployment - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2019#feedback)
* Content Source: [docs/deployment/clickonce-security-and-deployment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/clickonce-security-and-deployment.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@atrauzzi Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
