### ISSUE TITLE
Download of specific version of vs_buildtools installers is badly-/almost un-documented

### ISSUE THREAD

**Issue by l0calh05t** [MicrosoftDocs/visualstudio-docs#365]
The only information I could find is on [Advanced Example for Containers](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md), which states that one can download https://aka.ms/vs/15/release/channel and "examine bootstrapper URLs", however I can only find one .exe link in the JSON file, which points to a single version of vs_Setup.exe. The manifest to which it points doesn't include any vs_buildtools.exe URLs either. The linked documentation page also refers to [Create a network installation of Visual Studio 2017](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md) which mentions https://my.visualstudio.com to get links to installers for fixed versions. However, I can only find two versions 15.0, and 15.4, and none of the versions in between.

**Comment by TerryGLee** [comment]
FYI: This issue is in our backlog queue to investigate.

**Comment by JVimes** [comment]
This is really frustrating.

**Comment by TerryGLee** [comment]
@l0calh05t @JVimes This issue has been open for some time now; apologies for that. However, since this issue was originally posted, we've made changes to the documentation so that it includes more references to Build Tools (for example, the [Create an offline installation of Visual Studio](https://docs.microsoft.com/visualstudio/install/create-an-offline-installation-of-visual-studio) page now lists a download link to the .exe). 

And to address your specific request, we've got a PR in the queue that'll update the [Create a network installation of Visual Studio](https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio) page so that it also lists the .exe&mdash;the update should be published by noon tomorrow. 

Meanwhile, here is some more information that might also be useful: 

- For previous versions of executable files, see the [Visual Studio 2019 release history](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history) page. 
- To learn more about which versions are available and why, see [Update Visual Studio while on a servicing baseline](https://docs.microsoft.com/en-us/visualstudio/install/update-servicing-baseline?view=vs-2019)

Thanks for us improve the documentation!

**Comment by JVimes** [comment]
Thanks. So, it looks like the answer is, "specific versions of vs_buildtools.exe (no earlier than April) are [**here**](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers)".

**Comment by TerryGLee** [comment]
@JVimes The list is specific to Visual Studio 2019, by design. Unfortunately, we don't have an equivalent for earlier versions, other than what's offered here: https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by TerryGLee** [comment]
@JVimes Also, see the "Support for older versions of Visual Studio" section of the [Visual Studio Product Lifecycle and Servicing](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing#support-for-older-versions-of-visual-studio) page for additional info.

**Comment by JVimes** [comment]
Oh that makes sense. Thanks 🙂
