### ISSUE TITLE
Custom color palette in color chooser

### ISSUE THREAD

**Issue by IngmarBitter** [MicrosoftDocs/visualstudio-docs#3683]
I'd like to provide my own color palette in the area of "Basic colors" of the color chooser used in VS2019 Options-&gt;Fonts and Colors-&gt;Idem foreground-&gt;Custom...
Seems really hard to find instructions on how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56e9562-f71c-8427-8d3d-0b0891f79fc0
* Version Independent ID: 299eafb3-9b4a-2a5a-af7c-247fbb785ddd
* Content: [Colors and Styling for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/colors-and-styling-for-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/extensibility/ux-guidelines/colors-and-styling-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/colors-and-styling-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@IngmarBitter Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
