### ISSUE TITLE
Can I switch back from Preview Channel and get previous version VS4Mac?

### ISSUE THREAD

**Issue by BicycleMark** [MicrosoftDocs/visualstudio-docs#3697]
If I switch back to stable will I get previous version of VS4Mac
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f3608c-d434-e892-85db-032af35f919b
* Version Independent ID: d546284e-5cd8-6a41-790b-5302b628d357
* Content: [Updating Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/update?view=vsmac-2019)
* Content Source: [mac/update.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/update.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
