### ISSUE TITLE
No Pictures to Reference

### ISSUE THREAD

**Issue by zachlanger19** [MicrosoftDocs/visualstudio-docs#3707]
There are no pictures of what the final product should look like (intermediary steps would also be appreciated). So, I have no idea if what I did produced the expected outcome. Also, it would be useful to determine the type of extension I'm interested in. I.E.: Is a toolbar what I really want or should I go with a menu? IDK, I guess I'll code both to find out. It would be super useful. It could be simple screenshots or like the VSCode tutorials.

**Comment by msebolt** [comment]
@zachlanger19 Thank you for the feedback.

We strive to bring the best tutorials Visual Studio has to offer and apologize for the confusion.

As infrequent as screenshots are, some articles still include them, see [Extend the Properties, Task List, Output, and Options windows](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-properties-task-list-output-and-options-windows?view=vs-2019).

If you could kindly attach any article references below, they will be prioritized and updated accordingly.

**Comment by zachlanger19** [comment]
Thanks for getting back so quickly. 

The articles i thought could use pictures to assist in following along and also comparing to one another were  [https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window?view=vs-2019](Adding a Tool Window) and [https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-menu-to-the-visual-studio-menu-bar?view=vs-2019](Adding a Menu)

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
