### ISSUE TITLE
Link to "Data Transfer Object (DTO)" outdated

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/visualstudio-docs#3717]
In the section When To Suppress Warnings, the link is to a document that is no longer maintained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db6af07-b7d6-9395-223e-1a0f83fb2405
* Version Independent ID: 5ee87730-ff01-2571-494e-91d29c5fe211
* Content: [CA2227: Collection properties should be read only - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2227-collection-properties-should-be-read-only.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2227-collection-properties-should-be-read-only.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@DrGriff  Thank you for the feedback.

This content in particular is auto-generated so providing an additional note at this time is currently unfeasible.  

Since the existing link works and notes its outdated nature, I'm going to go ahead and close this issue.

Thanks again and please feel free to provide additional feedback as needed.

**Comment by gewarren** [comment]
The content is not auto-generated, but I don't believe there's currently a more suitable target for the DTO link.
