### ISSUE TITLE
Why never triggered even on sample code

### ISSUE THREAD

**Issue by frankguoguo** [MicrosoftDocs/visualstudio-docs#3721]
VS2017 version 15.9.14. Is there other switch to turn it on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36a7fc54-584b-4ae2-ad71-6343ad8e2801
* Version Independent ID: 0784bf12-f389-3660-ae7a-1641a82d3e46
* Content: [Convert a foreach loop to LINQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2017#feedback)
* Content Source: [docs/ide/reference/convert-foreach-linq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/convert-foreach-linq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by WilliamAntonRohm** [comment]
@frankguoguo Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
