### ISSUE TITLE
How can I restart a running VB program from within?

### ISSUE THREAD

**Issue by stewl** [MicrosoftDocs/visualstudio-docs#3726]
I have written a VB program that solves SUDOKU puzzles.
When it completes the solution, it asks if the user wants to run again with another puzzle.

I can not-
  1)  determine the first line of code that the program executes. The main() is empty. All code is on the tab for Form1. I have tried breakpoints, but still can't determine the starting point.

  2)  figure out how to cause the program to jump back to that point in the code.

Can you help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34fa60cd-9951-e81c-6513-70f937ac795c
* Version Independent ID: 30a23c9c-c76c-cfc9-7ec6-981f4aa0da5d
* Content: [Edit code and continue debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/edit-and-continue?view=vs-2019#feedback)
* Content Source: [docs/debugger/edit-and-continue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/edit-and-continue.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@stewl Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
