### ISSUE TITLE
Code Generator Error while adding a new Mvc Controller Vs2019 

### ISSUE THREAD

**Issue by CihanYet** [MicrosoftDocs/visualstudio-docs#3773]
When i try to add a controller i get following error:

There was an error running the selected code generator:
'The value -1 is outside the acceptable range of [0,2147483647].
Parameter name:value'

I also tried to add an Area and get the same error. I couldn't find any solution for that.

IDE: Visual Studio 2019 Community
MVC project .Net Framework 4.7.2

**Comment by WilliamAntonRohm** [comment]
@CihanYet Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
