### ISSUE TITLE
Incompatible with general format specifiers

### ISSUE THREAD

**Issue by seminumber** [MicrosoftDocs/visualstudio-docs#3782]
I think users generally expect a more familier formatting of type {var:formatstring} works in debugger eg., {Math.PI:0.###} (=3.142). 
It would be unlikely to be used in Watch windows, but is very likely to be the first shot (at least for me) when we create a simple DebuggerDisplay attribute, as things with single braces will be compatible with formatted string specifiers.
eg. DebuggerDisplay("{MyQuantity}") works but DebuggerDisplay("{MyQuantity:0.##}") fails.
Of course, there are some viable alternatives (override ToString on conditional compile, proxies, etc.,) but since : and  , maycoexist, it may be a valid feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ab3309-0c6a-5150-64d8-0339a03f3238
* Version Independent ID: e29ede27-d73c-7294-cdcc-c1227353bbb9
* Content: [Format specifiers in the debugger (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-csharp?view=vs-2019#feedback)
* Content Source: [docs/debugger/format-specifiers-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@seminumber It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
