### ISSUE TITLE
Where's the sample.,

### ISSUE THREAD

**Issue by KCarterSr** [MicrosoftDocs/visualstudio-docs#3805]
On this page it states, "You can find an example of nested projects in the C# Example.Nested Project sample."

I've been unable to locate this sample. Can you provide a link?

Thanks
K.L. Carter Sr.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e094e917-1d6c-d25a-2591-af1e9b039d2f
* Version Independent ID: d6c4e709-9560-e5ca-630b-18096ee90d46
* Content: [Nesting Projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/nesting-projects?view=vs-2019#feedback)
* Content Source: [docs/extensibility/internals/nesting-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/nesting-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@KCarterSr  Thank you for the feedback, please refer to [this article](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/how-to-implement-nested-projects?view=vs-2019).

The documentation has been updated.

**Comment by KCarterSr** [comment]
I've already seen that.  the question was about finding the project file listed in the article. I found several projects that begin with Examlple."projectname" but not the one listed. Can you point me to it?

Thanks

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
