### ISSUE TITLE
NgenApplication value incorrect

### ISSUE THREAD

**Issue by dtivel** [MicrosoftDocs/visualstudio-docs#3823]
After chatting with Mike Wade, I think that the XML example is incorrect.

    <NgenApplication>vsn.exe</NgenApplication>

To use the default vsn.exe you should be able to exclude the `NgenApplication` element.  Alternatively, you can explicitly use vsn.exe by specifying the full path:

    <NgenApplication>[installdir]\Common7\IDE\vsn.exe</NgenApplication>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b1b238-a9a9-b87a-2f9f-11f6abcfc367
* Version Independent ID: 86a2cfed-8300-96e3-8971-0fb7194a3886
* Content: [Ngen support in VSIX v3 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ngen-support?view=vs-2019)
* Content Source: [docs/extensibility/ngen-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ngen-support.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
