### ISSUE TITLE
Undocumented settings in sample .runsettings file 

### ISSUE THREAD

**Issue by N-Olbert** [MicrosoftDocs/visualstudio-docs#3842]
The following configuration settings are included in the sample .runsettings file but aren't documented anywhere:

```
            <UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            <CollectFromChildProcesses>True</CollectFromChildProcesses>
            <CollectAspDotNet>False</CollectAspDotNet>
```
Although it is recommended to "not change the values" it would be nice to know the exact impact of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019#feedback)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@singhsarab Could you help answer this question?

**Comment by singhsarab** [comment]
@mayankbansal018 Can you please take a look.

**Comment by mayankbansal018** [comment]
_<UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>_
This is needed for scenario to gather coverage for functions marked with Attribute "_**SecuritySafeCritical**_"
All this does is that instead of writing directly into memory location form the function marked with above attribute, we insert a probe which redirects to another function, which in turns writes into memory

_<AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>_
Child processes which are launched with low level acl like SilverLight or UWP apps, if we are to collection information from we need to set different acl level on IPC channels, which only gets set if this is set.

_<CollectFromChildProcesses>True</CollectFromChildProcesses>_
To collect coverage information from child processes which are launched by test/production code.

_<CollectAspDotNet>False</CollectAspDotNet>_
When enabled restarts IIS process, & collects coverage information from it. To be explicitly set by user.

**Comment by gewarren** [comment]
Thank you @mayankbansal018. I'll add that info to the page.
