### ISSUE TITLE
XAML debugging in a new view

### ISSUE THREAD

**Issue by ibelchamber** [MicrosoftDocs/visualstudio-docs#3852]
Hoe do you enable XAML debugging in a new view (window)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2baf39-d3c3-5d5a-d93c-f4040430c3dd
* Version Independent ID: c443e681-03f0-ea47-a09d-718693448b3d
* Content: [Inspect XAML properties while debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/inspect-xaml-properties-while-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/inspect-xaml-properties-while-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/inspect-xaml-properties-while-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@ibelchamber  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
