### ISSUE TITLE
Dismissing the legal disclaimer regarding software licensing, etc., and decompilation

### ISSUE THREAD

**Issue by jnpwly** [MicrosoftDocs/visualstudio-docs#3858]
I understand that MS needs to ensure that IP is being honoured, and hence the need for the dialog warning about this when the ILSpy decompilation is used. I am finding, however, that each day, when I navigate to decompiled sources, I am shown this dialog. Is there a way to stop this dialog being shown permanently? I don't mind seeing it once... but to see it each day I use this feature gets, um, annoying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f28ec7e-9069-4d36-632c-e195e7f6b21b
* Version Independent ID: ebe0a750-17c5-dfa7-f0c2-b35ebfdd45f6
* Content: [Viewing type definitions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/go-to-and-peek-definition?view=vs-2019#feedback)
* Content Source: [docs/ide/go-to-and-peek-definition.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/go-to-and-peek-definition.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@jnpwly  It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
