### ISSUE TITLE
No entry "Visual Studio Package" under Extensibility

### ISSUE THREAD

**Issue by haferburg** [MicrosoftDocs/visualstudio-docs#3864]
Under "Create a VSPackage" in item 2, the page reads: "In the Add New Item dialog, go to Visual C# > Extensibility and select Visual Studio Package". But there is no such entry, I only have "Visual Studio AsyncPackage". How come? Do I need to install something? Or is the documentation outdated?

The page later instructs to replace some attributes, which won't work with an AsyncPackage. Also there is no Initialize() method, and when I start the experimental instance, neither the Constructor nor the InitializeAsync() method is ever called.

I'm using 15.9.11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7aca15b-bfa6-33ac-8f45-78d5d6c4ffc0
* Version Independent ID: c3dc31a4-cf7a-4b25-8e39-91cb19565203
* Content: [Creating an Extension with a VSPackage - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-an-extension-with-a-vspackage?view=vs-2017)
* Content Source: [docs/extensibility/creating-an-extension-with-a-vspackage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-an-extension-with-a-vspackage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
