### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by adolabsnet** [MicrosoftDocs/visualstudio-docs#3868]
Then use this command to run the installation::
c:\vslayout\vs_community.exe --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Component.GitHub.VisualStudio --includeOptional

my question: how, install , ALL layout that I already downloaded

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Troubleshoot installation or upgrade issues - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues?view=vs-2019)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@adolabsnet  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by TerryGLee** [comment]
@adolabsnet You might also find what you need on the following Visual Studio installation-related pages on our site:

[Create an offline installation](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)

[Command-line parameter examples](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019)

[Update a network installation](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019)
