### ISSUE TITLE
Directory.Build.targets seems not work?

### ISSUE THREAD

**Issue by heku** [MicrosoftDocs/visualstudio-docs#3869]
Hi, according to this doc, I think if I set `TargetFrameworkVersion` to different values in `Directory.Build.props`, `Directory.Build.targets` and project.csproj. I suppose the effective one is the one in `targets` file, but from my test, I found `targets` file never work. I checked the `Microsoft.Common.targets` files in `windows\Microsoft.NET\Framework\v4.0.30319`, I don't see it imports `Directory.Build.targets`, I have .NET 4.7.2 installed and my environment is windows 10 + VS 2019 16.2.3.

Is there anything I missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#feedback)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@heku  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by heku** [comment]
@WilliamAntonRohm Thank you for your reply, I create a very simple [project](https://github.com/heku/DirectoryBuildTest) with structure below

Directory.Build.props

```xml
<Project>
  <PropertyGroup>
    <AssemblyName>DirectoryBuildTest.props</AssemblyName>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
  </PropertyGroup>
</Project>
```

Directory.Build.targets

```xml
<Project>
  <PropertyGroup>
    <AssemblyName>DirectoryBuildTest.targets</AssemblyName>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
  </PropertyGroup>
</Project>
```

DirectoryBuildTest.sln
└───DirectoryBuildTest   : A default `Class Library` project created by VS2019 16.2.4
```xml
    <AssemblyName>DirectoryBuildTest.csproj</AssemblyName>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
```

When build the project, I always get `DirectoryBuildTest.csproj.dll` (`.NET 4.5`), which supposed to be `DirectoryBuildTest.targets.dll` (`.NET 4.7`), so the **targets** file seem not work.

If I commented the lines in .csproj file, I got `DirectoryBuildTest.props.dll` (`.NET 4.6`), so the **props** file works as expected.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, can you help answer this question?

**Comment by heku** [comment]
@Mikejo5000 @WilliamAntonRohm May I know any response here?

**Comment by Mikejo5000** [comment]
@heku, might be more of a support question than a doc question, per @WilliamAntonRohm 's earlier comments. @rainersigwald for additional input.

**Comment by ghogen** [comment]
Is this still an issue?  If so please reopen and ping @rainersigwald
