### ISSUE TITLE
How to uninstall with network disconnected device?

### ISSUE THREAD

**Issue by MRatnam** [MicrosoftDocs/visualstudio-docs#3879]
Seems like the standard uninstall process doesn't work for a network disconnected machine. MAJOR oversight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac42ba7-edf2-06fb-dc6a-13a0c47b43c5
* Version Independent ID: 98b5c39a-ff89-f4c8-ef77-ae239564998a
* Content: [Uninstall Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/uninstall-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/uninstall-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@MRatnam  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by MRatnam** [comment]
Yes good point sorry!!!
