### ISSUE TITLE
Sample Solution for Code Analysis?

### ISSUE THREAD

**Issue by thomasgalliker** [MicrosoftDocs/visualstudio-docs#3880]
Is there a sample solution somewhere on github which correlates with the documentation? That would be really nice...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@thomasgalliker -- Thomas, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
