### ISSUE TITLE
How can we get Lines count in current file ( e.g class file ) i.e. total lines present in class file ? 

### ISSUE THREAD

**Issue by Prash-JD** [MicrosoftDocs/visualstudio-docs#3899]
I need to access line number count to get how many lines are there in class files and how many lines get added after code changes are done. Any API to access this information?

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d26f2c7-9dc7-f759-7d83-63b2b6a1acdc
* Version Independent ID: 7f55cfd7-5a45-21ac-294c-37b2130ebbcd
* Content: [Display line numbers for code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-display-line-numbers-in-the-editor?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/how-to-display-line-numbers-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/how-to-display-line-numbers-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@Prash-JD  Thank you for the question.

Since this is file-based you could use [System.IO.File](https://docs.microsoft.com/dotnet/api/system.io.file.readlines?view=netframework-4.8) which has a good solution posted [here](https://stackoverflow.com/questions/119559/determine-the-number-of-lines-within-a-text-file).

Other alternatives include PowerShell, with this solution posted [here](https://stackoverflow.com/questions/1244729/how-do-you-count-the-lines-of-code-in-a-visual-studio-solution).

**Comment by msebolt** [comment]
Closing this now, please comment below if there are any issues.
