### ISSUE TITLE
Layout for multiple editions of Visual Studio

### ISSUE THREAD

**Issue by sryabkov** [MicrosoftDocs/visualstudio-docs#390]
When I created the offline VS layout folder back in March 2017, when 15.0 was first released, the following guidance was not in place:

> "If you have multiple editions of Visual Studio in use within your enterprise (for example, both Visual Studio Professional and Visual Studio Enterprise), you must create a separate network install share for each edition."

So, I created a single layout folder for Professional and Enterprise editions, and later added Build Tools to it.

To update the layout folder, I download fresh bootstrappers (`vs_Enterprise.exe`, `vs_BuildTools.exe`, `vs_Professional.exe`) and run each of them against the SAME LAYOUT FOLDER (`\\server\software\msft\vs2017\offline`)

To install VS Ent, I created a script that runs:
```
"\\server\software\msft\vs2017\offline\vs_Enterprise.exe"   --in "\\server\software\msft\vs2017\offline\Response_ent.json" 
```
To install VS Pro, I created a script that runs:
```
"\\server\software\msft\vs2017\offline\vs_Professional.exe" --in "\\server\software\msft\vs2017\offline\Response_pro.json" 
```
And to install Build Tools, we plan to use
```
"\\server\software\msft\vs2017\offline\vs_BuildTools.exe"   --in "\\server\software\msft\vs2017\offline\Response_BuildTools.json" 
```
(I am omitting the response files, but I can provide them, if they are needed.)

Everything seems to be  working fine, so I am curious why the note to use separate layout folders for each edition was put in place. It strikes me as highly inefficient, because the majority of components seem to be the same.

Are there any problems with the above approach? If yes, what are they? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/install/create-a-network-installation-of-visual-studio.md)

**Comment by TerryGLee** [comment]
Thanks for your inquiry, @sryabkov. We will investigate this.

**Comment by sryabkov** [comment]
@TerryGLee Thank you and happy holidays!

Here are the `response.json` files I am using

`Response_ent.json`:
```
{
    "installChannelUri": ".\\ChannelManifest.json",
    "channelUri": "\\\\server\\software\\msft\\vs2017\\offline\\ChannelManifest.json",
    "installCatalogUri":".\\Catalog.json",
    "channelId":"VisualStudio.15.Release",
    "productId":"Microsoft.VisualStudio.Product.Enterprise",

    "quiet": false,
    "passive": false,
    "includeRecommended": true,
    "norestart": true,

    "addProductLang": [
        "en-US"
    ],

    "add": [
        "Microsoft.VisualStudio.Workload.ManagedDesktop",
        "Microsoft.VisualStudio.Workload.Data",
        "Microsoft.VisualStudio.Workload.NetWeb",
        "Microsoft.VisualStudio.Workload.Node",
        "Microsoft.VisualStudio.Workload.Office"
    ]

}
```
`Response_pro.json` and `Response_buildTools.json` look the same, except for one line, `productId`. In `Response_pro.json`, we have
```
    "productId":"Microsoft.VisualStudio.Product.Professional",
```
And in `Response_buildTools.json`, we have 
```
    "productId":"Microsoft.VisualStudio.Product.BuildTools",
```

Note: it is possible that in order to install VS 2017, some developers ran the bootstrapper (`vs_Enterprise.exe` or `vs_Professional.exe`) from the` offline` folder instead of executing one of the three installation cmd scripts.

**Comment by TerryGLee** [comment]
@sryabkov A quick note to let you know that this is still on our radar; we should have a response for you soon.

**Comment by sryabkov** [comment]
@TerryGLee Awesome, thank you

**Comment by MikeMarlowe** [comment]
When you create a layout, setup will create response.json and layout.json files in your layout folder that contain info about what is included in the layout (e.g. if you create a partial layout of VS Enterprise that only includes 1 workload for 1 English locale, that product, workload, and language info gets stored in those json files).  Setup uses that data when modifying or updating the layout to a newer version or when installing VS from the layout.  If you try to put multiple products into the same layout folder, these response.json and layout.json files will either get overwritten (so you lose info about the previous product) or get reused (so the product you think you are creating a layout for may not actually be that product).  Because there is only 1 response.json & layout.json per layout folder and those files can only reference one product, you can only have one product per layout folder.

If you need layouts for multiple products and don't want to re-download common packages, you could create a layout for product 1, copy that layout's packages (all the sub-folders in the layout) to a 2nd layout folder, then create the layout for the second product in the second layout folder.  Setup will verify the packages that already exist in the layout and only download any packages that are missing.

**Comment by TerryGLee** [comment]
@MikeMarlowe Thanks, Mike.

**Comment by sryabkov** [comment]
@MikeMarlowe Thank you for the information. Will the approach you suggested work if [symbolic links](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365680%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) are used for package folders instead of duplicates of the package folders? The idea is to have a location on the network with all the packages for all versions of Visual Studio 2017 and then create a script that would create symlinks for these package folders in the VS Ent layout folder and in the VS Pro layout folder...

**Comment by alski** [comment]
This is disappointing. My organisation has the same problem. Are there any plans to separate the layout.json and response.json so that we can avoid replicating the multi-Gb cabs?

**Comment by joeamnesiac** [comment]
My organisation would like this feature also, it seems very wasteful of storage space when the Enterprise, Professional and BuildTools all duplicate the same things.
