### ISSUE TITLE
Target "BeforeBuild" does not exist anymore in C++ projects

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [MicrosoftDocs/visualstudio-docs#3901]
In file `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.BuildSteps.targets` there is a line `<Target Name="AfterBuild">` but there is no line `<Target Name="BeforeBuild">`. BeforeBuild is not referenced anywhere either:
```
    <BuildDependsOn>
      _PrepareForBuild;
      $(BuildSteps);
      AfterBuild;
      FinalizeBuildStatus;
    </BuildDependsOn>
```

Because of this, the following lines will never be executed when placed in a .vcxproj file:
```
  <Target Name="BeforeBuild">
    <Message Importance="High"
             Text="BeforeBuild BeforeBuild BeforeBuild !!!" />
  </Target>
```
even though AfterBuild works just fine in the same .vcxproj file:
```
  <Target Name="AfterBuild">
    <Message Importance="High"
             Text="AfterBuild AfterBuild AfterBuild !!!" />
  </Target>
```

In .NET Classic .csproj files everything works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [Extend the build process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Science-and-Motion-Sports** [comment]
Is this a product issue or a documentation issue?

**Comment by WilliamAntonRohm** [comment]
@Science-and-Motion-Sports -- thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Mikejo5000** [comment]
@olgaark Is BeforeBuild still supported in .vcxproj? I would guess that BeforeBuild would work fine if added to Microsoft.BuildSteps.targets.  fyi @rainersigwald
