### ISSUE TITLE
Not seeing Test > Live Unit Testing > Reset Clean option

### ISSUE THREAD

**Issue by SamuelEnglard** [MicrosoftDocs/visualstudio-docs#3954]
Using Visual Studio Enterprise 2019 16.2.5, I don't have a "Reset Clean" option for testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3113c2af-d97e-7b35-17ce-c675c3dff889
* Version Independent ID: b716c4af-d92b-cb3b-8af0-1b3ada479ac0
* Content: [Live Unit Testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2019#live-unit-testing-and-large-solutions)
* Content Source: [docs/test/live-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/live-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tfosmark** [comment]
@SamuelEnglard  Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Mikejo5000** [comment]
I don't see Reset Clean in VS 2019 16.4 either, so it could be the product changed and the doc needs an update. I'll ask about it.

**Comment by Mikejo5000** [comment]
I understand the feature has been removed, so this will need a doc update. Waiting for additional info first.

**Comment by kendrahavens** [comment]
Yes, we've removed the menu option, but you can still use a more explicit way to clean the LUT data in Tools > Options > Live Unit Testing -> Delete persisted data when Live Unit Testing is stopped.

We should update the doc.
