### ISSUE TITLE
is there a way to set test case filter in the runsettings file?

### ISSUE THREAD

**Issue by shueybubbles** [MicrosoftDocs/visualstudio-docs#3968]
visual studio doesn't have a way to set TestCaseFilter to be used for the command line, that I can find so I was looking here for a way to add it to the runsettings but don't see it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@shueybubbles -- David, it looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by ffMathy** [comment]
The documentation doesn't document the TestCaseFilter setting in the runsettings file though.

**Comment by WilliamAntonRohm** [comment]
@ffMathy -- Mathias, thank you for your observation.

**Comment by ffMathy** [comment]
I made a PR for it recently. Can't remember the ID though.

**Comment by ffMathy** [comment]
Here it is: https://github.com/MicrosoftDocs/visualstudio-docs/pull/6139
