### ISSUE TITLE
Build action Content does not work in .NET Standard 2 library

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/visualstudio-docs#3990]
Build action Content does nothing in .NET Standard 2 library:
- file is not copied to output folder when Copy to Output is None or default
- file cannot be read with Assembly.GetManifestResourceStream in .NET Standard 2 library

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797c58ff-3694-adda-188b-4ec4d079bd5c
* Version Independent ID: 442f90ff-9a99-c7dd-23c8-fbe51bcd8c0d
* Content: [Build actions for files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2019)
* Content Source: [docs/ide/build-actions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/build-actions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rolfik -- Marek, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:  
•	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
•	[https://www.stackoverflow.com](https://www.stackoverflow.com) 
•	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
