### ISSUE TITLE
Cannot distinguish project enums from external dependencies enums

### ISSUE THREAD

**Issue by alessiot89** [MicrosoftDocs/visualstudio-docs#3991]
This will cause tons of C26812 warnings when using extenal enums (big examples: the entire winapi).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a83d2a0-6bec-6e5e-516c-819e53ee3578
* Version Independent ID: 0f15f93e-f2ff-bf26-29c9-84e508006370
* Content: [c26812 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26812?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26812)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/c26812.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26812.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @JordanMaples
* Microsoft Alias: **jomaples**

**Comment by JordanMaples** [comment]
You are correct. The goal is to help developers identify problems enums in their own code and then to encourage them to file bugs against the external API owners who are still using plain enums instead of class enums. 

So in your example, you can file bugs on the WinAPI by visiting their developer community page. https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home

**Comment by blunted2night** [comment]
Shouldn't this be a warning of the declaration of the enumeration, not the use? I have lots of warnings in my code for using different values from system provided enumerations. At least if they where on the declaration it would minimize noise, or I could suppress the warnings all togther when including the offending header files.

**Comment by JordanMaples** [comment]
We're planning to start investigation on how to target the declarations instead, however the way the current check is implemented we can only detect the enum when it's used.

**Comment by WilliamAntonRohm** [comment]
@alessiot89 (@JordanMaples, @blunted2night) Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:  
•	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
•	[https://www.stackoverflow.com](https://www.stackoverflow.com) 
•	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
