### ISSUE TITLE
Local Kubernetes Cluster?

### ISSUE THREAD

**Issue by bdschaap** [MicrosoftDocs/visualstudio-docs#4006]
Does the Snapshot Debugger work for a local Kubernetes cluster?  I have both AKS and on-prem K8s clusters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508e3d40-6ffc-a548-522f-c8b60a5cfa2a
* Version Independent ID: 256e56a3-d604-541c-29db-62fcf59f5884
* Content: [Debug live ASP.NET Azure Kubernetes Services - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-kubernetes?view=vs-2019)
* Content Source: [docs/debugger/debug-live-azure-kubernetes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-live-azure-kubernetes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @poppastring
* Microsoft Alias: **madownie**

**Comment by WilliamAntonRohm** [comment]
@bdschaap Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
