### ISSUE TITLE
Way to not flag internal classes instantiated via builtin DI framework?

### ISSUE THREAD

**Issue by ideoclickVanessa** [MicrosoftDocs/visualstudio-docs#4028]
Is there a way to get this warning to suppress itself when the class is instantiated via Dependency Injection?

I have a class defined like so:
`internal sealed class CurrentUserService : ICurrentUserService`

that triggers this warning.  However, I also have another class in the assembly like this:
```
    public static class DIConfig
    {
        public static IServiceCollection AddAPICommonServices(this IServiceCollection services)
        {
            services.TryAddSingleton<ICurrentUserService, CurrentUserService>();

            return services;
        }
    }
```

Instead of completely suppressing the warning (since 95% of my classes setup this way are used via DI), it would be great if the warning only showed up when I have forgotten to register the class in DI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4303a22-627d-4024-fee7-40db88a544ac
* Version Independent ID: 37cc2f4d-7002-1b29-cfa4-b8be2924d0a7
* Content: [CA1812: Avoid uninstantiated internal classes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1812-avoid-uninstantiated-internal-classes?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1812-avoid-uninstantiated-internal-classes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1812-avoid-uninstantiated-internal-classes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@ideoclickVanessa -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by flaxed** [comment]
Apologies for bumping a closed issue, but this one was misdiagnosed as a library issue when it is not.

@ideoclickVanessa example falls right into the `When to suppress warnings` categories, and what the user is asking is a way for the analyser to supress this warning when type implements a preconfigured set of interfaces, or a set of attributes, for example.
Supporting suppression by interface or attributes would go a long way since they're one of the main ways the type can be discovered for registration by the DI framework.

Hope my explanation made this case more clear and open to proper consideration by the analyser devs.
