### ISSUE TITLE
I do not see Kubernetes

### ISSUE THREAD

**Issue by masters3d** [MicrosoftDocs/visualstudio-docs#4029]
Only Fabric and docker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019#feedback)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by masters3d** [comment]
![image](https://user-images.githubusercontent.com/6539412/65997125-a5653980-e44d-11e9-8c56-0c40b9a3d3d2.png)

**Comment by masters3d** [comment]
I upgrade my visual studio and now only see one. 
![image](https://user-images.githubusercontent.com/6539412/66001557-8dde7e80-e456-11e9-931d-031fd41ca340.png)

**Comment by WilliamAntonRohm** [comment]
@masters3d -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by masters3d** [comment]
Documentation says that I can do this. Are there limitations ? 
![image](https://user-images.githubusercontent.com/6539412/66006908-38f63480-e465-11e9-9929-bb39723b29d9.png)
