### ISSUE TITLE
Way to suppress this rule for Controller Action Result methods?

### ISSUE THREAD

**Issue by ideoclickVanessa** [MicrosoftDocs/visualstudio-docs#4030]
Is there a way to suppress this warning for Controller Action Result methods?

My action results methods look something like:
```
        [HttpGet("performance")]
        [ProducesResponseType(typeof(GetPerformanceFiltersApiResponse), StatusCodes.Status200OK)]
        public async Task<ActionResult<GetPerformanceFiltersApiResponse>> GetPerformanceFiltersAsync([FromQuery]StoreContext storeContext,
            [FromQuery]DateRangeContext dateRangeContext)
        {
            Models.PerformanceFilterLists filters =
                await filterService.GetPerformanceFiltersAsync(storeContext.StoreID, dateRangeContext.StartDate, dateRangeContext.EndDate);
            GetPerformanceFiltersApiResponse response = autoMapper.Map<GetPerformanceFiltersApiResponse>(filters);

            return Ok(response);
        }
```
which triggers this warning twice for the `await` line.  However, this is a false positive as both the Controller's Model Binding and FluentValidation ensures that the input parameters are non-null before reaching the method body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@ideoclickVanessa -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
