### ISSUE TITLE
Error: The package 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' was not recognized.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4054]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/64 
The user reports an error in the documentation and module availability

@aisbergde commented 3 days ago — with docs.microsoft.com
When trying to install some components regarding to this list I get an error:

vs_community__818795694.1537480254.exe --layout D:\SQLServer_Setup_diverse\vslayout --add Microsoft.VisualStudio.Component.CoreEditor --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.DataScience --add Microsoft.VisualStudio.Workload.Python --add Component.GitHub.VisualStudio --add Microsoft.Component.HelpViewer --add Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration --add Microsoft.VisualStudio.Component.Git --includeRecommended --lang en-US

Great error message:
Visual Studio Setup Command Line Utility, version 1.18.1049.33485
Copyright (C) Microsoft Corporation. All rights reserved.

Download of 'https://aka.ms/vs/15/release/channel' succeeded using engine 'WebClient'
Download of 'https://download.visualstudio.microsoft.com/download/pr/82e3dcda-e8a0-44e4-8860-eb93a12d4e80/61c5d0ed852e311c8fd6a62627fcb326da6aa79028b40ae25ee062da3c33791b/VisualStudio.vsman' succeeded using engine 'WebClient'
Catalog load operation correlation: {"id":"e3e60385-1915-4031-8ea6-a6e1717ea8dc"}
Layout operation correlation: {"id":"d59730ed-a56e-4cb6-abf9-3ba824cd7af5"}
Planning 'Layout' operation
Error: The package 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' was not recognized.
Error: Failed to plan for layout.
Error: Setup completed with errors.
Error: The package 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' was not recognized.
Press any key to continue ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4891ebc9-fdea-c376-94f6-17295ca275d7
* Version Independent ID: ccc61918-cc18-a7ff-cc6c-8659d6c9c78a
* Content: [Visual Studio Community workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?vs-2019&view=vs-2019)
* Content Source: [docs/install/workload-component-id-vs-community.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-community.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@CeciAc I took a look at this yesterday and I believe the problem is that the customer tried to run a Visual Studio Community 2017 bootstrapper (vs_community.exe) against a Visual Studio Community 2019 manifest. The giveaway here is when they report using "https://aka.ms/vs/**15**/release/channel". The version "15" is associated with Visual Studio 2017, where the version "16" is associated with the Visual Studio 2019 version.

If you check both the **en-us** copy and the **de-de** copy of the Workload and Component IDs page for Visual Studio Community 2017, you see that the "Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration" component is not listed on either of them. 

Please if you would, advise the customer of this?

**Comment by aisbergde** [comment]
I used the bootstrapper from the link in the instruction: vs_community__818795694.1537480254.exe
And finally I prepared a VS 2019 installation.
If this is a bootstrapper for VS 2017 how a user should know? And if this is the wrong bootstrapper: why this link is included in the instruction but not a link to the right version? Then you should correct the link in the instruction. But I think it was the VS 2019 bootstrapper. 
I went step by step through the instructions and got an error which I reported. It should be easy possible to reproduce the error following the instructions.

**Comment by TerryGLee** [comment]
@aisbergde Our concern via this venue is that our documentation is correct. I've verified that the download links on our _en-us_ pages point to the right versions. However, I will make some adjustments to the direct download links for Visual Studio 2017 so that there are visual cues as to what version is being downloaded, which should prevent the possibility of someone accidentally downloading a bootstrapper for the previous version of Visual Studio.

As for the error you've run up against: I'll check with the engineering team as to verify that the Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration component is still viable for Visual Studio 2019.

And, if you are looking to have your scenario tested and possibly repro'd, the best place to do that is by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. (As well, you can provide the engineering team with the diagnostic information they need to do so.)

**Comment by TerryGLee** [comment]
@aisbergde The engineering team looked at this issue and here is their feedback:

1. The Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration component is still viable for Visual Studio 2019, so no updates need to be made to the [Visual Studio Community component directory](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?vs-2019&view=vs-2019) page.

2. The setup bootstrapper that generated the error message is indeed for Visual Studio 2017. Our engineer identified the "1.18" in the following line of the message as belonging specifically to the Visual Studio 2017 version 15.9 installer.

     `Visual Studio Setup Command Line Utility, version 1.18.1049.33485`

Because I am not sure where you downloaded your copy of the setup bootstrapper, and because I've verified that all our download links are correct in the _en-us_ set of installation content, I'd suggest deleting any vs_community__818795694.1537480254.exe file that you have and then downloading it again from this page: https://visualstudio.microsoft.com/downloads/. (Also, to make certain that you don't accidentally pick up a copy of the bootstrapper from a previous download, you might consider trimming `__818795694.1537480254` from the file name so that it reads simply as `vs_community.exe` and then revising your command-line script accordingly.)

Hope this helps,
~ Terry
