### ISSUE TITLE
Links for Visual Studio bootstrappers => old version of VS (2017 instead of 2019)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4073]
The comment below was machine translated 
@aisbergde commented on [Tue Oct 08 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/67)

I went through the instructions given here
Step 1: Download the Visual Studio bootstrapper
If you now load Visual Studio community vs_community.exe, you get
vs_community__818795694.1537480254.exe
This is according to Microsoft but not Visual Studio 2019 but an older version: 2017
This leads to problems:

#64
MicrosoftDocs / visual studio-docs # 4054
Maybe there were other cases. Now they are all closed, but the link here is still wrong (I do not know if that is only in German, so I'll write in German now, as the original should have been fixed in English)

The expectation of the documentation would be that you can understand it step by step and then also create an installer for Visual Studio 19. Maybe you should explicitly specify the version for the bootstrap downloads, so that you already recognize the name of the downloaded file, which is now for a version. How should a normal user recognize this in such a name? vs_community__818795694.1537480254.exe
Then you pull it all through, it takes a lot of time to build, somehow it has to get to a server, GB of data, and then you have a Visual Studio 2107 installed. Very frustrating.

It's hard enough that you have to put together an installer in such a complicated way. Since it is already stupid, if you still do not know how to create an installer for VS 2019.

Internet is limited on many servers, as it is only possible with offline installers.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Erstellen einer Offlineinstallation - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

---

@srvbpigh commented on [Tue Oct 08 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/67#issuecomment-539408179)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by TerryGLee** [comment]
@aisbergde @CeciAc This is related to https://github.com/MicrosoftDocs/visualstudio-docs/issues/4054, where I suggested a workaround to the issue.

Further, as I explained in the previous GitHub Issue, I've tested the links and they all work correctly. Specifically, I verified that the version that anyone downloads from the current version of the page (whether it's in _en-us_ or _de-de_) is for Visual Studio 2019. For example, I just clicked the link from the _de-de_ version of the page, received a setup bootstrapper named vs_community__1220778088.1554193305.exe, and when I ran it, I received the following message:

![image](https://user-images.githubusercontent.com/23244653/66416855-a2b99580-e9b3-11e9-800b-959e02a89395.png)

I cannot know what happened to the original poster earlier. Although were I to guess, perhaps one of the following two things might have happened:

1. They might have been erroneously on the Visual Studio 2017 version of the page when they downloaded the setup bootstrapper. There is a version selector at the top left of the page, as follows, to differentiate between the two:

     ![image](https://user-images.githubusercontent.com/23244653/66417523-fd9fbc80-e9b4-11e9-9b7a-5fdb47735dde.png)

2. The original poster could I have accidentally used a setup bootstrapper from a previous download that occurred before Visual Studio 2019 was released (on 4.2.2019). 

As the original poster notes, there isn’t a way to tell from the setup bootstrapper file name as to which version that the bootstrapper applies to.  

If this is the sole issue, then this is product feedback rather than documentation feedback, in that the original poster is looking for functionality that isn’t currently provided by the product. To resolve this, I suggest that the original poster use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

**Comment by aisbergde** [comment]
I am still not able to download the correct installer. Or maybe the installer is the right one but I am not able to check it it the right version.

The generated link is:
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=offline+install&utm_content=download+vs2019

In different browsers I get different downloads with different names, but when I compare them I get:
"All input files are binary euqal"

Some information from file details:
file version 16.3.29403.142
product version 16.3.29403.142

When I start this files there is no information about the VisualStudio Version. It startes to download something.

If the "product" is not able to show the Visual Studio version which is used for download so plaese at least at some instruction how a user after the download of the installer can check the Visual Studio Version which is used by the installer for generating an offline setup.

And I can't understand "this is not related to the documentation but to the product, please give feedback on another place for the product".
This is one company Microsoft and the documentation team and the product team should work together.

The issue is and I can't solve it for days:
- I need to install Visual Studio 2019 with some components on a server with limited internet access.
- There are no ready offline downloads but the user should prepare a customized download using some complicated instructions.
- I am willing to do and I try to follow the instructions, but I can't see which Version I prepare because it is not shown in the "product". 
- only when I start the offline setup I (may be) get some informations about the Visual Studio Version
- The documenters are not responsible for product issues.
- And finally I don't know how to install Visual Studio on the target server, based on the existing documentation
