### ISSUE TITLE
Why do you require write access to my public repos just so I can submit feedback on the docs pages?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#408]
Not that I think there is anything there I care that you read, but I do not see why you need to write to my repo for any reason.

To give a bit of context, I was looking for an MSBuild xsd at [its docs page](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference) and was presented with this choice
![image](https://user-images.githubusercontent.com/15381181/34414122-626f5c9c-ebb5-11e7-8e01-752eefc491e1.png)

Since I was not finding the xsd file I was looking for, I clicked on the "Sign in to give documentation feedback" and was presented with this...

![image](https://user-images.githubusercontent.com/15381181/34414072-1f0e294c-ebb5-11e7-918d-61617494a9d4.png)

... and I ain't clickin' that.

**Comment by gewarren** [comment]
@ghogen Can you follow up with the folks that implemented this feedback system to see if we really need all that access?

**Comment by ghogen** [comment]
We're looking into this to see if we can make this work without having to request permissions.

**Comment by StingyJack** [comment]
It kind of has to work without requiring the granting of that level of permission to a third party. 

How does something like this not get ferreted out during design or even cursory testing?

**Comment by EisenbergEffect** [comment]
Hey @StingyJack, thanks for your feedback! Yes, this issue was repeatedly discussed during our feature design work and we do have a plan to address it. Please allow me to provide a few details as to why you are (temporarily) having a less than desirable experience...

When one of our customers OAuths, we provide a list of scopes to GitHub that are intended to constrain our use of the GitHub API as much as possible. The only thing we need to be able to do is create an issue on a repo. Unfortunately, the scopes that GitHub provides don't allow for issue creation only permissions. The smallest [scope available](https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/) that includes issue creation is what you see above 😢  Our primary engineer for this feature is on vacation now. I've asked him to double check again when he returns. If we find a better choice, we'll switch to it asap. From a GitHub API perspective, this is probably the best we can do for now, without GitHub implementing new features. FYI I've already reached out to our GitHub rep to discuss this deficiency in scope options. I've had a similar experience to you on other sites that I felt requested too much access. No doubt they were struggling with the same GitHub api limitations.

Having said all that, we do have a feature planned that would allow you to leave feedback without ever needing to OAuth the docs.microsoft.com app. From a technical standpoint, all that is required for our feedback system to work is that we inject a special bit of metadata into the body of the issue itself. We're planning to provide a UI that would jump you over to GitHub directly, with the issue pre-populated with metadata so that you can provide feedback directly through GitHub without ever needing to OAuth.

So, why haven't we already implemented the above no-auth feature and addressed all these issues? Well, you are actually part of a pilot 😄  If you look out across all of docs.microsoft.com, you will only see two documentation sets that have this GitHub feedback system: Visual Studio IDE and Azure CLI. Part of the purpose of this pilot is to give us an opportunity to try out this system and gather feedback from people like you. So again, thank you @StingyJack for providing this feedback 🥇 This really helps me confirm a customer scenario that I believed was important. We weren't able to get the appropriate feature implemented during our pilot-timeframe, but because of your feedback I'm able to more easily prioritize the no-auth improvement as a critical requirement of our post-pilot, full docs site rollout.

Feel free to contact me directly with any additional thoughts on the new feedback system. We have plenty of improvements and features in mind, but it's the feedback from people like you that we want to guide us in what decisions we make.

**Comment by StingyJack** [comment]
> Feel free to contact me directly with any additional thoughts on the new feedback system
Preferred method?  This issue tracker doesnt do direct messages.

**Comment by EisenbergEffect** [comment]
You can email me at rob dot eisenberg at microsoft dot com

**Comment by StingyJack** [comment]
Fwiw, I didn't forget, I just don't want to inundate you with a large wall of text.

**Comment by EisenbergEffect** [comment]
LOL No problem @StingyJack 

Also, I've got some good news for you. Our engineers were able to switch our GitHub integration to using a newer app model that GitHub provides. Initially, they didn't think this was possible. The result of this is that we are now able to ask for "exactly" the permissions for Issues only and nothing else 😄 It's already live on the VS IDE docs. We shipped it last night. Let us know what you think. We've got more improvements coming as well. Thanks again for your feedback.

**Comment by StingyJack** [comment]
This necessary access list has definitely been corrected.
![image](https://user-images.githubusercontent.com/15381181/34892370-09e7baf8-f7a7-11e7-9386-bcce43a8019c.png)

I can use this, but really I've done far too much involuntary testing for MSFT this past year (closing in on 300 reported issues @~ 2 working months of delays) and I didn't even get the proverbial "stupid T-Shirt".  

If you all could try to test stuff before releasing it (this remark is directed solely at the VS and Nuget teams), or provide an opt-out for pilots (in this case) before subjecting me to additional delays it would be appreciated. 

Thats about as terse as I can make the wall thats been jumbling about in my head. If it isnt clear please say so.

**Comment by EisenbergEffect** [comment]
@StingyJack I understand completely. Thank you for all the contributions you've made over the months. As an open source project leader (outside of Microsoft) I understand the amount of time and work that community members often dedicate to others. With respect to this particular feature of the feedback system, feedback from a customer like you is one of the most powerful tools that I have to convince others internally and make changes that can sometimes be very difficult to make. I really can't emphasize just how valuable your feedback is. Thank you again.
