### ISSUE TITLE
Missing shapes

### ISSUE THREAD

**Issue by xiejiang2014** [MicrosoftDocs/visualstudio-docs#4092]
By default, there are only two shapes in the asset, Elipse and Rectangle, so where do the other shapes shown on this page come from? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0301c8-416c-59be-43a1-b5489716e50b
* Version Independent ID: c20b4f11-e646-5ba3-d5c7-82a753c4eef3
* Content: [Draw shapes and paths - Blend for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/draw-shapes-and-paths?view=vs-2019#feedback)
* Content Source: [docs/designers/draw-shapes-and-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/draw-shapes-and-paths.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@xiejiang2014 Thank you for the feedback.

This might be due to different assets in Visual Studio 2017 changing from Visual Studio 2015 (see [this post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/718d2163-cd65-45da-b471-a2604654be69/path-line-polygon-missing-from-toolbox-and-assets-in-visual-2017-and-blend?forum=wpf)).  

Assigning this to the author for review.

**Comment by TerryGLee** [comment]
@xiejiang2014 You're right; and in fact, @Jcardif reported the same issue. Since then, we've updated the screenshot on the [**Draw shapes and paths**](https://docs.microsoft.com/visualstudio/xaml-tools/draw-shapes-and-paths) page to reflect the issue that you both reported. Thanks for helping us improve the documentation!

(As an FYI, there is a related  [**Developer Community**](https://developercommunity.visualstudio.com/spaces/8/index.html) post, [_Missing drawing assets polygons, paths, polyline and lines in Shapes Asset window_](https://developercommunity.visualstudio.com/content/problem/795343/missing-drawing-assets-polygons-paths-polyline-and.html), which mentions an SDK that you might consider downloading and installing.)
