### ISSUE TITLE
VS Options aren't there

### ISSUE THREAD

**Issue by giorgited** [MicrosoftDocs/visualstudio-docs#4098]
When I right click the VM in Server Explorer the only options I get is Refresh and Configure. I am using VS Professional 2019 V16.2.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4faf174-cdfd-e0d5-3eaf-e2c47d6d8f70
* Version Independent ID: 3464f7d8-21bc-b920-93a8-f5447b835b82
* Content: [Debugging an Azure cloud service or virtual machine - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-debug-cloud-services-virtual-machines?view=vs-2019#feedback)
* Content Source: [docs/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@giorgited -- Giorgi, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
