### ISSUE TITLE
OpenGL ES Application Project Template?

### ISSUE THREAD

**Issue by MuzzyA** [MicrosoftDocs/visualstudio-docs#4104]
Does the project template no longer exist?  Is there a way to get it?  Can we update this guide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c068da-293e-ea09-c3ed-be7d3c7da17d
* Version Independent ID: 70af6750-b737-f536-8ebc-ad3a24becb80
* Content: [Build an OpenGL ES Application on Android and iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-an-opengl-es-application-on-android-and-ios?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MuzzyA 

It works for me, and should for you too, assuming you installed the mobile development with C++ workload. The procedure will be updated for the new project dialog in 2019 soon. Until then, you can find the project template by typing "opengl" in the search box at the top of the **Create a new project** dialog. Most everything else in the article remains the same, but use one of the Google Android emulators instead of the VS Emulator for Android, which still exists but isn't maintained and isn't available to install in the VS installer. I've found it's better to start the emulator before you try to run your code on it from VS; it doesn't always start when launched by VS, and there's no way to cancel it.

**Comment by MuzzyA** [comment]
I have VS 2017 and VS 2019 with Mobile Development with C++.  I get the same options on both of them for native android development.  Both do not have the OpenGL ES template.  Will the template be available in VS 2019 within ~ 3-4 weeks?

Honestly the only reason I want it is to see how drawing geometry in OpenGL ES works.  There are no useful guides online.  The original OpenGL guides don't help because they reference code that isn't available in the "Native-Activity Application" project template for Android.

**Comment by MuzzyA** [comment]
Thanks!  That did the trick.  I have the template available now.

**Comment by corob-msft** [comment]
The docs should be updated by tomorrow or Monday.
