### ISSUE TITLE
odd error

### ISSUE THREAD

**Issue by alkemiker** [MicrosoftDocs/visualstudio-docs#4206]
I'm going thru this tutorial.  At 2.4.4, when I run the app in the debugger, I get an error "ModuleNotFoundError: No module named 'HelloDjangoAppdjango'.  this arises from manage.py command, "execute_from_command_line(sys.argv).

No where in the code have I used HelloDjangoAppdjango.  How or where did the django get appended???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09d5f2d3-bebb-5564-87df-8ab0eedb410c
* Version Independent ID: c1dac521-a8f2-1b81-af35-bd9da71fb6e8
* Content: [Learn Django tutorial in Visual Studio step 2, views and page templates](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-02-create-an-app?view=vs-2019#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-02-create-an-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-02-create-an-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @alkemiker - I just ran through the tutorial up to step 2.4.6 to verify that it was working as expected and didn't encounter the error you mentioned. You might try checking the settings.py file and verifying that you didn't add HelloDjangoAppdjango to the INSTALLED_APPS section. I think that would give the error you mentioned. Otherwise, if everything was working in step 2.3, perhaps go back to that point and try moving forward again. Let me know if that helps.

**Comment by alkemiker** [comment]
Joshua,

 

I had looked there before.  However, after your note, I moved the line ‘HelloDjangoApp’, from the beginning of the declaration to the end.  This worked.  Apparently, inserting lines into the pre-loaded commands is a no-no?  Might have worked had I compiled?

 

Anyway, thanks for the quick response it pointed me in the direction of a solution.

**Comment by JoshuaPartlow** [comment]
Excellent, I'm glad that you were able to get back to a working state. Just as an added thought, it looks like you might also get that output if you didn't put a comma after the HelloDjangoApp entry. Anyway, since it seems like things are working again I'll close this issue, but feel free to open others if you encounter a problem with the tutorial.
