### ISSUE TITLE
Only code without form is displayed in the designer view

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4207]
Hi team,
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/70
The comment was machine translated

@eifcgn24 commented 2 days ago — with docs.microsoft.com
Hi,
I completed the "Getting started" tutorial and downloaded the forms for desktop development in Visual Studio. In the first program the designer form was still to be seen. But now Visual Studio always starts without form. Only the code view is displayed. SHIFT + F7 opens the code view. How do you get the shape displayed again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b7e2601-1fe4-228c-bde4-e29e52c8f7b9
* Version Independent ID: f5e06a1c-63aa-75fb-8398-0cb32db19677
* Content: [Step 3: Set your form properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-3-set-your-form-properties?view=vs-2019#feedback)
* Content Source: [docs/ide/step-3-set-your-form-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-3-set-your-form-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@CeciAc Thanks for forwarding this to us.

@eifcgn24 Vielen Dank, dass Sie uns darüber informiert haben; wir werden uns das ansehen und bald berichten. (Thanks for letting us know; we'll take a look at this and report back soon.)

**Comment by elsoft74** [comment]
I have the same problem. I'm using Visual Studio Community 2019, the forms design windows is missing.

**Comment by aidancahill** [comment]
having the same issue ^

**Comment by TerryGLee** [comment]
@eifcgn24 @elsoft74 Currently, the design window isn't available in the **.NET Core cross-platform development** workload and the _**Windows Forms App (.NET Core)**_ template. (Please know that it will be made available at a later date. We do apologize for the inconvenience.)

Meanwhile, to resolve the issue, please make sure that you are using the **.NET desktop development** workload along with the _**Windows Forms App (.NET Framework)**_ template, as described in [**Step 1: Create a Windows Forms App project**](https://docs.microsoft.com/visualstudio/ide/step-1-create-a-windows-forms-application-project?view=vs-2019) of the tutorial.

**Comment by eifcgn24** [comment]
Why did you close the ticket? I said I did the steps from the tutorial, and for the 1st project the design form was shown. But since the 2nd project on it disappeared. I downloaded Windows Desktop Development module and I select Windows Forms. How can it be unavailable, if I used the design form once?

**Comment by TerryGLee** [comment]
@eifcgn24 I am sorry to hear that you are still experiencing an issue. However, this forum is meant for documentation issues only, and we've tested the steps in the tutorial and cannot reproduce the problem that you describe. Therefore, this might be a product problem rather than a documentation problem.

As such, you might consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

And if its helpful, here some other avenues where you might consider asking a product-specific question:​

- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

Thanks,
~ Terry
