### ISSUE TITLE
Is this function "generating map" fit for linux project?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4209]
@yuqingyang888 commented on [Mon Oct 21 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/162)

Is this function "generating map" fit for linux project?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8e2a9062-ef1a-b4fb-c76c-2a284f2ccb93
* Version Independent ID: 26525968-81c9-f00c-c270-276245099ddd
* Content: [查看源文件和C++标头文件之间的依赖关系 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/modeling/code-maps-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/modeling/code-maps-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/modeling/code-maps-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

---

@srvbpigh commented on [Mon Oct 21 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/162#issuecomment-544537822)

Hello, @yuqingyang888
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the contibutor is requesting aditional information
best

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by thomps23** [comment]
@yuqingyang888 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
