### ISSUE TITLE
Does VSTO project supports visit network and file system?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4224]
@GvcZhang commented on [Thu Oct 24 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/164)

If a create a Excel plugin demo by use VSTO, can the demo support visit network and filesystem?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ccf9a3a9-baf0-3ad5-350f-f4a4eeebea11
* Version Independent ID: f73808db-0922-8266-7a85-90dce0229d65
* Content: [Office 解决方案开发概述 (VSTO) - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/vsto/office-solutions-development-overview-vsto?view=vs-2019)
* Content Source: [docs/vsto/office-solutions-development-overview-vsto.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/office-solutions-development-overview-vsto.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

---

@srvbpigh commented on [Thu Oct 24 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/164#issuecomment-545850781)

Hello, @GvcZhang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the contributor is requesting aditional information
best

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, this looks like the contributor is having an issue with the product itself, rather than an issue with the documentation. Here are a few options where they might consider asking their question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, they might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
