### ISSUE TITLE
List of MsBuild defined targets

### ISSUE THREAD

**Issue by AAATechGuy** [MicrosoftDocs/visualstudio-docs#4233]
It would have been good to have a list of MsBuild pre-defined targets... for e.g., AfterBuild/ BeforeBuild, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a67233-ab6a-e330-7b2d-21c95dd9caba
* Version Independent ID: 381c76df-d847-6ee0-b16e-c7bbc52cec13
* Content: [MSBuild Targets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-targets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-targets.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@AAATechGuy  Thank you for the feedback, assigning this to the author for review.

**Comment by futuralogic** [comment]
This would be helpful, although due to the complexity of various project types I would imagine default msbuild imports would cause a list to be convoluted.

Perhaps documenting the best/official/quickest way to interrogate an sln/csproj for a complete list of build targets and their order would be super helpful.

I stumbled upon this stackoverflow answer: https://stackoverflow.com/a/2781693 which outlines how to create a custom msbuild task to solve the problem.

I would prefer to know how I could simply cli msbuild and have it list them out for me.  Due to multiple default imports with .net core, etc. it's challenging to discover whats actually happening during a build - at least given the information here and around this question.

**Comment by rainersigwald** [comment]
> I would prefer to know how I could simply cli msbuild and have it list them out for me.

This will be possible soon, thanks to https://github.com/microsoft/msbuild/pull/5032

**Comment by StevenTCramer** [comment]
ComputeFilesToPublish doesn't show up in the docs anywhere.

**Comment by ghogen** [comment]
The ability to view all the supported / defined targets is now supported by using the /targets option. See https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference
