### ISSUE TITLE
When will the issue of EMS activation be resolved for Visual Studio Subscriptions?  

### ISSUE THREAD

**Issue by rtwaddell** [MicrosoftDocs/visualstudio-docs#4241]
I have paid for the Visual Studio and expected this to be there.  If this is not resolve, I will either have to incur additional costs (For something I have paid for) or my project will be behind schedule.

**Comment by WilliamAntonRohm** [comment]
@rtwaddell -- It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 

 

If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 

 

If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.

**Comment by rtwaddell** [comment]
@WilliamAntonRohm, I have a subscription and have an open ticket(119102926002643).  This is the issue I am having. https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems.  Any update on when the issue will be resolved would be great.
