### ISSUE TITLE
Command Line Argument Characters

### ISSUE THREAD

**Issue by beweir** [MicrosoftDocs/visualstudio-docs#4247]
There should be a note in the 'Command Line Arguments' section about what characters can not be used.  I have tried to use angle brackets and get an error when I try to run the program for debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4804e60-e04f-d313-96a9-5a070bad94c2
* Version Independent ID: d1bf3507-c21b-b5d1-804a-3ae62e407313
* Content: [Debug Page, Project Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/debug-page-project-designer?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vb.ProjectPropertiesDebug)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/debug-page-project-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/debug-page-project-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I'll ask about this. Thanks for the feedback.

**Comment by Mikejo5000** [comment]
From the product team:
There isn’t any special rules for the characters supported as debug command-line parameters. From the issue it seems like you had an issue passing in some args with <>. It’s not clear if the problem was:
1. The app rejecting the params
2. The project system/launching mechanisms don’t escape the chars correctly
The issues sounds like #1. For the rules around #2, not quite sure what the rules are for encoding and escape chars. That might be something for the project system though.

**Comment by Mikejo5000** [comment]
Issue appears related to app-specific parameters. We would need more info to follow up.
