### ISSUE TITLE
VS intellisense with doc comments from `file` attribute?

### ISSUE THREAD

**Issue by thomps23** [MicrosoftDocs/visualstudio-docs#4279]
Originally filed as issue [#10633](https://github.com/dotnet/docs/issues/10633) in the .NET content repo. Recommendation to refer to this issue for additional context.

> Is there any way to get docs included with the file attribute way to show up as "intellisense"in VS 2017/2019, as it does when the comments are directly in the code file? For example as a tooltip when hovering a member at the point of use. It does not work for me when the doc is in a referenced xml file.

**Comment by TobiasKnauss** [comment]
I stumbled over the same problem today. I have a class with 20 function overloads that all take the same parameters, only the type of one parameter changes (int i_value, bool i_value, double i_value, etc.). That's why I want to avoid copying the same intellisense comment block to all functions and refer to it in a file instead.
The xml file of that project is built correctly, but throughout the whole solution of 64 projects I don't see the comments that were included. Until this is solved, the include tag is pretty useless!
Actually I think that it is clear that included comments should also be shown locally and not be forwarded to another xml file only. Don't understand how you could miss that point when the functionality of the include tag was designed... I am still using VS 2015, but since it hasn't changed for years, updating to VS 2019 is pretty useless on that point.
Any plans when this will be worked on?

**Comment by deap82** [comment]
@TobiasKnauss Actually, when I switched to using VS 2019 this has started working for me.

Here is a summary defined within an included xml file showing up in a tooltip in VS 2019:

![image](https://user-images.githubusercontent.com/1295067/81566050-97d84080-939a-11ea-8372-db9045a5f36c.png)

Property:
![image](https://user-images.githubusercontent.com/1295067/81566291-fdc4c800-939a-11ea-901b-19c7a21fde2a.png)

XML file:
![image](https://user-images.githubusercontent.com/1295067/81566351-0cab7a80-939b-11ea-8450-4d0446c1032e.png)

**Comment by TobiasKnauss** [comment]
@deap82 I have to admit that you're right.
I remember that I have tested this not only on VS 2015, but also on VS 2019, but during my test it did not work. I cannot tell why it didn't at that time, but when I just tested again, I found it working.
Thank you for your notice!
From what I understand now by reading this issue and the orginal https://github.com/dotnet/docs/issues/10633 again, I likely has worked ever since VS 2019 was released... Is this true?
