### ISSUE TITLE
Is there any workarounds for the DLL output is not the location that the calling app is calling ?

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/visualstudio-docs#4283]
Is there any workarounds for the DLL output is **not** the location that the calling app is calling ?

I want to debug my DLL by `start external program`, the program will load my DLL at startup.
In order not to pollute the real target directory, I copy the `dll` and `pdb` to the real target directory by post build event. 
But the breakpoint not hitted. Is there any workaround for this purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c922c9cf-4c0b-18fb-d1bd-afa4303db5fd
* Version Independent ID: 72b4a51f-b499-41b4-6d68-19c9deaf7e3f
* Content: [How to: Debug from a DLL Project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-from-a-dll-project?view=vs-2019)
* Content Source: [docs/debugger/how-to-debug-from-a-dll-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-from-a-dll-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@GreatFireWall -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
