### ISSUE TITLE
But why this is bad?

### ISSUE THREAD

**Issue by PawcioCNCProfi** [MicrosoftDocs/visualstudio-docs#4284]
The case is well described and I understand the example but I don't understand what's wrong with invoking virtual method before the object is initialized? It's totally expected. And I never even assumed that an overridden method is invoked after base constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78518637-409c-e51b-5dfc-75449565ee49
* Version Independent ID: bf378336-08a3-de6c-1c60-18907691342a
* Content: [CA2214: Do not call overridable methods in constructors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214?view=vs-2019&redirectedfrom=MSDN#feedback)
* Content Source: [docs/code-quality/ca2214.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2214.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by ghogen** [comment]
It's bad because when the overridden virtual method is called, the derived class's portion of the object has not yet been initialized, because its constructor wasn't yet called.  This could lead to errors or unexpected behavior, for example, if members are accessed before they have been initialized or set in the derived class constructor.

**Comment by ghogen** [comment]
topic updated
