### ISSUE TITLE
The connection with the remote endpoint was terminated

### ISSUE THREAD

**Issue by silvanknecht** [MicrosoftDocs/visualstudio-docs#4305]
This error message is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284b9094-8c91-69e1-01a2-0183ca3ec2a9
* Version Independent ID: 8f7a16bb-32f6-3047-16e3-b82b82fbb7c0
* Content: [Unable to Connect to the Microsoft Visual Studio Remote Debugging Monitor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor?view=vs-2019)
* Content Source: [docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@silvanknecht Hi, thanks for the feedback. Did you find a resolution to the issue? If so, I can easily add it to this doc.

**Comment by Mikejo5000** [comment]
I saw in one case that running VS as an Administrator resolved it.

**Comment by silvanknecht** [comment]
No i wasn't able to resolve it. @Mikejo5000 I've seen the post with run as administrator but it didn't fix my problem. I was able to solve my problem without debugging. Maybe ill come back to this in the future.

**Comment by joshbouganim** [comment]
This is happening to me. Full Error Message: 

Unable to connect to the Microsoft Visual Studio Remote Debugger named 'mydomainname.azurewebsites.net:4022'.  The connection with the remote endpoint was terminated

* Connection Type: Default
* Attach to: Managed (CoreCLR) code
* Running as Admin didn't work
* It worked once when i first tried it but never worked again after that.
* I've tried closing/opening VS, disabling/enabling remote debugging in azure
* It doesnt ask me for my username/password when trying to connect, I think this is because I'm signed into my VS so

**Comment by Mikejo5000** [comment]
The app is running on Azure App Service, and you are trying to debug via Debug > Attach to Process? Is that correct? (Or is it an Azure VM?) The last time I tried this scenario, the "Attach Debugger" command was recommended instead:
https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure?view=vs-2019#remote_debug_azure_app_service

**Comment by Mikejo5000** [comment]
Need more info before we can update this doc.

**Comment by PrasekMatej** [comment]
In my case, I wanted to debug process on virtual machine hosted on Hyper-V. I tried to connect using IP instead of hostname and it started working.

Jonno Schmidt has a workaround that seems to help a lot of people, after re-installation of Visual Studio, but not me. Anyway I think it's good to mention. https://developercommunity.visualstudio.com/solutions/218098/view.html

**Comment by Mikejo5000** [comment]
Thanks! I'll add that info about the IP address. The link appears to be about an old issue (Windows Defender) that was fixed.
