### ISSUE TITLE
Newly Installed template not appearing under "New Project" templates

### ISSUE THREAD

**Issue by septst** [MicrosoftDocs/visualstudio-docs#4316]
Hello,

I followed the steps mentioned in the article to create a new template and installed the same to see if it works as expected. I can see it installed in "Manage Extensions" but it does not appear under "New Project". Can someone please tell what I may be doing wrong here?

Also, I have installed Steve Smith's Clean Architecture template and it does appear in all places properly. So, this may not be an issue with the IDE itself. 

Thanks in advance!

**Comment by msebolt** [comment]
@septst Thank you for the feedback.

Please include a link to the article and we can assign this to the author.

**Comment by septst** [comment]
> 
> 
> @septst Thank you for the feedback.
> 
> Please include a link to the article and we can assign this to the author.

This is what I had followed to create a new VSIX template.

https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-the-vsix-project-template?view=vs-2019

Please share if there is any updated post on the same. Thanks much!

**Comment by msebolt** [comment]
Assigning this to the author for review.

For issues involving unique user scenarios, please refer to [Visual Studio support](https://visualstudio.microsoft.com/support/) or move the issue to the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by tfosmark** [comment]
@septst It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
