### ISSUE TITLE
Document what it means to require MSBuild 15.8 for running `RoslynCodeTaskFactory`

### ISSUE THREAD

**Issue by caioproiete** [MicrosoftDocs/visualstudio-docs#4319]
The documentation and sample is very useful, but reading from statement "_The RoslynCodeTaskFactory is available in MSBuild 15.8 and above only_" it's not very clear what the minimum requirements are for consumers of MSBuild scripts that use `RoslynCodeTaskFactory`.

e.g.
* What is the minimum version of Visual Studio where a project using `RoslynCodeTaskFactory` would work?
  * i.e. Minimum version of Visual Studio where MSBuild &gt;= 15.8 is guaranteed to be present
* Minimum version of Visual Studio build tools
  * i.e. Minimum version of MSBuild tools where MSBuild &gt;= 15.8 is guaranteed to be present
* Minimum version of the C# language supported
* Minimum version of .NET Full Framework that would need to be installed on the machine (if any)
* Minimum version of .NET Core that would need to be installed on the machine (if any)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8c66d6-dd9b-dddc-dd69-41d22284ec10
* Version Independent ID: 1b750d67-95da-aa4c-ad32-2de54d7a46c5
* Content: [MSBuild Inline Tasks with RoslynCodeTaskFactory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-roslyncodetaskfactory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-roslyncodetaskfactory.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Similar to https://github.com/MicrosoftDocs/visualstudio-docs/issues/4320

**Comment by rainersigwald** [comment]
MSBuild versions follow Visual Studio versions, so `RoslynCodeTaskFactory` is available in Visual Studio (and Visual Studio Build Tools) 15.8 and higher. The rest of the answers follow from that: we require the same .NET version as Visual Studio, and support the same C# language version (this changes over time and isn't directly related to MSBuild/RoslynCodeTaskFactory support).

**Comment by augustoproiete** [comment]
Thanks @rainersigwald. This is helpful.

However, I don't think most developers know what "Visual Studio 15.8" means, to be honest. It would be more useful for everyone if the documentation said **Visual Studio 2017 15.8**.

On the C# version, it would also be very helpful to know what is the minimum version of C# one can use on a machine that has Visual Studio 2017 15.8 (or Visual Studio Build Tools 2017 15.8) so that library authors can target that version of C# to make sure their `RoslynCodeTaskFactory` will compile/run without issues for any dev.

Many of us are building libraries that are distributed via NuGet, with custom build scripts, and we have no idea what the user of the library has installed on the machine.

**Comment by rainersigwald** [comment]
I think you're right that `Visual Studio 2017 version 15.8` is the correct full name.

Do you mean minimum or maximum version? Support for C# 7.3 was introduced in Visual Studio 2017 version 15.7, so you can safely use C# features from 7.3 or lower in `RoslynCodeTaskFactory` cases.

> Many of us are building libraries that are distributed via NuGet, with custom build scripts, and we have no idea what the user of the library has installed on the machine.

If you are developing a build task for inclusion in a NuGet package, I strongly recommend that you build and distribute a task assembly rather than using `RoslynCodeTaskFactory`. It is faster (because it doesn't require compiling code on the developer's machine) and easier to debug.

**Comment by augustoproiete** [comment]
Perfect. Thank you @rainersigwald!

I meant minimum and you answered my question: Ensuring we stick to C# 7.3 features means `RoslynCodeTaskFactory` code will compile on machines that meet the minimum requirement of `Visual Studio 2017 version 15.8`.

Point taken on the advantages of shipping a task assembly together with NuGet packages. The reason `RoslynCodeTaskFactory` caught my eye was the ability to run custom build tasks on any platform (Windows, OSX, Linux) with little setup cost in terms of CI/CD.

I also had in mind that in order to have custom MSBuild tasks that run on any platform, one would have to ship at least two versions of the task assembly: One targeting .NET Standard, and another targeting .NET Framework and then choose which assembly to use at build time (all of which requires some effort and increase complexity... Another reason why `RoslynCodeTaskFactory` seemed attractive to me).

However, now that it's established that `RoslynCodeTaskFactory` requires at least `Visual Studio 2017 version 15.8`, it changes things given that [VS2017 15.8 ensures the user has the .NET Framework 4.7.2 runtime](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.8) on the machine, which means [they can run assemblies targeting .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), so no need to ship a .NET Framework version of the assembly anymore if a project states compatibility with VS 2017 15.8+, which seems fair at this point in time...

Thanks for the help!
