### ISSUE TITLE
Instead of trying to tattle tale/blame a plugin, you should be taking up any issues directly with the author.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4321]
As a user, these messages have no real value to me. Since there is no evidence given to me when VS reports "extension bad, VS good" I dont believe what I'm being told. This is easy to believe because VS has had a very poor stability record over the last 2-3 years. Even if some evidence was provided where a 3rd party plugin was part of a stack trace, that does not absolve VS of any blame. Most of its extension points can be complicated with little useful documentation or examples, and are fairly easy to get wrong.

Instead of disabling an extension I need (that either gives me productivity/work quality increases or that replaces a feature I needed that VS has dropped) I just close Yet Another Gold Bar whine and continue what I was working on before _VS had some problem that interrupted me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and install extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2019#extension-crash-and-unresponsiveness-notifications)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@StingyJack It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
