### ISSUE TITLE
Don't forget to set the extension project as StartUp Project

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/visualstudio-docs#4344]
After the "Save the csproj file and close it." phrase it could be added not to forget to set again that project as Startup Project (using the Set as Startup Project context menu) if you are using more than one project in the solution, because unloading / editing and reloading it loses the startup project setting that that project had before unloading it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa63b4dc-21b4-307f-61d3-a13ce9d0475a
* Version Independent ID: de62d1bc-6f08-edf9-9624-fee65b90185e
* Content: [How to Roundtrip Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-roundtrip-vsixs?view=vs-2019)
* Content Source: [docs/extensibility/how-to-roundtrip-VSIXs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-roundtrip-VSIXs.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @willbrown
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
