### ISSUE TITLE
Can't use local filesystem as installation path when publishing

### ISSUE THREAD

**Issue by tomwimmenhove** [MicrosoftDocs/visualstudio-docs#4349]
After the publish location has been specified, Visual Studio will ask "How will the user install the application?", which gives an option to browse the local filesystem. This, however, is impossible, since every path will result in the following error:
![PublishBug](https://user-images.githubusercontent.com/11983060/69137859-d9f48980-0abd-11ea-94e9-29bc26945ccc.PNG)

It seems like it's impossible to have this set to the local filesystem, which makes me wonder why the option to do so is available.

**Comment by tomwimmenhove** [comment]
I should've looked a little longer at this. Turns out the wizard just fails to convert the path to a URI. Using file:////Deployement/SomeFolder/ does work. This is still a bug, but at least you can work around it.

Next question: What do you do when the folder is not on the main (C) drive?

**Comment by msebolt** [comment]
@tomwimmenhove Thank you for the feedback, we're sorry you're experiencing issues.

Since this is more product-related, please start a ticket using **Report a problem** in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) and link back to this issue.

Also, please include which version Visual Studio you're using and the project type.  For instance, using a web application in Visual Studio 2019 seems to work without issue.

![Capture](https://user-images.githubusercontent.com/6675884/69169119-a9582400-0aac-11ea-961c-2acf272a1ae3.PNG)

To answer your question, for network folders, the format `//serverIP/share` or `//servername/share` should suffice with FTP shares, else use [Map a network drive](https://support.microsoft.com/help/4026635/windows-map-a-network-drive) when user/password access is involved.
