### ISSUE TITLE
IntelliSense completion for unimported types is not working on Visual Studio 2017

### ISSUE THREAD

**Issue by mossila** [MicrosoftDocs/visualstudio-docs#4357]
I have try following on Visual Studio 2017 and it's not working properly. 
```c#
namespace xx.yyy
{
    public class MockObject
    {
        // I type to JsonPropert no such auto complete for `using Newtonsoft.Json;`
        [JsonPropert("id")] 
        // I type full `Guid` but I have to click on light bulb to `using System` 
        public Guid Id { get; set; }
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd2aa72-f769-b1ae-4b9c-55c1d87b74d6
* Version Independent ID: c146f58e-37d4-b7b7-e3c3-ed5990eaaba7
* Content: [IntelliSense completion for unimported types - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/intellisense-completion-unimported-types?view=vs-2019&utm_source=t.co&utm_medium=referral)
* Content Source: [docs/ide/reference/intellisense-completion-unimported-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/intellisense-completion-unimported-types.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@mossila -- Sutean, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

You might also look for answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
