### ISSUE TITLE
Class Library support?

### ISSUE THREAD

**Issue by samtrion** [MicrosoftDocs/visualstudio-docs#4359]
Is there any information about when this feature will be rolled out to other project types? Like netstandard Class Libraries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019&source=docs#feedback)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by WilliamAntonRohm** [comment]
@samtrion -- Martin, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
