### ISSUE TITLE
file path too long exception visual stusio 2019 and git

### ISSUE THREAD

**Issue by arunkumar899** [MicrosoftDocs/visualstudio-docs#4360]
When trying to use git with visual studio 2109 I am getting the exception stating "file path too long exception ". I tried changing the value in the reg to 1 (Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem) and did restart the system but it didn't help and I also modified the git config for filelongpaths to true but even it didn't fix the issue. How do I resolve this issue?

**Comment by ThePiranha** [comment]
@arunkumar899  please try clone the repo directly into C:\ drive. I solved it this way.

**Comment by WilliamAntonRohm** [comment]
@arunkumar899 -- thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
