### ISSUE TITLE
HTTP Error 500.0 - Internal Server Error An unknown FastCGI error occurred

### ISSUE THREAD

**Issue by shobhitnpm** [MicrosoftDocs/visualstudio-docs#4361]
I'm having the issue while deploying Flask application by IIS mapping, please suggest appropriate solution.

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
           <add name="StichingHandler" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Users\DCL45\AppData\Local\Programs\Python\Python37\python.exe|C:\Users\DCL45\AppData\Local\Programs\Python\Python37\Lib\site-packages\wfastcgi.py" resourceType="Unspecified" requireAccess="Script" />
         </handlers>
		 <httpPlatform processPath="C:\Users\DCL45\AppData\Local\Programs\Python\Python37\python.exe"
                  arguments="D:\DCPL\image-stitching-opencv\image-stitching-opencv\ServiceApi.py --port %HTTP_PLATFORM_PORT%"
                  stdoutLogEnabled="true"
                  stdoutLogFile="c:\home\LogFiles\python.log"
                  startupTimeLimit="60"
                  processesPerApplication="16">
      <environmentVariables>
        <environmentVariable name="SERVER_PORT" value="%HTTP_PLATFORM_PORT%" />
      </environmentVariables>
    </httpPlatform>
    </system.webServer>
	<appSettings>
    <!-- Required settings -->
    <add key="WSGI_HANDLER" value="ServiceApi.app" />
    <add key="PYTHONPATH" value="C:\Users\DCL45\AppData\Local\Programs\Python\Python37\" />
  </appSettings>
    <system.web>
        <authentication mode="Forms" />
    </system.web>
</configuration>
```
![image](https://user-images.githubusercontent.com/31316434/69249499-faaf0300-0bd3-11ea-9aaf-0967a4635710.png)

**Comment by WilliamAntonRohm** [comment]
@shobhitnpm -- Shobhit, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
