### ISSUE TITLE
Can't interact with Visual Studio on Catalina

### ISSUE THREAD

**Issue by OMGerCoder** [MicrosoftDocs/visualstudio-docs#4383]
When I try to launch a script in Unity, It does not open!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be31e5a-ccb8-93c5-43a0-ef8327f4ed4e
* Version Independent ID: 2ed7a14e-12ea-ea72-6678-0db050023a62
* Content: [Setup Visual Studio for Mac Tools for Unity - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/setup-vsmac-tools-unity?view=vsmac-2019#feedback)
* Content Source: [mac/setup-vsmac-tools-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/setup-vsmac-tools-unity.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by msebolt** [comment]
@OMGerCoder Thank you for the feedback, we apologize for the issues.

This issue was reported a few months ago in the [forums](https://developercommunity.visualstudio.com/content/problem/619789/visual-studio-wont-open-on-macos-catalina.html) and was reported as fixed.

Please make sure you're using the latest version and post any updates below.

**Comment by OMGerCoder** [comment]
I now use VSCode with Unity.
