### ISSUE TITLE
Getting a "404 page not found error"

### ISSUE THREAD

**Issue by JohnStraumann66** [MicrosoftDocs/visualstudio-docs#4391]
Hi:

I tried to follow this article using an existing project I am working on, however it is not MVC, it is Razor, and I am getting an error, but not sure if that matters? I am able to run the web app, and access the Swagger page, but when I run the GET Command, either in Swagger or postman, I get the error. I am using a "User" model class, and I have a folder with CRUD pages under Pages-&gt;Users, so in the Api folder I named the Controller "PersonController". The site runs fine, uses https://localhost:44309/ but in Postman when I try https://localhost:44309/api/person I get the 404 error? I did add "  services.AddControllers();" to my Startup.cs file. Can you flip me any tips to try to track down what I am doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788828c4-74bc-1bcb-7480-38e490358f18
* Version Independent ID: d62da0a4-9a26-a89d-ff8f-d3314cf35724
* Content: [Step 4: Exposing a web API From Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-04?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@JohnStraumann66 Thank you for the question.

Since this is the documentation forum, our support is limited, however here are some things to try:

- make sure the *web.config* is properly configured, see [here](https://stackoverflow.com/questions/9703090/http-404-page-not-found-in-web-api-hosted-in-iis-7-5) and [here](https://stackoverflow.com/questions/49699639/net-core-404-error-on-server-only)
- make sure IIS has the right features installed, see [here](https://serverfault.com/questions/239081/getting-404-error-on-mvc-web-site)
- enable logging for further details, see [here](https://stackoverflow.com/questions/569252/logging-errors-in-asp-net-mvc)

For additional support options, please refer to [Visual Studio support](https://visualstudio.microsoft.com/support/).
