### ISSUE TITLE
How to copy folders instead of a single file

### ISSUE THREAD

**Issue by TangMonk** [MicrosoftDocs/visualstudio-docs#4421]
If I have multiple files need copy output directory, set Build action for per files in inconvenient 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 797c58ff-3694-adda-188b-4ec4d079bd5c
* Version Independent ID: 442f90ff-9a99-c7dd-23c8-fbe51bcd8c0d
* Content: [Build actions for files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2019#feedback)
* Content Source: [docs/ide/build-actions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/build-actions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@TangMonk  -- Mr. Wu, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
