### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by Caleb-D** [MicrosoftDocs/visualstudio-docs#4423]
I have assertions in my code.  Sometimes I want to run my program without getting any assertion dialogs.  How can I temporarily disable the dialog?  Hopefully without code modifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39dd376d-0708-9844-7689-2d5e2bd3e472
* Version Independent ID: 394b6577-4960-3429-b665-9b1276eecb40
* Content: [Assertion Failed Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/assertion-failed-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/debugger/assertion-failed-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/assertion-failed-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Caleb-D -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Caleb-D** [comment]
No, I came to the documentation looking for information about how to disable.

**Comment by Mikejo5000** [comment]
@Caleb-D You may see this error even if you are not debugging (Release build), so it's not necessarily a debugger issue. Have you tried disabling the Win32 Assertion failed exception? (Debug > Windows > Exception Settings, search for "assertion"). I'm not sure if this will get you the behavior you want, but might be worth a try.

**Comment by Caleb-D** [comment]
@Mikejo5000 This is without the debugger attached.  I assume the Exception Settings only apply when attached.

It's not a problem, per se, except that I would like a way to tell Windows, "don't pop up any assertion dialogs for this process right now," without having to make code changes.  They are my (or my teammates') assertions, so they are expected.  Sometimes I just don't want to see them.

**Comment by Mikejo5000** [comment]
@Caleb-D Do you need to run without the debugger? In VS, the Exception Settings are likely the only method. Closing this again in favor of recommendations by @WilliamAntonRohm

**Comment by Caleb-D** [comment]
I think maybe there is a misunderstanding here.  The exception settings are not going to affect the assertion dialog, regardless of whether the debugger is attached.  This is not the VS exception dialog.  This is the Abort/Retry/Ignore dialog mentioned in the help topic...
