### ISSUE TITLE
Great job moving feedback!

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/visualstudio-docs#443]
Just a small thank you for moving the comments as you have. I kind of expected to see 'give documentation feedback' take me to GitHub. It's not overly clear from the UI, how I follow up on any comments I make (but I found it nevertheless!).

A small point but a great move forward!

When will the rest of the docs be like this???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/visual-studio-ide.md)

**Comment by gewarren** [comment]
@ghogen can you comment on if/when the rest of the docs will have the same feedback mechanism?

**Comment by ghogen** [comment]
@EisenbergEffect for the feedback about the UI.

This is a pilot program on VS, but we expect to refine the mechanism based on feedback and roll it out across the docs.microsoft.com site by the end of March.

**Comment by EisenbergEffect** [comment]
Hey @doctordns Thanks for the feedback. As @ghogen states, we're basically piloting this new experience on just a couple of repos now so that we can iron out the kinks, get some customer feedback and make minor improvements/enhancements before we roll it out more broadly. Assuming the pilot does go well, we'll absolutely be making this the new feedback mechanism across all of docs. We'll be putting ongoing effort into the evolution of this feature as we get feedback from people like you and other, so that we can refine the UI/UX and make this a great experience for you and Microsoft employees to engage.

**Comment by EisenbergEffect** [comment]
@doctordns I've noticed some of these inconsistencies. There may be a few different causes. Can you link me to a few examples where you are not seeing the contributors listed? I'd like to investigate.

**Comment by guibirow** [comment]
As much I like the new system idea, I hate the fact that this is happening over and over.
It used to be a Disqus comment system, then moved to LiveFyre, then moved now to this new system, what will be the next?
The worst part of this all is that MS does not care about past content lost on these discussions, so many times I found issues described in the docs that are gone now.
Please, pay attention to your previous mistakes, don't let the information be lost again, at lest import them as closed issue in the new system.

**Comment by guibirow** [comment]
The '[content source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/visual-studio-ide.md)'  link point to the wrong location, shouldn't it point to [here](https://github.com/MicrosoftDocs/visualstudio-docs/blob/live/docs/ide/visual-studio-ide.md)

**Comment by doctordns** [comment]
I have some sympathy with comments by  @guibirow. But having said that, I think converging on GitHub for both comments (ie issues) and the code (ie solutions) should be in the same place.

In my experience, the idea that MS does not care about past content is just not true. I do agree that some comments, etc were left out with the move from msdn/technet to docs.microsoft.com.  The costs of trying to bring those across sensibly is likely enormous - have you seen just how much junk there is in old comments?

**Comment by guibirow** [comment]
Sure, there were a lot of junk. But in the middle of the junk we could find some valuable information not contained in the docs.
The migration from there to github won't cease the spam, because something that lacks is moderation, so the junk will just have a new the location.

**Comment by gewarren** [comment]
@guibirow thanks for your feedback. We have seen a decrease in "junk" comments since moving to the GitHub issues system. Also, we have all the old LiveFyre comments stored in a database and, time allowing, we plan to address the most important concerns expressed there.

Also, you commented that content source should be linking to the visualstudio-docs repo instead of the visualstudio-docs-pr repo. @EisenbergEffect can you comment on that?

**Comment by EisenbergEffect** [comment]
@ShevaDas Can you follow up with @jdanyow about the GitHub issues content linking? This involves the scenario where there is a public/private repo pair and the content link is pointing to the private repo rather than the public repo.

**Comment by jdanyow** [comment]
@EisenbergEffect, @ShevaDas- I'm working on an update to correct the content linking. Thanks for the heads up :+1:

**Comment by jdanyow** [comment]
@EisenbergEffect, @ShevaDas - the fix for the content linking has shipped. :ship: :shipit: :rocket:

**Comment by EisenbergEffect** [comment]
Great work @jdanyow ! Thank you!

**Comment by gewarren** [comment]
@guibirow thank you for pointing out the bug. @jdanyow thank you for fixing it!
