### ISSUE TITLE
Shared configuration for SDK-style projects?

### ISSUE THREAD

**Issue by lothrop** [MicrosoftDocs/visualstudio-docs#4456]
I was wondering if the shared configuration approach also works for SDK-style projects? I can't seem to get those projects to honor the settings in the shared .editorconfig file. And I can't see the line

```csharp
<Import Project="..\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\build\Microsoft.CodeAnalysis.FxCopAnalyzers.props" Condition="Exists('..\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\build\Microsoft.CodeAnalysis.FxCopAnalyzers.props')" />
```

in the csproj file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b086b-cda0-2741-2b2b-b2d7e87d0ac9
* Version Independent ID: 29465605-4eda-76c5-4254-8976bc17ca37
* Content: [Configure FxCop analyzers using editorconfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/configure-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/configure-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@lothrop -- Kerry, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
