### ISSUE TITLE
Not seeing Data tab in Visual Studio Blend

### ISSUE THREAD

**Issue by dominicgrayDHG** [MicrosoftDocs/visualstudio-docs#4462]
Unable to create sample data like I used to in Blend for a UWP project as I no longer see Data tab.

Microsoft Blend for Visual Studio Community 2019
Version 16.4.0

Microsoft Blend for Visual Studio Community 2019
Version 16.4.0
VisualStudio.16.Release/16.4.0+29519.181
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Blend

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b99aa95-1284-6dbc-22a4-e94a713822c3
* Version Independent ID: d089529d-cb4d-eb0f-7d97-79179618f04b
* Content: [Visualize sample data in a XAML UI - Blend for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/display-data-in-blend?view=vs-2019#feedback)
* Content Source: [docs/xaml-tools/display-data-in-blend.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/display-data-in-blend.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@dominicgrayDHG -- Thanks for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by OZ1** [comment]
https://developercommunity.visualstudio.com/content/problem/436497/this-features-is-not-available-for-projects-target-1.html

**Comment by mgoertz-msft** [comment]
@WilliamAntonRohm, @gewarren, what is the guideline for marking content like this in a way that it only applies to a certain platform?

In this case, this functionality is only available for .NET Framework project and not .NET Core or UWP.

This is a source of confusion for our customers.

Also, the screenshots used here are from a very old version of Blend that we no longer ship.

**Comment by gewarren** [comment]
The best way is probably with a callout block like

```
> [!NOTE]
> Generating sample data is only supported for projects that target .NET Framework. It's not supported for UWP projects or projects that target .NET Core. 
```
