### ISSUE TITLE
How to make custom fording section ???

### ISSUE THREAD

**Issue by UnitSeven** [MicrosoftDocs/visualstudio-docs#4466]
How to make custom fording section ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a727f2b4-d72a-869f-b13b-6a97aa62b7b8
* Version Independent ID: 5321793a-5b70-671c-3829-43ab1483fb43
* Content: [Collapse and expand regions of code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/outlining?view=vs-2019#feedback)
* Content Source: [docs/ide/outlining.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/outlining.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@UnitSeven -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
