### ISSUE TITLE
Release error

### ISSUE THREAD

**Issue by propovednick** [MicrosoftDocs/visualstudio-docs#4468]
This fix for linux image works in debug mode only. When I try to run project using docker in release mode I still get an error: 
npm: not found
MSB3073: The command "npm install" exited with code 127.
Of cause, npm installed and accessible from cmd.
Visual Studio 2019 16.4, core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Visual Studio Container Tools with ASP.NET Core and React.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019#feedback)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-tools-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@propovednick -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
