### ISSUE TITLE
Custom null-check validation methods still reporting a false positive

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/visualstudio-docs#4481]
Regarding the section: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019#null-check-validation-methods

The example shows how to add 'custom' methods that validate for null, e.g.

dotnet_code_quality.CA1062.null_check_validation_methods = Validate1|Validate2

But I'm finding that this isn't working in my hands.  Using a WebApi written in C# using .Net Core 3.1 and set to have nullables with FxCopAnalyzer v2.9.8, I have the following line in my .editorconfig file:

dotnet_code_quality.null_check_validation_methods = HasItems | HasNoValue | HasValue| HasNoItems

Note: I have tried this without spaces, e.g. '...= HasItems|HasNoValue|HasValue|HasNoItems', and with the brackets, e.g. '....= HasItems() | HasNoValue() | HasValue() | HasNoItems()

So these are all extension methods that check for nulls and other stuff too....

In my Controller I have:

public async Task&lt;ActionResult&lt;List&lt;string&gt;&gt;&gt; GetSomethingAsync(...)
{
....
List&lt;string&gt;? possibleData = await this.TryGetSomeDataAsync(...).ConfigureAwait(true);
if (possibleData.HasItems())
{
    return possibleData;  // &lt;-- this is giving me 'Possible null reference argument...'
}
....
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019)
* Content Source: [docs/code-quality/ca1062.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@DrGriff -- Thanks for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
