### ISSUE TITLE
How do I reopen Solution Explorer?

### ISSUE THREAD

**Issue by esapilearn** [MicrosoftDocs/visualstudio-docs#4483]
Accidentally closed the window.  How do I get it back??? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@esapilearn -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by TerryGLee** [comment]
@esapilearn To get Solution Explorer back, click **Window** > **Reset Window Layout** from the menu bar. I'll add this info to the page.
