### ISSUE TITLE
not happy about " To activate the Office Developer subscription, a new tenant is required."

### ISSUE THREAD

**Issue by chuckrichards** [MicrosoftDocs/visualstudio-docs#4484]
really disappointed that I cannot utilize an existing development subscription  this requires me to reconfigure my existing MSDN dev environment.  is there a long term plan to resolve this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [The Microsoft 365 benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#feedback)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by skeeler** [comment]
+1 / agreed. I have an existing AAD tenant my Office Dev E3 (from VS) is using, which has been configured with a custom domain name, and is part of a Windows Virtual Desktop demo/test environment. I'd rather not set everything up from scratch simply because the O365 E3 VS benefit can't be upgraded in-place to the new M365 E5. What's the best way to track & get notified when this capability becomes available (as now indicated in the docs as "in coming months")?

**Comment by WilliamAntonRohm** [comment]
@chuckrichards, @skeeler -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by skeeler** [comment]
@WilliamAntonRohm, this isn't a problem with Visual Studio per-se, so I'm not sure that using the Report a Problem instructions is most applicable in this scenario. Would it be better perhaps for us to use the [Contact Support](https://visualstudio.microsoft.com/subscriptions/support/#talktous) link at the bottom of the [My Visual Studio > Get Help](https://my.visualstudio.com/GetHelp) page?

**Comment by evanwindom** [comment]
@skeeler, @chuckrichards - I spoke to our engineering team.  They're working on a solution, but it's still not going to be an "upgrade in place" kind of thing.  The plan is to enable users to create a new E5 tenant and migrate assets over from their existing E3 tenant.  The team posted the following on User Voice recently regarding this issue:

"Thanks for all your feedback and votes. Understand this is frustrating. Not sure it helps you, but many of us in the team are also frustrated and wanted to get this done sooner. We have been resource constrained.

I can tell you this is getting high priority based on the feedback we have been getting, which helps us to make sure this gets the priority it deserves.

The featured is speced and we are looking to get this done by Feb 2020. The good news is you will also get the ability to delete a subscription and start over, which is something we have also heard from our developers they wanted."

**Comment by skeeler** [comment]
@evanwindom - I don't think what you've described as the engineering team's plan will help me at all. I.e. "not an upgrade in place" but rather "migrate assets from E3 tenant". This is because my configuration (which takes a long time to setup by the way) involves configuration outside of the Office tenant - in the Azure & AAD portals for WVD setup, and I'm assuming any settings pointing "inward" at the O365 tenant will not get migrated as part of their plan. I suspect there are other scenarios (beyond my WVD specific one), where there is going to be a lot of manual effort needed to take advantage of the E3 to E5 offer. I don't understand why entitlement has to be so difficult (for the engineering team and for customers); shouldn't it just be a licensing switch?

**Comment by evanwindom** [comment]
@skeeler - I have forwarded your response to the engineering team.  Since we're in the middle of the holidays, it may be after the first of the year before we get a response.

**Comment by pocketfox** [comment]
+1 ,  also want to upgrade my MSDN dev tenant from E3 to E5 to test some EMS capabilities.  I have o365 tenant config, custom domain, and associated Azure AD / PaaS services set up and don't want to start over.

@evanwindom, It's the end of Feb now, is there any announcement or update to your comment above:  "The featured is speced and we are looking to get this done by Feb 2020. "

**Comment by jopgommans** [comment]
+1 on this. I have had a tenants since the age of MSDN indeed. Moving to a new tenant would have a big impact on my personal test-environments. Adding this for existing tenants (EMS E5 and moving to O365 E5) would be very, very, very much appreciated!

**Comment by Ayanmullick** [comment]
AzAD signin to AzVM requires the M365 licenses to be on the same tenant as the subscription.
https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows
Having to create a new tenant beats the purpose.
