### ISSUE TITLE
Configure Severity for Asp.netcore Controller Action methods [CA1822: Mark members as static]

### ISSUE THREAD

**Issue by fvilches17** [MicrosoftDocs/visualstudio-docs#4504]
Hi,

If you install the FX Cop analyzer on an asp.net core project which contains controllers (e.g. web api template), you get this warning on Controller Actions. E.g.

[HttpGet]
public IEnumerable&lt;WeatherForecast&gt; Get() //member Get does not access instance data and can be marked as static

Is there a straightforward way to have the analizer ignore this rule JUST on controllers for instnance? E.g. via the editorconfig file.

Or better yet, have the analyzer itself ignore this rule on asp.net core controllers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b086b-cda0-2741-2b2b-b2d7e87d0ac9
* Version Independent ID: 29465605-4eda-76c5-4254-8976bc17ca37
* Content: [Configure FxCop analyzers using editorconfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/configure-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/configure-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@fvilches17 -- Francisco, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
