### ISSUE TITLE
Button step introduces issue if you only have the view->other windows command

### ISSUE THREAD

**Issue by javierdlg** [MicrosoftDocs/visualstudio-docs#4507]
The document says to modify the existing button, but if a user follows the steps in the "Create a tool window" page, the only button they have is the command button to start the toolwindow. this will break their experience and wont be able to run the extension. Instead it should say "make a new button command"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce85c6d-373e-1ba7-487c-4f5fe7592604
* Version Independent ID: 079ce197-1df6-361f-be99-6ceac03256ca
* Content: [Adding a Toolbar to a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-toolbar-to-a-tool-window?view=vs-2019#feedback)
* Content Source: [docs/extensibility/adding-a-toolbar-to-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-toolbar-to-a-tool-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
