### ISSUE TITLE
add new exolenation is outdated

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4509]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/75
@BrayanKhosravian commented 3 days ago — with docs.microsoft.com
hi. this seems to be outdated: "In the Solution Explorer, right-click the project node and select Add &gt; New Item. Go to the Visual C# Extensibility node and select Editor Classifier. Leave the default file name (EditorClassifier1.cs)."

it is possible to add a new Editor Classifier with Add =&gt; Component =&gt; then search for "Editor Classifier"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3619ee-c26c-770f-595e-f3932b4852b0
* Version Independent ID: 677edcd7-7893-369d-0e06-11a56b05eff5
* Content: [Creating an Extension with an Editor Item Template - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-an-extension-with-an-editor-item-template?view=vs-2019)
* Content Source: [docs/extensibility/creating-an-extension-with-an-editor-item-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-an-extension-with-an-editor-item-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
