### ISSUE TITLE
How to cancel item creation?

### ISSUE THREAD

**Issue by PawcioCNCProfi** [MicrosoftDocs/visualstudio-docs#4515]
Hi, I've created cancel button in my view and I would like to cancel creation of the item when it is hit. How do I do that?

```c#
public void RunStarted(object automationObject,
			Dictionary<string, string> replacementsDictionary,
			WizardRunKind runKind, object[] customParams)
{
    var pop = new System.Windows.Window();
    pop.Width = pop.Height = 400;
    pop.WindowStartupLocation = WindowStartupLocation.CenterScreen;
    var wv = new ToolTemplateWizzardView();
    pop.ShowDialog();

    if (wv.confirmed) {
        replacementsDictionary.Add("$myMessage$", wv.iconFile);
    } else {
        //????
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* Content: [How to: Use Wizards with Project Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2019)
* Content Source: [docs/extensibility/how-to-use-wizards-with-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@PawcioCNCProfi  Thank you for the question.

Unfortunately, since this is the documentation forum our support options are limited.

For help with specific user scenarios, please use one of the following:

- [Visual Studio community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Visual Studio on Stack Overflow](https://stackoverflow.com/questions/tagged/visual-studio)

@madskristensen

**Comment by priteshdahivelkar** [comment]
I also want same solution
