### ISSUE TITLE
No such thing as DTE.SolutionBuilder

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/visualstudio-docs#4525]
There is no such thing as DTE.SolutionBuilder in the EnvDTE automation model. Maybe you refer to DTE.Solution.SolutionBuild, which BTW is so lame (http://www.visualstudioextensibility.com/2008/08/29/the-convoluted-build-configuration-of-the-automation-model-envdte-envdte80/) that even when you understand it, it doesn't allow to delete solution platforms (https://www.mztools.com/articles/2013/MZ2013009.aspx). So, there is no Visual Studio API (neither native service API nor automation API) to delete solution configurations for a given platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7426cc2a-fcd8-e8a3-5fe6-4e5473be9cc5
* Version Independent ID: cef55019-bdd5-aec6-ac24-96227bdc8828
* Content: [Solution Configuration - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-configuration?view=vs-2019)
* Content Source: [docs/extensibility/internals/solution-configuration.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-configuration.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@carlos-quintero -- Carlos, thank you for your feedback and for catching that typo.  The remainder looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

@madskristensen -- Mads, please look into this issue.

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- please review the above-mentioned PR 5935.
