### ISSUE TITLE
Which versions of Visual Studio support XSLT debugger.

### ISSUE THREAD

**Issue by sguitardude** [MicrosoftDocs/visualstudio-docs#4537]
On the overview page
https://docs.microsoft.com/en-us/visualstudio/xml-tools/debugging-xslt?view=vs-2019
It states: XSLT debugger is only available in the Professional and Enterprise editions of Visual Studio.

On the Walkthrough:  Debug an XSLT style sheet page
https://docs.microsoft.com/en-us/visualstudio/xml-tools/walkthrough-debug-an-xslt-style-sheet?view=vs-2019
It states:  The XSLT debugger is only available in the Enterprise edition of Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd893f19-8b45-6789-ee72-15439f7a7816
* Version Independent ID: 12d0b503-0dc0-3777-d73f-306fbdc425b4
* Content: [Ways to debug XSLT code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xml-tools/debugging-xslt?view=vs-2019)
* Content Source: [docs/xml-tools/debugging-xslt.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xml-tools/debugging-xslt.md)
* Product: **visual-studio-windows**
* Technology: **vs-xml-tools**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by TerryGLee** [comment]
@sguitardude Thanks for your feedback, and apologies that it's taken us so long to respond. You are absolutely right; the Note on the [Walkthrough: Debug an XSLT style sheet](https://docs.microsoft.com/en-us/visualstudio/xml-tools/walkthrough-debug-an-xslt-style-sheet?view=vs-2019) required updating. We have a PR in the queue to change it so that it says "The XSLT debugger is only available in the Professional and Enterprise editions of Visual Studio." This update should be published after 4:00pm PST today. We'll close this issue now, with our thanks to you for helping improve the documentation!
