### ISSUE TITLE
VS2019 Tools for Unity does not work for Unity versions earlier than 2019

### ISSUE THREAD

**Issue by Lyrcaxis** [MicrosoftDocs/visualstudio-docs#4538]
Highlights and auto-complete for VS2019 do not appear for Unity versions before 2019.
Is that intended? Is there a way to remove that limitation?

**Comment by WilliamAntonRohm** [comment]
@Lyrcaxis -- Lyrc, thanks for your questions. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your questions:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
