### ISSUE TITLE
Missing code example

### ISSUE THREAD

**Issue by PhilJollans** [MicrosoftDocs/visualstudio-docs#4545]
This page contains the text  
&lt;CodeContentPlaceHolder&gt;8 

I think this is probably a mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80f34ed-f876-6490-af53-dd6968ad6591
* Version Independent ID: 51cd1707-9139-8873-51e8-237a153bd0a9
* Content: [Language Service and Editor Extension Points - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-service-and-editor-extension-points?view=vs-2019#feedback)
* Content Source: [docs/extensibility/language-service-and-editor-extension-points.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/language-service-and-editor-extension-points.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
