### ISSUE TITLE
Coded UI Test Builder of Visual Studio 2019

### ISSUE THREAD

**Issue by aramadasu** [MicrosoftDocs/visualstudio-docs#4548]
With coded UI test builder being deprecated after Visual Studio 2019,it was written as recommended to use Selenium for functional web testing. How about support of edge browser,whats the alternative over there? .Is it really true that Coded UI test builder getting deprecated ?

**Comment by StingyJack** [comment]
CodedUi will no longer be included after Vs2019. I was told this publically either here on GH or on Developer Community by a MSFT Program Manager.

If I can find that post or the announcement, I will link it here. The gist of the reasoning was that "everyone was using selenium already". Which is mostly true, coded ui had a significantly high knowledge barrier of entry. I still think they should have worked to reduce that barrier, or taken steps to automate a-la intellitest.

**Comment by WilliamAntonRohm** [comment]
@aramadasu -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
-[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
