### ISSUE TITLE
Transcript not automatic

### ISSUE THREAD

**Issue by codejoncode** [MicrosoftDocs/visualstudio-docs#4561]
I am not getting any errors. However, when I change the elements it does not render. I have to perform the test where you run the cmd node_modules\.bin\webpack app.tsx --config webpack-config.js again.    

I understand 

> "Each time you make changes to app.tsx, you must rerun the webpack command. To automate this step, add a build script to transpile the JSX."

For the reason above I followed the instructions and added "scripts"

![image](https://user-images.githubusercontent.com/38900224/71533327-b6dba780-28bd-11ea-8b64-23e7a9db6281.png)

Not sure how else I can get past this.

**Comment by WilliamAntonRohm** [comment]
@codejoncode -- Jonathan, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
