### ISSUE TITLE
Unclear how to specify which architecture to build for

### ISSUE THREAD

**Issue by al45tair** [MicrosoftDocs/visualstudio-docs#4562]
It's unclear how to specify which architecture to build for using the CL task. For now I've used a hacky solution by explicitly setting the ToolExe argument (which isn't documented).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f661a-927a-adb4-10b0-b4f04cec61a9
* Version Independent ID: e87ab8a0-6a80-fd99-9332-e5263ce9539a
* Content: [CL Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/cl-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/cl-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/cl-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
Added links to the C++ docs which cover how platforms work with MSBuild, especially the environment variables.

**Comment by al45tair** [comment]
**This does not, in fact, fix this issue. Please re-open it.**

**Comment by ghogen** [comment]
@al45tair Looking more closely, thanks for your patience.

**Comment by ghogen** [comment]
One does not normally invoke the CL task directly, as the task is usually called in the imported .targets files (starting with Microsoft.Cpp.targets imported at the end of a C++ project file created by Visual Studio) that handle the architecture in the property $(Platform) and $(ProjectConfiguration) which is $(Configuration)|$(Platform). 

So, to build a C++ MSBuild project file with the architecture 'x86', this is $(Platform) == Win32 and for "x64" it's "x64".  Other values may be found in the MSBuild targets folder structure at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Platforms

You can specify one configuration to build on the command line :
msbuild Project1.vcxproj /p:Platform=Win32

Or set the ProjectConfiguration

msbuild Project1.vcxproj "/p:ProjectConfiguration=Debug|Win32"

This works because the properties are set when the Microsoft.Cpp.Common.targets file is imported, which eventually imports a project file that defines a target that includes the CL task.

If you do not specify $(Platform) at the command line, this comes from the environment variable $(Platform), or if you are running MSBuild from Visual Studio, it is the active configuration.

Are you creating an MSBuild script from scratch and using CL task directly or how are you customizing the build?  I can add some clarifications to the documentation for the situations just desribed, but if you are doing something more complex, it would help to have more information.

**Comment by al45tair** [comment]
Thanks for the extra information. Indeed, I was attempting to create an MSBuild script from scratch that used the CL task directly. It seems to me that, while not many people are likely to do this, the documentation (and indeed MSBuild) probably should support doing it.

The reason I didn't want to just use Visual C++'s ".targets" files is that I was trying to use it as an alternative to make, to build a project where I explicitly want to build both 32-bit and 64-bit versions of libraries and binaries in a single MSBuild invocation without changing project settings to do so. The fact I wanted to do both builds in one invocation meant that telling people to use vcvarsXX.bat or run from the various command prompts wasn't really an option either.

I spent quite some time reading through the .targets files, trying to figure out how they made this work, but in the end came to the conclusion that it just wasn't obvious why the "Platform" option worked and that there was a little too much undocumented behaviour involved.

In the end, after investigating what MSBuild and the vcvarsXX batch files did, I settled on using GNU Make, with vswhere and some registry queries to automatically pick up the tools and include/library paths.

**Comment by al45tair** [comment]
You can see my attempt at an MSBuild-based build system [in my ArgX project](https://github.com/al45tair/ArgX/blob/83633fd1e525d74fd17e410eedeb5de2ad8a7eb3/ArgX.vcxproj). I had it basically working with the version of MSBuild on my system, but eventually ditched it because I was finding it difficult to make it work on Travis-CI.

**Comment by ghogen** [comment]
Thanks for the context. We'll be discussing this internally and decide what actions to take, if any.

**Comment by ghogen** [comment]
Talked with the engineers, and we feel that using the Cl task directly is a pretty advanced scenario, not the priority right now. I'll close this for the moment and see if any further inquiries about this come up.
