### ISSUE TITLE
View menu, Other Windows > Data Sources not available

### ISSUE THREAD

**Issue by Xenon69** [MicrosoftDocs/visualstudio-docs#4581]
I can't found "Data Sources" in Visual Studio Community 2019, any hint?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019#feedback)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Xenon69 -- Fred, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
