### ISSUE TITLE
AD0001 Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.FixAnalyzers.CSharpFixerWithFixAllAnalyzer' threw an exception of type 'System.TypeInitializationException

### ISSUE THREAD

**Issue by menaheme** [MicrosoftDocs/visualstudio-docs#4614]
i get the warning in the title for almost all my prjects in VS 2019 (16.4.2) (running on windows 10).

The reason i posred here is that i
cannot open an issue from VS as its in a closed network, 
cannot figure out how to open an open an issue from the website. (can you juts use git hub for VS as well ? its good enough for docs no ?)

**Comment by WilliamAntonRohm** [comment]
@menaheme -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by menaheme** [comment]
Code analyzers in visual studio

**Comment by menaheme** [comment]
The kind that is describes here [https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019](docs)

**Comment by WilliamAntonRohm** [comment]
@menaheme -- thank you for clarifying.  It seems this case is a product issue rather than a documentation issue.  You may find additional information here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by menaheme** [comment]
@WilliamAntonRohm i gues you did not read my post where i explained why i posted here and why i cant use the tool you suggested. Never mind ill figure something out
