### ISSUE TITLE
No description of asset types

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/visualstudio-docs#4641]
There's a list here of all the asset type names:
https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019#assets-element
But there's no description of what each of them are for (some you can guess, but the first one I have no idea).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55af1eb8-318c-fac9-410d-550b74425218
* Version Independent ID: 5b62e93a-9d46-6cde-9293-9c775ae61816
* Content: [VSIX Extension Schema 2.0 Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019#assets-element)
* Content Source: [docs/extensibility/vsix-extension-schema-2-0-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vsix-extension-schema-2-0-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by dotMorten** [comment]
Why close it if it hasn't been addressed and will be later? That just seems counter intuitive and a bit demoralizing for submitters
