### ISSUE TITLE
Warnings of limited value

### ISSUE THREAD

**Issue by glburman** [MicrosoftDocs/visualstudio-docs#4666]
I'm not the first person to say this and imho it needs to be taken more seriously :  There is limited value to warnings or, having a 'properties' box, when there is no indication of where in the project the warning was generated.  I can't scour 10,000's of lines of code trying to figure out where I went wrong.

Now, its possible that I'm going to go off on this and there is in fact an answer buried somewhere in the docs, but as far as I can tell questions about it are simply being referred back to the page which as far as I can tell, is an entry to an infinite loop.

Knowing where the warning was triggered is what would give the warning critical context for the elegantly concise (ahem) messages, and thus understanding, for people who's lives are not buried in the compiler.

There is a lot here about  how to suppress or re-grade warnings. 

Why would I do that? Why would I install the Analyzer packages and then set about spending hours learning about how to and suppressing the output? How do I know which ones I really care about? Maybe I should only note the "X's" and downgrade them to "!" ? If I wasn't the boss I'm sure it would make the boss happier. Hmmm.

OK, some of the warnings do provide a bit of an idea where one might look, depending on how advanced a user is, but in general terms I (and I'm thinking many others) simply don't have the time to jack around with them which is frustrating because I'm pretty sure there are things in there I *should* be aware of and fix, and it doesn't strike me as all that difficult an ask. 

All we need is to know where the thing burped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#analyzers-in-solution-explorer)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@glburman -- Greg, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
