### ISSUE TITLE
Does not work in .net core

### ISSUE THREAD

**Issue by TonyKenny666** [MicrosoftDocs/visualstudio-docs#4669]
Template parameters do not work in .Net core 3.0 as using them generated code that depends upon System.Runtime.Remoting which is not available in core. 
Example from the code generated when the template is saved:  object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TheSetting");
Created in VS For mac, 8.4 build 2657
Runtime Version:4.0.30319.42000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4771496c-436c-0b91-87ec-30e480d02a34
* Version Independent ID: d9431d72-6bc8-f0be-6ae7-c57f2a205e6f
* Content: [T4 Parameter Directive - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/t4-parameter-directive?view=vs-2019#feedback)
* Content Source: [docs/modeling/t4-parameter-directive.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/t4-parameter-directive.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by mgoertz-msft** [comment]
This is not a doc issue. There is a Developer Community ticket for this here: https://developercommunity.visualstudio.com/content/idea/881587/support-loading-of-net-core-libraries-in-t4-templa.html

**Comment by JoshuaPartlow** [comment]
Closing based on above.

**Comment by A9G-Data-Droid** [comment]
It becomes a document issue when there is nothing that tells you about this limitation. Over two years later this problem is still present and there is no compatibility matrix that shows you can't  make a .NET6 project that contains a T4 template, despite that being the current LTS version of .NET. 

Even the error message you get in VS2022 isn't clear. It says that the dependency is missing which sends the developer on a goose chase that ends in that dependency will never be brought into .NET6. So how can we use a T4 template in a modern LTS .net6 project?

The documentation needs to be clear that for your T4 project to be compatible with a .NET6 project it needs to target `.netstandard2.0`

**Comment by mgoertz-msft** [comment]
I would like to add a small but important distinction. You can use T4 templates in .NET 6 projects. You just cannot use .NET 6 assemblies within your T4 templates.

**Comment by A9G-Data-Droid** [comment]
@mgoertz-msft Can you elaborate on this a bit? I have a T4 template in a .NET6 project and it's throwing the above error because the code generated by `TextTemplatingFilePreprocessor` is adding lines with `System.Runtime.Remoting`, which doesn't exist in .NET6. This sounds like the exact opposite of what you are saying.

How can you use a T4 template in a .NET6 project when the template processor depends on assemblies that don't exist in .NET6?

**Comment by mgoertz-msft** [comment]
@A9G-Data-Droid I'm sorry, I see where the confusion is coming from now. I missed the fact that this is all about VS for Mac, which has an entirely different T4 implementation not owned by my team. I was talking about VS Windows, which should support this just fine. I'm afraid I don't know much about the limitations of the mono/t4 implementation.

The referenced documentation link above  actually says that only applies to VS, and not VS for Mac or VS Code:
> Applies to: yesVisual Studio noVisual Studio for Mac noVisual Studio Code

**Comment by A9G-Data-Droid** [comment]
I am using Windows. I am not using MonoT4 .

```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.6
```

That's just an example I can find on GitHub of the same issue.

**Comment by mgoertz-msft** [comment]
@A9G-Data-Droid In that case, would you mind opening a feedback ticket via VS's Report a problem functionality and attaching a small repro project?

**Comment by A9G-Data-Droid** [comment]
@mgoertz-msft Sorry, I know this isn't the place but those report a problem things don't exist in my copy of Visual Studio for whatever reason. I'm missing both the icon and the Help menu item.

Looks like this:

![image](https://user-images.githubusercontent.com/26984068/195444239-497cb494-cbea-4546-a4ce-4b74dde7bbc4.png)

I tried going to the website and it tells me to use the menus in visual studio that don't exist.

https://developercommunity.visualstudio.com/report?space=8&entry=problem

**Comment by mgoertz-msft** [comment]
@A9G-Data-Droid Thanks for reporting this problem with report a problem. I'm trying to find someone to follow up with you on that...

**Comment by WilliamAntonRohm** [comment]
@A9G-Data-Droid -- String, for issues with the Feedback Tool in Visual Studio, please email us at [vsfeedback@microsoft.com](mailto:vsfeedback@microsoft.com).
