### ISSUE TITLE
Publish to staging

### ISSUE THREAD

**Issue by nothingimportant55** [MicrosoftDocs/visualstudio-docs#4672]
In visual studio for windows, I can publish to the staging area, but with mac, I can only choose the prodution slot (for Azure Functions). It would be great if we could also publish to staging using visual studio for mac. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4caaf0cc-3cea-375a-1160-6540db5557f1
* Version Independent ID: cfd2fe36-1325-9ff0-bc18-af563bb920e4
* Content: [Introduction to Azure Functions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions?view=vsmac-2019#feedback)
* Content Source: [mac/azure-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by WilliamAntonRohm** [comment]
@nothingimportant55 -- It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
