### ISSUE TITLE
VS 2019 hangs with "initializing debugger" for "Linux-Debug" and "Linux-Release"

### ISSUE THREAD

**Issue by oviupstack** [MicrosoftDocs/visualstudio-docs#4680]
I have Microsoft Visual Studio Professional 2019 Version 16.4.2
I want to build and debug a c++ project for Linux.  My whole setup used to work great, I was able to build my project (c++) and debug it as well. 
One day it stopped working (I am not 100% sure if it was before or after I installed latest VS update). 

Problem: When I start debugging the VS builds the project and __hangs forever__ with the dialog showing the message __"Initializing debugger"__.

I have my bash setup correctly, ssh server started and tested (VS has a connection opened and tested to it), the MS cmake 3.16.3311152-MSVC_2,  build-essential, gdb, zip, rsync, gcc.

The "Debug->Linux Console" window is empty, not showing anything.
On the output window there's no error or warning printed/shown and no other popup either.

How can I investigate, understand what is going on? I can provide any detail needed to move on with this matter which is blocking my progress.

Thank you!

**Comment by corob-msft** [comment]
@oviupstack 
Sorry it's giving you difficulty. Your issue is really a product support request, not a doc bug, and the best place to get help with the product is on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). That's where issues get the attention of the development team and other helpful people who may be able to set you right. Good luck!
