### ISSUE TITLE
Which version(s) of Visual Studio supports .Net SDK-style projects?

### ISSUE THREAD

**Issue by bhardwajs** [MicrosoftDocs/visualstudio-docs#4691]
This question came up in an[ issue with CMake team](https://gitlab.kitware.com/cmake/cmake/issues/20227).

CMake has generators for different versions of Visual Studio (VS, e.g., VS 2017, 2019, etc.) Which versions of [VS support .Net SDK-style projects](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)? I have asked .Net team [and they redirected here](https://github.com/dotnet/docs/issues/16787).

**Comment by msebolt** [comment]
@bhardwajs Thank you for the question and for contacting Microsoft.

Please refer to [CMake projects in Visual Studio](https://docs.microsoft.com/cpp/build/cmake-projects-in-visual-studio) for further guidance.

Assigning the author for further review.

**Comment by corob-msft** [comment]
@bhardwajs

I'm sorry, it appears you've been misdirected yet again. (Glares at @msebolt )

I don't know where to point you if you're looking for which version of VS first supported a particular version of .NET Core for SDK projects. I would have suggested @mairaw or @Thraka, but I see the latter has already [answered your other query](https://github.com/dotnet/docs/issues/16787).

For a question about *when* a particular feature appeared in VS, you might find the answer in the [Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-history) documentation. I'm not sure who manages those, but it might be something @TerryGLee would know.

Otherwise, this sounds like a question for the product team, not the writers. [Developer Community](https://developercommunity.visualstudio.com/spaces/61/index.html) may be the best place to get traction on that kind of question. And I'm really sorry that you're getting the runaround.

**Comment by mairaw** [comment]
I think the closest you'll have to that answer is https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-windows#install-with-visual-studio. But that article only covers the currently supported SDK versions (we do need to update to remove 2.2 from that article). 

But VS 2017 was when the SDK-style projects were introduced. This is from a legacy branch we have in our repo: https://github.com/dotnet/docs/blob/project.json/docs/core/windows-prerequisites.md#prerequisites-with-visual-studio

**Comment by bhardwajs** [comment]
Thank you all! Seems Visual Studio 2017 and later is what we should target for SDK-style projects. I will close the issue.
