### ISSUE TITLE
Specify the location Exec uses to run a command

### ISSUE THREAD

**Issue by pcunite** [MicrosoftDocs/visualstudio-docs#4698]
Exec does not directly invoke a command and thus creates a cmd file in "AppData\Local\Temp". However, this is a restricted folder on my system. I need to specify the path to a valid directory marked for execution.

How to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@pcunite -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup, or for a documentation update request.  We hope to hear from you again.
