### ISSUE TITLE
DTE Dependencies

### ISSUE THREAD

**Issue by aodl** [MicrosoftDocs/visualstudio-docs#4701]
On this page its state that "Features that use the following types will need to adopt new APIs to support Open Folder: ... DTE", but there isn't any further discussion about when and why this is the case. 

What if you are using DTE to trigger IDE commands like "File.Openfile" or "Edit.GoTo"? Currently in Open Folder I'm able to retrieve the global service provider, get the DTE object, and trigger commands like this, and it works. However based on the information in this page, presumably Open Folder is not intended to work well with DTE and it shouldn't be used? What are the alternatives for the various use cases, such as the one I've described?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6499173e-c4c5-1403-37fa-ef87a734bd10
* Version Independent ID: b1235a7f-3f73-be6b-2cd3-3dae3fd2ba98
* Content: [Visual Studio Open Folder extensibility overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/open-folder?view=vs-2019#feedback)
* Content Source: [docs/extensibility/open-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/open-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @vukelich
* Microsoft Alias: **svukel**

**Comment by msebolt** [comment]
@aodl  Thank you for the feedback.

Assigning this to the author for further review.

**Comment by vukelich** [comment]
@msebolt , can you please assign this to @sgreenmsft ?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
