### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by 161134050** [MicrosoftDocs/visualstudio-docs#4702]
Similar to issue #2103

I do not see "Windows Forms" as an option in the 'Create a new project' window.

![image](https://user-images.githubusercontent.com/39843740/73118696-7a6d9b00-3f92-11ea-889f-fee9b82f50d1.png)

I do, indeed have the feature installed as requried

![image](https://user-images.githubusercontent.com/39843740/73118698-8194a900-3f92-11ea-8bee-8b48f965dcba.png)

**Comment by msebolt** [comment]
@161134050 Thank you for the feedback, we apologize for any issues you're having.

Try a search for `forms`, and press the `Clear filter` or `Clear all` option before your search:

![Capture](https://user-images.githubusercontent.com/6675884/73202883-d9492680-40f0-11ea-99ed-a3b3e7bfe7ac.PNG)

If this issue is product-related based on setup, it should be directed to the product team [here](https://developercommunity.visualstudio.com/spaces/8/index.html) for further troubleshooting.

@TerryGLee

**Comment by msebolt** [comment]
Closing this issue now.
