### ISSUE TITLE
Doesn't work ... # 77

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/visualstudio-docs#4707]
@shendayan commented on [Sat Jan 25 2020](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/77)

I try to drag a table onto a form from the Data Sources window, but nothing happens. I can neither create a DataGridView nor individual controls if I have previously set the table up for details. I don't know what it could be, but I'm not too stupid to drag and drop.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2de1af78-290b-4177-65ed-d8fc91d38f64
* Version Independent ID: 3d0ac0a3-8ef2-645b-0528-2176852b80c4
* Content: [Binden von Windows Forms-Steuerelementen an Daten - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/data-tools/bind-windows-forms-controls-to-data-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/data-tools/bind-windows-forms-controls-to-data-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/data-tools/bind-windows-forms-controls-to-data-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

---

@srvbpigh commented on [Sat Jan 25 2020](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/77#issuecomment-578431891)

Hello, @shendayan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team, could you please check the above issue from user?

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by shendayan** [comment]
Hi Team,
at least I've identified the problem. It was because I had Visual Studio displayed on an external monitor. If I have it displayed on the monitor of the laptop, it works without problems. The external monitor has a solution of 1920x1080 and the laptop monitor 3000x2000. Maybe this helps you solving the issue. Discussed it on Stackoverflow too: [https://stackoverflow.com/questions/59911883/cant-insert-a-table-into-a-windows-forms-application-in-visual-studio-2019-via](url)

**Comment by ghogen** [comment]
We'll close this issue, but good to be aware of this, thanks.
