### ISSUE TITLE
Warning received calling member function on managed pointer

### ISSUE THREAD

**Issue by caspringer** [MicrosoftDocs/visualstudio-docs#4712]
The following example program will produce this warning:

```
#include <iostream>
#include <memory>

class MyClass
{
public:
	void displayValue() { std::cout << "The value"; }
};

int main()
{
	auto instance{ std::make_unique<MyClass>() };
	instance->displayValue();

	return 0;
}
```
The warning is given in the call to `instance->displayValue()`.

The text of the warning is the following:
> main.cpp(13): warning C26486: Don't pass a pointer that may be invalid to a function. Parameter 0 '@instance' in call to 'MyClass::displayValue' may be invalid (lifetime.3).

Why am I receiving this warning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2b55e4b-0473-1a82-2fce-6a099cb7e3e2
* Version Independent ID: 18a66256-6dfc-bc14-7d04-022487a596be
* Content: [C26486 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26486?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26486)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/code-quality/C26486.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26486.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @kylereedmsft
* Microsoft Alias: **kylereed**

**Comment by msebolt** [comment]
@caspringer Thank you for the question.

Unfortunately support options in this forum are limited to article examples only.

Please refer to a specific example or contact the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=8) if this issue is product-related.

For additional support options, see:

- [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html)
- [Visual Studio on Stack Overflow](https://stackoverflow.com/questions/tagged/visual-studio)

@kylereedmsft

**Comment by msebolt** [comment]
Closing this issue now.
