### ISSUE TITLE
Explicitly defined pkgdef

### ISSUE THREAD

**Issue by eogas** [MicrosoftDocs/visualstudio-docs#4713]
It might be worth mentioning that if your project uses an explicitly defined pkgdef file (not one generated during the build), that there are some additional entries that need to be added for a new ToolWindow to be picked up. I just killed the better part of a day struggling to add a ToolWindow to my project before I figured this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554db2bb-c0c2-d694-be77-44cb0fd311f8
* Version Independent ID: e7a691ea-7540-f6c4-46e4-66abdbd07c37
* Content: [Adding a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window?view=vs-2019)
* Content Source: [docs/extensibility/adding-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-tool-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by eogas** [comment]
Maybe it would make the most sense to mention it on [Register a tool window](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/registering-a-tool-window.md) and cross link instead.

**Comment by msebolt** [comment]
@eogas  Thank you for the feedback.

Assigning this to the author for further review.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
