### ISSUE TITLE
Missing SelectionPatternAvailable, TogglePatternAvailable, and DynamicAutomationName

### ISSUE THREAD

**Issue by javierdlg** [MicrosoftDocs/visualstudio-docs#4721]
These were added in 16.4/16.5 and should be added to this list. Here's their description:
TogglePatternAvailable: exposes the toggle pattern to screen readers and reads on/off when focused. Example: test explorer test filter buttons 
SelectionPatternAvailable: exposes the selection patter to screen readers and reads when the command is selected. Example: choosing the startup project from the toolbar
DynamicAutomationName: Enables querying for an automation name for when you want screen readers to read a different text from the text displayed on the button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efa0d04-5773-b7f3-b0cf-23d84cb423bb
* Version Independent ID: 10dae449-a2d5-ebc1-5866-e4ce96d4cea4
* Content: [Command Flag Element - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/command-flag-element?view=vs-2019#feedback)
* Content Source: [docs/extensibility/command-flag-element.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/command-flag-element.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
