### ISSUE TITLE
Issues with restoring nuget packages in vs 2019

### ISSUE THREAD

**Issue by ObinnaChinke** [MicrosoftDocs/visualstudio-docs#4725]
Hi,
I installed vs 2019 community edition on my pc. When ever i create an aspnet core 3.0 or 3.1 web application with individual authentication, when the project loads the package restore does not work. Secondly, i also have this error: "error occurred while restoring nuget packages: an error occurred while retrieving package metadata for 'system.reflection.primitives.4.3.0' from source 'c:\program Files\dotnet\sdk\nugetfallbackfolder'.
I have uninstalled and reinstalled the vs 2019 but same error occurs and packages are not restored.
I have vs 2013 installed on my machine so i'm wondering if this is the reason this problem is occurring because i installed vs 2019 in two other pcs that visual studio has not been previously installed and it worked fine.
If I use the dotnet cli to create the asp.net core 3.1 app with individual authentication, everything works perfectly. So I don't know why this is happening when i create the app with my vs 2019.
Please help!
Thanks

**Comment by WilliamAntonRohm** [comment]
@ObinnaChinke -- Obinna, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
