### ISSUE TITLE
Very Spare Information - Need More Details macro preprocessor definitions

### ISSUE THREAD

**Issue by buzz3791** [MicrosoftDocs/visualstudio-docs#4749]
I've added the third party TCL visual studio project https://github.com/tcltk/tcl/blob/master/win/tcl.dsp to my solution (I've migrated their VC6 dsp to vcxproj format).  This third party is using a Configuration Type Makefile.  TCL's nmake Makefile uses options to determine the macro preprocessor defines.  In particular, I've set STATS=memdbg which results in the nmake Makefile #define TCL_MEM_DEBUG.  When setting a breakpoint and breaking into TCL, I noticed that IntelliSense has a lot of grayed-out code because the code is nested in a #ifdef TCL_MEM_DEBUG.  How do I get IntelliSense to understand that the nmake Makefile compiled the code with TCL_MEM_DEBUG defined?  Where is this explained in more depth ideally with some examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21849b01-28b7-0a1e-151c-2d4f6ad24226
* Version Independent ID: eba95b03-5da5-e641-4812-6d92bc78a0d5
* Content: [NMake Properties (Android C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/nmake-android-prop-page?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCNMakeTool.IncludeSearchPath)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/cross-platform/nmake-android-prop-page.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/nmake-android-prop-page.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by WilliamAntonRohm** [comment]
@buzz3791 -- Brian, thanks for your question.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@corob-msft -- Colin, please look into this potential documentation issue.

**Comment by corob-msft** [comment]
@buzz3791 

It's probable you got to this NMake Properties (Android C++) page accidentally, since it doesn't sound like you were making an Android project. We've fixed one of the problems with our F1 help links, and it should send you to the correct page now: [/D (Preprocessor Definitions)](https://docs.microsoft.com/en-us/cpp/build/reference/d-preprocessor-definitions?view=vs-2019).

More information about setting the right preprocessor macros for IntelliSense in Makefile projects can be found in [How to: Enable IntelliSense for Makefile Projects](https://docs.microsoft.com/en-us/cpp/build/reference/creating-a-makefile-project?view=vs-2019#how-to-enable-intellisense-for-makefile-projects). The essence is, enter values in the **Preprocessor Definitions** property to match your project configuration. That is, if a certain macro is defined for Debug builds, then add it to the property for your project's debug configuration. Separate multiple macros with semicolons.
