### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by ZeroComfort** [MicrosoftDocs/visualstudio-docs#475]
This tutorial fails to compile after updating the <ListBox> control, which is right before replacing the custom constructor for the Report Page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc46effb-7f50-917a-5a68-fc1654d7cfb5
* Version Independent ID: 17a9b615-4ff9-bde5-9600-84000ffaf2f0
* [Content](https://docs.microsoft.com/en-us/visualstudio/designers/walkthrough-my-first-wpf-desktop-application2)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/designers/walkthrough-my-first-wpf-desktop-application2.md)
* Service: unspecified

**Comment by gewarren** [comment]
@ZeroComfort Thanks, I'll see if the directions need to be updated.

**Comment by ChrisWFowler** [comment]
<disclaimer>This is the first WPF project I tried so my solution may not be best practices.</disclaimer>

The Datagrid threw the error "The tag 'DataGrid' does not exist in XML namespace".
I had to get the WPFtoolkit with NuGet:
(Install-Package WPFToolkit -Version 3.5.50211.1).
I then added the schema to ExpenseItHome.xaml and App.xaml since they both reference the DataGrid:
(xmlns:wpfTool="http://schemas.microsoft.com/wpf/2008/toolkit")
I then had to add the prefix to all Datagrid references:  <wpfTool:DataGrid...

**Comment by aM3z** [comment]
Add Grid.Resources to the Grid such that the components, like the ListBox, are below it.  Otherwise, when you try to Build, you'll see an error that looks something like this:

System.Windows.Markup.XamlParseException: ''Provide value on 'System.Windows.StaticResourceExtension' threw an exception.' Line number '35' and line position '55'.'

Inner Exception:
Exception: Cannot find resource named 'nameItemTemplate'. Resource names are case sensitive.

**Comment by gewarren** [comment]
@ZeroComfort and @aM3z thanks again for the feedback. There is [another topic ](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)that builds the same app as in this topic.

**Comment by gewarren** [comment]
The original walkthrough topic has been deleted. The "Get started with WPF" topic [now links to](https://docs.microsoft.com/en-us/visualstudio/designers/getting-started-with-wpf#where-should-i-start) the same walkthrough over in the .NET docs, where the code has been verified to compile. Thanks again for alerting us to this problem. Closing this issue.
