### ISSUE TITLE
Uninstalling Visual Studio removes dotnet.exe from PATH

### ISSUE THREAD

**Issue by mikevanoo** [MicrosoftDocs/visualstudio-docs#4757]
Related to https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2019

Scenario:

1. Install VS2017
2. Install VS2019
3. Uninstall VS2017
4. Open CMD prompt
5. Type "dotnet.exe". The program is not found.

Not sure what else a VS uninstall breaks. For safety I repaired the VS2019 install and all seems good.

**Comment by WilliamAntonRohm** [comment]
@mikevanoo, thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation.  Please consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
