### ISSUE TITLE
Runtime error - TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtensionWithDebugInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by cesaralc** [MicrosoftDocs/visualstudio-docs#4763]
I am using Microsoft.EntityFrameworkCore.SqlServer and Microsoft.EntityFrameworkCore, however, I am getting this as a runtime error.
Closed issue 3698 says this was fixed with version 6 preview of EntityFrameworkCore.SqlServer. However, the issue still seems to exists with 3.1.1. Do I need another package to resolve this error? https://github.com/MicrosoftDocs/visualstudio-docs/issues/3698

Thanks for helping!

**Comment by WilliamAntonRohm** [comment]
@cesaralc -- thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation.  Please consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

Also, you may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
