### ISSUE TITLE
Mismatch to https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.writelinestofile?view=netframework-4.8

### ISSUE THREAD

**Issue by RobertAcksel** [MicrosoftDocs/visualstudio-docs#4766]
Im currently confused by the API missmarch to 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.writelinestofile?view=netframework-4.8 
WriteOnlyWhenDifferent is missing and in my solution the WriteOnlyWhenDifferent does not work since it seems that it is not implemented or present. but most Core SDKs like Microsoft.NET.Sdk.Razor are making use of it and no doubt it works.
Not sure what is going wrong in my case since i am also using Sdk="Microsoft.NET.Sdk".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee06fdb3-143d-fa36-54ee-5f9af813615e
* Version Independent ID: 5739dfe6-6a88-1487-4f29-1b91502ec7ad
* Content: [WriteLinesToFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2019)
* Content Source: [docs/msbuild/writelinestofile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/writelinestofile-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@RobertAcksel The MSBuild API reference was very outdated - it hadn't been updated since MSBuild was separated from the .NET Framework several years ago.  We've now published the MSBuild reference for MSBuild 15 and 16 (.NET Framework and .NET Core versions).  The APIs are available in the .NET API Browser, and we're also updating the MSBuild API article (https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-api) to add a table of links to all the MSBuild namespaces. That should be published by 6/25/2020.

**Comment by ghogen** [comment]
The updated version of the topic you referred to is here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.writelinestofile?view=msbuild-16
WriteOnlyWhenDifferent is there and should work.
