### ISSUE TITLE
Is there a 64bit version of vsixsigntool available?

### ISSUE THREAD

**Issue by kapoorankush** [MicrosoftDocs/visualstudio-docs#4786]
Certain HSMs (such as AWS CloudHSM) support 64bit operations only. Is there a 64bit version of the vsixsigntool available?

**Comment by WilliamAntonRohm** [comment]
@kapoorankush -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
