### ISSUE TITLE
Does it make a difference, if my colleagues use a different version?

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/visualstudio-docs#4794]
I use VS 2019 Enterprise Edition. My colleagues use VS 2017 Enterprise, or even older. If I install these FxCop analyzers into my VS 2019, will that cause a change to any of the projects I work on, with my colleagues?

**Comment by WilliamAntonRohm** [comment]
@Rod-in-NM -- Rod, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
