### ISSUE TITLE
how is this actually useful?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4802]
Why not ask the consuming user for what to use for $color1$, instead of making them edit the template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8d3eee-0d9c-09a0-ba91-c19e9f1d29ce
* Version Independent ID: d70dfb5a-f208-b2cc-904b-b1c554037dae
* Content: [CustomParameter Element (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/customparameter-element-visual-studio-templates?view=vs-2019)
* Content Source: [docs/extensibility/customparameter-element-visual-studio-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/customparameter-element-visual-studio-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@StingyJack It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by StingyJack** [comment]
Yeah, no. I want an IRL (not contrived) working example of a project template that uses custom params in addition to the built in ones. This feature looks like its been abandoned or having some regression because the docs dont jibe with what I remember from a few years ago.  Its fine if nothings been added to the feature, but the docs reflect a regression with nonsensical descriptions of usage like the one I cited.
