### ISSUE TITLE
Are any string operations possible for this?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4803]
Typically a project name is going to be something like `Fabrikam.Sales.AccountsManagement.CustomRules` or something like that pattern. If using this project name in the template I'd only want to pick out `CustomRules` and use that for a few file name prefixes, and still use the full project name for namespaces, etc. Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@StingyJack Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
