### ISSUE TITLE
VS 2019 information on Network Profiler

### ISSUE THREAD

**Issue by vborovikov** [MicrosoftDocs/visualstudio-docs#4805]
Is Network Profiler for UWP available in VS 2019? If so how to install it?

The page doesn't have information specific to VS 2019 and the tool is missing in VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a70e435-8c99-5920-d2a2-5c6e1f85772d
* Version Independent ID: e1aa7f86-2d39-6109-e4f7-7bb0d441a9ca
* Content: [Analyze network usage in UWP apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/network-usage?view=vs-2017&viewFallbackFrom=vs-2019#feedback)
* Content Source: [docs/profiling/network-usage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/network-usage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@vborovikov -- Vadislav, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by michael-hawker** [comment]
@WilliamAntonRohm this is a question about the docs being out-of-date with the latest version of the product.

There is no 'network' option listed in the tooling in VS2019 for a UWP app. If this feature was removed, this doc should specify so. If this feature was changed to something like the 'Event Viewer' option, then it should be updated to match the current experience:

![image](https://user-images.githubusercontent.com/24302614/91611197-9756bc00-e92f-11ea-81bb-345bacfe3aec.png)

However, even performing a trace with the Event Viewer option, I didn't see any of my HTTP events I would have expected.

**Comment by WilliamAntonRohm** [comment]
@michael-hawker -- Michael, thank you for clarifying.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
The version selector indicates it's VS 2017 only. There's a banner comment when you switch to the VS 2019 view. This tool isn't available in VS 2019.
![image](https://user-images.githubusercontent.com/11948536/98052346-dc451600-1dea-11eb-8bb1-38140264e463.png)

**Comment by michael-hawker** [comment]
@Mikejo5000 the banner saying the page not existing isn't clear enough saying the feature was removed for some reason and how developers migrating to VS 2019 should perform the same scenario with the missing feature.

It'd be better if the same document existed for VS 2019 still and clearly explained that the feature was removed, why, and how to migrate to some other solution for the same task.
