### ISSUE TITLE
VSTU does not maintain solution items

### ISSUE THREAD

**Issue by aybe** [MicrosoftDocs/visualstudio-docs#4812]
It would be great if those things were preserved as projects are, e.g. editorconfig put by VS etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ad57fa-5862-e7c9-fb0c-99298e461bfd
* Version Independent ID: 2e6eb5e8-de91-6515-76f4-69922152db43
* Content: [Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-tools-for-unity?view=vs-2019)
* Content Source: [docs/cross-platform/visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/visual-studio-tools-for-unity.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@aybe -- It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by aybe** [comment]
alright, thank you.
