### ISSUE TITLE
Is there any more documentation available for this?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4824]
There's something I think that should be available but I don't see any content regarding it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019#feedback)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
Please clarify "something" :^)

**Comment by StingyJack** [comment]
Something like string manipulations. 

Or other built in variables. The last time I made a project template was about 10 years ago, and I could swear there was more functionality than what is described in the current docs (and more documentation was available too).  I can't even find the instructions for making templates work in VS.

**Comment by TerryGLee** [comment]
@StingyJack Thanks for the suggestion; we'll research this and update the docs as necessary (and report back when we have done so).

**Comment by StingyJack** [comment]
@TerryGLee  @WilliamAntonRohm  - I have learned that if I ask specifically for something, I will get effectively autoclosed as a product support question without further discussion. 

However, if I am vague (or mention crummy muppet sci-fi), then at least I can get some kind of assistance with docs. 

Is this really what you want to be teaching me? 
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4803

**Comment by TerryGLee** [comment]
@StingyJack There's a reason for the pattern you've described. And it's this: The GitHub Issues venue is meant specifically for [documentation feedback](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019#improve-the-documentation). 

Granted, sometimes there is a fine line between what is considered documentation feedback and product feedback, because the product issues reported here can at times provide us with information that we can use to improve our documentation. 

However, when a solution must be provided for a product issue, we re-route it to the proper support venue (typically, the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool, where you can include diagnostic information in your feedback that helps Visual Studio engineering teams diagnose and fix issues much more effectively). 

Conversely, if a question is asked about whether something is possible in the product, as was the case in [#4803](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4803), we refer you to other support mechanisms where you might find further help. 

For more information about all our feedback avenues, please see our [Visual Studio feedback options](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) page.

Thanks,
~ Terry

**Comment by StingyJack** [comment]
But I asked for the very same thing here, just with a different lead in. And probably would have gotten more traction, had I not called it. I'm not one to work people over or take an advantage via deception.

I would like the docs team to relax the trigger finger on "product issue" closures, the eagerness to keep a tidy issue list doesn't always consider that someone is logging the issue to get _help with a Microsoft product_. Documentation is another important facet of the support structure, so I don't see that there should be any dividing line for the customer to navigate when they need help with one of the programs they have paid for. There isn't a decision point required for my customers, at any place I've worked, ever. (And to be clear, I'm not the one who set those policies in place anywhere. Not making your customers figure out who to call for something at your company when they need help is just a well known customer service industry best practice)

Case in point - for users in the general population like me, the difference between product or docs is as clear as mud; Is it missing/not yet written docs or is it a bug? We can't really know. Sometimes the docs team doesn't know and has to go find out.

**Comment by TerryGLee** [comment]
@StingyJack, thank you for the info. Your feedback will help us continue to improve our triage process.

**Comment by EddieLotter** [comment]
> I could swear there was more functionality than what is described in the current docs (and more documentation was available too).

@StingyJack, you can access older docs on [archive.org](https://web.archive.org/web/20120211210541/http://msdn.microsoft.com/en-us/library/eehb4faa.aspx) and hopefully you can identify what you saw there that you're not seeing here.

**Comment by StingyJack** [comment]
@github-actions bot you are a cancer on the community. 

However, I am closing this because the new dotnet new style templates are much friendlier to work with overall and has examples and instructions on how to customize.
