### ISSUE TITLE
/edit and /command incompatible if VS instance already open

### ISSUE THREAD

**Issue by cniggeler** [MicrosoftDocs/visualstudio-docs#4837]
If I run  devenv /edit /command "Edit.Goto 5" foo.c  and there is no VS instance open, the operation is as expected: foo.c opens in the VS editor at line 5. If I then run  devenv /edit /command "Edit.Goto 6" bar.c  bar.c will open but it will NOT move to line 6! So the documentation in here, somewhere, needs to indicate this non-operation. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05945d0a-396b-0697-ab78-81d617b365c9
* Version Independent ID: 860cb1bf-47aa-b35d-4d30-be9f62796d40
* Content: [Devenv command line switches - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/devenv-command-line-switches.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/devenv-command-line-switches.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cniggeler Thanks for letting us know; we'll investigate and update the docs as necessary (and report back when we have done so).

**Comment by cniggeler** [comment]
Thanks! Of course, I think it would be better for the software to conform to the docs, but some of the online stuff seems to indicate usoft is not that interested; please see https://stackoverflow.com/a/45278849/4096837

Appears the feedback page referred to no longer exists; do you have suggestions for usoft devops to perhaps take a look at this issue again?

**Comment by cniggeler** [comment]
Uh, pls leave open until resolved as described by Terry. Epitome of lazy to have a bot close an active issue.

**Comment by TerryGLee** [comment]
@cniggeler Apologies for the delay in following up with you. After some research, this looks to be an issue with the product instead of with the documentation (where our charter is to describe what's supposed to work instead of what doesn't).

Please consider reporting this as a product problem so that it can get fixed; there are two ways you can do so:

- **Create a new product problem report**; see the [Report a problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) page for details
- **Upvote a previously submitted product problem report**; see the "[devenv command-line switches](https://developercommunity.visualstudio.com/search?space=8&q=devenv+command-line+switches)" search string on the Developer Community website (where product problem reports are listed and triaged)

We hope this helps, and we thank you for taking the time to write up this GitHub Issue, where it'll remain on file for others to view (and to also see the proposed solution, too).
