### ISSUE TITLE
Start page shows old items sometimes

### ISSUE THREAD

**Issue by ranjan-ranjan** [MicrosoftDocs/visualstudio-docs#4860]
The page goes back to the previous stage - means that there are new items dated 26 Feb, but we can see those items sometimes, and sometimes we can see items dated 25 Feb.

The new items dated 26 Feb will come again and then they will disappear again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019#feedback)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@ranjan-ranjan -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

fyi @ornellaalt

**Comment by ranjan-ranjan** [comment]
Thanks. Today articles dated 5 Feb are showing up.
