### ISSUE TITLE
upgrade msdn developer tenant from "office365 e3 developer" to "microsoft 365 e5 developer" already possible?

### ISSUE THREAD

**Issue by bbregman** [MicrosoftDocs/visualstudio-docs#4876]
I have an "MCT Developer Software & Services" subscription, with an already activated "Office 365 E3 Developer" license associated to this tenant, as per this article I understand that I can upgrade this license to a "Microsoft 365 E5 Developer" in the near future. @evanwindom mentioned this to be speced and done by end of Feb 2020 in one of the closed feedback beneath, can someone give an update on this feature? Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [The Microsoft 365 developer subscription benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#feedback)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@bbregman -- It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
