### ISSUE TITLE
CodedUI test logs in text format.

### ISSUE THREAD

**Issue by Afsah-k** [MicrosoftDocs/visualstudio-docs#4881]
currently i am working in coded UI for recording my testcases. For that i am generating log file in HTML format, containing all the steps i have performed in course of performing my testing like click button 2,click add button, click 3 button etc and my HTML file is generating correctly.What i need is that my coded UI log file must be created in text format in notepad and must be saved in same notepad file. 
https://github.com/Afsah-k/CodedUI-testing is the link of my code with screenshot of codedUI test log in html.

If anyone can guide, it would be great help for me.

Thanks in advance.

**Comment by Afsah-k** [comment]
![Screenshot (354)](https://user-images.githubusercontent.com/61530930/75853067-2070b880-5e0f-11ea-8afc-5350fdda9e9e.png)

**Comment by Mikejo5000** [comment]
@PBoraMSFT @jayaranigarg Do you have any suggestions for how to generate the log file in text format?

**Comment by Mikejo5000** [comment]
Likely a product issue as I'm not sure that text output is supported.

**Comment by WilliamAntonRohm** [comment]
@Afsah-k -- it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

@Mikejo5000 -- thank you for your assistance.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Afsah-k** [comment]
> 
> 
> Likely a product issue as I'm not sure that text output is supported.

In all of our testing projects where we perform testing on data; all of that data is in text format. then how is it possible data visual studio is not giving text file of codedUI test logs?

**Comment by Mikejo5000** [comment]
I will ask, but I suspect there would need to be a product change here.

**Comment by icnocop** [comment]
Maybe one of these posts will help:
[Coded UI Testing Extensibility Points. Writing to Text Files, Visual Studio & the Event Log](https://social.technet.microsoft.com/wiki/contents/articles/14046.coded-ui-testing-extensibility-points-writing-to-text-files-visual-studio-the-event-log.aspx)

This post in Microsoft's `Visual Studio Development` > `Visual Studio Unit Testing` forum [How to create the custom HTML report using CODEDUI?](https://social.msdn.microsoft.com/Forums/vstudio/en-US/9d41a992-064d-4e17-9969-6aae7e2a03bf/how-to-create-the-custom-html-report-using-codedui-?forum=vsunittest)

With those approaches, you have to create your own log file and write your own text to it.

Another approach is to convert the HTML log to plain text.

See Judah Gabriel Himango's answer on the stack overflow post, [How do you convert Html to plain text?](https://stackoverflow.com/a/1121515/90287).

**Comment by Mikejo5000** [comment]
Thanks, @icnocop for the links. I think the solution here will need to be a custom solution or hook into extensibility.
