### ISSUE TITLE
What is the use of Task List Shortcuts

### ISSUE THREAD

**Issue by RaoulSteffen** [MicrosoftDocs/visualstudio-docs#4885]
Double clicking an item in the Task List makes the cusor jump to the task's Token. It is unclear what additional fuctionality a Task List Shortcut provides.

**Comment by WilliamAntonRohm** [comment]
@RaoulSteffen -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by RaoulSteffen** [comment]
This is about [Use the Task List](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2017) for VS 2017. In section [Shortcuts](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2017#shortcuts), it says "Double-click the shortcut in Task List to go to the corresponding location in the code."
The issue is, that double clicking an item in the Task List jumps focus to the location in the code anyways, no matter if a Shortcut has been set or not.

**Comment by WilliamAntonRohm** [comment]
@RaoulSteffen -- It looks like you have product feedback rather than documentation feedback.  To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
