### ISSUE TITLE
NuGet instructions are missing

### ISSUE THREAD

**Issue by L4ZZA** [MicrosoftDocs/visualstudio-docs#4890]
There are no instruction on how to use boost using NuGet packages on vs2019.

Example:
- create a console project
- right click on the project &gt; Manage NuGet packages..
- search online for boost test vc142
- install package

the above steps are the ones I was using, but without success because the the tests are not discovered so you guys need to figure out what are the working instructions for this scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* Content: [How to use Boost.Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019&source=docs#feedback)
* Content Source: [docs/test/how-to-use-boost-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-boost-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@L4ZZA 
I'm sorry you're not finding the content you feel you need. We recommend vcpkg as the superior solution for C++ package management and project integration. We've intentionally featured it here instead of showing another package installation option. I found it fairly easy to add Boost.Test to a solution using vcpkg, and it worked immediately when I used it as a separate project. When it was merged into my existing project, I had to create a separate test configuration for it, and exclude at least one of its files from my debug and release builds, before it would work. It's possible a similar issue exists for the NuGet integration. At any rate, we left out NuGet instructions on purpose here. Unless we get feedback like yours from rather more customers, we plan to leave it that way. However, there'd be no chance of a change if you didn't speak up, so don't be discouraged from telling us when you see something that could improve. Thanks for the feedback.

**Comment by L4ZZA** [comment]
@corob-msft using vcpkg I get linker errors and there is no clear instruction on how to fix it on this page.
Using NuGet I only had to install the package to get it all building and linking correctly. 

The main issue I'm facing is that VS test explorer does not discover the tests. Even after re-installing boost 
On top of that there is:
- no instruction online on how to setup the .runsetting file for Boost
- no option "Add New Item dialog, expand Installed > Visual C++ > Test. Select Boost.Test, then choose Add to add Test.cpp"
- no option to add a boost.test project to the solution

**Comment by corob-msft** [comment]
@L4ZZA 
I'm curious about your linker errors with vcpkg. That's unexpected. The C++[Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site can help with those issues.

I've never needed to edit a .runsettings file. Many projects should work okay with the default settings. There's [some general documentation available](https://docs.microsoft.com/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019), and a [couple](https://github.com/microsoft/vs-boost-unit-test-adapter/blob/dev15/BoostTestAdapterNunit/Resources/Settings/sample.runsettings) of [samples](https://github.com/microsoft/vs-boost-unit-test-adapter/blob/dev15/BoostTestAdapterNunit/Resources/Settings/sample.2.runsettings) in the test adapter repo. 

If you don't see the Boost.Test entry when you open the **Add New Item** dialog and navigate to **Installed** > **Visual C++** > **Test**, then the Boost.Test integration is broken. One possibility is that the project configurations are incompatible. For example, if your project targets x64, you have to use vcpkg to build, install, and integrate an x64 version of Boost.Test.
