### ISSUE TITLE
Subscription assignment notification

### ISSUE THREAD

**Issue by bucmic** [MicrosoftDocs/visualstudio-docs#4918]
Will the e-mail notification automatically be sent to the notification e-mail address if a user has been added to an AAD group that is assigned to a VS subscription? I don't see the notification e-mail addresses when I open the subscriptions in a group. When I add a user manually I can see it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac6f4b8-da9d-5b7b-0c18-b6ed1f85433a
* Version Independent ID: 1ac1ddeb-b1a4-e8d3-9abf-0e629796c5ef
* Content: [Assign licenses to groups of users for Visual Studio subscriptions](https://docs.microsoft.com/en-ca/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions)
* Content Source: [subscriptions/assign-license-bulk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-license-bulk.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@bucmic -- Michael, it looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 
- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by evanwindom** [comment]
@bucmic -Thanks for reaching out.  Your understanding is correct.  Notification emails are not supported when subscriptions are assigned via the Azure AD group assignment feature.  I have submitted a PR to add that information to the article.  Thanks for bringing that to our attention.

**Comment by bucmic** [comment]
> @bucmic -Thanks for reaching out. Your understanding is correct. Notification emails are not supported when subscriptions are assigned via the Azure AD group assignment feature. I have submitted a PR to add that information to the article. Thanks for bringing that to our attention.

Thanks. Btw, I didn't see the note "Separate email addresses for notifications are not supported for subscriptions added using Azure AD groups.". That is a bad thing since the e-mail addresses of our users mailboxes differ from the UPNs.

**Comment by evanwindom** [comment]
@bucmic  You didn’t see the note because I added it yesterday.  You can always add users individually or using the “bulk edit” feature if having the notification email is important.

**Comment by bucmic** [comment]
> @bucmic You didn’t see the note because I added it yesterday. You can always add users individually or using the “bulk edit” feature if having the notification email is important.

Ha :-). Support pointed out to this new note. Great, but when using "bulk edit" I have to know all different notification e-mail addresses with different domains etc. Hard to handle. We just ignore the notifications from now.
