### ISSUE TITLE
Mono mismatch

### ISSUE THREAD

**Issue by pjsoftcoUser** [MicrosoftDocs/visualstudio-docs#4961]
Why don't you guys release the Mac and Windows updates at the same time! this causes a lot of problems for us! when does the new mac version release? I cannot use the preview version on macincloud machines!

**Comment by WilliamAntonRohm** [comment]
@pjsoftcoUser -- It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
