### ISSUE TITLE
Missing options in the Code Analysis tab in the project properties

### ISSUE THREAD

**Issue by binte** [MicrosoftDocs/visualstudio-docs#4975]
I am trying to configure FxCop as per the [link](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-configure-code-analysis-for-a-managed-code-project?view=vs-2019).

But I don't have the rule set section within the Code Analysis tab in the project properties. Moreover, it does not allow me to choose neither the Configuration nor the Platform. This is how this tab looks like in my Visual studio:

<img width="362" alt="fxcop" src="https://user-images.githubusercontent.com/5520287/77445732-5b9a5200-6de5-11ea-9e4d-9fd65dd79652.png">

Any idea how I can fix this?

**Comment by Mikejo5000** [comment]
@binte You will only see the rule set section for .NET Framework project (not .NET Core or .NET Standard). Also, your screenshot shows that you have the new analyzers installed (Microsoft.CodeAnalysis.FxCopAnalyzers). The topic referenced here only applies to legacy anayzers (static FxCop analysis rather than the new source code analysis).

**Comment by binte** [comment]
@Mikejo5000 thanks for putting me in the right direction. It is installed, but it is not checking anything.  

Is there a topic for FxCop Analyzers on .NET Core then?

**Comment by Mikejo5000** [comment]
Yes, there's quite a few topics. You should see results of the analysis in the editor (squiggles) and the Error List window.
https://review.docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019&branch=pr-en-us-6296

**Comment by binte** [comment]
yes, but I have none of that, even if I break some of the listed rules. 

I can't open that link due to permissions

**Comment by Mikejo5000** [comment]
Sorry, here's the public link:
https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019

**Comment by Mikejo5000** [comment]
It's recommended to install the NuGet package instead of the vsix:
https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019
If it is still not working, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by binte** [comment]
I will report a problem then, I still didn't manage to make it work. Thanks for your help @Mikejo5000

**Comment by Mikejo5000** [comment]
Closing as a support request.
