### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by comarius** [MicrosoftDocs/visualstudio-docs#501]
After one run, I have log log off and on on remote machine... Did anyone tested this ?

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP2100: Cannot copy the file "C:\Users\<my-project>\bin\Debug\project.exe" to the target machine "MACHINE". [0x80070020] The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)	my-project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/remote-debugging.md)
* Service: unspecified

**Comment by gewarren** [comment]
@Mikejo5000 do you know if the log off and on again is required?

**Comment by Mikejo5000** [comment]
@comarius Log off and on is not required normally, but is due to some process lock on the file, possibly because of something like multiple instances of VS running, though it may be something else. Here is a StackOverflow post on this error: https://stackoverflow.com/questions/1121386/unable-to-copy-file-reference-dll-to-bin-reference-dll-the-process-cannot-acces
