### ISSUE TITLE
Wouldn't it be wonderful if Visual Studio 2019 16.5.1 could actually create a runsettings file rather than a testsettings file...

### ISSUE THREAD

**Issue by ThomasRapidis** [MicrosoftDocs/visualstudio-docs#5022]
I guess that would be too easy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7145ed3-6107-b870-4d6b-2d4419235f07
* Version Independent ID: f6bd7e86-8a5a-d00c-c1c1-7ed5fbd5ca83
* Content: [Run a unit test as a 64-bit process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-a-unit-test-as-a-64-bit-process?view=vs-2019)
* Content Source: [docs/test/run-a-unit-test-as-a-64-bit-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-a-unit-test-as-a-64-bit-process.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@ThomasRapidis -- Thomas, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
