### ISSUE TITLE
Multithreaded unit tests with Unit Testing Framework for C++

### ISSUE THREAD

**Issue by eranzim** [MicrosoftDocs/visualstudio-docs#5062]
Hi!

I hope this is the right place to post this...

I have some tests that must be multithreaded. My main thread is the TEST_METHOD, and it spawns a few new threads. Their thread functions also use Assert::'s, however if any such assertion fails, the whole process is terminated, I don't get proper output of what failed, and other tests don't continue running. This makes debugging very uncomfortable.
It would be really helpful if those thread functions could be wrapped by something that would connect to the test runner and notify it of the test's failure, with the proper message and line number to display, and allow other tests in the same class to run. Perhaps this already exists, just isn't documented (or I didn't find it)?

Thanks!

I think this is the GUID of the relevant page I came from:
"e0e84806-41ff-fa5e-1aa1-775beed16d78"

**Comment by WilliamAntonRohm** [comment]
@eranzim -- Eran, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

Also, if you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
