### ISSUE TITLE
Code Map not in Visual Studio 2019

### ISSUE THREAD

**Issue by gt488** [MicrosoftDocs/visualstudio-docs#5064]
The Code Map item is not in the Individual components section of Visual Studio Installer. Will this be added at some point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c6b3cd-fc32-1501-68a6-1da597bfd33b
* Version Independent ID: 499fd553-6e2e-aefe-aefd-2711c01e39e0
* Content: [Code maps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2019#feedback)
* Content Source: [docs/modeling/map-dependencies-across-your-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/map-dependencies-across-your-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@gt488 -- thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by PlaysafePP** [comment]
I agree with the OP, and those of other similar feedback. These tools are not available in he VS2022 installer either

**Comment by WilliamAntonRohm** [comment]
@PlaysafePP -- thank you for your follow-up.  Please add this issue here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
