### ISSUE TITLE
JSON-RPC connection with remote party was lost before the equest could complete

### ISSUE THREAD

**Issue by djmarcus1** [MicrosoftDocs/visualstudio-docs#5067]
Looks like there is another ou-of-proc process that is not in your list.

I get this stack trace on the err:

StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync(&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72292f7a-7616-4727-ccd3-cf44bb130477
* Version Independent ID: fe3cca82-dfd7-a85c-ab4f-014bc546d668
* Content: [A process has encountered an unrecoverable error - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error?view=vs-2019)
* Content Source: [docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by jmoralesv** [comment]
I also got the same issue when working with a .NET Core project where a migration of Entity Framework Core has a very large data to be seeded to a database. I think that causes one of the Visual Studio's out-of-proc processes to crash in the background, as it tries to compile the whole code base I guess.

**Comment by djmarcus1** [comment]
I get this error when my system is idle (or I'm in the editor editing code). I've not had it while running (debugging) code.

**Comment by t-fost** [comment]
I recently installed VS 2019 and it was working well for a week or two, and then suddenly I am constantly getting this specific message (JSON-RPC).  Often VS will freeze up and then automatically restart, making it practically unusable.

**Comment by mcmillab** [comment]
I get the same problem, repeatedly. Any solution?

**Comment by as-srandall** [comment]
I'm getting exactly the same issue when I'm editing razor pages in a Blazor server solution. Happens multiple times a day. Result is that it keeps trying to run task in the background that never finish and slow down VS. I'm running the latest VS update:

Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 2.0

StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by myialine** [comment]
I just got this issue while coding on Net Framework. It has been two days since I have updated Visual Studio:
Microsoft Visual Studio Enterprise 2019
Version 16.6.2

Microsoft .NET Framework
Version 4.8.03752

Error:

StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by ellwoods** [comment]
I get this issue repeatedly, it seems to be regardless of framework which for me is usually .net 4.7.1 or one of the .net core LTS versions

Microsoft Visual Studio Enterprise 2019
Version 16.6.2

It was certainly doing it in earlier versions of VS recently.

**Comment by Nikhilpp26** [comment]
I was facing same issue recently with VS2019. Followed below step solved problem for me.
1. In Account Settings page, under All Accounts section remove each added account. Sign out any personalized account as well.
2. Restart the VS.
3. Sign-in under All Accounts section.
4. Here select Use Another Account option even if your account if prelisted. Complete sign-in process.
5. You can sign-in to personalized account as well now.
5. Done. You can retry the action which was throwing you error earlier.

**Comment by ryanjmchale** [comment]
I'm having the same issues with the Version 16.7.0 Preview 4.0 and .Net Core 5.0 Preview 8.0.
This occurs whilst editing the code and break intellisense after the error is thrown, so I'm forced to restart.

[Activity Monitor Log_xml.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/4948383/Activity.Monitor.Log_xml.zip)

**Comment by irdublu** [comment]
Took Nikhilpp26's advice and it worked.  Thank you.
Been having all sorts of issues with VS Community 2019 version 16.8.0 preview 1.0

**Comment by twurm** [comment]
I've got the same issue.  It happens when I try to sign into VS.  I did try the steps mentioned by Nikhilpp26, that didn't seem to help the issue.  A screen shot of what VS is showing is below.  I'm running VS16.7.3.

![image](https://user-images.githubusercontent.com/23122687/92771463-e73e7580-f368-11ea-8209-2f339e8bed45.png)

**Comment by TerryGLee** [comment]
Thanks everyone for your posts. As an FYI, this product feedback also appears in the [**Developer Community**](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=+The+JSON-RPC+connection+with+the+remote+party+was+lost+before+the+request+could+complete), where it was triaged and redirected to another locale: https://github.com/dotnet/roslyn/issues/43855. From what's posted there, it looks like a fix is planned for an [upcoming release](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap?view=vs-2019). 

Meanwhile, we'll add a Note to the "_Visual Studio unrecoverable process error_" page that will help direct folks to the right place to report product feedback (i.e., via the **[Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio)** tool), going forward. The update should be published by noon tomorrow. So, we'll close this issue now, with our thanks for helping us improve the documentation.

**Comment by Aze1337** [comment]
I'm getting this error message and a few different when trying to use the built in machine learning models. Going to try @Nikhilpp26 's solution.

**Comment by reccesoft** [comment]
@as-srandall I have the same issue or similar when I try and edit Blazor Razor, the error that comes up is

Task failed: Activating language client: HtmleLanguageClient
Your task failed with the message: The JSON-RPC connection with the remote party was lost before the request could complete

This error makes it so that the intelisence is so bad, and I cant even use ctrl+k+d, it wont format. I tried  @Nikhilpp26 solution and it didn't work, i'm using Visual Studio 2022 v 17.0.0 (that I upgraded from the RC). So currently, to get good coding experience, I have had to set Visual Studio to use the legacy Razor Editor (Tools > Options > Text Editor > HTML > Advanced > Razor).

@as-srandall if you found a solution, please let me know, since there is something I am doing wrong, or my configurations might be wrong, or maybe @TerryGLee the fix might not be available yet.
Thanks
