### ISSUE TITLE
Add and remove property pages guid is not working in VS2019

### ISSUE THREAD

**Issue by jacquesbrits1** [MicrosoftDocs/visualstudio-docs#5068]
I was not able to Add a new property page to my project by following the below guide.

https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-and-removing-property-pages?view=vs-2019

Can anyone please provide samples or let me know if they can implement it?

Thank you

**Comment by WilliamAntonRohm** [comment]
@jacquesbrits1 -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
