### ISSUE TITLE
These examples are all wrong

### ISSUE THREAD

**Issue by jmarolf** [MicrosoftDocs/visualstudio-docs#5079]
1. `vs_installer.exe` is the name of the process not `vs_enterprise.exe` /  `vs_professional.exe` so none of these examples work at all right off the bat
2. `--wait` is not a valid option. It was removed at some point but the docs were never updated
3. `--update` and `update` are used interchangeably. only `--update` exists

This page should either be update or deleted as having completely wrong documentation is worse than having none

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#feedback)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @jmarolf, thanks for your feedback. I'll look into it and update the documentation.

**Comment by ornellaalt** [comment]
Hi @jmarolf, the problem you are running into is that you are trying to use the installer executable directly, instead of the bootstrapper. The examples in this doc only work if you use the bootstrapper executables, as the commands are different for the installer executable, like you mention. I.e. vs_enterprise.exe supports --wait, but vs_installer.exe does not. In the one example that contains both the --update and update commands, "--update" updates the Visual Studio Installer itself, while "update" updates the actual Visual Studio instance, as explained in the purple Note on the Docs page. I'll discuss with the product team if they want to document these steps for using the installer executable directly, but closing out this issue for now.
