### ISSUE TITLE
Build Action for XSD file not appear

### ISSUE THREAD

**Issue by buddhikac96** [MicrosoftDocs/visualstudio-docs#5083]
I am using Visual Studio 2019 community edition and I can't see build action option for **XSD** file.

![image](https://user-images.githubusercontent.com/28675970/78698290-bbcddf80-791f-11ea-8a6e-024ec2175c0d.png)
Do I need to enable that feature or what I have missed?

**Comment by WilliamAntonRohm** [comment]
@buddhikac96 -- Buddhika, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
