### ISSUE TITLE
ext_ prefix does not work with VS2019

### ISSUE THREAD

**Issue by Ben-P-Leda** [MicrosoftDocs/visualstudio-docs#5088]
I'm trying to create a boilerplate template for a series of web applications my team needs to create - they are structured in the 3-tier (data access/business logic/ui) style.

The solution template works apart from the references. For example, when I create a new solution with this template (call it "MyAPI"), I get my three projects: "MyAPI.Data", "MyAPI.Business" and "MyAPI.UI", which is great - but instead of MyAPI.Business having the expected reference to MyAPI.Data, I am seeing "$ext_projectsafename$.Data" in the references.

If I replace remove the "ext_" (ie: use "$projectsafename$"), then the substitution works as expected, and I end up with a reference to "MyAPI.Business.Data" - which is wrong, but it shows that $safeprojectname$ is being replaced with "MyAPI.Business", which is the expected behaviour. But the reference needs to be to "MyAPI.Data".

Can anyone advise on this? Thanks.

**Comment by WilliamAntonRohm** [comment]
@Ben-P-Leda -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
