### ISSUE TITLE
"Loading additional symbols" for fastlink pdbs

### ISSUE THREAD

**Issue by daviddetweiler** [MicrosoftDocs/visualstudio-docs#5097]
Is there a way to load symbols from .obj files in a fastlink build, or does a full pdb have to be generated to make these available? It's unclear what is meant by "requires loading additional symbols" here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5adf8f88-74dd-5871-3904-a70d16d9a156
* Version Independent ID: 0984de0b-c6cb-40c6-3ade-ff46eab347db
* Content: [CompilandDetails - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/debugger/debug-interface-access/compilanddetails?view=vs-2019)
* Content Source: [docs/debugger/debug-interface-access/compilanddetails.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-interface-access/compilanddetails.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@daviddetweiler -- David, thank you for your feedback. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@Mikejo5000 -- Mike, please look into this clarification.

**Comment by Mikejo5000** [comment]
Asking about this now.

**Comment by Mikejo5000** [comment]
@daviddetweiler  From the product team:

For fastlink PDB, msdia140.dll will locate the relevant OBJs or LIBs (for the case where OBJ comes from static LIB) and find debug records for CompilandDetails.

But msdia140.dll won’t accept a generic query on fastlink PDB.  For example, if client is asking for CompilandDetails info for all the OBJs/LIBs that contribute to the binary, msdia140.dll would refuse to do so, since doing that means we will have to look into all the input OBJs/LIBs, which would be a potentially problem on throughput.

However, on the other hand, if client asks CompilandDetails info on a particular module (OBJ), then msdia140.dll will go looking for it.

**Comment by daviddetweiler** [comment]
Thanks!
