### ISSUE TITLE
"Create Unit Tests" for VB projects

### ISSUE THREAD

**Issue by bigtfromaz** [MicrosoftDocs/visualstudio-docs#5101]
I am using VS 2019 Enterprise and only see this feature for C# but not for VB dotnetstandard projects.  We are modernizing a large number of old VB projects (no unit tests done back then) and the feature would be really useful.  Is this a bug or a docup reminding us that our VB apps are now second class citizens?  Last time I checked VB is managed code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a859ec6-03a2-2d8c-bcfe-c9499db55286
* Version Independent ID: 4ac4f045-660e-e159-edeb-315cf491568c
* Content: [Create unit test method stubs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/create-unit-tests-menu?view=vs-2019#feedback)
* Content Source: [docs/test/create-unit-tests-menu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/create-unit-tests-menu.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@bigtfromaz -- Tom, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by bigtfromaz** [comment]
@WilliamAntonRohm I have to disagree.  You can only make a determination on this issue if you know the answer to the following question, "Is this feature supported on Visual Basic projects?".  If the answer is yes, then I need to file a bug report.  If the answer is no, then the documentation needs to be updated to indicate that it's a C# only feature.

**Comment by Mikejo5000** [comment]
According to the linked blog post, it is C# and MSTest only:
https://devblogs.microsoft.com/devops/creating-unit-test-method-stubs-with-create-unit-tests/
That is from 2015 though, so could be out of date. @kendrahavens to comment

**Comment by kendrahavens** [comment]
Correct, this is an open feature request since Visual Studio 2017. You can vote on it here: https://github.com/Microsoft/testfx/issues/376

**Comment by Mikejo5000** [comment]
Closing as a feature request.

**Comment by bigtfromaz** [comment]
You should add a note to the document in question indicating that the feature as C# only.  If it's ever implemented for VB then update the doc.  The oversite sent me down the garden path looking for a feature that doesn't exist.

**Comment by Mikejo5000** [comment]
We will add that.
