### ISSUE TITLE
Python Chunks

### ISSUE THREAD

**Issue by joe-cormier** [MicrosoftDocs/visualstudio-docs#5102]
Update - I can run python code in a chunk, but the results are not shown in the real-time preview.  When knitted, the pdf will show the results.  Is there something I need to do to get the python results to show in the preview?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da4e19d-500e-5b87-a186-552a393939d0
* Version Independent ID: 20bdb33b-334c-d0b9-724f-33f211d9a85b
* Content: [R Markdown - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/rmarkdown-with-r-in-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/rtvs/rmarkdown-with-r-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/rmarkdown-with-r-in-visual-studio.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by WilliamAntonRohm** [comment]
@joe-cormier -- Joe, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
