### ISSUE TITLE
Dcproj is not being automatically created

### ISSUE THREAD

**Issue by aluong** [MicrosoftDocs/visualstudio-docs#5103]
With an existing project, I am able to generate the `Dockerfile` with `Add Docker Support`. However, the dcproj does not get generated.

Is there a way to get VS to manually create it?

**Comment by WilliamAntonRohm** [comment]
@aluong -- Andy, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
