### ISSUE TITLE
No

### ISSUE THREAD

**Issue by phuong127** [MicrosoftDocs/visualstudio-docs#5117]
inefficient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47c267f-87b7-fc11-8c1b-20e00c39e5a7
* Version Independent ID: f2b01182-c437-70fd-4fea-d8c75afc08f1
* Content: [How to: Expose code to VBA in a C# project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-expose-code-to-vba-in-a-visual-csharp-project?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-expose-code-to-vba-in-a-visual-csharp-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-expose-code-to-vba-in-a-visual-csharp-project.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@phuong127 -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by phuong127** [comment]
I want to ask is there a way to declare VBA for word functions in c # winfrom project.Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by WilliamAntonRohm** [comment]
@phuong127 -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
