### ISSUE TITLE
Which version of TypeScript is used?

### ISSUE THREAD

**Issue by ericmutta** [MicrosoftDocs/visualstudio-docs#5134]
When you enable the "Compile On Save" option the IDE will generate JavaScript code from any TypeScript files you have  in the project (this is really handy by the way). However, what version of TypeScript is used? I have four different versions under `C:\Program Files (x86)\Microsoft SDKs\TypeScript`. Which one does the IDE use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 783bb55e-13cd-fd00-4179-d39a4172535c
* Version Independent ID: 5d311bdd-1c0f-4170-c266-87ddd0b872d9
* Content: [Options, Text Editor, JavaScript, Project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-javascript-project?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.TypeScript.Project.General);k(DevLang-typescript)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-javascript-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-javascript-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@ericmutta -- Eric, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Mikejo5000** [comment]
Might have some doc impact.

**Comment by ericmutta** [comment]
@WilliamAntonRohm / @Mikejo5000 many thanks for following up on this. I can confirm that the IDE uses the latest version of TypeScript installed for "Compile On Save". It would be handy if the docs said something to that effect :+1:

**Comment by Mikejo5000** [comment]
Updating doc. Thanks!

**Comment by ericmutta** [comment]
Many thanks @Mikejo5000 :+1:
