### ISSUE TITLE
No option  to "set as startup file" after "Right-click app.py in Solution Explorer and select Set as startup file" 

### ISSUE THREAD

**Issue by gretchunkim** [MicrosoftDocs/visualstudio-docs#5146]
There's no option to select  "set as startup file" after right-click app.py. 

Using  Visual Studio version: 16.5.4. 
<img width="410" alt="Capture" src="https://user-images.githubusercontent.com/8564035/79663062-c3dd1900-8182-11ea-9051-e7701cc192b4.PNG">

**Comment by WilliamAntonRohm** [comment]
@gretchunkim -- Azores, thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
