### ISSUE TITLE
R samples always running on macOS!

### ISSUE THREAD

**Issue by hindermath** [MicrosoftDocs/visualstudio-docs#5149]
The R samples on the web page are also running for a quick test on my CRAN R interpreter on macOS Catalina! 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde63717-000d-d97c-0898-36c005d8541f
* Version Independent ID: 4c63fc76-7fac-4e58-cca7-e8476cb1248f
* Content: [Getting started with R Tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/getting-started-with-r?view=vs-2017&source=docs)
* Content Source: [docs/rtvs/getting-started-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/getting-started-with-r.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@hindermath Thanks for the note. It seems that you're just commenting on having a success here, and aren't running into an issue, correct?

Either way, though, because support for R was dropped from Visual Studio 2019, the RTVS documentation that you refer to here is no longer actively maintained, and for that reason I'm closing this issue. Thanks.
