### ISSUE TITLE
Does not fit on screen

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#5150]
### The recovery screen does not fit on a 1920 x 1080 screen.

![image](https://user-images.githubusercontent.com/7513795/79736308-e47baf00-82f9-11ea-934b-be405ad13a19.png)

![image](https://user-images.githubusercontent.com/7513795/79736123-9e265000-82f9-11ea-9560-6e290b888201.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5090ac82-e40b-257a-cea4-d6ea75d5964c
* Version Independent ID: 88e71b46-e31f-1a7b-7b76-41cfc3c57ed3
* Content: [AutoRecover, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/autorecover-environment-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.DialogAutoRestore)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019)
* Content Source: [docs/ide/reference/autorecover-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/autorecover-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
