### ISSUE TITLE
Sandboxed Environment?

### ISSUE THREAD

**Issue by KJDietrich** [MicrosoftDocs/visualstudio-docs#5152]
What can someone do if they're developing on an isolated environment?  I have an a lab environment that is  completely isolated and I can not sign in to a live account using the IDE to get passed the trial prompt.  What then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff48e07-208e-a8b1-0855-3f677cdf788b
* Version Independent ID: 0fd3926f-d997-c744-3f48-85568a2d462e
* Content: [Sign in to Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/signing-in-to-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/signing-in-to-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/signing-in-to-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@KJDietrich -- KJ, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
