### ISSUE TITLE
Implicit and explicit types doesn't work with template type

### ISSUE THREAD

**Issue by Metrowerks** [MicrosoftDocs/visualstudio-docs#5168]
I have this in my .editconfig:
csharp_style_var_for_built_in_types = false:suggestion
csharp_style_var_when_type_is_apparent = true:error
csharp_style_var_elsewhere = false:error

but it still tells me to use explicit type wherever I use generic type like this:
var ignore = property.GetCustomAttribute&lt;SomeAttribute&gt;();

where the GetCustomAttribute is defined to return the template type:
public static T GetCustomAttribute&lt;T&gt;(this MemberInfo element) where T : Attribute;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@Metrowerks -- TDao, thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
