### ISSUE TITLE
Two accounts - connect - Pull Requests says not connected

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/visualstudio-docs#5178]
VS Preview 16.1 and connecting to Git Repo on https://dev.azure.com/{repo} OK. View and create Branches OK. Sync, Work Items OK etc. 

Pull Requests "You are not connected to a remote repository. Go to the Connect page to connect ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@OzBob -- thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
