### ISSUE TITLE
Please Provide an Option to Leave Only Braces On Same Line

### ISSUE THREAD

**Issue by ChayimFriedman2** [MicrosoftDocs/visualstudio-docs#5195]
`csharp_preserve_single_line_statements` will keep both
```c#
string a = ""; int b = 1;
Console.WriteLine(a); Console.WriteLine(b);
```
and
```c#
if (a) { Console.WriteLine(a); }
```

Whilst many developers like the second form, but discourage the first one. But with this option on it is being formatted to
```c#
if (a)
{ Console.WriteLine(a); }
```
Which is even worse (IMO) than
```c#
if (a)
{
    Console.WriteLine(a);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db54afa5-fc7b-394f-ede3-4d1d46ec695d
* Version Independent ID: 86441bf6-9e5b-85c2-d42d-3afd5a9a069b
* Content: [.NET formatting conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-formatting-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-formatting-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@ChayimFriedman2 -- Chayim, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
