### ISSUE TITLE
Possible to clarify instructions?

### ISSUE THREAD

**Issue by asherabrams** [MicrosoftDocs/visualstudio-docs#520]
Thank you for this interesting and informative tutorial.  Unfortunately I'm having trouble following the instructions for adding code in this step.  Does the code beginning with [ Random randomizer = new Random();] precede the line [ public Form1()]?  Exactly where does the [StartTheQuiz()] method go?  It might be helpful to include the completed code, highlighting the parts to be added by the learner in this step.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf98f2-d920-def8-7c71-6c236603b33d
* Version Independent ID: f427c6dd-7abe-ae96-0325-e9e9ad579c8d
* [Step 2: Create a random addition problem](https://docs.microsoft.com/en-us/visualstudio/ide/step-2-create-a-random-addition-problem#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-2-create-a-random-addition-problem.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@asherabrams Thanks for your feedback; we appreciate it. This is in our backlog queue to get fixed; we'll report back when it is.

**Comment by TerryGLee** [comment]
@asherabrams We've added to the Note at the top of the page so that it includes a link to the completed code. Thanks for helping us improve the documentation!

**Comment by rtbolton** [comment]
@TerryGlee Hello,  it looks the original code has disappeared in the web.   Any idea where I might find it?   I'm new to C# and have the questions as @asherabrams.   Thanks!

**Comment by TerryGLee** [comment]
@rbolton Thanks for letting us know. The MSDN Code Gallery has been retired, unfortunately. I'm investigating where this sample landed so that we can add it to the list on this page: https://docs.microsoft.com/en-us/teamblog/msdn-code-gallery-retired

Meanwhile, I'll remove the link from the tutorial until I can confirm the new link for the sample, at which time we'll add the link back to the tutorial.

**Comment by rtbolton** [comment]
Thanks Terry!   I was wondering,  if this tutorial is retired,  is there a better place I should be learning from?  
It is my goal to learn C# to develop applications for AutoCAD software.  Would you be able to recommend a starting point?
 I appreciate your time and recommendation.


    On Tuesday, January 7, 2020, 12:20:17 AM CST, Terry G. Lee <notifications@github.com> wrote:  
 
 
@rbolton Thanks for letting us know. The MSDN Code Gallery has been retired, unfortunately. I'm investigating where this sample landed so that we can add it to the list on this page: https://docs.microsoft.com/en-us/teamblog/msdn-code-gallery-retired

Meanwhile, I'll remove the link from the tutorial until I can confirm the new link for the sample, at which time we'll add the link back to the tutorial.

**Comment by TerryGLee** [comment]
@rtbolton Unfortunately, the original code sample (as a downloadable .zip file) cannot be retrieved. Our apologies for that.

As for learning how to us C# to develop apps for AutoCAD software, I haven't found any content on our sites that address that specifically, but here are a few pages that can help you sharpen your C# skills:

- [A tour of the C# language](https://docs.microsoft.com/dotnet/csharp/tour-of-csharp/)
- [How to (C#)](https://docs.microsoft.com/dotnet/csharp/how-to/)
- [C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/)
- [C# Walkthroughs](https://docs.microsoft.com/en-us/dotnet/csharp/walkthroughs)

Otherwise, for content that addresses both C# and AutoCAD, there are courses and content sets out there; here's a set of search results for "[learn C# for AutoCAD](https://www.bing.com/search?q=learn+c%23+for+autocad)" that might prove useful to you.

Happy coding!
