### ISSUE TITLE
Writing tests in the same project

### ISSUE THREAD

**Issue by ArtTemiy** [MicrosoftDocs/visualstudio-docs#5206]
Hello,
Using vs2019, tried to write unit tests in the same project, but they don't run

Test Logger: Stack trace is not available. This may be because of missing PDB file(s)

Debug shows exception in CppUnitTest.h:
![image](https://user-images.githubusercontent.com/47613619/80638539-427e6400-8a69-11ea-9325-9218503156c2.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking questions: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
