### ISSUE TITLE
Fix affirmation that "continuation occurs in the same thread that created the task"

### ISSUE THREAD

**Issue by giggio** [MicrosoftDocs/visualstudio-docs#5216]
A task may continue on a different thread. It all depends on the Async Context.
See [the docs](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#configure-context) for more info.

A feedback not on the page, but on the product itself:
For this exact reason, also, this diagnostic should not be enabled by default. This makes sense mostly for library authors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d637a6-6f73-c865-94ea-28ca5d9861a0
* Version Independent ID: df24f234-848f-e04c-488d-6b6346e51fa6
* Content: [CA2007: Do not directly await a Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019)
* Content Source: [docs/code-quality/ca2007.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2007.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mavasani for input. In the "See the docs" link above (link to Async/Await doc), it looks to me like a Task will only continue on a different thread (in the thread pool) if you set .ConfigureAwait(continueOnCapturedContext: false). So the original statement in the doc seems valid, since it implies that you are awaiting directly on the Task without using ConfigureAwait.

@giggio If you would like to see the rule disabled by default, can you open the issue on https://github.com/dotnet/roslyn-analyzers? Thanks!

**Comment by mavasani** [comment]
@giggio For this very reason there is an option to configure the output kinds for this rule: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#analyzed-output-kinds

**Comment by Mikejo5000** [comment]
Great, thanks. Since the configurability is already doc'ed here in CA2007, I'll close this issue.

**Comment by Mikejo5000** [comment]
Revising the text. Thx!
