### ISSUE TITLE
Maybe defined SuppressMessageAttribute.Scope as an enum type is good

### ISSUE THREAD

**Issue by CwjXFH** [MicrosoftDocs/visualstudio-docs#5220]
Maybe defined [SuppressMessageAttribute.Scope](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.scope?view=netcore-3.1#System_Diagnostics_CodeAnalysis_SuppressMessageAttribute_Scope) as an enum type is good.

**Comment by WilliamAntonRohm** [comment]
@CwjXFH -- WenJun, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by CwjXFH** [comment]
@WilliamAntonRohm 

[Docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.scope?view=netcore-3.1#remarks) says, the value for `SuppressMessageAttribute.Scope` is  `"member", "resource", "module", "type", "method", "namespace"` etc. It's too much. So, if `SuppressMessageAttribute.Scope` is an enum type, it will be more convenient to use.

Thanks!

**Comment by WilliamAntonRohm** [comment]
@CwjXFH -- WenJun, thank you for clarifying.  It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
