### ISSUE TITLE
Unable to see individual rules for Analysis Ruleset

### ISSUE THREAD

**Issue by udlose** [MicrosoftDocs/visualstudio-docs#5225]
I have a number of Code Analyzers added to my ASP.NET Core 3.1 project.  However, I can only see individual rules listed for some of the analyzers.  Any ideas?

![image](https://user-images.githubusercontent.com/656118/80838517-d281f200-8bbe-11ea-82bf-ae2d723de1d9.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by WilliamAntonRohm** [comment]
@udlose -- Dave, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by udlose** [comment]
Problem went away after restarting VisualStudio
