### ISSUE TITLE
Can we modify  XML comments default text?

### ISSUE THREAD

**Issue by michaldengusiak** [MicrosoftDocs/visualstudio-docs#5229]
we have 

        /// &lt;summary&gt;
        /// 
        /// &lt;/summary&gt;
        /// &lt;param name="geometry"&gt;&lt;/param&gt;
        /// &lt;param name="construction"&gt;&lt;/param&gt;
        /// &lt;param name="panelType"&gt;&lt;/param&gt;
        /// &lt;returns&gt;&lt;/returns&gt;
        public static SAM.Analytical.Panel ByGeometry(object geometry, SAM.Analytical.Construction construction, object panelType = null)

would be possible to add 
        /// &lt;search&gt;&lt;/search&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d705255d-06b6-5980-a525-5766f8c60ddc
* Version Independent ID: f832369d-1fd1-ebe9-7e64-e098c110f68c
* Content: [Insert XML documentation comments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/generate-xml-documentation-comments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-xml-documentation-comments.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by michaldengusiak** [comment]
For reference: I need to follow this standard:

https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development

**Comment by WilliamAntonRohm** [comment]
@michaldengusiak -- Michal, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
