### ISSUE TITLE
JS instead of TSX

### ISSUE THREAD

**Issue by mk-16** [MicrosoftDocs/visualstudio-docs#5231]
hi , this guide specify the steps for app based on typescript
may i get an explanation or maybe can you guys add to the guide on how to work with .js instead of .tsx files?
or if not, i see that there is an npm of create-react-app  if its possible to guide on how to run it ???
to be more precise if i run it through command prompt like npx create-react-app {name of the app} it works just fine but the i have to include all the files in the project cause it installs them as hidden for some reason ???....
if i install the create-react-app in npm manager all it does is put it in dependencies but no app creation happens... can someone explain to me how to use correctly the npm manager and how to make the node package execute? and not only install it and show it in dependecies ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mk-16 The tutorials here are mainly to provide proof of concept for a few scenarios. It's not possible for us to cover every scenario and framework, but I may be able to take a quick look at this later on. A main intent here is to cover JSX for React, which needs to get transpiled to JavaScript via a transpiler, typically either TypeScript or Babel. So, you weren't planning on using JSX?

**Comment by Mikejo5000** [comment]
Also, if you have a pre-existing Node.js app (create-react-app), you might try using an [Open Folder](https://docs.microsoft.com/en-us/visualstudio/javascript/develop-javascript-code-without-solutions-projects?view=vs-2019) project instead. In general, it's a bit easier to hookup Node.js to VS with a project created using one of the Node.js templates, such as the Blank Node.js Web Application template. In any VS scenario we are talking about here, you need the Node.js development workload in Visual Studio installed, and the Node.js runtime. For the create-react-app sample, you might also try it with Visual Studio Code instead, since that sample is directly targeted in the following tutorial: https://code.visualstudio.com/docs/nodejs/reactjs-tutorial. We would probably need a new tutorial to get that sample hooked up in VS.

**Comment by Mikejo5000** [comment]
May re-open this later if we decide to do a doc enhancement around this.
