### ISSUE TITLE
Debugging restrictions

### ISSUE THREAD

**Issue by pclaessendrs** [MicrosoftDocs/visualstudio-docs#5258]
There is a note here that says
"Although you could also add the new managed project to your existing C++ solution, creating a new solution supports more debugging scenarios."
a. What are those additional debug scenarios, and
b. Why wouldn't those work when both projects are in the same solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec762474-4eeb-cba2-5290-fd664ab88f8c
* Version Independent ID: 318fa7f6-e54a-1777-1f3f-3a30bb736f69
* Content: [Tutorial: Debug C# and C++ code (mixed mode) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-to-debug-managed-and-native-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-managed-and-native-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I will rephrase the note. If I recall, the two solutions were used to make the scenario more difficult to for debugging instead of easier. But the note should probably just say that you could alternatively add the new managed project to your existing C++ solution. It should work fine when both projects are in the same solution.

**Comment by pclaessendrs** [comment]
Thanks Mikejo5000, that makes sense!
