### ISSUE TITLE
Wrong category while suppressing message 

### ISSUE THREAD

**Issue by Kelvin-K** [MicrosoftDocs/visualstudio-docs#5264]
I am working with visual studio for project building and warning resolution.
And for deployment purpose i am using azure pipelines.

suppression logic works in visual studio 
but the azure pipeline does not recognize suppression in global suppression.

upon investigation i found that azure recognizes 
``` CSharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "
```
But when i am use visual studio suppression then it generates below code

```CSharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "
```

I am not able to figure out what to do and how to resolve this.

I am using visual studio version 4.8.03752
and for code analysis i am using VSIX extension named "Microsoft Code Analysis 2019"
Please provide some solution as i was not able to find any article related to this online.

**Comment by WilliamAntonRohm** [comment]
@Kelvin-K -- thank you for your feedback.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Kelvin-K** [comment]
https://developercommunity.visualstudio.com/content/problem/1027180/wrong-category-while-suppressing-message.html

**Comment by WilliamAntonRohm** [comment]
@Kelvin-K -- Kelvin, thank you for posting that.
