### ISSUE TITLE
Mass Code Generation

### ISSUE THREAD

**Issue by CarlBinneman** [MicrosoftDocs/visualstudio-docs#5265]
Can this be done on the entire document?

If one has typed out a number of method thats have yet to be created, is there a way to have all missing methods generated with a few clicks? 

Pressing alt + enter for 220 missing methods is going to suck

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35ba564-ec70-2884-3568-20e6233e069f
* Version Independent ID: 35681f64-4d07-c3c8-3e36-f702257000d2
* Content: [Generate a method - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-method?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/generate-method.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-method.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@CarlBinneman -- thank you for your questions.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your questions:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by CarlBinneman** [comment]
You have assumed incorrectly.
The product provides the functionality I want, I have an issue with the documentation.

It is not documented how to run generated code for all suggested places in the open document.
The product is perfectly capable of doing this.

**Comment by CarlBinneman** [comment]
It used to be documented that after previewing the suggested changes, one could "Apply to all occurrences in ..." 

This is now gone, so I guess you are right, no documentation is needed for features that no longer exist. 
Though the documentation very strongly implies that the quick actions apply to files as a whole and it is pretty starnge that you cant handle all occurrences at once

**Comment by TerryGLee** [comment]
@CarlBinneman Does this page describe the functionality that you're looking for? [Preview Changes window](https://docs.microsoft.com/en-us/visualstudio/ide/preview-changes?view=vs-2019)
