### ISSUE TITLE
Missing dist folder

### ISSUE THREAD

**Issue by jayanthimurugesan** [MicrosoftDocs/visualstudio-docs#5270]
I can't find the folder dist which contains app-bundle.js and app-bundle.js.map.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jayanthimurugesan -- again, thank you for your feedback.  This repo is solely for documentation issues, with few support options.

It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
