### ISSUE TITLE
Solution Explorer

### ISSUE THREAD

**Issue by MarineOne84** [MicrosoftDocs/visualstudio-docs#5281]
When I create the project as described above, and it opens, I do not have all or the resources in the Solution Explorer that are shown here and in the video. When I check where the project is stored on my PC, the information is there, it just does not show up in the Solution Explorer. What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96bf0705-d0c2-d0ad-3e77-60b99a462e25
* Version Independent ID: 022345f2-1126-ec6c-e268-a73ca554aa39
* Content: [Step 2: Creating Your First ASP.NET Core Web App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-02?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-02.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-02.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@MarineOne84 -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
