### ISSUE TITLE
How to set cursor position for completion since snippet template is not supported in Visual Studio language server client

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/visualstudio-docs#5290]
Hi, team,
I am using LSP for auto-completion and diagnostic for the Visual Studio. however, from the "ClientCapabilities" it shows that Visual Studio do not support snippet template.
```
{
    "textDocument": {
        "completion": {
            "completionItem": {
                "snippetSupport": false,
            },
        },
...
}
```
I want to change the cursor position after user selecting the completion item,

when snippet template is supported, I can use the templete as below:
```
"name": "$1"
```
However, snippet template is not supported in VS, are there any other ways to achieve this?
Do we have plans to support snippet template in Visual Studio?

**Comment by WilliamAntonRohm** [comment]
@SLdragon -- Renlong, thank you for your question. Are you referring to a specific docs.microsoft.com article?  Meanwhile, please consider these options:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by SLdragon** [comment]
Thanks, however I cannot find any discussions about snippet template for VS language server, do we have any plans to support this in future release of the Visual Studio?

**Comment by WilliamAntonRohm** [comment]
@SLdragon -- Renlong, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
