### ISSUE TITLE
Create ASP.NET Core Web App Tutorial 

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#5300]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1022203/create-aspnet-core-web-app-tutorial.html)._

---
Is there an update to the C# Tutorials: Create an ASP.NET Core Web App.  In particular, the section "Expose a web API"  shows code samples that don't match what get created in Visual Studio 2019 when I go through the steps.  Here are some examples:
1. After generating an "API Control with actionstions, using entity Framework", my GetGame method does not have the [FromRoute] attribute and is missing the "if (! ModelState.IsValid)..." block.  It also has "return game;" instead of "return Ok(game);"
2. Attributes [FromRoute] and [Frombody] are also missing from PutGame(), PostGame(), and DeleteGame().
3. In the "Adding Swagger" section, in "services. AddSwaggerGen()", "Info" is marked with red wavy lines, indicated not known, and when I add "using Swashbuckle.AspNetCore.Swagger;" it is shown grayed (as not needed).
4. We're told to add some code to the Configure() method just before "UseMvc", but my Configure() method does not have "UseMvc" anywhere in it.

It's not a very good tutorial if I can't match it up with what happens in my Visual Studio 2019 when I follow the indicated steps.

---
#### Visual Studio Feedback System on 5/7/2020, 08:48 PM: 

&lt;p&gt;We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.&lt;/p&gt;

#### Visual Studio Feedback System on 5/7/2020, 10:24 PM: 

&lt;p&gt;Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: &lt;a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq"&gt;https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq&lt;/a&gt;. In case you need answers to common questions or need assisted support, be sure to use &lt;a target='_blank' href="https://visualstudio.microsoft.com/vs/support/"&gt;https://visualstudio.microsoft.com/vs/support/&lt;/a&gt;. We’ll keep you posted on any updates to this feedback.&lt;/p&gt;

---
### Original Solutions
(no solutions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788828c4-74bc-1bcb-7480-38e490358f18
* Version Independent ID: d62da0a4-9a26-a89d-ff8f-d3314cf35724
* Content: [Step 4: Exposing a web API From Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-04?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @Rick-Anderson, thanks for your feedback. I'll create a work item to get this tutorial updated.

**Comment by ornellaalt** [comment]
Hi @Rick-Anderson, I just went through the tutorial and could not duplicate the following issues:

1. After generating an "API Control with actionstions, using entity Framework", my GetGame method does not have the [FromRoute] attribute and is missing the "if (! ModelState.IsValid)..." block. It also has "return game;" instead of "return Ok(game);"
2. Attributes [FromRoute] and [Frombody] are also missing from PutGame(), PostGame(), and DeleteGame().
3. In the "Adding Swagger" section, in "services. AddSwaggerGen()", "Info" is marked with red wavy lines, indicated not known, and when I add "using Swashbuckle.AspNetCore.Swagger;" it is shown grayed (as not needed).

Regarding 4. (We're told to add some code to the Configure() method just before "UseMvc", but my Configure() method does not have "UseMvc" anywhere in it.) -- you should have `app.UseMvc();` at the bottom of your Configure() method. I have noted this as something to fix. 

**One important note**: I ran into an issue in [Step 3: Work with data using Entity Framework](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019) when editing the `main` method in `Program.cs`. When I followed the directions exactly, using the code block provided, I got an error on localhost when I tried to navigate to the /Games page. I added `Data.` before `AppDbContext` in this line: `var context = services.GetRequiredService<AppDbContext>();` and it solved my issue. 

For reference, I used Visual Studio 2019 Community with ASP.NET Core 2.2. I installed the 4.0.1 version of Swashbuckle.AspNetCore according to the tutorial, even though it is not the most up-to-date stable build, and marked this as something to fix.

**Comment by Rick-Anderson** [comment]
@ornellaalt  thanks for the report.
