### ISSUE TITLE
Alternate Accounts

### ISSUE THREAD

**Issue by muralidaran** [MicrosoftDocs/visualstudio-docs#5322]
I have visual studio subscription with my office account and i have added my personal Microsoft account as an alternate account, will i be able to view my office VS Azure Subscription when i login to azure using the Microsoft account ?

**Comment by WilliamAntonRohm** [comment]
@muralidaran -- it looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
