### ISSUE TITLE
I cant reinstall to set the uwp compile.

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/visualstudio-docs#534]
When I use VisualStudio to compile a uwp app that will say that `The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.` and I think maybe reinstall can help that I try to reinstall it but it always cant compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac42ba7-edf2-06fb-dc6a-13a0c47b43c5
* Version Independent ID: 98b5c39a-ff89-f4c8-ef77-ae239564998a
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/install/uninstall-visual-studio.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@lindexi It looks like you're having an issue with the product itself, rather than an issue with the documentation. For options to report your product issue, consider using the following venues:

* You can report product issues to us via the [Report a Problem](../ide/how-to-report-a-problem-with-visual-studio-2017.md) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.
* You can share a product suggestion with us on [UserVoice](https://visualstudio.uservoice.com/forums/121579).
* You can track product issues in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), and ask questions and find answers.
* You can also engage with us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

Thanks,
~ Terry

**Comment by lindexi** [comment]
@TerryGLee Thx .
