### ISSUE TITLE
Add include file

### ISSUE THREAD

**Issue by piedacoulisse** [MicrosoftDocs/visualstudio-docs#5342]
Hello,
I have a cpp file with many `#include <tlist.hpp> `
When I try to compile with a setup file, the builder can't find the file.
I try to modify the configuration `include_dirs=['pybind11/include','C:\Users\ME\FILES'], ` but it doesn't work.

Do you have an idee ?

Thanks.

Documentation : https://docs.python.org/3/distutils/setupscript.html

_System : Windows 10
IDE : Visual Studio 2019_

**Comment by WilliamAntonRohm** [comment]
@piedacoulisse -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
