### ISSUE TITLE
Visual Studio C++ for Android

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5355]
@Serguk commented on [Thu May 21 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/103)

I work with Unreal Engine and make games for android and ios.
I liked work with Visual Studio with C++. And I would like to learn more about make programs and games for android and ios with Visual Studio on C++. 
Can I get some documentation or information about these?
The main areas that interest me: gaining access to the settings of the android and ios mobile device (camera, flashlight, gyroscope, compass, location, etc.) and connect to server.
Cane I get description about library and how use its?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a762b2ab-91e6-eda8-01ad-977f89d4462b
* Version Independent ID: cca4863b-8658-968f-b1fa-5e2b0d292f56
* Content: [Кроссплатформенная разработка для мобильных устройств в Visual Studio - Visual Studio](https://docs.microsoft.com/ru-ru/visualstudio/cross-platform/cross-platform-mobile-development-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/blob/live/docs/cross-platform/cross-platform-mobile-development-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

---

@srvbpigh commented on [Thu May 21 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/103#issuecomment-632044457)

Hello, @Serguk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this issue.  Please send @Serguk the following links and best wishes:

- https://visualstudio.microsoft.com/vs/features/game-development/
- https://answers.unrealengine.com/questions/352144/how-to-get-mobile-acceleration-and-gyroscope-data.html

**Comment by Serguk** [comment]
Thank you all for participating in solving my problem. I have already read these articles. They describe the possibilities of a visual studio. But I'm interested in practice. How can I interact with android devices using c ++?
Since I work in Unreal Ungine, I am writing c ++ code. And I would like to receive data from a mobile device and manage it.

With Regards,
Serg.

**Comment by Serguk** [comment]
Thank you all for participating in solving my problem. I have already read
these articles. They describe the possibilities of a visual studio. But I'm
interested in practice. How can I interact with android devices using c ++?
Since I work in Unreal Ungine, I am writing c ++ code. And I would like to
receive data from a mobile device and manage it.

With Regards,
Serg.



пт, 22 мая 2020 г. в 23:55, William Anton Rohm <notifications@github.com>:

**Comment by WilliamAntonRohm** [comment]
@Serguk -- thank you for your followup.  This repo is solely for documentation issues, and your questions are more broad than we can cover.  Please consider the following resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by Serguk** [comment]
can i get direct access to the file
C: \ NVPACK \ android-ndk-r17c \ sysroot \ usr \ include \ camera \
NdkCameraManager.h
using #icnlude "......" ???

пт, 29 мая 2020 г. в 21:25, William Anton Rohm <notifications@github.com>:
