### ISSUE TITLE
Solution/Project Name longer than 60 chars not allowed

### ISSUE THREAD

**Issue by gcsizmadia** [MicrosoftDocs/visualstudio-docs#5363]
In VS 2019 16.6 it seems that solution/project name field is limited to 60 chars.
I suspect that this limitation is related to MAX_PATH.
I set LongPathsEnabled to 1 in registry but I still cannot set a name longer than 60 chars.

My colleague uses 16.4.1 and he somehow can set a name that is longer than 60 chars.

How can this limitation be eliminated? It is really annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b25eea-0531-fc29-14c3-97b01d3c9ffc
* Version Independent ID: 93399d12-64f7-aa0c-f7d6-7ed8ecd95086
* Content: [Create a new project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2019&github-auth-complete=true#feedback)
* Content Source: [docs/ide/create-new-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-new-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@gcsizmadia -- Gabor, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
