### ISSUE TITLE
List of blob storage to whitelist for Azure DevOps agent behind proxy

### ISSUE THREAD

**Issue by aruvinkun** [MicrosoftDocs/visualstudio-docs#5376]
Hi, 

Is it possible to get a list of blob storage URLs required to whitelist for running an on-prem self-hosted Azure DevOps agent behind a proxy? *.blob.core.windows.net is too generic for the Security team to allow as this opens to any blob storage account in Azure. 

We are using the on-prem agent to run a deployment pipeline (YAML) in Azure DevOps - grab the artifacts and deploy to on-prem servers.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@aruvinkun -- thank you for your question. Here are a few resources you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ornellaalt -- please look into this issue.

**Comment by ornellaalt** [comment]
Hi @aruvinkun, please post your question on https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=vssetup and someone from the product team will be able to give you a more specific response. The list on this page is not meant to be tailored to a specific use case, instead giving a general overview of possible endpoints and URLs.

**Comment by aruvinkun** [comment]
@ornellaalt @WilliamAntonRohm  - thanks for your response but this is the only documentation that I can find and if there's another one, please direct me. Directing me to stackoverflow isn't really the kind of response I'm expecting as the reason I'm here is for official documentation from Microsoft - not someone else's opinion. I believe the documentation is based from official knowledge of how it works so I think it's relevant here. 

Also, I don't think this is a very specific use case. It is a generic use case and very relevant to the content to this documentation page I'm asking about as that should be the purpose of this doc - https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md

One of the main usage of Azure DevOps is CI and CD and the associated artiffacts. Anyone who does this behind a proxy will make this a generic concern. Again, if there's another documentation that you know that touches on this, please direct me.

**Comment by ornellaalt** [comment]
Hi @aruvinkun, I spoke to someone on that team and this is the information I received: 
_Blob storage URLs are specific to an account. So if you have an account named “contoso” the Blob URL endpoint would be contoso.blob.core.windows.net. The use of a wildcard might whitelist all accounts that have the blob.core.windows.net extension (which means all accounts). The only way to be more specific is to use the names of the accounts to be whitelisted. For example: contoso.blob.core.windows.net._

The generic use case, and documentation that we show on this page intentionally shows *.blob.core.windows.net as the URL to whitelist. In order to make this URL specific for your use case (using the on-prem agent to run a deployment pipeline (YAML) in Azure DevOps), you can add the accounts of your agent to the URL. At this time, we do not have documentation specific to this use case. If you are looking for more specific product help or advice, you can post on the **official** Microsoft Visual Studio forums [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=vssetup). You can also post on the **official** Azure Storage Q&A website [here](https://docs.microsoft.com/en-us/answers/index.html). These forums are monitored by Microsoft employees who are members of the product teams.
