### ISSUE TITLE
 var host = CreateWebHostBuilder(args).Build();  CS 1061 Error

### ISSUE THREAD

**Issue by apikman** [MicrosoftDocs/visualstudio-docs#5377]
I am getting a CS1061 Error in this line 

"  var host = CreateWebHostBuilder(args).Build(); "

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'object' does not contain a definition for 'Build' and no accessible extension method 'Build' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)	

Please help

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f156aaa-839a-b9bb-5912-b3a537dfdb36
* Version Independent ID: 51888076-400e-0a51-8ae4-6fe745829436
* Content: [Step 3: Working with Data in Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@apikman -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @ornellaalt for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
