### ISSUE TITLE
How to modify PDB files

### ISSUE THREAD

**Issue by daravi** [MicrosoftDocs/visualstudio-docs#5406]
I want to write a program that patches PDB files to point to specific source paths. I see that the DIA-SDK provides methods for reading source filenames (i.e. `IDiaSourceFile::get_fileName`). And I see that Microsoft has open sourced the layout of the PDB file (https://github.com/Microsoft/microsoft-pdb). I am wondering if there is a tool like DIA that would let me modify the PDB, or if I have to manually modify it. If manual modification is the only route what are some suggestions that you could give me to help me get started?

Also I have a suggestion for Microsoft team to open source DIA-SDK if possible. Specially since you have already opened the PDB layout.

Thank you for everything. Any help is greatly appreciated!

**Comment by WilliamAntonRohm** [comment]
@daravi -- thank you for your question.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
