### ISSUE TITLE
can not get example to run

### ISSUE THREAD

**Issue by stevenevans-j2** [MicrosoftDocs/visualstudio-docs#5408]
I am working on developing an add -in for Excel.  So was working thought the example.  unfortunately when i get to test project i get the following 

![image](https://user-images.githubusercontent.com/18507416/83355090-f6b72700-a354-11ea-99f2-e53e4b75db3f.png)

looking in the event log I see

![image](https://user-images.githubusercontent.com/18507416/83355123-40077680-a355-11ea-8042-47065d468557.png)

I am developing with VS 2019 and have Office 2019 installed on my machine
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926f7f34-3f79-cfe2-c9ea-2d36bcdbafae
* Version Independent ID: 7ac3f98c-c147-3378-a2c8-7bd2944a2acd
* Content: [Walkthrough: Create your first VSTO Add-in for Excel - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel?view=vs-2019)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@stevenevans-j2 -- thank you for your feedback.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
