### ISSUE TITLE
win ok ok ok马茨克 ok ok ok

### ISSUE THREAD

**Issue by q28wertyuio** [MicrosoftDocs/visualstudio-docs#5409]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@q28wertyuio -- thank you for writing.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
