### ISSUE TITLE
No clear explanation of difference between win32 and x86 build configuration provided

### ISSUE THREAD

**Issue by omatai** [MicrosoftDocs/visualstudio-docs#5419]
I can build my Visual Studio project for x86, win32 or x64 platforms. What exactly is x86 as distinct from win32? It is not explained anywhere obvious under the "target platforms" section(s) of the Visual Studio documentation. x64 should be explained too in case someone comes up with win64 in the future and it has a different exception model or instruction set or something.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb5a706d-01d5-40c8-69af-e223a73a5948
* Version Independent ID: 8d5a1950-1b98-7e22-0f40-02a8ab0e7233
* Content: [How to: Configure projects to target platforms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms?view=vs-2019)
* Content Source: [docs/ide/how-to-configure-projects-to-target-platforms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-configure-projects-to-target-platforms.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
"Win32" is used for C++ projects and it means "x86."  I think what's confusing here is that you really have both "project-level platforms" and "solution-level platforms" and the project platforms come from the language-specific project systems. C++ projects use "Win32" and "x64", but the solution platforms use 'x86' and 'x64', NOT Win32. But, when you choose 'x86' as the solution configuration, VS selects the Win32 project configuration, so it works.  This could be explained in the topic.

**Comment by omatai** [comment]
If you’re going to explain that, please supplement the text with a diagram and/or table – show relationships between project-level, solution-level compared/contrasted with language-specific. As pure text, it comes across as word salad – repeated similar terms mixed without obvious structure.

**Comment by aidtopia** [comment]
> C++ projects use "Win32" and "x64", but the solution platforms use 'x86' and 'x64', NOT Win32.

The part about _solutions_ is not entirely true:  Some of mine have "x86" and "x64", but others do indeed have "Win32" and "x64".  In all cases, these solutions contain nothing but C++ projects.  (You seem to be correct that the C++ projects always use "Win32" rather than "x86".)

As best as I can tell, whether a solution has "Win32" or "x86" as a platform depends on what version of Visual Studio it was originally created with.  My oldest solutions have "Win32" and newer ones have "x86".

Further confusing the issue is that the `$(PlatformTarget)` macro in the property pages.  It's unclear to me whether this is the project platform or the solution platform.  Either way, it expands "x86" even when both the solution and project platforms are "Win32".  I'm fine with that behavior, but it sure is confusing.
