### ISSUE TITLE
Visual Studio family

### ISSUE THREAD

**Issue by dlibor** [MicrosoftDocs/visualstudio-docs#5421]
With _Visual Studio family_ you mean the settings can be synchronized even with Visual Studio Code and Visual Studio Codespaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f452163a-5b45-243c-9601-585359deec53
* Version Independent ID: 881229c0-dfb7-6e68-00ae-868abd0c6687
* Content: [Synchronize settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/synchronized-settings-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/synchronized-settings-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@dlibor It looks like this page is misleading when it mentions the "Visual Studio family." While including the word "family" was true in the past, it's no longer true since the advent of Visual Studio Code and Visual Studio Codespaces.

To answer your direct question: Visual Studio settings aren't shared with Visual Studio Code or Visual Studio Codespaces. 

FYI: We've got a PR merged that removes the word "family" from this page. It's queued up for publish and will go live after 10:00am Pacific Time tomorrow (6/19/20). We'll close this issue now, however. 

Thanks for helping us improve the documentation!
