### ISSUE TITLE
exec-task UseCommandProcessor="true"  not working properly

### ISSUE THREAD

**Issue by gojimmypi** [MicrosoftDocs/visualstudio-docs#5446]
The [UseCommandProcessor](https://docs.microsoft.com/en-gb/visualstudio/msbuild/exec-task?view=vs-2019) appears to not be implemented properly.

When I turn it on like this:
```
    <Exec Command=".\build\vs-build.bat" UseCommandProcessor="true"  Condition="'$(Configuration)'=='Release' " />
```
Here's the diagnostic output:
```
1>Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>Task "Exec" (TaskId:4)
1>  Task Parameter:Command=.\build\vs-build.bat (TaskId:4)
1>  Task Parameter:UseCommandProcessor=True (TaskId:4)
1>  .\build\vs-build.bat (TaskId:4)
1>  .\build\vs-build.bat (TaskId:4)
1>   (TaskId:4)
1>  C:\Users\gojimmypi\source\repos\Verilog45\Verilog45>/Q /D /C C:\Users\gojimmypi\AppData\Local\Temp\tmp8ac98e48c6494f4e94b2bb958db28141.exec.cmd  (TaskId:4)
1>  '/Q' is not recognized as an internal or external command, (TaskId:4)
1>  operable program or batch file. (TaskId:4)
1>C:\Users\gojimmypi\source\repos\Verilog45\Verilog45\Verilog45.csproj(112,5): error MSB3073: The command ".\build\vs-build.bat" exited with code 1.
1>Done executing task "Exec" -- FAILED. (TaskId:4)
1>Done building target "Build" in project "Verilog45.csproj" -- FAILED.: (TargetId:2)
```
Note that the `cmd` command seems to be missing, and instead the `/Q /D /C` are passed _first_ in the generated command.

```
1>  C:\Users\gojimmypi\source\repos\Verilog45\Verilog45>/Q /D /C C:\Users\gojimmypi\AppData\Local\Temp\tmp8ac98e48c6494f4e94b2bb958db28141.exec.cmd  (TaskId:4)
1>  '/Q' is not recognized as an internal or external command, (TaskId:4)

```
Edit:
```
Microsoft Visual Studio Enterprise 2019
Version 16.6.1
VisualStudio.16.Release/16.6.1+30128.74
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise
```

**Comment by WilliamAntonRohm** [comment]
@gojimmypi -- thank you for your feedback.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
