### ISSUE TITLE
$ext_projectname$ as the value of the custom property didn't work

### ISSUE THREAD

**Issue by Eliador** [MicrosoftDocs/visualstudio-docs#5452]
I trying to create VS Template with several projects.
And in progress, I collided with problem related to the $ext_projectname$ template property by using it as Value of the custom property.

Here is a simple example of my issue: [TemplateExtPropertyIssue.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/4751675/TemplateExtPropertyIssue.zip)

As you can see I create a custom property TemplateExtPropertyIssue with value "$ext_projectname$":
![image](https://user-images.githubusercontent.com/10233346/84140769-52cc2a80-aa7c-11ea-9ef2-9124ea18830c.png)

And I set CopyParameters to true in ProjectTemplateLink in root vstemplate file:
![image](https://user-images.githubusercontent.com/10233346/84140855-71322600-aa7c-11ea-88a5-052dfab67ac4.png)

And, for example, I use $ext_projectname$ directly in code and through the custom property:
![image](https://user-images.githubusercontent.com/10233346/84139846-d422bd80-aa7a-11ea-81af-c6ea6bdc3cb1.png)

But by creating a new project from this template, $ext_projectname$ that used directly in code was replaced to the value from parent vstemplate property, but through the custom property, it was replaced to an unexpected value ("$ext_projectname$"):
![image](https://user-images.githubusercontent.com/10233346/84139988-14823b80-aa7b-11ea-8add-9335356f4017.png)

It is correct behavior?

Note: when as the value of the custom property I will use $projectname$ - it works as I expect, it will be replaced to "MyProject.Console" and definition of the namespace in program.cs will be looks like "namespace MyProject.Console.Console". This is not what I want.

**Comment by WilliamAntonRohm** [comment]
@Eliador -- thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
