### ISSUE TITLE
VS Templates - Mac templates a subset of Windows ones

### ISSUE THREAD

**Issue by robsoft** [MicrosoftDocs/visualstudio-docs#5465]
It's still the case that even having installed everything, and 'updated' the templates with 
**dotnet new --update** (etc).... 
the Mac thinks the templates are complete and up to date but there are some missing that are in the current Windows version, particularly with respect to Core ASP.Net, Razor type projects. 

This is also true with some of the 'Add New.... Controller' and Razor stuff once you're inside a project, too - I find it easier to spin things up in the Windows version and once the project is roughly 'ready to code behind', move it over to my Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51fedc16-c24d-6dcc-c13e-30bdafbc2507
* Version Independent ID: 5213b76c-52cd-d46d-89ad-eeaafcc78d35
* Content: [Why can I not see all available templates? - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/troubleshooting-no-templates?view=vsmac-2019)
* Content Source: [mac/troubleshooting-no-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/troubleshooting-no-templates.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@robsoft -- Rob, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
