### ISSUE TITLE
Error List scope filter

### ISSUE THREAD

**Issue by thelosslessone** [MicrosoftDocs/visualstudio-docs#5476]
Is it possible to have a filter that responds to "Scope to This" from Solution Explorer in dropdown list on the left side ( Entire Solution, Current Project, ... )?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 619b7785-c2cb-c582-6478-debc1d5e40d6
* Version Independent ID: 91e701f2-a959-e25b-d9cc-48d0b4e8ba50
* Content: [Error List Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/error-list-window?view=vs-2019)
* Content Source: [docs/ide/reference/error-list-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/error-list-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@thelosslessone -- it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
