### ISSUE TITLE
.NET Async profiler always Loading Data

### ISSUE THREAD

**Issue by egmkang** [MicrosoftDocs/visualstudio-docs#5477]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/65175/84679783-4e17e280-af64-11ea-924e-3810b811c9d6.png)

![image](https://user-images.githubusercontent.com/65175/84679923-815a7180-af64-11ea-8069-fdf472583f68.png)

always Loading Data. 
i never saw the profiling result....

how can i solve this problem.

thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1ff01f-ec92-a385-f11b-83ed8919b056
* Version Independent ID: 8ffd1f76-0577-d50e-4277-713284897974
* Content: [Analyze performance of .NET asynchronous code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-async?view=vs-2019)
* Content Source: [docs/profiling/analyze-async.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/analyze-async.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @esteban-herrera
* Microsoft Alias: **esherrer**

**Comment by WilliamAntonRohm** [comment]
@egmkang -- thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
