### ISSUE TITLE
Gift wrapping the toy

### ISSUE THREAD

**Issue by LastWordSword** [MicrosoftDocs/visualstudio-docs#5500]
So I followed the tutorial, but now I'd like to be able to use the app, if nothing more than a proof of concept. How can I build an publish it to my own computer, such that it shows up alongside other programs, can be pinned to start, etc. 

In other words, just a normal program.

**Comment by WilliamAntonRohm** [comment]
@LastWordSword -- thank you for your feedback.  Which docs.microsoft.com tutorial were you following?  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by LastWordSword** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/tutorial-1-create-a-picture-viewer?view=vs-2019

I understand that best practices are being taught here, but the lack of instruction, and the Pri3 designation here, both seem very patronizing and belittling. This is not the way to attract authentic talent to the field. It all seems more like Mel's "pessimum", rather than optimum. 
P;D

**Comment by LastWordSword** [comment]
If you'd like someone who has the potential to understand Kunuth, maybe you ought to understand the whole spirit of Christmas trees a bit better.

**Comment by WilliamAntonRohm** [comment]
@LastWordSword -- thank you for your followup.

@ornellaalt -- please look into this issue.

**Comment by ornellaalt** [comment]
Hi @LastWordSword, the priority designation for GitHub issues in our repo is based solely on number of page views for the page on which the issue was filed. 

To answer your question, you can check out the Deployment in Visual Studio documentation [here](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2019). There are a variety of different deployment methods based on what language you are using. In particular, the [Deploy to a local folder](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-local-folder?view=vs-2019) documentation will help you understand the process of publishing your app to your own computer. 

Closing out this issue.

**Comment by LastWordSword** [comment]
Thank you for directing me to some resources. "In these challenging times"
I may not be able to look them over immediately, but I'm presuming that
they're more than likely to be helpful.
