### ISSUE TITLE
This determination is too ambiguous

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#551]
> When a solution created in an earlier version of Visual Studio is opened in a newer version, the IDE checks the solution file to determine if it needs to be upgraded.

What goes into making this determination? 

I don't recall a time when visual studio actually upgraded a project. I remember it telling me through the years that various setup and deployment project types are no longer supported. I still have many projects that have ToolsVersion 12 or 4.0 and the corresponding old targets, despite being opened in VS 2017 (ToolsVersion 15) and changed to use 4.5.2 or 4.6.2 framework. 

Can the upgrade be triggered, or do I have to hand edit every project file to bring it up to the correct tooling level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f92ef18-cced-6d73-ce8f-741b3487100b
* Version Independent ID: 2550cbd9-41b4-ab4e-7836-a3889dd8396e
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/upgrading-projects)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/internals/upgrading-projects.md)
* Service: unspecified

**Comment by kraigb** [comment]
Apologies for the delay; I got more information from engineering a little while ago but left on a trip before I could relate it to you.

I'm answering your question generally, by the way, and not specifically for extensibility projects. 

First, any given version of VS may simply end support for certain project types. The [Platform Targeting and Compatibility](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-compatibility-vs) page indicates what project types are supported in VS 2017. If a project type isn't supported at all, then VS won't load it and doesn't offer a migration path. The only answer here is to maintain that project in a previous version that does support it.

The [Porting & Migration page](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects) also identifies what happens with different project types, both supported and unsupported.

Now then, if VS 2017 can open a project, what determines whether it's migrated? This depends on a couple of criteria:

- Compatibility with the target versions of platforms, back to VS 2013 RTM.​ 
- Compatibility of design-time assets with previous versions of VS. (Namely different channels of VS 2017; VS 2015 RTM & Update 3; VS 2013 RTM & Update 5; VS 2012 Update 4; VS 2010 SP 1.) VS 2017 aims to fail gracefully with deprecated design-time assets without corrupting them (e.g. so previous versions can still open the project).
- Whether new design time assets would break compatibility with previous versions down to VS2013 RTM & Update 5.

The engineering owner of the project type in question looks at these and makes the call where support, compatibility, and migration is concerned. 

In general, the goal is to provide transparent "round-tripping" between VS versions if possible, meaning that one can create and modify projects in one version of VS and it just works in other versions. That's the ideal user experience.

If transparent round-tripping is not possible, then VS opens the upgrade wizard to make the necessary one-way changes. [The article you were looking at originally](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/upgrading-projects) describes the extensibility interfaces that are used with custom project types (via extensions).

Those changes may involve changing the ToolsVersion in the project file, which is specifically what would render the project unbuildable by a previous version of VS. That is, what makes a project incompatible with an earlier version is not the VS version, but the MSBuild version, because that's what ultimately turns a project and source code into its runnable/deployable artifacts.

Put another way, a project, when created, is configured to build using a particular MSBuild version. So long as your version of Visual Studio contains the MSBuild toolchain that can handle that configuration, then VS can invoke that toolchain to build the project (which is the goal, right?). It's thus MSBuild that's providing the compatibility with *it's* previous versions, more so than VS providing compatibility with previous VS versions.

For more discussion, see these articles:
- [ToolsVersion guidance](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion)
- [Framework targeting guidance](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview)

What it all boils down to, as I understand it, is that the ToolsVersion isn't really all that important. That is, it's not necessary to change the ToolsVersion number in a project file to some "correct" value just because you've opened it in VS 2017 and changed a framework target. VS 2017 is perfectly happy with ToolsVersion set to 15, 14, 12, and 4 and builds accordingly, meaning that any of them are "correct" because any of them will result in a successful build. In fact, I would think that changing ToolsVersion to 15 may just generate a bunch of warnings and errors that you'd need to fix to get the project to build.

A future version of VS might, of course, decide to no longer support, say, ToolsVersion 4. If that happens, opening the project will certainly trigger the project upgrade process because ToolsVersion *must* be changed. In such a case, the subsystem for the specific project type in question will know exactly what needs to be changed and can do all of that automatically, which is exactly what happens today for various project types as described on [Porting & Migration page](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects).

Does all this make some sense?

**Comment by StingyJack** [comment]
> Does all this make some sense?

Yes, it does. And you are _awesome_ for finding this stuff and coalescing it. I was getting weird, sometimes conflicting advice about this topic before, and this clears all that up. Thank You.

**Comment by kraigb** [comment]
You're welcome. I own the Porting & Migration page myself, a subject which is occasionally shrouded in mystery. Thus I was keenly interested in knowing more myself. :) In any case, I appreciate your taking the time to ask, and for your other contributions.
