### ISSUE TITLE
How do I use the Immediate window in Visual Studio to print out Lists vertically during unit testing

### ISSUE THREAD

**Issue by sdg002** [MicrosoftDocs/visualstudio-docs#5532]
Hi All,
I have written some Python code and some unit tests. While debugging the unit tests , I felt the need to print out the content of some of the variables in the Immediate Window. This is something very commonly done in the C# world.

I found that the Immediate Window does not print out the results. 

Consider the following scenario. 
- I am debugging an unit test by launching a specific unit test from the Test Explorer.
- I have setup the break point
- The debugger nicely pauses at the break point
- I want to examine the contents of some of my variables and I open up the Immediate window and type
```
print(*somelist, sep="\n")
```
I have no idea where the output was displayed. This would not be the case if I were to debug a regular Python script via Visual Studio because there is a Console window which is showing me the formatted output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Unit test Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@sdg002 -- Saurabh, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

 cc @JoshuaPartlow for awareness
