### ISSUE TITLE
Not supported for Microsoft Professional.

### ISSUE THREAD

**Issue by jwisener** [MicrosoftDocs/visualstudio-docs#5547]
It's unfortunate Fakes on are not supported for Microsoft Professional. That puts it out of reach for smaller development shops/teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d29c9-b269-6e1f-08af-91ac135ebb1e
* Version Independent ID: cd993f76-8077-d566-4c48-0ab425c62b83
* Content: [Isolating Code Under Test with Microsoft Fakes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019)
* Content Source: [docs/test/isolating-code-under-test-with-microsoft-fakes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/isolating-code-under-test-with-microsoft-fakes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jwisener -- Jason, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
