### ISSUE TITLE
Needs update this page with VS2019 and TypeScript

### ISSUE THREAD

**Issue by kingsimba** [MicrosoftDocs/visualstudio-docs#5557]
1. 'Run tests in Visual Studio 2017' should be updated to 2019
2. The table-of-contents on the left says "Unit testing JavaScript". But the title is "Unit testing JavaScript and TypeScript in Visual Studio".
3. According to my test. Breakpoints work well in "Debug Selected Tests". So the document may not mention this as a bug.
4. For TypeScript, the test result can not show the correct file&line. It seems the source mapping is not used. Should it be mentioned in the doc? https://github.com/kingsimba/NodeJS-TypeScript-in-VS2019#testing

![file and lineno error](https://user-images.githubusercontent.com/8407634/86599344-159e7e00-bfd1-11ea-97ec-9e86eb0f1031.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32738a06-835b-5bd5-7a6c-942c681aca97
* Version Independent ID: e715d12c-a4aa-eec3-c05f-1ff6243d209b
* Content: [Unit testing JavaScript and TypeScript - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2019)
* Content Source: [docs/javascript/unit-testing-javascript-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kingsimba Thanks for your feedback! I tested this using the steps in the doc and the Mocha Unit Test File, and I get the same result. The test appears to run against the generated .js files instead of the .ts files, and reports against the .js file. This behavior might be by design, but I'm not certain. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. That will help identify whether the feature is working like this by design or is a bug.

I will make the relevant doc fixes that you pointed out, and for now at least, add a note about TypeScript behavior when running the tests.

**Comment by kingsimba** [comment]
I believe it's indeed a problem. I found a report on
https://developercommunity.visualstudio.com/content/problem/1009131/typescript-test-file-go-to-definition-f12-should-g.html
