### ISSUE TITLE
Updating Visual Studio 2019 from 16.0 to 16.6

### ISSUE THREAD

**Issue by daveime68** [MicrosoftDocs/visualstudio-docs#5576]
There is no progress indicator on the update system. Just a message "this may take a few minutes", and a spinning indicator which has currently been spinning for and hour and a half. Would including a progress indicator be SO difficult???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2019)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@daveime68 -- it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
