### ISSUE TITLE
Attribute `ConsoleToMsBuild` not shown by intellisense

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#5577]
Attribute `ConsoleToMsBuild` of `exec` task is not available in my .net core 3.0 .csproj project ?
VS2019

Means: It's not shown by intellisense, but I can set it manually.

Something with the xsd ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(http%3A%2F%2Fschemas.microsoft.com%2Fdeveloper%2Fmsbuild%2F2003%2523Exec);k(http%3A%2F%2Fschemas.microsoft.com%2Fdeveloper%2Fmsbuild%2F2003%2523Target);k(vs.xmleditor)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Legends -- thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @ghogen for awareness
