### ISSUE TITLE
Add extensibility documentation for Open Folder and Microsoft.VisualStudio.Workspace.*

### ISSUE THREAD

**Issue by vukelich** [MicrosoftDocs/visualstudio-docs#559]
The Open Folder feature released in Visual Studio 2017 is missing architectural documentation that ties together the components in the underlying Microsoft.VisualStudio.Workspace.* namespaces. Internal and external extension authors have needed individual support to understand necessary concepts in order to integrate with the new APIs. Extenders need information on how to produce and consume data and actions in this new scenario. 

Specifically, documentation is needed on the following subjects to make extension authors successful:

- FileContexts
- Indexing
- Settings
- Tasks and Launch
- Build and debugging
- Suggested patterns for code structuring
- Anti-patterns and pitfalls

**Comment by vukelich** [comment]
I think this doc(s) should be added under docs/extensibility, but I'm open to suggestions.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
