### ISSUE TITLE
How to open .slnf files with Visual Studio under macOS? 

### ISSUE THREAD

**Issue by stanimiryakimov** [MicrosoftDocs/visualstudio-docs#5597]
I didn't find a way to open .slnf files with VS under macOS. Double click results in open the .slnf file as plain text in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108b5373-83a5-8d82-0414-939b0caf2866
* Version Independent ID: 9bb010ce-5641-c2a4-ce2a-d53943ac5432
* Content: [Load a subset of projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019#feedback)
* Content Source: [docs/ide/filtered-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/filtered-solutions.md)
* Product: **visual-studio-dev16**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **stsu**

**Comment by WilliamAntonRohm** [comment]
@stanimiryakimov -- Stanimir, thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options  you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @jillre for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
