### ISSUE TITLE
Edit.SelectCurrentWord shortcut error

### ISSUE THREAD

**Issue by ponderingprogrammer** [MicrosoftDocs/visualstudio-docs#5602]
Edit.SelectCurrentWord in default settings of Visual Studio 2019 is Ctrl+Shift+W, and not Ctrl+W which is a start of a chord.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [Default keyboard shortcuts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ponderingprogrammer Thanks for letting us know; we'll check in to this and report back soon.

**Comment by TerryGLee** [comment]
@ponderingprogrammer After some research, we've discovered that this is a bug in the product rather than a problem with the documentation. The documentation is correct when it states that Ctrl+W is the keyboard shortcut for Edit.SelectCurrentWord in the text editor. 

Here are the steps that reproduce the error:

1. Bring up Tools\Options and switch to the Keyboard page
2. Set the keyboard scheme to Default and Reset it
3. Filter on Edit.Select
4. Select Edit.SelectCurrentWord
5. Note that the Shortcut at the bottom is set to Ctrl+W (Text Editor)
6. Change the Keyboard scheme to Visual Basic 6 (For instance)
7. Note that the Shortcut at the bottom changes to Ctrl+Shift+W (Text Editor)
8. Change the Keyboard scheme back to (Default)

**Expect:**
Edit.SelectCurrentWord should switch back to Ctrl+W when setting back to Default

**Current:**
Edit.SelectCurrentWord stays on Ctrl+Shift+W

So, for this specific issue, we'll pursue it internally to get the problem fixed. Should you discover further problems of this nature, please do file them by using the "[**Report a Problem**](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)" tool. Meanwhile, we'll close this (non)Docs issue, with our thanks!
