### ISSUE TITLE
Getting DDoS errors

### ISSUE THREAD

**Issue by derekgreer** [MicrosoftDocs/visualstudio-docs#5621]
I'm following the tutorial for ASP.Net Core 3.1 and getting DDoS errors for the responseString coming back from http://mywebapi/WeatherForecast.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Multicontainer tutorial using Docker Compose & ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@derekgreer -- Derek, thank you for your feedback.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
