### ISSUE TITLE
HTTPS with docker-compose and local development

### ISSUE THREAD

**Issue by BrunoGaudette** [MicrosoftDocs/visualstudio-docs#5733]
Hi,
I am pulling my hair out trying to get https working in development.

I tried this, but doesn't mention how to communicate between multiple containers. Using the container name doesn't work over https.
[https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1)

Do I have to setup a network? use alias?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Multicontainer tutorial using Docker Compose & ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@BigMorty 
You should not have to do anything special, if you are using Visual Studio, the certificates should be handled by VS.  What kind of problems are you seeing, and can you provide the code snippet where you're sending the request that's not working?

Are you using HTTPS for container-to-container communication or only for external-to-container communications?

**Comment by BrunoGaudette** [comment]
external-to-container works out of the box.

The problem is container-to-container. I am trying to setup IdentityServer4 but the redirection doesn't work.
I am getting different errors depending on the settings I change. Right now I'm at :

AuthenticationException: The remote certificate is invalid according to the validation procedure.
System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)

> HttpRequestException: The SSL connection could not be established, see inner exception.
> System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

I must admit that it is my first time playing with containers so this is all new. I'll try to upload a repo if I manage to get something clean. Right now I am at 25 different tutorials and blog posts to try to understand this.

I understand that the containers communicate by their expose port, not the post exposed on the host but I can't figure out how to configure the call between two containers.

I have my client redirecting to idsvr for auth in the configureservices like that and that's when I get the certificate error.
It works well without docker.

```csharp
public void ConfigureServices(IServiceCollection services)
{
	services.AddControllersWithViews();

	IdentityModelEventSource.ShowPII = true;

	JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

	services.AddAuthentication(options =>
	{
		options.DefaultScheme = "Cookies";
		options.DefaultChallengeScheme = "oidc";
	})
	.AddCookie("Cookies")
	.AddOpenIdConnect("oidc", options =>
	{
		options.Authority = "https://identityserver:443";

		options.ClientId = "mvc";
		options.ClientSecret = "secret";
		options.ResponseType = "code";

		options.SaveTokens = true;

		options.Scope.Add("api1");
	});
}
```

**Comment by NCarlsonMSFT** [comment]
@BrunoGaudette
The dotnet development certificate is only designed for communication between the browser and the app. It does not support communication between containers. Further due to a [bug](https://github.com/openssl/openssl/issues/1418)) in open ssl, the local development certificate can not be trusted on linux [dotnet tracking bug](https://github.com/dotnet/aspnetcore/issues/7246)

If you do need to use https between containers in local development I would recommend:
1. Create a self signed certificate to use as a root CA.
2. Export the public cert and trust it in windows and in the images [dockerfile example](https://stackoverflow.com/questions/26028971/docker-container-ssl-certificates#answer-38467061)
3. Use the above root CA to issue certificates for each service.
  If the service will only be called from another service, use the service name as the certificates subject name; if it will only be called externally (for instance from the browser), use localhost; if your service may be called from another service or the browser, you will need to use a Subject Alternative name so that the certificate can be used both for your service's DNS name and for localhost.
4. Use the per service certificates in your compose file instead of the generic development certificate.

**Comment by BrunoGaudette** [comment]
Thanks  for the answer!

I'll try setting it up.
