### ISSUE TITLE
Faulty instructions on Attach the debugger

### ISSUE THREAD

**Issue by Ricardoaraujo00** [MicrosoftDocs/visualstudio-docs#5809]
How come can we see the processes running in other machine just by pointing to ssh wit user@192.168.5.111 and not even putting a password?
How can Visual studio attach to a linux machine and see the proccesses running?
How is it supposed to see the dotnet core process running if there were no previous instructions to start any aspnet core application?

This document seems useless...
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ecc1202-a940-caa0-968f-9abfe2679d8b
* Version Independent ID: 20ed4d8d-35ff-f1fe-74e4-ce2c27bb72c8
* Content: [Remote debug .NET Core on Linux - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-dotnet-core-linux-with-ssh?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-dotnet-core-linux-with-ssh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-dotnet-core-linux-with-ssh.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Ricardoaraujo00 -- Ricardo, thank you for your questions.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- Mike, please look into this issue.

**Comment by IVTore** [comment]
How about the port requirements? Is there any?

**Comment by Mikejo5000** [comment]
@IVTore Would this help in your scenario? https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019#BKMK_Linux_Docker_Attach

**Comment by Mikejo5000** [comment]
@Ricardoaraujo00 The instructions mainly describe build/deploy configuration to support the remote debugging scenario, rather than a full set of build/deploy/start your app instructions. From your initial comments, it sounds like you didn't try out the procedure, but are pretty certain that it won't work because there is no instruction to enter a password. Is that correct? @gregg-miskelly @leslierichardson95 for input.

**Comment by gregg-miskelly** [comment]
RE: Deploying - Mike, would it make any sense to link to the instructions on publishing and deploying a .NET Core application?

RE: Password - Yes, obviously a password or authentication key file needs to be provided. Mike, if you think that makes the documentation more clear, you could certainly add an extra sentence in step 3 (ex: "If you haven't already provided credentials, you will be prompted to enter a password and/or private key file.").

RE: Docker - Mike, I am not sure how hard it would be to move, but it is a bit weird that the instructions for SSH Linux attach, and Docker Linux attach are in such different sections, and that the title of the SSH one is `Remote debug .NET Core on Linux'.

RE: Port requirements - there are no additional port requirements beyond whatever port the SSH server is running on. Personally I think this is kind of obvious -- the authentication dialog even lists the port. But it could be added.

**Comment by Mikejo5000** [comment]
@gregg-miskelly Thanks, Gregg. I'll look for a good link to .NET Core deployment. On the password, yes, that sounds good. I'll clarify.

On the location and title, yes, I can do something about this. Sounds like we should not say "Remote" in the title, because it the server might be running in a local container?

**Comment by gregg-miskelly** [comment]
I personally would think of a local container as "remote", but I can see how not everyone would, so makes sense to me. The same is true of SSH - you can use SSH to attach to a "local" WSL process. So I would be consistent between the two.

**Comment by IVTore** [comment]
Well I've tried and asked then. My deployment is on an AWS linux ubuntu running docker-compose, I can connect and attach the debugger, then the breakpoints did not work. Well I have to work both locally and remotely on that project, so. If I have to modify something in the project definitions, it should be practical. ;)

**Comment by IVTore** [comment]
Ps: remote ubuntu has dotnet installed on it. (or should I install something different into each container?)

**Comment by gregg-miskelly** [comment]
@IVTore "breakpoints don't work" has many possible causes. You can find the general troubleshooting instructions [here](https://docs.microsoft.com/en-us/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2019#:~:text=Troubleshoot%20Breakpoints%20in%20the%20Visual%20Studio%20Debugger.%2001%2F23%2F2018%3B,process%2C%20it%20will%20stay%20a%20solid%20red%20circle). 

In addition, here are some special notes for this scenario:
1. If you are building the app on Windows, make sure you are deploying the PDBs. @Mikejo5000 We should probably add this to the "Build the app on Windows..." section.
2. Make sure you either deploy debug bits (recommended) or you disable Just-My-Code and be prepared for a flaky debug experience due to optimizations. See the first bullet under [Build and deploy the application](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-dotnet-core-linux-with-ssh?view=vs-2019#build-and-deploy-the-application).

**Comment by Mikejo5000** [comment]
If there's a support issue here, we need to get this logged in the right place; please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). I'll keep this issue open for now until I get the doc issues resolved. Thanks!

**Comment by IVTore** [comment]
@gregg-miskelly  thanks for the pointers. It finally worked but in a weird way:
1 Disabling Just-My-Code did not solved (but helped the solution, I think) the problem alone.
2 I deployed the source and compiled it with docker-compose build ... Nada! Server works, attach ok, breakpoint no.
3 I compiled the source out of docker also with dotnet build... Well still no heartbeat.
4 I cleaned the local build on local docker. Weird.
5 Then attached the remote again and breakpoints worked as a charm!.
