### ISSUE TITLE
C++ EditorConfig formatting conventions not working

### ISSUE THREAD

**Issue by lichti81** [MicrosoftDocs/visualstudio-docs#5862]
I tried out the C++ EditorConfig formatting conventions.
E.g. I set `cpp_space_within_control_flow_statement_parentheses = true` for `*.cpp `file
In my visual studio setting this option is set `false`

I added now following code to a cpp file:
`if (a < b )`
After pressing CTRL +K, D the code changes to following:
`if (a < b)` (without spaces)

I'm sure that the `.editorconfig` file is used, because I tried to set a common EditorConfig option (indent_size), which takes effect.

I use latest Visual Studio Version (16.7.3) and [EditorConfig Language Service](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig) extension is installed

I also tried it with VisualStudio Code and there it also does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c294b23-74d7-45b1-370d-5ba97841baaf
* Version Independent ID: 169dc1b6-76ea-1b8d-eda3-e9925997bdc9
* Content: [C++ EditorConfig formatting conventions](https://docs.microsoft.com/en-us/visualstudio/ide/cpp-editorconfig-properties?view=vs-2019)
* Content Source: [docs/ide/cpp-editorconfig-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/cpp-editorconfig-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jureid
* Microsoft Alias: **jureid**

**Comment by WilliamAntonRohm** [comment]
@lichti81 -- thank you for your feedback.  Your issue seems to be with the product, and not with this documentation.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by lichti81** [comment]
I created a problem report [#1186683](https://developercommunity.visualstudio.com/content/problem/1186683/c-editorconfig-formatting-conventions-not-working.html)
