### ISSUE TITLE
Visual Studio Uninstall Rema retention cleanup instructions, in this article, are absolutely not useful or applicable. You need downloadable Cleanup tool! 

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/visualstudio-docs#5886]
Moving issue from [https://github.com/MicrosoftDocs/visualstudio-docs.it-it/issues/18](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/issues/18) as it's feedback for English content.

Original Italian feedback:
Questo articolo è totalmente inutile, senza inserire un link per il download di uno strumento di pulizia aggiornato (e valido anche per le versioni precedenti di Visual Studio)!
La cartella indicata nelle istruzioni fornite non è attualmente presente sul mio sistema, e non è assolutamente detto, al contempo, che un utente abbia accesso ad un pacchetto di installazione di Visual Studio al momento di dovere effettuare la pulizia di Visual Studio dal sistema.
Dovete quindi modificare questo articolo per includere una modalità di pulizia sempre funzionante per tutti gli utenti in qualsiasi situazione i loro sistemi siano.
Io mi trovo con cartelle di Visual studio versioni 10.0 e 12.0 contenenti ancora tutti i componenti, ed ho verificato che i percorsi ed componenti stessi centinaia di voci) sono linkati da voci del registro, non è possibile rimuoverle tutte a mano.
Eppure la voce di disinstallazione per entrambe le versioni non è più presente.
Non ho modo di eliminare questa porcheria dal mio sistema, e le vostre istruzioni non sono applicabili né funzionanti.
Per favore risolvete il problema, ovviamente vale sia per la versioni inglese dell'articolo che per quella italiana.

Bing Translation:
This article is totally useless, without inserting a download link for an updated cleanup tool (and also valid for previous versions of Visual Studio)!
The folder in the instructions provided is not currently present on my system, and it is absolutely not said, at the same time, that a user has access to a Visual Studio installation package when you have to clean up Visual Studio from the system.
You must then edit this article to include a working cleanup mode for all users in whatever situation their systems are.
I find myself with Visual Studio folders versions 10.0 and 12.0 still containing all components, and I have verified that the paths and components themselves hundreds of entries) are linked by registry entries, you can not remove them all by hand.
Yet the uninstall entry for both versions is no longer present.
I have no way of removing this rubbish from my system, and your instructions are neither applicable nor working.
Please solve the problem, of course it applies to both the English version of the article and the Italian version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Recommendations given to the customer in the original Italian issue. Closing out this one.

**Comment by AlbertoP64** [comment]
Hi tanks to all the helpers for their commitment (@WilliamAntonRohm @ornellaalt).
Anyway, by seeking solutions into MS and net, I had been able (with much effort) to solve my problem, even if some little annoyance remains in the system.
In the end, only remaining trouble is, Windows Update still giving me updates for a removed VS2010 sub-product (Visual studio 2010 tools for Office), all else is good (succesfully - and with much work - removed VS products).

Also to help anyone who finds itself in the same trouble I was, I list below the steps I made, the MS tools I downloaded and tested (with MS download links valid as of september 2020), and the results I've got.

[OT]: [other thread!], I ask here if someone could point me to the correct forum/thread concerning Sql Server 2012 removal problems, as I cannot remove it and trying to do it,  leaded me to rollback my Windows system, because broke it.

Thanks to all for help.

------------------ list of steps done: -------------------
a) 
https://devblogs.microsoft.com/setup/visual-studio-2010-uninstall-utility/
downloaded file:
--> VS2010_Uninstall-RTM.ENU.exe

not effective, as VS2010 actually remained after execution.

b) 
https://github.com/Microsoft/VisualStudioUninstaller/releases
downloaded file:
--> Total(Vs2013+)Uninstaller_V5.zip

Tremendously effective, as it uninstalled all related products first,
then the main product(s). It was very good and fast!

But as said, VS < 2013 gets not interested in this.

c) 
msiinv.zip
(taken from W 8.1 resource kit)

reference - Original article explaining how to use it:
"Manually remove Microsoft Visual Studio 2010 Tools for Office Runtime (x86) from x64 Win 7?"
https://social.msdn.microsoft.com/Forums/vstudio/en-US/f3cc7377-7d88-490c-95e8-79acb13b466b/manually-remove-microsoft-visual-studio-2010-tools-for-office-runtime-x86-from-x64-win-7?forum=vssetup

Expanded in a folder and used with subcommands:

1)
msiinv.exe -p > msiinv_output.txt
-> to list all the installed products on system

2)
after having analysed the document produced in previous step,
reordering and reorganizing the subproducts by strands,
I have repeatedly used the subcommand:

msiexec /x <product code>
(please keep the Clsid curly braces)
-> to remove a single product that needed to.

It helped me a lot to remove the remaining products.

It's all ok now, except that, Windows Update is still giving me
updates for a removed sub-product (Visual studio 2010 tools for Office).
Could it be needed by Office 2013? It seem strange to me.
(I have hidden the update in WU, because doing it reinstalled the same product again).
