### ISSUE TITLE
Design time debugging does not work

### ISSUE THREAD

**Issue by JochenAuinger** [MicrosoftDocs/visualstudio-docs#5945]
[Enter feedback here]
When following the steps in the description in Visual Studio Pro 2019 (.Net WPF 4.8) it just doesn´t work. I have even tried to start VS as Adminsitrator, but that still doesn´t work. Each time I have attached the debugger to the XDesProc process, I have been told, that the break points can´t be reached...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c195bbb1-22be-9da7-9792-1c829d73a21b
* Version Independent ID: 0d83875a-56c4-d897-e771-aa3ef9bf910d
* Content: [Debug at design time - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2019)
* Content Source: [docs/debugger/walkthrough-debugging-at-design-time.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-debugging-at-design-time.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@JochenAuinger -- thank you for your feedback.  This repo is solely for documentation issues, and it appears your issue is regarding product behavior.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
