### ISSUE TITLE
Debugger Visualizers all to often do not work in practice without serious error messages.

### ISSUE THREAD

**Issue by snuup** [MicrosoftDocs/visualstudio-docs#5946]
As nice as the possibility of debugger visualizers is, but there are too many obstacles in the way of getting them to work.

I ended with the same troubles as so many others: VS 2017 and 2019 display a msg box "could not load this visualizer" without any further hint about the problem. 

See here:
https://stackoverflow.com/questions/2511798/show-visualizers-error-could-not-load-this-custom-viewer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@snuup -- thank you for your feedback.  This repo is solely for documentation issues, and it appears your issue is regarding product behavior.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
