### ISSUE TITLE
Very bad example of recursion

### ISSUE THREAD

**Issue by jakubrpawlowski** [MicrosoftDocs/visualstudio-docs#596]
If you have to explain factorial to explain recursion that means example is wrong. There are so many intuitive examples you could have given but you chose to explain docs to math major instead of JS programmer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e391bc6b-eb62-016e-7a19-137f9fdcfc1b
* Version Independent ID: 4af94735-aefb-88e3-787d-6607c2c3fef3
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/advanced/recursion-javascript)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/advanced/recursion-javascript.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@bterlson for input

**Comment by bterlson** [comment]
Factorial is a canonical example when teaching recursion as far as I know. If someone wants to suggest a better alternative I'm sure we'd be open to it, but I can't come up with anything clearer off the top of my head.

**Comment by jakubrpawlowski** [comment]
```
const countDownFrom = num => {
  if (num>0) {
    console.log(num)
    return countDownFrom(num-1)
  }
}

countDownFrom(5)
```
Sorry I don't want to be rude. I'm just giving feedback that the docs should have an example that's easy to understand for everybody. Then maybe your example could go afterwards once everybody gets the initial idea.

**Comment by Aditya7861** [comment]
Yep

**Comment by bterlson** [comment]
@jakubrpawlowski do you think it's confusing that countDownFrom is not a case when you would use recursion in reality? A maximally practical and simple example seems ideal, just not sure countDownFrom fits that bill.

**Comment by 425devon** [comment]
@jakubrpawlowski great example, thanks!

**Comment by Mikejo5000** [comment]
Planning to close this unless we have a simple real-world example that I can add to the docs.

**Comment by Mikejo5000** [comment]
This issue is captured in a work item for our backlog.

**Comment by AWulkan** [comment]
Even though I personally don't factorial stuff very difficult, it can definitely be for many that are young or just getting into programming. I know that I've gotten stuck a lot of times trying to decipher walls of code from Microsoft documentation.

@jakubrpawlowski is right. The Microsoft docs are infamous for creating very complex guides to make it more "realistic", instead of just explaining the actual functionality of something with easy examples. A countdown example is a great way of explaining recursive functions. In fact, that's what they do in many other places like in this article (https://www.sitepoint.com/recursion-functional-javascript/).

First teach the bare minimum to give the reader a basic understanding of how it works, then after that you can start giving more advanced examples.
