### ISSUE TITLE
Azure Government Work Accounts

### ISSUE THREAD

**Issue by gwturner** [MicrosoftDocs/visualstudio-docs#5988]
When will Visual Studio Subscriptions support Azure Government Azure AD work accounts? It's a security concern when users have to create a Microsoft Account (MSA) tied to their work account and/or utlize a non work account (e.g., @hotmail.com, @outlook.com, @gmail.com, etc.) to access a subscription provided by the user's organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc961a41-fb31-d3d3-307f-b80013f9267c
* Version Independent ID: f2b3f1ae-9dfc-95fd-e86d-8dd66c88c46e
* Content: [Sign in to Visual Studio Subscriptions with work or school accounts](https://docs.microsoft.com/en-us/visualstudio/subscriptions/sign-in-work)
* Content Source: [subscriptions/sign-in-work.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/sign-in-work.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
cc @evanwindom for awareness

**Comment by evanwindom** [comment]
@gwturner - This looks like a duplicate of the other issue you submitted.  As I mentioned, tenants that are using GCC High or other private Azure Active Directory (Azure AD), i.e. the non-public Azure AD services, are not supported by Visual Studio Subscription services. If your organization is using these non-public Azure AD solutions you have the following options:

1.	Change the tenant back to a public Azure AD tenant (Please note this may not be compatible with your organization’s security requirements, please consult with your organization’s internal policies before making this change)
2.	Use Microsoft Accounts (MSAs) to assign subscriptions (this may limit those individuals from linking some Visual Studio subscription functions with internal resources, depending on your organization’s policies). This solution gives your organization less control since you will not be able to close the individual Microsoft Accounts.
3.	Create a new public Azure AD tenant and create and assign users from that tenant (for Visual Studio Subscription purposes only). This options gives your organization more control.

If your organization has specific needs outside the above options please contact Microsoft support:  https://visualstudio.microsoft.com/subscriptions/support/#talktous

**Comment by evanwindom** [comment]
@please-close
