### ISSUE TITLE
Azure Government Work Accounts Support?

### ISSUE THREAD

**Issue by gwturner** [MicrosoftDocs/visualstudio-docs#5989]
Agree with this article which states "Organizations are increasingly moving to Azure AD-based identities to provide improved security and support for automated management of subscription."

Given that Microsoft understands the security and support benefits of "work accounts", when will Visual Studio Subscriptions support Azure Government Azure AD work accounts? It's a security concern when users have to create a Microsoft Account (MSA) tied to their work account and/or utilize a non work account (e.g., @hotmail.com, @outlook.com, @gmail.com, etc.) to access a subscription provided by the user's organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8a5f5e2-2957-f296-5551-750ff9d0cff1
* Version Independent ID: 88a13bf8-eddc-3e72-0c97-93d7013854ac
* Content: [How to use connected Microsoft account and Azure Active Directory identities](https://docs.microsoft.com/en-us/visualstudio/subscriptions/use-connected-identities)
* Content Source: [subscriptions/use-connected-identities.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/use-connected-identities.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
cc @evanwindom for awareness

**Comment by evanwindom** [comment]
@gwturner - Thanks for reaching out.  I apologize for the delay in responding.  

Tenants that are using GCC High or other private Azure Active Directory (Azure AD), i.e. the non-public Azure AD services, are not supported by Visual Studio Subscription services. If your organization is using these non-public Azure AD solutions you have the following options:

1.	Change the tenant back to a public Azure AD tenant (Please note this may not be compatible with your organization’s security requirements, please consult with your organization’s internal policies before making this change)
2.	Use Microsoft Accounts (MSAs) to assign subscriptions (this may limit those individuals from linking some Visual Studio subscription functions with internal resources, depending on your organization’s policies). This solution gives your organization less control since you will not be able to close the individual Microsoft Accounts.
3.	Create a new public Azure AD tenant and create and assign users from that tenant (for Visual Studio Subscription purposes only). This options gives your organization more control.

If your organization has specific needs outside the above options please contact Microsoft support:  https://visualstudio.microsoft.com/subscriptions/support/#talktous

**Comment by evanwindom** [comment]
#please-close
