### ISSUE TITLE
Outdated versions of the framework

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#599]
Missing the newer versions and out-of-support versions are still listed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@mairaw Removing references to 4, 4.5, 4.5.1. Adding references for 4.6.1, 4.6.2, 4.7, 4.7.1. Is that correct?

**Comment by mairaw** [comment]
@preetikr @vivmishra any thoughts on this? Should we exclude out of support versions like 2.0 and 3.0 as well?

It also seems to be missing the x64 platform. Not sure if it's missing any other.

When I change the target platform, it seems to set a property named PlatformTarget and not just Platform.

These are some things that I noticed.

**Comment by Mikejo5000** [comment]
@rainersigwald Poking around, should this doc use PlatformTarget instead of Platform? The former applies to the project, and the latter to the solution? Or would either work in this example?

**Comment by rainersigwald** [comment]
@Mikejo5000 VS sets `PlatformTarget` and that's what gets [passed to the compiler](https://github.com/dotnet/roslyn/blob/d86b98d0153b501291f5c0572485f669634feb00/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L97) so it's probably best to have the docs refer to it here.

Setting `Platform` usually works, because the (non-SDK-style) templates do something like:

```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```

So setting `Platform` above that opts into the correct `PlatformTarget`. So it's not so much that `Platform` is a solution-level concept as that it's a higher-level concept usually set at the solution level. But that's extremely subtle and probably not important.

**Comment by Mikejo5000** [comment]
@rainersigwald OK, thanks! I'll make that change.
