### ISSUE TITLE
Azure Government Work Accounts

### ISSUE THREAD

**Issue by mikecassidy** [MicrosoftDocs/visualstudio-docs#5990]
Azure Gov users need the ability to use their work account to assess Visual Studio and not create or use a personal account to manage Visual Studio Subscriptions.

**Comment by WilliamAntonRohm** [comment]
cc @evanwindom for awareness

**Comment by evanwindom** [comment]
@mikecassidy - Thanks for reaching out.  I apologize for the delay in responding.  

Tenants that are using GCC High or other private Azure Active Directory (Azure AD), i.e. the non-public Azure AD services, are not supported by Visual Studio Subscription services. If your organization is using these non-public Azure AD solutions you have the following options:

1.	Change the tenant back to a public Azure AD tenant (Please note this may not be compatible with your organization’s security requirements, please consult with your organization’s internal policies before making this change)
2.	Use Microsoft Accounts (MSAs) to assign subscriptions (this may limit those individuals from linking some Visual Studio subscription functions with internal resources, depending on your organization’s policies). This solution gives your organization less control since you will not be able to close the individual Microsoft Accounts.
3.	Create a new public Azure AD tenant and create and assign users from that tenant (for Visual Studio Subscription purposes only). This options gives your organization more control.

If your organization has specific needs outside the above options please contact Microsoft support:  https://visualstudio.microsoft.com/subscriptions/support/#talktous

**Comment by evanwindom** [comment]
#please-close
