### ISSUE TITLE
Add a section for employees to activate their msdn subscription

### ISSUE THREAD

**Issue by vishalkumarsa** [MicrosoftDocs/visualstudio-docs#605]
I found it time consuming to figure this out, I suggest adding a section for internal employees where we can outline details to go to within VS **help -> about visual studio -> license status -> check for an updated license**, this automatically links to employees' msdn visual studio subscription when logged in with msft account. If this is documented somewhere, please ignore

**Comment by gewarren** [comment]
@TerryGLee can you look at this and see what you think? I'm not sure such information belongs on docs.microsoft.com though.

**Comment by TerryGLee** [comment]
@vishalkumarsa I don't think that adding content that specifically addresses internal employees is appropriate for a public-facing site. 

That being said, we do have a page that covers this: [How to unlock Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-unlock-visual-studio). The "To unlock Visual Studio using an online subscription" section gets you to the same dialog box that you describe, albeit by a different means. (Rather than using Help > About Visual Studio, it takes you to the same screen by using File > Account Settings.)

We could possibly mention the "Check for an updated license" link on this page, but it might be best handled by the content that's in our Subscription node, here: [https://docs.microsoft.com/en-us/visualstudio/subscriptions/](https://docs.microsoft.com/en-us/visualstudio/subscriptions/). And in fact, this page might be the most useful to you: [https://docs.microsoft.com/en-us/visualstudio/subscriptions/using-the-subscriber-portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/using-the-subscriber-portal).

**Comment by vishalkumarsa** [comment]
Thank you for the clarification. It was just a suggestion, and I guess it
makes more sense to do it your way.

Warm Regards,
Vishal
