### ISSUE TITLE
Missing documentaton for EditorConfigFiles propperty.

### ISSUE THREAD

**Issue by JimBobSquarePants** [MicrosoftDocs/visualstudio-docs#6051]
As of Visual Studio 16.7 the `EditorConfigFiles` property is supported in project files. 

See https://twitter.com/davkean/status/1296314723512639490/

```xml
<EditorConfigFiles Include="..\..\linting\.editorconfig" Link=".editorconfig"/>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
Hey! This appears to be a new MSBuild property that was added and needs to be documented. Adding @baronfel who is the PM on MSBuild.

**Comment by baronfel** [comment]
While this is an MSBuild Item, it looks like it's been defined by the Roslyn targets as an input for the C# and VB compilers:

* [C# Usage](https://github.com/dotnet/roslyn/blob/079474b518dc3684408b1d3f848113d901b0b0c9/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L80)
* [VB Usage](https://github.com/dotnet/roslyn/blob/079474b518dc3684408b1d3f848113d901b0b0c9/src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets#L46)

I think the documentation might be better placed on the `Compiler Options` sections for those compilers:
* [C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/)
* [VB](https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/command-line-compiler/) maybe?

**Comment by baronfel** [comment]
After speaking with @jmarolf we do think the compiler options pages are the proper place for this, but we need to detail the use case between this property (which we don't think people should use anymore) and the global analyzer config property (which we recommend instead)

**Comment by DAud-IcI** [comment]
I have a use-case: we want a single repository of shared config files that other repositories can reference. So put all the config files in a single git repository and import that either via git submodules (for internal projects) or as a NuGet package (for some client projects where they don't want to deal with git submodules).

We already have a props file that adds other configurations like StyleCop and SonarLint, I figure we can add `EditorConfigFiles` to that. (I'm not sure if this is the correct use of EditorConfigFiles as it's not documented, but I guess it'd work like this.)
```xml
  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)SonarLint.xml" Link="SonarLint.xml" />
    <EditorConfigFiles Include="$(MSBuildThisFileDirectory).editorconfig" Link=".editorconfig"/>
  </ItemGroup>
```
Currently we copy the _.editorconfig_ into the importing project's file
```xml
  <Target Name="Copy editorconfig" AfterTargets="AfterResolveReferences" Condition="'$(SolutionDir)' != '*Undefined*'">
    <Copy SourceFiles="$(MSBuildThisFileDirectory).editorconfig" DestinationFolder="$(SolutionDir)" SkipUnchangedFiles="true" />
  </Target>
```
and add it to the importing repository's _.gitignore_ because it's treated like a generated file.

You mentioned the global analyzer config property as a recommended alternative, would that be a better fit for this use-case as well?

**Comment by WilliamAntonRohm** [comment]
@DAud-IcI -- Dávid, thank you for your follow-up.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

**Comment by DAud-IcI** [comment]
@WilliamAntonRohm I was under the impression, that @baronfel asked for real-life use-cases before this property can get a documentation because they think it's not useful. If I misunderstood what they wrote, that's fine, but sending me away to ask the community forums about an undocumented feature seems somewhat inappropriate.

**Comment by JimBobSquarePants** [comment]
Bad bot! A lack of action from the documentation owners does not a stale issue make. I'm not making a duplicate of a perfectly valid, relevant and open issue.

**Comment by Piedone** [comment]
Aggressively closing otherwise valid issues because it didn't get attention from maintainers nor have people been spamming "Yes, this is still an issue." seems to me something that discourages community participation.

So, let me add it: this is still an issue. This issue here is what comes up first when you search for "csproj EditorConfigFiles". I don't see any official documentation still. And what @DAud-IcI commented above is still relevant: is this actually a property we should use? Or only `.globalconfig` files?

**Comment by BenedekFarkas** [comment]
> Aggressively closing otherwise valid issues because it didn't get attention from maintainers nor have people been spamming "Yes, this is still an issue." seems to me something that discourages community participation.

And (speaking from experience) it becomes a nightmare to investigate and properly learn from a problem a few months (or even years) down the line, because you need to comb through multiple iterations of the same issue, where some or most of the discussion had to be repeated.

**Comment by TheXenocide** [comment]
Just want to add that ideally this functionality would work for things besides the compiler itself (code analyzers) since there are a lot of style conformity features that we would want Visual Studio/VS Code to enforce (tabs v space, how many spaces, new lines before braces, etc.) within the context of the project using this item type and it is unclear what the supported/expected behavior should be here.
