### ISSUE TITLE
This still needs an offline installer

### ISSUE THREAD

**Issue by kcwilsonii** [MicrosoftDocs/visualstudio-docs#607]
Contrary to popular belief many people are still struggling with datacaps on the Internet due to greedy corporations that want charge you for data usage on the internet. A complete download would at least allow me to download once somewhere else and then bring it home to install as a full download of Visual studio is larger than my datacap. Suddenly a "free" download would cost me a $1000.00 in overage fees due to archaic internet standards still be held by many large corporations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@kcwilsonii Thanks for your feedback! We'll pass this along to the product team, but please be advised that this specific GitHub Issues page is meant for feedback on our documentation. If you'd like to give feedback on the product itself, our [Talk to Us](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) page includes more information about how best to do so.

**Comment by kcwilsonii** [comment]
I ended up having to use the layout option, which seems to work, 

so go here
https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network

download the bootstrapper you need, I downloaded vs_community.exe

You need to read ahead a bit but this option allows you to pick all the features you want
in one go and copy those files to the layout directory

vs_community.exe --layout c:\vs2017layout --lang en-US

You can then run the install from that local directory running setup (vs_setup.exe) or the community one (vs_Commmunity.exe) and it will not download using the internet. There is some minimal internet usage while doing this.

I was able to copy the final layout directory to a portable drive and run the install from their on the other computers. This worked best for me due to my ongoing problem with ATT and datacaps interfering with using the internet.

**Comment by nagaraj-analytics** [comment]
this is disgusting.... not sure what is the issue for releasing .iso file installer?

**Comment by kishorerv** [comment]
Our company does not allow Dev server connecting to Internet. Everything should be offline. So download the whole package, then notify security for scan and clearance. Install it on the server and Develop applications. As Microsoft is pain for Developers may be time to go out for other platform.

**Comment by zlb-weduc** [comment]
I'm sorry but this is ludicrous.

I still don’t understand why there are no ISO’s that include the most common components for a .net and C++ Windows development system.

This will take me days to download at home. I need to download it at work and then transfer from there. Just because I’m a developer, doesn’t mean I want to faff around with command line tools to complete simple tasks.

**Comment by TerryGLee** [comment]
We appreciate your continued feedback, and will respond soon.

**Comment by tedvz** [comment]
Thank you for the feedback.  We appreciate hearing about these various pain points so we can consider alternatives in the future.  Here's our current reasoning on the topic of ISO images.

1. Visual Studio 2017 is a huge product, because we support so many types of development: from Android to UWP to C++ to Unity to Linux. If we were to still offer a 'full' install, it would come in at over 50GB. That's one huge ISO image! 

2. We surveyed hundreds of people during the previews and RCs, and people told us that they had historically used an ISO for two reasons: 
(i)	because they wanted to download once and create a network install for enterprise deployment;
(ii)	because they had a shaky internet connection and wanted to be sure they'd downloaded successfully before installing. A single monolithic ISO isn't the best solution for either of those scenarios - it's just the one that people are habituated to over all these years. 

3. For the former (enterprise deployment), we have a full administrators' guide that provides detailed guidance on how to deploy the product: https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-administrator-guide. This includes PowerShell scripts, examples of using the installer to create and update a network cache, descriptions of how to deploy Visual Studio in a fully offline environment, and so on.

4. For the latter, we've worked really hard to improve the robustness of the installer. The componentization work we've done means that the smallest install is one-tenth the size of Visual Studio 2015, making it far more likely to succeed. And other typical installs are smaller too. We download VS in small packages that are more likely to succeed, and we use multiple ways (WebClient, BITS, WinInet) to download those files to minimize problems with AV and proxy software. If you want to download first then install, you can cache the components locally and then install from there. 

5. Because of the nature of our product (rapidly updating, lots of third-party components), an ISO is problematic. We don't have the rights to redistribute several large components (including Android), and others update on a rapid cadence that often includes critical security fixes, meaning an ISO image is incomplete, often outdated, and potentially insecure. Most customers assume that an ISO would support offline installation, but that's not true. And so we fear that offering an ISO will just be creating more disappointment. 

Lastly, we're continuing to listen. We’ve made lots of changes in for 15.2 and 15.3 to further improve the enterprise deployment scenario, we’re adding lots of new documentation to the administrator guide to address specific scenarios (e.g. ‘pushing’ updates, deployment via SCCM), and we’re continuing to explore other options, up to and including bringing the ISO image back.

**Comment by JiraiyaO** [comment]
I see your points there tedvz, but there are some holes in there. For instance, the reason the full install is so large is due to all the additional optional features that you have to tick to install in the web installer, so why include all those in one ISO when they're optional in the web installer? It would make more sense to have the core application in its own separate ISO and have the additional options downloadable separately for those who want to add that functionality.

As already stated, not everyone has good internet. I live in a country where a descent connection is quite costly and not even available where I live, but I'm still better off as I have ok, but mostly unreliable, mobile broadband. The fact that my internet is unreliable, and the tiny monthly cap (a lot of which is used up by Windows 10 without consent or any warning at all despite my best efforts to try and limit such usage) is way too small. So offline installers offer far more than just what has already been stated, their conveniece help out a lot of people, those with not-so-good internet and those completely without. I think the assumption that every Windows user can afford to download tens of gigabytes at a whim is quite a dangerous one.

**Comment by LeeC2202** [comment]
Why not just state the real reason, which is "If we let people download an ISO, we wouldn't be able to collect the exact data about what applications they might be developing and collecting data is more important than your convenience".

VS2015 was a 3.6GB installer package, there is no way on this earth that you now need almost 15x that amount of data, for what is fundamentally the same product. That would be like installing all possible versions of Windows 7, which is just nonsense.

You build a core installer package and then people download whatever extras they require once that core has been installed. That means a single download that is guaranteed to provide a base (functional) installation. That's what Microsoft used to do, when it used to have some modicum of reputation left.

What happens if your web installer repeatedly fails to complete? You get a whole stack of half-installed files and knowing your previous mess-ups, that's only going to lead to problems. I had enough problems with a .net upgrade that screwed VS up when I installed it, then screwed even more when I rolled back to remove it. I'm still left with a VS install that locks my PC for 20 seconds while it hammers my HD to death after about 5 minutes... that never used to happen.

I think you also need to remember that the people who download these development tools, are the ones that put products in your store. If you want to drive people to other stores (and there are others) then carry on regardless. I'll stick with VS2015, I don't have time to waste jumping through your installation and download hoops.

**Comment by steampunk1** [comment]
This is the stupidest idea ever! I can appreciate what you are trying to do but I've wasted a day now trying to just repair VS2017 because the Git extension doesn't want to play nice.  Then I come here and get sent in circles! Yay! ... Not Happy... Please, Please Fix This!! An offline full installer would be nice about now.. sigh...

**Comment by mprevot** [comment]
I understand the depreciation of ISO file. Something would be neat: to create ISO **from Visual Studio Installer**, together with hash etc. This would ease the job.

**Comment by syedrashid47** [comment]
how stupid can the research team be, As tedvz mentioned, "We surveyed hundreds of people during the previews and RCs" in an ecosystem of more than a few millions your surveyed hundreds, there are more then a thousand reasons why we need ISO, 
as LeeC2202 pointed out, Create a simple core with the framework and web/forms application, and then allow additional, options to download,

**Comment by MilesGibson** [comment]
Then there are those of us with a large pipe.  Usually downloading a few gig is not a problem....  There is no reason we couldn't have a base install via .ISO, and then download additional components as required later. 
FWIW, M2CW.

**Comment by GCPD** [comment]
I would suggest that the Development team investigate system which make it easier to construct an appropriate file that has all the features they need, but most important any dependencies on those features.  There have been countless times when I have tried to build a product installation at an environment with a sensible Internet connection for use at home, [unfortunately I think my home Broadband still uses 'Carrier Pigeons',] and then when I get home and start work, find that some vital part/s are missing.  The problems in trying to correct this either take too many lost hours at home or the whole exercise has to be abandoned until I can gain access to the good Internet environment. Note this is not a problem exclusive to Microsoft by any means.  Companies have got to remember that not everybody has perfect or even any access to the Internet.  I know that this is a site to do with Documentation and here is the other problem when it is only available in HTML format and not  PDF or similar. It is quite time consuming extracting HTML to a form that can be sensibly printed for off-line reading.
