### ISSUE TITLE
Explanation of debugging a Workflow does not seem to match

### ISSUE THREAD

**Issue by ole1986** [MicrosoftDocs/visualstudio-docs#6081]
To be honest I have read all the notes and I am aware of such. But still debugging a workflow does not work for me using Visual Studio 2019 (Version 16.7.7)

An example of my Workflow setup using MEF to load it as additional assembly can be found here:
https://github.com/ole1986/TestWF

Breakpoint is function inside custom CodeActivity in code-behind, but adding breakpoints to designer simply has no effect.

Ping Back: https://stackoverflow.com/questions/64765201/how-to-debug-workflow-foundation-with-mef-using-visual-studio-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6351584-90d3-fb0b-469e-d790d3a822b7
* Version Independent ID: ca652088-f01d-454b-484f-d7a4b8e6028d
* Content: [Workflow Designer - How to: Set Breakpoints in Workflows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/workflow-designer/how-to-set-breakpoints-in-workflows?view=vs-2019)
* Content Source: [docs/workflow-designer/how-to-set-breakpoints-in-workflows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/workflow-designer/how-to-set-breakpoints-in-workflows.md)
* Product: **visual-studio-windows**
* Technology: **vs-workflow-designer**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ole1986 -- Ole, thank you for your feedback and research.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio) 

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
