### ISSUE TITLE
"Migration" option is not an actual migration option, please make a migration possible!

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/visualstudio-docs#6113]
You mention the option to "migrate" an existing tenant to the M365 licensing. This is *not* a migration option but simply recreating the tenant. When is an actual migration option coming? Still waiting to apply a Microsoft 365 license to my existing (O365 Developer) tenant...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [Microsoft 365 developer subscriptions in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@jotheman0303 -- thank you for your feedback.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@jotheman0303 - Thanks for reaching out.  The terms of the offer and the behavior of the tenant are determined by the Office team.  I checked with them, and you do need to create a new tenant because of the way free offers like this are set up.  To my knowledge, there are no immediate plans to change how this works, but if it does change we will update the article.

**Comment by evanwindom** [comment]
@please-close

**Comment by evanwindom** [comment]
#please-close
