### ISSUE TITLE
This is not working with VS 2017 + .Net Core/Standard

### ISSUE THREAD

**Issue by laszlohorvath** [MicrosoftDocs/visualstudio-docs#615]
It is very sad that I feel that I can not rely on official documentation anymore. I'm porting a lot of stuff into VS 2017-.NET Standard/Core Environment, and I'm constantly blocked by undocumented obstacles. For example, there is no IWizard interface at all in VS 2017. These assemblies are not available for VS 2017. But ok we can find it manualy in the GAC, and we can add it as a direct reference. However, I have stopped here. The whole concept of GAC is lost at this point. And maybe it wouldn't work at runtime, but I don't want to wste time on things that clearly differs from the documentation.

But you should clearly point it out (at least at the start, or where you list migrations steps) that this not works with .NET Standard, or .NET Core at all. It would be an important information for everyone to spare some time on this, because it won't work. If you reference a Core/Standard project from these kind of wizards, it won't build.

It would be a minimum to state for all pages that are only for .NetFx, and not for Core/Standard. Would save a lot of time for the developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Service: unspecified

**Comment by gregvanl** [comment]
Hi @laszlohorvath Sorry to hear you are having difficulties. IWizard is available in VS 2017. You can find it in the shipped Microsoft.VisualStudio.TemplateWizardInterface assembly located under Common\IDE\PublicAssemblies. You can add a reference to IWizard by searching for "TemplateWizard" in the project Add Reference dialog.
It is true the IWizard interface is missing from the docs.microsoft.com/dotnet/api and we'll soon correct this oversight. The MSDN documentation for IWizard is still valid.
In general, VS Extensibility is only available for .NET Standard since Visual Studio itself only runs on .NET Standard.
