### ISSUE TITLE
Has the VSTO runtime 2010 reached end-of-life?

### ISSUE THREAD

**Issue by Sephizor** [MicrosoftDocs/visualstudio-docs#6168]
Hi,

After reaching out to support contacts at Microsoft, I have been told that the VSTO runtime 2010 has reached end-of-life as of July 14th 2020, and is no longer supported. All of the pages relating to VSTO add-in development still reference this runtime as being the version that should be used and there is no indication of an upgrade path. I am building a Word add-in project that is already in a Visual Studio 2019 solution but when run without the VSTO runtime in Word 2019, it results in a COM Exception. This seems to suggest that the runtime is still required for the latest version of Word.

Can anyone shed some light on this?

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 452374f5-e8d0-37e6-558d-c44c3926fec4
* Version Independent ID: 8f3cb5a2-ed9e-3c10-a507-6a9e3bc0588e
* Content: [How to: Install the Visual Studio Tools for Office runtime redistributable](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2019)
* Content Source: [docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@Sephizor the VSTO 2010 runtime is still supported.  I'm sorry you were told differently.  

It ships with Visual Studio 2019 and Office 2019 and will follow the support lifecycle of these products.

**Comment by Sephizor** [comment]
@John-Hart Thanks for the incredibly prompt response! We'll inform our customers that they have no need to worry 👍

**Comment by rfresh** [comment]
@John-Hart Please could you direct me to a page where the official support lifecycle for VSTO 2010 is published? 

We have customers who are unwilling to install our software as they are convinced that it is now out of support. They reference the following page - https://docs.microsoft.com/en-us/lifecycle/products/visual-studio-2010 - and claim that it has been out of support since July since the page references "Tools for Office System 4.0 Runtime". We actually got this same message from Microsoft support when we contacted them, so there does seem to be some confusion that would benefit from an officially published reference page.

**Comment by John-Hart** [comment]
Here's the support information for Visual Studio 2019 and Office 2019.   These do not specifically mention the VSTO runtime but since VSTO runtime ships with both of these products it will follow the support lifecycle of these products. 

I've also included the Visual Studio lifecycle page that mentions VS 2010 support in connection with VSTO.

https://docs.microsoft.com/en-us/lifecycle/products/microsoft-office-2019
https://docs.microsoft.com/en-us/lifecycle/products/visual-studio-2019
https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing#microsoft-visual-c-redistributable
