### ISSUE TITLE
Change textBox1 leave event to TextChanged event

### ISSUE THREAD

**Issue by aBrokenDonut** [MicrosoftDocs/visualstudio-docs#625]
It is quite impossible to leave the focus of the textbox on MyUserControl .

For the tutorial sake, i would advise to change it to TextChanged event instead of let people wonder why the property is not saved to disk.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0d7a70e9-8bed-6595-ac09-852b47459ac1
* Version Independent ID: 180b6f77-7ef2-a8e1-83f9-18d8d5127f75
* [Content](https://docs.microsoft.com/nl-nl/visualstudio/extensibility/creating-an-options-page)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/creating-an-options-page.md)
* Service: unspecified

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
