### ISSUE TITLE
Creation of New Build Platforms....

### ISSUE THREAD

**Issue by DynConcepts** [MicrosoftDocs/visualstudio-docs#6379]
[Enter feedback here]
PAge does not include any information on how to create NEW Platforms....   Perhaps for a dedicated processor type...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8b801b-785b-f43a-94be-2b5691c20ae6
* Version Independent ID: 275d2129-4c31-030f-b6bb-6fa7b90909ca
* Content: [Understand build platforms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/understanding-build-platforms?view=vs-2019)
* Content Source: [docs/ide/understanding-build-platforms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/understanding-build-platforms.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@DynConcepts -- David, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this issue.

**Comment by dcorbin-wintellect** [comment]
Looks like my previous comment got lost.....   None of the Microsoft Documentation I have found provides information about new Build PLATFORMS.... For example, let's presume I want to use Visual Studio to target my classic DEC PDP-11. I have command line compilers and other tools needed, but want to "**I**ntegrate them into the **D**evelopment **E**nvironment" of Visual Studio...

If this is possible, where is the documentation?  If this is not possible/not supported, where is that located in the documentation?

Perhaps the Visual Studio documentation should suggest using VS-Code rather than VS-2022???? [If so where is *that* documentation?
