### ISSUE TITLE
Visual Studio and New Project Platforms...

### ISSUE THREAD

**Issue by DynConcepts** [MicrosoftDocs/visualstudio-docs#6387]
[Enter feedback here]
This page has been repeatedly a landing point for searches about how to create a NEW platform, yet there is no information on that....

I would expect this to at least include a link to material (which I can not find anywhere) about that subject...  Perhaps I want to target my code to an old PDP-11 platform? What is the procedure (with examples, step by step) for accomplishing this...

If memory serves this content was on MSDN all the way back when MSDN was on DVD (and perhaps even during the CD error)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8b801b-785b-f43a-94be-2b5691c20ae6
* Version Independent ID: 275d2129-4c31-030f-b6bb-6fa7b90909ca
* Content: [Understand build platforms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/understanding-build-platforms?view=vs-2019)
* Content Source: [docs/ide/understanding-build-platforms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/understanding-build-platforms.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@DynConcepts -- David, thank you for your feedback.  We had a PDP-11/70 in college, a solid beast.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this issue.

**Comment by dcorbin-wintellect** [comment]
As of this point, I still have not seen any documentation [aka content at docs.microsoft.com] on how to create a brand new platform... Not x86, not x64, not ARM, something totally new, and have it registered with Visual Studio so that the "right thing" can be done to build code for that platform (and yes, this would include being able to integrate the right compilers/tools, transform the settings all of that...

**Comment by ghogen** [comment]
@dcorbin-wintellect 
@DynConcepts 
I understand the scenario. The request falls into the category of Extensibility, and it is certainly possible with Visual Studio to create extensions that support custom platforms and their associated tool chains.  I don't see a good sample or walkthrough that covers this end-to-end.

I think there are two parts to this Part one is creating the MSBuild infrastructure to support builds for the architecture/platform. You need custom Task (see https://docs.microsoft.com/en-us/visualstudio/msbuild/task-writing?view=vs-2022 ) created for all the relevant tools in the tool chain, then targets created that call the necessary tasks for the required outputs. The targets would be defined in ".targets" files similar to the ones in the .NET and C++ build systems distributed with Visual Studio.  Once everything is working for command-line MSBuild invocations on your custom project files, part two is to write the Visual Studio IDE integration by creating a custom project system. This what the C++ team in VS did to create the C++ MSBuild-based build system. You can read about that here: https://docs.microsoft.com/en-us/visualstudio/extensibility/visual-cpp-project-extensibility?view=vs-2022. For the C++ project system, the platform is extensible by providing the appropriate MSBuild support files (defining the properties, targets, tasks relevant to the platform) in a particular folder.  Your custom system would define an equivalent and the $(Platform) property value, with say "PDP-11" as the value, be used as input to the tasks that wrap the PDP-11 build tools, so that the right command lines could be generated. 

https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-reference-cpp?view=msvc-170
https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-visual-cpp-overview?view=msvc-170

What language will users be writing the code in that will be compiled to this new platform architecture? If they're using C or C++, or even assembler I suppose, you can leverage the existing C++ build system infrastructure (the targets files, etc.) and add the platform-specific files as appropriate as a new folder under $(VCTargetsPath)/Platforms as described in https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-reference-cpp?view=msvc-170

**Comment by ghogen** [comment]
Closing this as a doc issue for this page, in reference to the information provided in other places.
