### ISSUE TITLE
connect R with mdf file

### ISSUE THREAD

**Issue by RawanRadi** [MicrosoftDocs/visualstudio-docs#639]
It's possible to connect R to mdf file? (sql server mdf file)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ee57e7-f1a1-3ea5-b188-41af8106ac92
* Version Independent ID: 08a2d04e-9ac5-ca1e-49fa-3441ea39b672
* [Content](https://docs.microsoft.com/en-us/visualstudio/rtvs/integrating-sql-server-with-r)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/rtvs/integrating-sql-server-with-r.md)
* Service: unspecified

**Comment by kraigb** [comment]
In the "Add a database connection" section, the Connection Properties dialog has an option for "Attach a database file" which might do what you want.

@jflam Can you comment on this option?

**Comment by RawanRadi** [comment]
yes , I tried it many times but  the connection filed

**Comment by jflam** [comment]
How did the connection fail? What was the error message?

**Comment by kraigb** [comment]
@RawanRadi Any further input here? If it's no longer an issue then we can close the issue.

**Comment by RawanRadi** [comment]
yes this error message 
![r](https://user-images.githubusercontent.com/30637049/37424573-d51927f2-27d1-11e8-8edb-daa6b1e33a2e.png)

**Comment by kraigb** [comment]
@jflam Any comments?

**Comment by kraigb** [comment]
@RawanRadi On further investigation, this appears to be a product bug. In that case, please file an issue on https://github.com/Microsoft/rtvs/issues so the engineering team can follow up with you directly. When creating the issue, include a link to this present issue, https://github.com/MicrosoftDocs/visualstudio-docs/issues/639.

Thanks. In the meantime, I'm closing this issue here in the docs repo.
