### ISSUE TITLE
Package Caches and Offline Installs

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/visualstudio-docs#6400]
If I create an offline installation layout using only a few selected workloads and then install these same workloads from that layout with either the `--Cache` or `--NoCache` options along with the `--NoWeb` option, would caching to a different directory still take place **OR** would _neither_ of the cache options, including `--Path Cache="{ProgramPath}"`, even apply to offline layout installs?

In addition, does specifying `--NoWeb` for an install from an offline layout simply disable the package caching altogether as well, thereby causing those other cache options to be ignored if they are specified?

And also, if the cache options still _do_ apply to installs from an offline layout _without_ the use of `--NoWeb`, would specifying `--NoCache` for such an install actually delete the contents of the offline layout (which I do not want to happen) as it would still be considered cached data?

If you could please list the answer in the document that would greatly be appreciated in order to avoid confusion.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@VikingByNature -- Collin, thank you for your questions.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

@ornellaalt -- Ornella, please look into this issue.

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by christineruana** [comment]
Hi @VikingByNature Collin,   

I'm just now seeing your questions that you submitted quite a while ago.  Please be advised that I made a significant overhaul to all the offline layout documentation a couple months ago, so hopefully that clarifies some of your questions.  It used to be the case that with the installer that shipped in VS 2019 and below, it didn't really support the idea of having layouts in different directories, but we addressed this in the VS 2022 installer which released in Nov 2021.  Furthermore, the --noWeb parameter is really intended to be used on the client to prevent the client from reaching out to the internet to acquire bits.  --noWeb is not really relevant in scenarios where you're trying to manage the layout.  

Can you please review the updated online documentation regarding offline layouts (links below), and let me know if you have any further questions?  If you do have a question, please also try to frame it in the context of both what you're trying to achieve as well as how you're trying to achieve it, because we might have a solution for you that may not be down the same implementation path that you went down.  

https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio
https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio

Thanks,  Christine

**Comment by christineruana** [comment]
#reassign: @christineruana

**Comment by christineruana** [comment]
We don't need to keep this open any longer.  Hopefully my answer above works for @VikingByNature and if not, please feel free to re-open or start another issue. 

#please-close
