### ISSUE TITLE
git checkout <commit>

### ISSUE THREAD

**Issue by extensibleseth** [MicrosoftDocs/visualstudio-docs#6415]
Please document the process to checkout a commit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by extensibleseth** [comment]
Thanks @TerryGLee. I appreciate your time.

That page doesn't document the process to check out a commit. I'm looking for an equivalent for  `git checkout commithash`. 

https://docs.microsoft.com/en-us/visualstudio/ide/git-team-explorer-feature-comparison?view=vs-2019#git-changes

**Comment by TerryGLee** [comment]
@extensibleseth Thanks for clarifying. I'll re-open the issue.
@prnadago @Taysser-Gherfal FYI on this request.

**Comment by extensibleseth** [comment]
It occurred to me that if VS doesn't do checkout, a workflow to achieve the same would suffice. Something like creating new branches for the commits you'd like to checkout.

**Comment by TerryGLee** [comment]
@extensibleseth We have new documentation published that covers Git in Visual Studio more extensively. Please check out our landing page at for more details. (In specific, the "Repo management" section might include the info you're seeking.)

**Comment by extensibleseth** [comment]
Thanks again @TerryGLee.

'master' branch ought to be 'main' in the examples.

Please include a note on how to create a new branch from the selected commit on this page, "Browse Git repositories in Visual Studio" - https://docs.microsoft.com/en-us/visualstudio/version-control/git-browse-repository?view=vs-2022.

**Comment by TerryGLee** [comment]
@extensibleseth Thanks for your reply; we'll look into this and report back soon. 
@Taysser-Gherfal FYI

**Comment by TerryGLee** [comment]
#sign-off

**Comment by TerryGLee** [comment]
@extensibleseth We've updated the [Browse Git repositories in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-browse-repository?view=vs-2022) page to include the information you requested; specifically, we added a new [**Create a branch from a commit**](https://docs.microsoft.com/en-us/visualstudio/version-control/git-browse-repository?view=vs-2022#create-a-branch-from-a-commit) section to it. We also added a link to a blog post that outlines new functionality that's currently in Preview, so that you can see what's coming soon. (FYI: after the Preview is released to GA, we'll update the Docs.) Meanwhile, we'll close this issue now, with our thanks to you for helping improve the documentation!
