### ISSUE TITLE
Breakpoint on class

### ISSUE THREAD

**Issue by Planche95** [MicrosoftDocs/visualstudio-docs#642]
Hi!

Is there a possibility to easily set a breakpoints on all function in class in c#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919f11c1-eae7-8c9f-8968-911824ab81e2
* Version Independent ID: 0a5dd710-97d5-ad40-fcd4-c5a7a6fe57ab
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/getting-started-with-the-debugger)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/getting-started-with-the-debugger.md)
* Service: unspecified

**Comment by StingyJack** [comment]
You can use a powershell script to insert (and remove) `Debugger.Break();` after the opening brace of each function. Its not a toggleable breakpoint but does the same., [This](https://github.com/StingyJack/Vs-Utility/blob/master/Remove-TrailingWhitespace.ps1) is a script I run from within visual studio to remove trailing whitespace at the end of lines that I invoke in one of the builtin powershell consoles and pass `$dte.ActiveDocument.FullPath` as the parameter.

You may also want to explore [this](https://docs.microsoft.com/en-us/dotnet/api/envdte.debugger.breakpoints?redirectedfrom=MSDN&view=visualstudiosdk-2017#EnvDTE_Debugger_Breakpoints) way of using $dte to set proper breakpoints, but in my experience documentation for DTE and related stuffs is hard to find or incomplete.

**Comment by Mikejo5000** [comment]
@Planche95 I don't believe there's an easy way to do that from the UI.

**Comment by StingyJack** [comment]
VS has the ExternalTools menu you can use to hook in scripts, exe's, etc. So that's kind of an easy way from the UI (easier than writing a vs extension). 

I have few currently defined, including the one i mentioned earlier. 
![image](https://user-images.githubusercontent.com/15381181/37341703-bd32e93c-2698-11e8-904e-38aa4a0032f6.png)
Define a script to run as 
![image](https://user-images.githubusercontent.com/15381181/37341723-d2ecb99c-2698-11e8-8da8-eb5ad21384ed.png)

the full command is `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`
the full args is `-command  Remove-TrailingWhitespace '$(ItemPath)'`

**Comment by Mikejo5000** [comment]
You might try StingyJack's workaround. There's no standard way to do this in the UI.
