### ISSUE TITLE
More security options is not an option

### ISSUE THREAD

**Issue by peter-bain** [MicrosoftDocs/visualstudio-docs#6430]
Unlinking GItHub account says to select _"More security options"_ but this is not an available option.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9c21c0-7587-fb94-2ef7-9abd48fcad2b
* Version Independent ID: 970392f5-4e9a-6cd9-c450-4e2e00699775
* Content: [Signing in to Visual Studio subscriptions with your GitHub account](https://docs.microsoft.com/en-us/visualstudio/subscriptions/sign-in-github)
* Content Source: [subscriptions/sign-in-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/sign-in-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@peter-bain -- thank you for your feedback.

@evanwindom -- please look into this issue.

cc @TerryGLee for awareness

**Comment by evanwindom** [comment]
@peter-bain -- Thanks for pointing this out.  It looks like the UI on the account management page has changed a little bit.  The option you're looking for if you want to unlink a GitHub account is "Advanced support options" instead of the "more support options mentioned in the FAQ.  I've submitted an appropriate change.  Thanks again for the report.

**Comment by evanwindom** [comment]
#please-close
