### ISSUE TITLE
THIS ISN"T WORKING

### ISSUE THREAD

**Issue by AriethNinja** [MicrosoftDocs/visualstudio-docs#6438]
[Enter feedback here]

I have told VS to trust my folder of pictures that i pull from

I then told VS to trust my folder where i put the pictures in my program
```css
- VS STILL DOESN"T TRUST MY PICTURES
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d756ce43-92a4-e3fc-14e5-00762c715790
* Version Independent ID: 4fdef01a-d2b2-948e-8ac8-8684b00ff729
* Content: [Trust Settings for Files and Folders - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/trust-settings?view=vs-2019)
* Content Source: [docs/ide/reference/trust-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/trust-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @2percentsilk
* Microsoft Alias: **allisb**

**Comment by TimShererWithAquent** [comment]
@AriethNinja - This looks like you've encountered an issue with the product itself, rather than the documentation. Please look here to see if anyone has raised a similar issue:

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

Please consider these resources:

- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now. You are welcome to @ mention me for any follow up.
We hope to hear from you again.
