### ISSUE TITLE
Managing Python environments in Visual Studio

### ISSUE THREAD

**Issue by ThomasVandenbon** [MicrosoftDocs/visualstudio-docs#644]
After reading the Python in Visual Studio documentation, I'm very confused as how Virtual Environments should be defined to be able to use them as a team of developers (not using GitHub for version-control).

In particular, it seems as if Virtual Environments should be created per development machine, but at the same time, the Python project directly references them, making you unable to check the project file into version-control without removing the environment.

My first guess would be that the environments shouldn't actually show up in the Python proj-file, but I might be missing something obvious.
On the other hand, I've heard that the Visual Studio Code environments work completely different, which might indicate that this is still a work-in-progress.

Could you clarify how a Python-project with Virtual Environments should be checked in to version-control?
(Also, see: [Visual Studio Python Virtual Environments in source-control](https://stackoverflow.com/questions/49040191/visual-studio-python-virtual-environments-in-source-control) for a free-bounty)

**Comment by kraigb** [comment]
@ThomasVandenbon thanks for the question.

@zooba @qubitron your thoughts? Is this primarily a matter of using requirements.txt?

**Comment by zooba** [comment]
There's certainly some work in progress around this area. We're looking at different designs here and ways to better align VS and VS Code.

For Visual Studio: the intent for virtual environments in a Python project file is that you have the environment within your project directory, so it is only referenced by a relative path. If you also keep a `requirements.txt` file in your project, it should only be a couple of clicks to recreate it on a new machine (we had considered automatic prompts to help out here, but most user feedback indicated we had other stuff to fix first).

So our broad recommendations would be:
* have the "main" virtual environment be at the default location (`env` in the project folder)
* exclude the entire environment itself from version control
* keep development requirements in a `requirements.txt` file
* recreate the virtual environment on new machines with the normal `Add Virtual Environment` command (having the default location and requirements file will make this smoothest - we'll change it from "missing" to found as soon as it's created)

Obviously feel free to vary these as they make sense. You can also have a different task create the virtual environment (e.g. a batch file that runs `python -m venv path\to\env`) and we'll still pick it up just fine without having to modify the project file.

And as we work on improvements here for the overall process, it should get easier to just have an environment "somewhere" and use it, rather than having to make specific configuration settings in your project.

**Comment by ThomasVandenbon** [comment]
Thank you very much for the clarifications.
