### ISSUE TITLE
GenerateResource Task missing parameters

### ISSUE THREAD

**Issue by atniomn** [MicrosoftDocs/visualstudio-docs#6504]
Here's the invocation I see in the latest VS 16.9 Microsoft.Common.CurrentVersion.targets:

```
    <GenerateResource
        Sources="@(EmbeddedResource)"
        UseSourcePath="$(UseSourcePath)"
        References="@(ReferencePathWithRefAssemblies)"
        UsePreserializedResources="$(GenerateResourceUsePreserializedResources)"
        AdditionalInputs="$(MSBuildAllProjects)"
        NeverLockTypeAssemblies="$(GenerateResourceNeverLockTypeAssemblies)"
        StateFile="$(IntermediateOutputPath)$(MSBuildProjectFile).GenerateResource.cache"
        StronglyTypedClassName="%(EmbeddedResource.StronglyTypedClassName)"
        StronglyTypedFileName="%(EmbeddedResource.StronglyTypedFileName)"
        StronglyTypedLanguage="%(EmbeddedResource.StronglyTypedLanguage)"
        StronglyTypedNamespace="%(EmbeddedResource.StronglyTypedNamespace)"
        StronglyTypedManifestPrefix="%(EmbeddedResource.StronglyTypedManifestPrefix)"
        PublicClass="%(EmbeddedResource.PublicClass)"
        OutputResources="@(EmbeddedResource->'$(IntermediateOutputPath)%(ManifestResourceName).resources')"
        Condition="'%(EmbeddedResource.Type)' == 'Resx' and '%(EmbeddedResource.GenerateResource)' != 'false' and '$(GenerateResourceMSBuildRuntime)' != 'CLR2'"
        SdkToolsPath="$(ResgenToolPath)"
        ExecuteAsTool="$(ResGenExecuteAsTool)"
        EnvironmentVariables="$(ResGenEnvironment)"
        MSBuildRuntime="$(GenerateResourceMSBuildRuntime)"
        MSBuildArchitecture="$(GenerateResourceMSBuildArchitecture)">
```

I don't see any documentation regarding "UsePreserializedResources"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b2f0075-0c8e-830e-666e-be5c77d35252
* Version Independent ID: b9ddf4d0-bfc2-895c-a709-bafeaaf4093c
* Content: [GenerateResource Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/generateresource-task?view=vs-2019)
* Content Source: [docs/msbuild/generateresource-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/generateresource-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/msbuild/issues/5787> has information about the GenerateResourceUsePreserializedResources property. It causes non-String resources in the `.resources` file to use a new format that does not involve BinarySerializer. This makes it possible to generate the `.resources` file with `dotnet build`, which would not be possible in the original format because many of the resource types are no longer serializable in .NET Core.

Related error messages:

- [error MSB3822: Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references.](https://docs.microsoft.com/visualstudio/msbuild/errors/msb3822?view=vs-2019)
- error MSB3823: Non-string resources require the property GenerateResourceUsePreserializedResources to be set to true.

**Comment by ghogen** [comment]
@rainersigwald

**Comment by KalleOlaviNiemitalo** [comment]
Why was this issue closed? It doesn't look like the parameter has been documented yet. Is the documentation in a private repo from which it will be published later?

**Comment by ShannonLeavitt** [comment]
@KalleOlaviNiemitalo - This PR was apparently closed because it shared a commit with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9141. 

This scenario can happen when you create a working branch from another working branch or when you leave a PR open for some time and inadvertently carry one commit into one or more PRs.

To prevent this from happening again, be diligent while managing your working branches, and be careful not to create a new working branch from another working branch--create a new working branch only when you're in the default branch.

If you want to revert the updated content in the unintentionally merged PR, you can submit a new PR.

**Comment by KalleOlaviNiemitalo** [comment]
@ShannonLeavitt, I don't understand. This is an issue, not a PR.

**Comment by rainersigwald** [comment]
@ShannonLeavitt, @KalleOlaviNiemitalo is an external community member here.

@KalleOlaviNiemitalo, as you guessed this got closed because a PR in an internal repo was checked in that will fix it once internal merges back to public and gets deployed (which is usually pretty quick but I don't fully understand the process).
