### ISSUE TITLE
Automatically remote debugger attaching support

### ISSUE THREAD

**Issue by idokka** [MicrosoftDocs/visualstudio-docs#6548]
Is there possible to automatically attach Remote Debugger like [for vsjitdebugger](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/a329t4ed(v=vs.100)?redirectedfrom=MSDN) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019#bkmk_configureService)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@idokka -- Oleksii, thank you for your question.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- Mike, please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
If you need to re-attach the debugger, you can do that easily using [Re-attach]().
If you are debugging child processes, you may be interested in the [Microsoft Child Process Debugging Power Tool](https://marketplace.visualstudio.com/items?itemName=vsdbgplat.MicrosoftChildProcessDebuggingPowerTool&ssr=false#overview). This works for Attach to Process, but it's not clear that would work for Attach to Process when using the remote debugger.

**Comment by idokka** [comment]
You didn't give an answer on the question. If attaching cannot be done **automatically**, then answer is simple "no".

**Comment by Mikejo5000** [comment]
I thought it was possible that you didn't know about re-attach and that might be helpful, but you're right, I believe the answer is no.

**Comment by Mikejo5000** [comment]
@idokka Also, If you are looking for functionality that isn’t currently provided by the product, please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.

This is also a good idea because it's always possible you will find out about some type of workaround that will enable your scenario.
