### ISSUE TITLE
Spelling checker

### ISSUE THREAD

**Issue by pi3k14** [MicrosoftDocs/visualstudio-docs#655]
Please provide some information about how to change the spelling checker to something other than English(en), and how to use several spelling checkers in the same project.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: c38ef98e-53d7-920d-c88a-eeb32a2fb0bd
* Version Independent ID: 061657aa-6026-c796-49f1-dcd344e98878
* Content: [CA2204: Literals should be spelled correctly | Microsoft Docs](https://docs.microsoft.com/nb-no/visualstudio/code-quality/ca2204-literals-should-be-spelled-correctly)
* Content Source: [docs/code-quality/ca2204-literals-should-be-spelled-correctly.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca2204-literals-should-be-spelled-correctly.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani is it possible to use a dictionary other than English for this code analysis rule?

**Comment by mavasani** [comment]
@gewarren See documentation on this here: https://blogs.msdn.microsoft.com/codeanalysis/2007/08/12/new-for-visual-studio-2008-spelling-rules. 

> how to use several spelling checkers in the same project.
This is not possible - culture is a per-project property.

Also note that we have not implemented any naming rules yet in FXCop analyzers. Primary reason being the rules are based on a non-portable MS Office spell checker library and we are still investigating any possible improvements/alternatives.

**Comment by pi3k14** [comment]
@mavasani isn't that link for different rules?
The problem is for string literals, are they handled as resource strings?

**Comment by gewarren** [comment]
@pi3k14 The LiteralsShouldBeSpelledCorrectly rule is not mentioned in the blog post that @mavasani linked to, because I assume it was added to Visual Studio at a later time. However, the same culture functionality probably applies. If you haven't explicitly [created resource strings for your literals](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-resource-files-for-desktop-apps), then I assume you'd add the <CodeAnalysisCulture> MSBuild property to your project, with a culture value of nb-no (or whatever you want it to be).

P.S. I think @mavasani meant "Roslyn analyzers" and not "FxCop analyzers" in his last paragraph?

**Comment by mavasani** [comment]
@gewarren - Yes, I meant Roslyn analyzers that port FXCop rules (we also call them FXCop analyzers for short). I did not mean the legacy FXCop rules.

**Comment by gewarren** [comment]
@pi3k14 I verified that adding the line \<CodeAnalysisCulture>nb-no</CodeAnalysisCulture> to the .csproj file silences the CA rules for incorrectly spelled literals (that aren't in a resource file). Please note that we are only able to spell-check English cultures due to licensing issues.
