### ISSUE TITLE
Not Mac Compatible

### ISSUE THREAD

**Issue by SeamusMacRat** [MicrosoftDocs/visualstudio-docs#6567]
So, why do C# devs on Macs not need code analysis tools like Maintainability? Are you saying that we are obviously so good that we don't need them? Or does your website just talk about the Windows version AGAIN?

This is what is meant when people say MONOPOLY, guys ... refusing to add tools that aren't for use on your own products.

Without saying "use a windows machine", can someone tell me how I am supposed to run these metrics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@SeamusMacRat -- Kev, thank you for your questions.  It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.


Please also consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
