### ISSUE TITLE
CODE CỦA DUONGHOANGHAI GITHUB QUẢN LÝ CỨ HỎI GITHUB

### ISSUE THREAD

**Issue by duonghoanghai** [MicrosoftDocs/visualstudio-docs#6631]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396b8809-b144-6e13-0ff3-50529985f69c
* Version Independent ID: 1c78314d-2e04-ba4f-ec56-ca5a622ac414
* Content: [Overview of GitHub Codespaces (Preview) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/codespaces/codespaces-overview?view=vs-2019)
* Content Source: [docs/ide/codespaces/codespaces-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/codespaces/codespaces-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@duonghoanghai -- Dương, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@gregvanl -- Greg, please look into this potential documentation issue.

**Comment by gregvanl** [comment]
Hi @duonghoanghai The article referenced by your issue is for a deprecated feature, using VS IDE to connect to GitHub Codespaces.
You can learn more about GitHub Codespaces and the available clients (VS Code or browser-based editor) at https://docs.github.com/github/developing-online-with-codespaces/about-codespaces.
I hope that documentation link is helpful for you.
