### ISSUE TITLE
offline installer

### ISSUE THREAD

**Issue by nagaraj-analytics** [MicrosoftDocs/visualstudio-docs#666]
Not what is the issue to release .iso file? this is disgusting and wasting most of our times.

**Comment by TerryGLee** [comment]
@nagaraj-analytics Thanks for your feedback. We understand your frustration about the lack of an ISO for Visual Studio. Here's a little more information about ISOs that you might find useful.

1. Visual Studio 2017 is a huge product, because we support so many types of development: from Android to UWP to C++ to Unity to Linux. If we were to still offer a 'full' install, it would come in at over 50GB. That's one huge ISO image! 

2. We surveyed hundreds of people during the previews and RCs, and people told us that they had historically used an ISO for two reasons: 
    (i)	because they wanted to download once and create a network install for enterprise deployment;
   (ii)	because they had a shaky internet connection and wanted to be sure they'd downloaded successfully before installing. A single monolithic ISO isn't the best solution for either of those scenarios - it's just the one that people are habituated to over all these years. 

3. For the former (enterprise deployment), we have a full administrators' guide that provides detailed guidance on how to deploy the product: [https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-administrator-guide](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-administrator-guide). This includes PowerShell scripts, examples of using the installer to create and update a network cache, descriptions of how to deploy Visual Studio in a fully offline environment, and so on.

4. For the latter, we've worked really hard to improve the robustness of the installer. The componentization work we've done means that the smallest install is one-tenth the size of Visual Studio 2015, making it far more likely to succeed. And other typical installs are smaller too. We download Visual Studio in small packages that are more likely to succeed, and we use multiple ways (WebClient, BITS, WinInet) to download those files to minimize problems with AV and proxy software. If you want to download first then install, you can cache the components locally and then install from there. 

5. Because of the nature of our product (rapidly updating, lots of third-party components), an ISO is problematic. We don't have the rights to redistribute several large components (including Android), and others update on a rapid cadence that often includes critical security fixes, meaning an ISO image is incomplete, often outdated, and potentially insecure. Most customers assume that an ISO would support offline installation, but that's not true. 

Again, we thank you for your feedback, and we hope that you'll give our other non-ISO methods a try, such as that which is described on our [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/visualstudio/install/create-an-offline-installation-of-visual-studio) page.
