### ISSUE TITLE
Problem where my tasks are showing up twice

### ISSUE THREAD

**Issue by sbrevolution5** [MicrosoftDocs/visualstudio-docs#6682]
All of my tasks with TODO (or Todo) are showing up twice in the task list, which is very annoying.  I'm guessing this is because there are two default tokens (TODO and todo) but I cannot remove one to test it.  Another alternate fix may be to only return one TODO per line (or provide the user with an option to do so).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b78b04-7dd5-453e-de60-8cdd16594a99
* Version Independent ID: 27ddd786-e4c5-2b2e-e7c8-e103745dd656
* Content: [Task List, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/task-list-environment-options-dialog-box?view=vs-2019)
* Content Source: [docs/ide/reference/task-list-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/task-list-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@sbrevolution5 -- Seth, thank you for your feedback.  It looks like you're having an issue with the product itself, rather than an issue with the documentation. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
