### ISSUE TITLE
Problem in fresh installation on fresh laptop

### ISSUE THREAD

**Issue by saysmaster** [MicrosoftDocs/visualstudio-docs#6683]
I just installed visual studio 2019 on fresh laptop.

I tried to install some extensions but the extension manager shows this:

![Annotation 2021-05-14 004509](https://user-images.githubusercontent.com/3409322/118193897-24578c00-b451-11eb-8fdf-3ec2be03264e.png)

I have no clue on what the problem is and how to fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and install extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2019)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@saysmaster -- Ioannidis, thank you for your feedback.  This appears to be a product-related issue rather than a documentation issue.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

You are welcome to use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by saysmaster** [comment]
You are right. I'm really sorry, I don't even know how did I end up here!

**Comment by WilliamAntonRohm** [comment]
@saysmaster -- Ioannidis, no problem -- we're happy to help!
