### ISSUE TITLE
"ShimsBehaviors" does not exist

### ISSUE THREAD

**Issue by tevino** [MicrosoftDocs/visualstudio-docs#6728]
`ShimsBehaviors` should be `ShimBehaviors`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b356f491-a828-65ee-915b-b1ccdf71024c
* Version Independent ID: 3fa9dddf-b328-8e2f-c7b2-016a38f71bf6
* Content: [Isolate your app with shims (unit testing) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2019#change-the-default-behavior)
* Content Source: [docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by tevino** [comment]
All the occurrences of `ShimsBehaviors` are included, [here's the first one](https://github.com/MicrosoftDocs/visualstudio-docs/blame/e262f4c2a147c3fa2d27de666aae3a0497317867/docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md#L426).

**Comment by WilliamAntonRohm** [comment]
@tevino -- Tevin, thank you for catching this.

@Mikejo5000 -- Mike, please review this update in [private PR 8181](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8181).

**Comment by Mikejo5000** [comment]
Hmm. This is not just a typo, since every instance in code and text shows ShimsBehaviors, not ShimBehaviors. Also, it follows the naming pattern like ShimsContext and ShimsDelegates. I verified ShimsContext, but at the moment I'm not able to verify either ShimsBehaviors or ShimBehaviors (does not exist in the current context). I think there might be some steps missing from this doc. We need to confirm this before making any change. @AbhitejJohn Abhitej, do you have any insight on this?

**Comment by AbhitejJohn** [comment]
**Shim**Behaviors is indeed correct. Thanks for the fix. I've approved the linked PR as well.
