### ISSUE TITLE
Failed to find a documentation page for error C1117

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/visualstudio-docs#6837]
While trying to found out the reason for a compilation error with C++20 modules I failed to find the compiler error description on MSDN when clicking on it inside the error view on Visual Studio.

![grafik](https://user-images.githubusercontent.com/608876/124663773-d2f4d780-deaa-11eb-87c8-a791847a4cef.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* Content: [F1 help no-match fallback - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(keywords_removed)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/not-in-toc/default.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/default.md)
* Product: **visual-studio**
* Technology: ****
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@pjmlp -- thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- please look into this issue.

**Comment by pjmlp** [comment]
C1117 is still not documented at https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999?view=msvc-170

**Comment by pk1954** [comment]
I run into the same problem. Weird error message with error C1117. No docu available.

**Comment by corob-msft** [comment]
@pjmlp, @pk1954 
While this error is not common, some reports of error C1117 have been false positives due to unanticipated corner cases in combining modules with other translation units. In other words, if it's not a clear case of a type definition for something that's already defined in an imported module, the issue could be a compiler bug. To track such issues down, I recommend the procedure for creating a minimal repro case in [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170). Submit the result via **Help > Send Feedback > Report a Problem** to [Developer Community](https://aka.ms/vsfeedback/browsecpp). If it's a real compiler bug, that will get it investigated. If not, perhaps someone will chime in with a fix for your problem. There's no article yet, as we don't have anything useful to add to the text of the error message itself for now. Only that it might not be your fault, and we don't know how to tell you if it isn't.

**Comment by WilliamAntonRohm** [comment]
@corob-msft -- Colin, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by pjmlp** [comment]
Some documentation is better than leaving your customers in the dark, wondering why the compiler is screaming at them, but I guess it is easier to close the ticket and tell us to find support elsewhere.

**Comment by corob-msft** [comment]
@pjmlp Ah, I didn't realize even the boilerplate entry is missing. Well, that needs fixing.

**Comment by corob-msft** [comment]
There's now a boilerplate article, [Fatal error C1117](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1117?view=msvc-170), in the C++ documentation. F1 should find it from the IDE, though it might take another business day before it propagates across the Docs search engine service.
