### ISSUE TITLE
The DataCamp training benefit in Visual Studio subscriptions

### ISSUE THREAD

**Issue by whve** [MicrosoftDocs/visualstudio-docs#6849]
[Enter feedback here] I watched this tutorial, and datacamp disappeared. I hope you can solve this problem as soon as possible. 
——The DataCamp training benefit in Visual Studio subscriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce19f95f-b1b3-98d0-76c1-ae7bd64e3b50
* Version Independent ID: f5615c72-044d-65c7-73f7-189cebcdf2c2
* Content: [Grow data science skills with DataCamp in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-datacamp#feedback)
* Content Source: [subscriptions/vs-datacamp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-datacamp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@whve - Thank you for reaching out.  I'm not sure what you mean when you say you watched a tutorial.  Are you talking about the article?  When you say that DataCamp disappeared, do you mean that you couldn't see a tile for DataCamp in the https://my.visualstudio.com portal?  If that's the case, the most common cause is that you are using a subscription that is not eligible to receive the DataCamp benefit.  For information about which subscriptions include it, please visit:  https://docs.microsoft.com/visualstudio/subscriptions/vs-datacamp#eligibility.  For example, if you are using a Visual Studio Dev Essentials membership, you won't see the DataCamp tile because Dev Essentials doesn't include the DataCamp benefit.  To see a list of your subscriptions, please sign in to https://my.visualstudio.com/subscriptions.

**Comment by evanwindom** [comment]
#please-close
