### ISSUE TITLE
Setting up permissions described procedure isn't complete

### ISSUE THREAD

**Issue by evil-shrike** [MicrosoftDocs/visualstudio-docs#687]
I setup permissions for collector directory and trace log location as described:
icacls "C:\temp\trace" /grant "IIS APPPOOL\DefaultAppPool":F
icacls "C:\Prog\IntelliTraceCollection" /grant "IIS APPPOOL\DefaultAppPool":RX

But when I run Start-IntelliTraceCollection it fails with bizarre error:
PS C:\temp>Start-IntelliTraceCollection -ApplicationPool DefaultAppPool -CollectionPlan C:\Prog\IntelliTraceCollection\collection_plan.ASP.NET.default.xml -OutputPath C:\temp\trace

Start-IntelliTraceCollection : The following application pool requires read and execute permissions for the IntelliTrace directory: "IIS APPPOOL\DefaultAppPool", "C:\WINDOWS\system32\WindowsPowerShell\v1.0\".

It looks like cmdlet needs permissions on powershell folder ("C:\WINDOWS\system32\WindowsPowerShell\v1.0\"). But why? 
The problem is that it's not possible to change permissions for that folder. Add/Remove buttons are disabled in Permissions dialog. Probably it's because of the owner of this folder is TrustedInstaller. It seems to be wrong to change owner for powershell home folder to allow iTrace collectionn.

Env: Windows 10 Fall Creator Update, eng, PSVersion 5.1.16299.98, running under local admin user.

Please advice a workaround.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995e3a2f-5674-63c4-5899-ba9a6b0e5da6
* Version Independent ID: b93833ad-9195-96b4-6fac-8893836cde4e
* Content: [Using the IntelliTrace stand-alone collector | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-intellitrace-stand-alone-collector#ConfigurePermissionsRunningCollector)
* Content Source: [docs/debugger/using-the-intellitrace-stand-alone-collector.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/using-the-intellitrace-stand-alone-collector.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by evil-shrike** [comment]
But even if I change owner of "C:\WINDOWS\system32\WindowsPowerShell\v1.0\" to me and grant permissions for the folder to IIS APPPOOL\DefaultAppPool, the error won't gone!

Start-IntelliTraceCollection : The following application pool requires read and execute permissions for the IntelliTrace directory: "IIS APPPOOL\DefaultAppPool", "C:\WINDOWS\system32\WindowsPowerShell\v1.0\".

**Comment by Mikejo5000** [comment]
@deborahc Deborah, could you advise on this? Thanks.

**Comment by Mikejo5000** [comment]
@evil-shrike Sorry for the slow response, evil.
It looks like you're having an issue with the product itself, rather than an issue with the documentation, which is what these GitHub issue are for. For options to report your product issue, consider using the following venues:
- You can report product issues to us via the [Report a Problem](https://github.com/MicrosoftDocs/visualstudio-docs/ide/how-to-report-a-problem-with-visual-studio-2017.md) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.
- You can track product issues in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), and ask questions and find answers.
- You can also engage with us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
Thanks,

**Comment by evil-shrike** [comment]
@Mikejo5000  :) you're right, it's an issue the product(s), thanks for the links. 
it's just much easier to create an issue here than in developercommunity.visualstudio.com.
