### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by ramtechjoe** [MicrosoftDocs/visualstudio-docs#7025]
Please update to current 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8368af75-bb65-b3bc-bcbc-67a2739e5bc3
* Version Independent ID: f6142191-d659-83f2-76a2-6b8afda90774
* Content: [Troubleshooting XAML Hot Reload - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-troubleshooting?view=vs-2019)
* Content Source: [docs/xaml-tools/xaml-hot-reload-troubleshooting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/xaml-hot-reload-troubleshooting.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ramtechjoe We've made several updates to the XAML Hot Reload troubleshooting page since you've created this GitHub issue; as such, we'll close this issue now with our thanks to you for your interest in the documentation! (And, if you find that the XAML Hot Reload troubleshooting page is still not meeting your expectations, please open a new GitHub Issue with the specifics of what might be missing or unclear.)
