### ISSUE TITLE
Missing docs - how to create and build njsproj projects with the dotnet command

### ISSUE THREAD

**Issue by RobertPepkaSEL** [MicrosoftDocs/visualstudio-docs#7029]
### Observed

The instructions for creating a nodejs app in Visual Studio work nicely, exactly as expected. However, when I move to the command line (using `dotnet`) to build the solution, it instead issues this message: 

> error MSB4019: The imported project "C:\Program Files\dotnet\sdk\5.0.400\Microsoft\VisualStudio\v16.0\Node.js Tools\Microsoft.NodejsToolsV2.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.400\Microsoft\VisualStudio\v16.0\Node.js Tools\Microsoft.NodejsToolsV2.targets" is correct, and that the file exists on disk.

### Expected

The instructions should include what steps I need to create a njsproj and build a njsproj app from the command line with `dotnet`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2bc34b-ee38-4dab-308c-a6c45c36200a
* Version Independent ID: e2b3ef7f-3106-674d-a995-c7b14cf53cc9
* Content: [Create your first Node.js app - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-nodejs?view=vs-2019)
* Content Source: [docs/ide/quickstart-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@RobertPepkaSEL -- Robert, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- Mike, please look into this issue.

**Comment by RobertPepkaSEL** [comment]
Thank you! I amended the initial comment to be a bit more specific; I am using `dotnet` to build from the command line. My main use case is trying to build this all in a containerized build environment that builds all my other asp.net core dotnet applications that I can then deploy in a docker container.

**Comment by Mikejo5000** [comment]
@RobertPepkaSEL The error message looks like it's expecting the Node.js development workload to be installed (per instructions in the doc). Is it installed? Second, likely bigger issue is that this doc shows how to create a Node.js app, not an ASP.NET Core app; I don't expect that dotnet CLI would work with a Node.js app, since it has no built-in .NET support. I would think the ASP.NET Core articles would be much more relevant to your scenario.

VS 2022 has a new project type, esproj (we are still working on docs) and we have several articles that are relevant (for ASP.NET Core with React | Angular | Vue). These are two-project solutions: One project is ASP.NET Core, and one is an esproj, which supports Node.js.
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022

For npm support within an ASP.NET Core project in VS 2019 or VS 2022, the following doc might be more relevant. This is a standard ASP.NET Core project type.
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2022
