### ISSUE TITLE
Cannot select C# form

### ISSUE THREAD

**Issue by AndrewDavid007** [MicrosoftDocs/visualstudio-docs#7041]
When I get to Step 4 "Name the project QuickDate, then select Create."
I am using VB 2022 (Preview) and I want to build it on NET 5.0 but the dropdown only goes as high as 4.8
I have NET 5.0 installed because I can select other templates that support its use.
Will these templates be updated or replaced?
Your attention is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5b432e-98af-2784-12f3-5da298a7a6a3
* Version Independent ID: 0d0b207d-4ea3-3716-3894-b898b279e667
* Content: [Introduction to projects and solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019)
* Content Source: [docs/get-started/tutorial-projects-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/tutorial-projects-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by AndrewDavid007** [comment]
Expand Visual C# Items, then select Code. In the middle pane, select the Class item template. Name the class Calendar, and then select the Add button.

Only C## files are shown. No C#

**Comment by WilliamAntonRohm** [comment]
@AndrewDavid007 -- Andrew, thank you for your feedback.  This appears to be a product issue rather than a documentation issue.  Please add it here:
- [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio)


Also, consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
