### ISSUE TITLE
Wrong ID "Microsoft.VisualStudio.Product.TestAgent"

### ISSUE THREAD

**Issue by gs-rs-21** [MicrosoftDocs/visualstudio-docs#7060]
The ID **Microsoft.VisualStudio.Product.TestAgent** did not work with downloaded _vs_testagent*,exe_  when I tried to create an offline installation.

The ID **Microsoft.VisualStudio.Workload.TestAgent** on page [Visual Studio Test Agent component directory](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-test-agent?view=vs-2019) worked for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f80d9f-168b-e3cb-6499-e03a44206826
* Version Independent ID: 4b235b0d-1436-0a36-ef55-f76ba8d95bd1
* Content: [Visual Studio workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019)
* Content Source: [docs/install/workload-and-component-ids.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-and-component-ids.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@gs-rs-21 - thank you for your feedback. This appears to be a product issue rather than a documentation issue. Please create a feedback ticket:  [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

I am closing this issue now; thanks again for contacting us.
