### ISSUE TITLE
No "Other Windows" item in the "View" menu

### ISSUE THREAD

**Issue by gpion** [MicrosoftDocs/visualstudio-docs#7075]
There are several reference to "View" > "Other Windows" in the page.
I don't see "Other Windows" item in the "View" Menu of Visual Studio Code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a426e3db-8d10-e7d2-0957-5eb07d28e76d
* Version Independent ID: e54ea195-0592-0424-a5b1-54dba78257e4
* Content: [Python interactive window (REPL) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/python-interactive-repl-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/python-interactive-repl-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/python-interactive-repl-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@gpion -- thank you for your feedback.  Please consider these resources, and let me know if your issue is resolved:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)
