### ISSUE TITLE
v14 or v15 references?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#718]
Does this need a version number update or is v14 the correct references?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d605fcb-d42d-e11c-097d-f74b7061d20e
* Version Independent ID: 6f6ef619-7636-7a96-157c-2ab986d38d07
* Content: [Creating a Custom Start Page - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-custom-start-page)
* Content Source: [docs/extensibility/creating-a-custom-start-page.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/creating-a-custom-start-page.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @StingyJack, you are correct, the walkthrough needs to be updated for VS 2017. 
Besides the *Shell.14*, there may be other version specific information (ex Documents\Visual Studio 2015\StartPages).
PRs welcome. Thanks for pointing this out.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
