### ISSUE TITLE
SSMS Search opens EVERY file searched even when the search string is not found. (Unlike Visual Studio)

### ISSUE THREAD

**Issue by kingletit** [MicrosoftDocs/visualstudio-docs#7199]
Whenever I search for text in my project or solution, SSMS opens, **and keeps open**, every file it searches whether or not the search string was found. 

****_- E.g. Say I have references to a particular table in perhaps 3 or 4 SQL scripts in my project. If I'm making a change to that table, I need to find those scripts to see if they also need to be changed. I don't want to open any other files._**** 

At the moment, when I search for that table name SSMS **opens EVERY script and leaves it open**. Half way through the process, the app is taking up so much memory that it becomes unresponsive and then crashes. In contrast, a similar search in Visual Studio **only** opens those files that contain the search string. I cannot understand why SSMS does it this way.

It's got so bad I can no longer use Search within Project or Solution. I'm having to do a search in windows File Explorer, make a note of the files that need looked at, and then open each separately.

Is there something wrong with my setup or is it a bug? I've reinstalled SSMS several times but to no effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@kingletit -- thank you for your feedback, and sorry to hear of your difficulties.  This appears to be a product issue rather than a documentation issue.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

And you are welcome to pursue this here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
