### ISSUE TITLE
setupProxy.js not working

### ISSUE THREAD

**Issue by Chryogenic** [MicrosoftDocs/visualstudio-docs#7232]
While following this documentation my frontend app is failing to call the backend. Upon closer inspection the API call that was being used was `https://localhost:3000/weatherforecast` - so it's basically ignoring what was set in the setupProxy.js. 

I have tried `npm install` and have tested altering the target to a few different values, but each time localhost:3000 is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by PranavSenthilnathan** [comment]
Thanks for the feedback! When you Debug (F5), a command prompt should open up for the react server. Can you please share the output of that? It should be similar to the following (you will have to manually scroll up in the window because some text might be hidden):
![image](https://user-images.githubusercontent.com/12225508/140826277-e851592f-cb9c-4448-93de-ae85f93016d2.png)

Also could you please share the setupProxy.js file contents? 

The command prompt that runs the react server is long running and doesn't pick up the proxy changes automatically, so you will have to close that window when you change the port (it will start up again when you F5 again).

**Comment by Chryogenic** [comment]
@PranavSenthilnathan - Thanks for the reply, this was exactly the issue. I had run the react project before updating the setupProxy.js. When I stopped the project, I didn't realise that the command prompt window was actually still running & that it was blocking changes to the setupProxy.js file.

After closing the command prompt and then rerunning the code, it was working as expected :)

FYI - this was output of the command prompt window:
![image](https://user-images.githubusercontent.com/12728043/141036838-16d0b492-aee2-4b15-8b6e-a4f14c9b2012.png)

**Comment by Pushylup** [comment]
Hello @PranavSenthilnathan, for me its not working even if i restart the server with the update target proxy

**Comment by Mikejo5000** [comment]
@Pushylup I'm making a doc update based on MicrosoftDocs/visualstudio-docs#7275. If this is a different issue, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
