### ISSUE TITLE
Terminology use - "View files"

### ISSUE THREAD

**Issue by sabuncumurat** [MicrosoftDocs/visualstudio-docs#7234]
This section: https://docs.microsoft.com/en-us/visualstudio/version-control/git-with-visual-studio?view=vs-2019#view-files-in-solution-explorer

2nd paragraph: "Solution Explorer loads the folder at the root of the Git repository and scans the directory tree for any **View files.**"

"View files" - first I am hearing of this term; is this a thing?  If it is, a link to it would help.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b430664f-79e1-35fa-5292-34f517092b08
* Version Independent ID: c72b1131-9035-bb27-2465-50328f12dc93
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/version-control/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/version-control/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@sabuncumurat You're right; that was not optimally phrased. We've changed the text so that it's more specific to its meaning. You can see that in the Visual Studio 2019 version of the page, here: 

- https://docs.microsoft.com/visualstudio/version-control/git-with-visual-studio?view=vs-2019

And also in the Visual Studio 2022 version of the page, here:

- https://docs.microsoft.com/visualstudio/version-control/git-with-visual-studio?view=vs-2022

We'll close this issue now with out thanks for bringing this to our attention, and for your help in improving the documentation.

**Comment by sabuncumurat** [comment]
@TerryGLee Thank you for clarifying.
