### ISSUE TITLE
Clarify VS version for Microsoft.VisualStudio.Shell.14.0 and the repetition of DLLs

### ISSUE THREAD

**Issue by PureWeen** [MicrosoftDocs/visualstudio-docs#730]
I'm going through this on VS 2017 so initially when I searched for Microsoft.VisualStudio.Shell.14.0 using the search box nothing came up.  Once I visually searched I realized I needed to use 15.0 so maybe clarifying that this documentation is for VS 2015 would be helpful or to look for 15 would be helpful.   Also after installing the VSSDK I noticed that there are two copies of each of these DLLs.  I get that it's because one of them is in the VSSDK folder and the other is distributed with the product but I'm not sure if it matters which one I add. I would think I need to add the one in the VSSDK folder but maybe it doesn't matter? Because they will always be the same version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9702447d-6173-b296-9a8c-9bb527caa6e7
* Version Independent ID: 505b382a-c4f2-ebd4-0376-da5220ffaca3
* Content: [Walkthrough: Using a Shortcut Key with an Editor Extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-using-a-shortcut-key-with-an-editor-extension)
* Content Source: [docs/extensibility/walkthrough-using-a-shortcut-key-with-an-editor-extension.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/walkthrough-using-a-shortcut-key-with-an-editor-extension.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@PureWeen Thanks for the feedback. We will try to address this soon.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
