### ISSUE TITLE
Get error when run docker mount with local directory

### ISSUE THREAD

**Issue by trtan** [MicrosoftDocs/visualstudio-docs#7324]
When I ran: docker run -dp 3000:3000 -v ${PWD}:/app node:12-alpine sh -c "yarn install && yarn run dev"
And I checked the log, I got this in log:
yarn install v1.22.15
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.07s.
yarn run v1.22.15
error Couldn't find a package.json file in "/"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I am running Docker on windows, and I'm at the app folder on windows bash command 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e42a144-9901-78d8-1082-a1c5b35a3602
* Version Independent ID: 34e7cab6-29bd-cb03-f100-a186b407a23f
* Content: [Docker tutorial - Part 6: Use bind mounts](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-bind-mounts)
* Content Source: [docker/tutorials/use-bind-mounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/use-bind-mounts.md)
* Product: **visual-studio-family**
* Technology: **vs-docker**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by trtan** [comment]
Never mind, it worked on now, don't know what was wrong before.

**Comment by hawada96** [comment]
Can we necro this issue? I am having the exact same problem.

**Comment by trtan** [comment]
This issue came back again and I don't know what the exact fix is. reopen it.

**Comment by WilliamAntonRohm** [comment]
@trtan, @hawada96 -- thank you for your feedback. This appears to be situational rather than documentation-related.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.
