### ISSUE TITLE
Trying to profile slow startup on my MVC project and I get "There is no data in the current set of filters"

### ISSUE THREAD

**Issue by PRMan99** [MicrosoftDocs/visualstudio-docs#7332]
There is absolutely nothing that looks anything like this page at all whatsoever.  No function calls.  No percentage of CPU. Nothing.

Just a message that it can't be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0410dc57-c6ba-8256-a844-d6951e8b7c2f
* Version Independent ID: 80be647c-e762-acb5-cf56-2cf6b6f423c7
* Content: [Analyze CPU usage in the Performance Profiler - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/profiling/cpu-usage?view=vs-2022)
* Content Source: [docs/profiling/cpu-usage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/cpu-usage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@PRMan99 -- thank you for your feedback.  This looks like a product issue, rather than documentation-related.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @Mikejo5000 for awareness
