### ISSUE TITLE
Default schema cannot be accessed...?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [MicrosoftDocs/visualstudio-docs#7341]
[Enter feedback here]
I'm a bit confused: http://schemas.microsoft.com/developer/msbuild/2003 does not exist? So why should it be referenced in the project file?

```sh
$ curl -I http://schemas.microsoft.com/developer/msbuild/2003
HTTP/1.1 404 Not Found
Content-Length: 103
Content-Type: text/html
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Mon, 22 Nov 2021 20:38:40 GMT
Connection: keep-alive
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73afcd0b-3717-082a-e429-428bfac1c826
* Version Independent ID: 7f6f3bd1-c584-6a63-513d-a541db4e585c
* Content: [MSBuild Project File Schema Reference - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-project-file-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-project-file-schema-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@GwynethLlewelyn 
Thanks for your feedback. The schema link is not required with Visual Studio 2017 and later. See
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference?view=vs-2022

This is not currently used in MSBuild but is still recognized by MSBuild for backward compatibility, since MSBuild is used to process older project files that still reference that link, even though it no longer works.

**Comment by GwynethLlewelyn** [comment]
Thanks for the clarification! I was just wondering because I was planning to do some XML validation on the project file (with externally scripted tools, not inside VS) and the schema could be valuable in that case. On the other hand, the link you sent lists the various elements in the old schema, so I guess that's more than enough for my own purposes.
