### ISSUE TITLE
Part 8, Docker compose app exits with code 1 instead of listening on port 3000

### ISSUE THREAD

**Issue by TechsquareJoseph** [MicrosoftDocs/visualstudio-docs#7373]
In step 3, the docker compose logs show "exited with code 1", instead of "listening on port 3000"

Full log output:
Attaching to app_app_1
app_1    | yarn install v1.22.15
app_1    | info No lockfile found.
app_1    | [1/4] Resolving packages...
app_1    | [2/4] Fetching packages...
app_1    | [3/4] Linking dependencies...
app_1    | [4/4] Building fresh packages...
app_1    | success Saved lockfile.
app_1    | Done in 0.09s.
app_1    | yarn run v1.22.15
app_1    | error Couldn't find a package.json file in "/app"
app_1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_app_1 exited with code 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de887cb2-50a1-274a-061e-793326e0c584
* Version Independent ID: 1a792327-7d77-2542-d58e-4fded6de417e
* Content: [Docker tutorial - Part 8: Use Docker Compose](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-docker-compose)
* Content Source: [docker/tutorials/use-docker-compose.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/use-docker-compose.md)
* Product: **visual-studio-family**
* Technology: **vs-docker**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@TechsquareJoseph -- Joseph, thank you for your feedback.  This issue seems more code-related than documentation-related.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

cc @nebuk89, @ghogen for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
