### ISSUE TITLE
Download Visual Studio 2022 offline installer 

### ISSUE THREAD

**Issue by appelmrl** [MicrosoftDocs/visualstudio-docs#7435]
Sorry but this command line is not usable in for VS2022;
   vs_enterprise.exe --layout c:\localVScache --lang en-US

How to download an offline installer of VS 2022 to install in an evnironment wihtout Internet?

Kind reguards,
Roy Appelman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@appelmrl -- Roy, thank you for your question.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@anandmeg -- Megha, please look into this issue.

**Comment by christineruana** [comment]
Hi Roy (@appelmrl)  Pardon me, but I'm not really understanding what the problem is.  The command you list above should work fine to create a local cache of VS product files.

The general approach for installing onto a disconnected machine is that first you create the cache of Visual Studio files, and then you can use that cache as the source to install from onto the disconnected machine.   The creation of the cache absolutely requires the internet, because you have to acquire the product which is available on the internet.  Once you create your file cache, then you can install from it *without* using the internet.  I described the latter step (installing exclusively from a network or local cache in a couple of places:  https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?#step-3---install-visual-studio-from-the-local-cache and https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?#install-on-a-client-that-doesnt-have-internet-access.   Basically, you want to use the --noWeb switch.   Please take a look at those and let me know if that answers your question.  

Thanks,  
   Christine

**Comment by christineruana** [comment]
We don't need to keep this issue open any longer.  Hopefully my answer above works for @appelmrl and if not, please feel free to reactivate this or open another one.  Thank you. 

#please-close
