### ISSUE TITLE
Project creation error using "Stand alone react project using JavaScript template"

### ISSUE THREAD

**Issue by pramod-hegde** [MicrosoftDocs/visualstudio-docs#7440]
Issue found in latest VS 2022 version-17.0.3 while creating the project using Stand alone react project using JavaScript template.

![issue-1](https://user-images.githubusercontent.com/20237168/146647903-87938754-1c1c-473c-820c-2de67b93fcc5.png)

![issue-2](https://user-images.githubusercontent.com/20237168/146647913-f52e5814-7c50-42b9-baf5-0d2d5a8ac756.png)

![issue-3](https://user-images.githubusercontent.com/20237168/146647914-f0a4c83c-6cf5-4dd1-96da-68f1dd85c09b.png)

![issue-5](https://user-images.githubusercontent.com/20237168/146647985-8d821966-863c-4cc4-b4cc-4d08034f7a0a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@pramod-hegde -- Pramod, thank you for your feedback.  I am looking into this issue.  Meanwhile, please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

**Comment by WilliamAntonRohm** [comment]
@pramod-hegde -- Pramod, this appears to be product-related, rather than a documentation issue.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
