### ISSUE TITLE
This is an old version of visual studio screen captured

### ISSUE THREAD

**Issue by Bouguerra-S** [MicrosoftDocs/visualstudio-docs#7447]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1254d11a-1f2d-fc93-961f-c68ca4207ccb
* Version Independent ID: 284cc66e-a215-3f6a-9c2e-3d0aca1b9be6
* Content: [XML Schema Designer Graph View - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xml-tools/graph-view?view=vs-2022)
* Content Source: [docs/xml-tools/graph-view.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xml-tools/graph-view.md)
* Product: **visual-studio-windows**
* Technology: **vs-xml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Bouguerra-S Thanks for taking the time to write up this issue. We're aware that the screenshots are outdated in the XML content set, and we apologize for that. Unfortunately, due to the sheer volume of feedback in our repo, we must prioritize other content over this particular content set. We'll close this issue now, with our thanks to you for your interest in improving the documentation.
