### ISSUE TITLE
A merge conflicted on path "/.vscode/launch.json".

### ISSUE THREAD

**Issue by LumberJackBr13** [MicrosoftDocs/visualstudio-docs#7514]
This message apears in a console window running NPM just after clicking the Create button on the Aditional Information page when creating a project based on the Standalone Typescript Template on VS 2022.

I just floowed the instructions from this page, installing NPM and also Angular.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@LumberJackBr13 -- thank you for your feedback.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- please look into this potential documentation issue.

**Comment by geraldbauer** [comment]
I too am getting this error on step three of the instruction [Tutorial: Create an ASP.NET Core app with Angular in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022). 

FWIW: The documentation is out of date. Documentation states to select "Standalone Angular Template" but what is listed is "Standalone TypeScript Angular Template"

**Comment by Xeinaemm** [comment]
To bypass this problem you need to get into the project folder (after clicking "Create") and remove the firstly created .vscode folder. Under the hood template that creates projects have 2 VSC setups and both are in conflict (race condition) because the second cannot overwrite first.

I also will write it there(because the newly created project also has problems and I cannot find places where to send bugs):
When you will create a project(.esproj) it will destroy backward compatibility with MSBuild and dotnet CLI. If you have other projects inside the solution all of them will blow up.

Don't work(which I spotted):
1. dotnet test(VSTest target doesn't exist, the whole solution will fail - MSBuild will throw an exception)
2. dotnet restore(MSBuild will send a warning that .esproj has problems with Restore target but will skip throwing error)
3. dotnet publish(same as dotnet test, SDK don't implement Publish target and the whole solution will fail - MSBuild will throw an exception)

To fix that I overrode SDK implementations of standard targets because current templates shouldn't be published into .NET 6 runtime as a new feature that breaks backward compatibility of dotnet CLI and MSBuild under the hood.

**Comment by Mikejo5000** [comment]
@Xeinaemm You said you weren't sure where to file bugs. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by niltor** [comment]
Any update? I had the same error when I  try to create angular  project. 
Is it a visualstudio bug?

**Comment by Mikejo5000** [comment]
@niltor @Xeinaemm I will see if I can get a repro on this, but please file [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
I could not repro this issue on testing with VS2022 17.0,3 (not Preview) so please use Report a Problem to move forward.
@Xeinaemm Is that a satisfactory workaround to get the dotnet commands working again? @gcrev93 for comment.

**Comment by Mikejo5000** [comment]
Also, it doesn't appear related, but you might try updating Node.js (npm). I did that prior to testing the other tutorial on React.

**Comment by PGrkovic** [comment]
This should not have been closed as it's still unresolved and still happening with the latest node and VS2022 17.0.5.

**Comment by Xeinaemm** [comment]
> Also, it doesn't appear related, but you might try updating Node.js (npm). I did that prior to testing the other tutorial on React.

@Mikejo5000 Because the problem itself is not related to Visual Studio but Visual Studio Code. When Visual Studio starts creating projects from the template firstly is added a setup for browsers(which will be used to run the project) and a second-time setup for Angular. You cannot have both of them in separated files, you need to merge them if you want to move forward and the system warns you that will abort creating a project because don't know how to merge these things  (under the hood .NET Template is very straightforward and don't know how to do that)

I will fill form because the problem spans Visual Studio, Visual Studio Code, and .NET because the new template is a real blocker for people that have all of them.

**Comment by geraldbauer** [comment]
Hmmm I am experiencing this with Visual Studio. 

Steps to reproduce:
1. Select Create a new project then choose Next
2. Select "Standalone TypeScript Angular" then choose Next
3. Give the project name, the location, and the solution name then choose Next
4. Nothing to do on Additional information page other than selecting Create
5. npm command prompt appears telling us "A merge conflicted on path "/.vscode/launch.json" and "Press any key to continue . . ."

As @Xeinaemm pointed out earlier in this thread: 
> To bypass this problem you need to get into the project folder (after clicking "Create") and remove the firstly created .vscode folder. Under the hood template that creates projects have 2 VSC setups and both are in conflict (race condition) because the second cannot overwrite first.

Speculating here: I do not think this has anything to do with Visual Studio Code nor npm but with the Visual Studio template for "Standalone TypeScript Angular" when creating a solution/project

**Comment by Mikejo5000** [comment]
@Xeinaemm @PGrkovic Thanks for the additional information. I am asking about this. We also need to make sure this bug is in the right place, so I suggest Report a Problem. We track only doc bugs here and there's a definite product bug in this case. I recognize there appears to be a VS Code conflict issue here, though I can't repro (message sounds like a Git message).
It might be good to doc the workaround, if we can be certain about it: Sounds like (1) If you see this message after Create, (2) Delete the /vscode folder. Is that accurate?

**Comment by Mikejo5000** [comment]
@Xeinaemm Can you provide a link to the issue you opened?

**Comment by Xeinaemm** [comment]
@Mikejo5000 Sure, [issue](https://developercommunity.visualstudio.com/t/Race-condition-in-Visual-Studio-Template/1651439)
I linked this post, so everything should be in place.

**Comment by Mikejo5000** [comment]
@PranavSenthilnathan for comment on this issue

**Comment by lend-a-tailor** [comment]
I normally use VS Code for Angular projects but I was able to use the following workaround for Visual Studio.
After creating the project: 

1. Delete or rename the **.vscode** directory.
2. Right click the project name in the solution explorer and select **Open in Terminal**.

Type in the terminal window: 

1. repos>_yourProject_ >**cd ..** 
2. repos> **ng new** _yourProject_

You should see the **ng serve** to run in debug mode. Although I been getting a failure to attach to the browser error when trying to launch from the debugger - So in the terminal window, change to your project directory: 

1. **cd** _yourProject_
2. repos>_yourProject_ >**ng serve**

You'll have to open the browser manually.
