### ISSUE TITLE
why I can not debug both python and C code?

### ISSUE THREAD

**Issue by samyuchao** [MicrosoftDocs/visualstudio-docs#7750]
[Enter feedback here]
if I enable native code debugging, only debug C++ code, but cannot step into Python code.
if I disable native code debugging, only step into python code, cannot step into C/C++ code. 
Why? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
* Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
* Content: [Mixed-mode debugging for Python - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by DietmarSchwertberger** [comment]
Same here with VS 2017.

And btw.: the Youtube video link is invalid. It's probably private.

**Comment by WilliamAntonRohm** [comment]
@samyuchao, @DietmarSchwertberger -- this may be a product issue.  To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

Also, please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@rjmolyneaux -- please look into this issue.

**Comment by DietmarSchwertberger** [comment]
Yesterday and today also tried VS 2022. There it also does not work.
For the extension module, the option "Python/Native" is missing completely.


I even did un- and re-install to be able to submit a clean bug report as you suggested.
I have to stop this now. There are so many problems with VS and Python, I really cannot imagine that this has ever been used or tested or that it will result in a viable solution in finite time.

First bug after the re-installation: VS' own Python installation was not usable.
Root cause: the previous uninstall did not remove all registry entries, e.g. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Pytho\PythonCore\3.9\PythonPath
Therefore the Visual Studio Installer did not re-install Python 3.9. Took me quite some time to find out why VS was listing 3.9 as installed but could not actually select it.
After manually removing registry entries and repeating the Python workload installation, the interpreter is available now.


For the further tests, now I created a Python extension module "module1" and added a "new project" of type "Python Application".
For the Python Application I have activated "Native Code debugging". This does not seem to have an effect, but I could not further investigate.
For the extension module, the option "Python/Native" is missing completely.

Next bug: There seems to be no way to actually select the Python environment that will be used for the extension module.
There should be a way in the project folder explorer to select the Python environment for the extension module or for the complete folder.


The include paths are relative to "$(PythonHome)", but that's usually not defined. Therefore, building the extension module will fail with "Python.h" not found.
Replacing "$(PythonHome)" with the path does now result in error messages about .NET assemblies not being found.


I'm now no longer suprised that I found almost no references or examples on the net about mixed mode debugging. This all seems to be in alpha status, even though it has been around since 2015.

**Comment by DietmarSchwertberger** [comment]
I could actually debug mixed mode with VS 2017 and the supplied (obsolete) Python 3.6.6.
But: it's probably not worth the effort. I can't step through Python's own code (contained in python36.dll or python36_d.dll).
Symbols are found and I have copied the sources over the Python installation.
With the native debugger, I can step through the python36.dll code and set breakpoints etc.
From the screenshots in the documentation page, I can't tell whether this is a bug or a 'feature'. It's certainly a must have to make mixed mode really useful.

Also, when an assertion is triggered in the _d version, I can't debug it. I get the message that I can hit "Retry" to debug it, but actually, on selecting "Retry" it will just display the core dump if VS is active. If it's not active, it will do nothing.


As first step, I would suggest to re-work the documentation page:
 - Provide a step-by-step description to get a working setup.
 - Update the page with screenshots from _that_ setup such that users can see what to expect.
Then:
 - Improve the diagnostics to allow also a working setup with other Python versions.
 - Include sources with the installed Python version.
 - Fix re-installation of Python (see post above about the experiences with VS 2022).
 - Install Python version somewhere where the user can work with it. (Install libraries, work on source code).
 - Actually, it should be possible to use the Python source tree from the github repository.
 - Make the selection of Python interpreters transparent and editable. Currently it's read from the registry, as one can see from looking at the vcxproj file. This is not a good idea.

The experience with VS 2022 was too much beta. So, I'm not sure what's the best VS version to start with.

**Comment by int19h** [comment]
You can't step through python*.dll normally, because it is treated as being "in Python code", and thus Python stepping applies. For most users, the expectation is to be able to step through their extension, while Python internals are transparent.

However, when you do need to debug Python itself, there's a trick. If you set the registry key as defined [here](https://github.com/microsoft/PTVS/blob/main/Python/Product/Debugger.Concord/PythonDeveloper.reg), you'll see some new items in the context menu that has "C++ View" and "Python View" items. One of those lets you see the entire native stack, including parts in python*.dll. The other one lets you temporarily override stepping, so that you can step through python*.dll.

**Comment by DietmarSchwertberger** [comment]
Thanks. I will try the registry key.
Shouldn't that behaviour be enabled automatically if I set a breakpoint in a source file that belongs to the python*.dll or even when I just open it? Or maybe have an option in the Python environment setup.

My use case for this is to debug a complex extension (wxPython) that triggers an error `SystemError: ... returned a result with an exception set`
I would think that such requirement is not too unusual.


Mixed mode debugging is a great concept. If it was more robust to set up, then it would be a great tool and should be presented to the audience. E.g. a post to c.l.p.announce and maybe an up-to-date Youtube video. I think the last announcement was 2013.

**Comment by DietmarSchwertberger** [comment]
I tried the registry key and it does not seem to make a difference for debugging python*.dll:
(Tried with both python.exe and python_d.exe)

![grafik](https://user-images.githubusercontent.com/5512021/159356268-d31f591c-47a9-4467-9c92-0603763ce073.png)

![grafik](https://user-images.githubusercontent.com/5512021/159355773-1af34fde-cbbb-4a1f-beaa-53de8fcb1e97.png)

It made one difference, though: the post mortem debugger seems to work now.

**Comment by int19h** [comment]
PTVS doesn't really know anything about native breakpoints - they're handled entirely by the C debugger, which is separate. It might be possible to query for them and auto-enable the setting, but debugging Python itself was deemed a sufficiently niche scenario (hence why this is an undocumented reg key, and why it's called "PythonDeveloper" - we anticipated that it'd be primarily be used by people working on CPython).

Regarding the new breakpoint error, that one is also coming straight from the native debugger, so there's some limitation that you're hitting there. Since this is a debug build of Python, optimizations shouldn't be an issue. But it might be that this particular line simply doesn't have an executable code associated with it even in debug builds. I notice that on the screenshot, both of your breakpoints are on lines that only contain a string literal - I'm not sure this would actually be triggered when function is called. Try moving those breakpoints to the line which has the `(` for the call and see if that helps. If not, that might be a separate C++ debugger issue to file on VS.

**Comment by DietmarSchwertberger** [comment]
Thanks, you're right. The breakpoints are actually not set due to the line being a string literal. I would have expected the debugger to be clever enough to set the breakpoint to the function call...
I can try with my _d builds again, once my long running builds are finished.
With the non-debug build it certainly does not work. Setting a breakpoint inside Python effectively turns "F5" into "single step": it will stop at every Python line.

**Comment by int19h** [comment]
Depending on where you've set the breakpoint in CPython source, it's entirely possible that it is, in fact, hit on every Python line. That's also why it's a checkbox in the context menu - this way you can switch between Python stepping and C stepping as needed for a given scenario.

**Comment by rjmolyneaux** [comment]
Hi @WilliamAntonRohm, following up on this thread and @int19h 's feedback. It looks as though this particular issue may boil down to a C++ debugger issue.  Is it possible to label this **C++** in VS?

> "PTVS doesn't really know anything about native breakpoints - they're handled entirely by the C debugger, which is separate..."
> 
> "...Try moving those breakpoints to the line which has the `(` for the call and see if that helps. If not, that might be a separate C++ debugger issue to file on VS."

**Comment by WilliamAntonRohm** [comment]
@rjmolyneaux -- Ryan, thank you for the clarification.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
Added this discussion as a link in https://developercommunity.visualstudio.com/t/Mixed-mode-debugging-CPython-projects/950641.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
