### ISSUE TITLE
Describe how a user arrived on the "oops no F1 help" page

### ISSUE THREAD

**Issue by liamlaverty** [MicrosoftDocs/visualstudio-docs#7778]
It'd be handy to have a description of how the user arrives at this page somewhere near the top. Something like "you are viewing this page because you pressed F1 in Visual Studio, and there is no help article available". 

I've arrived here confused a few times, I assume accidentally after meaning to click `esc` in VS & hitting F1 instead. The only context on the page is the "didn't mean to click?" link near the bottom. Sometimes the browser window (firefox) doesn't take focus when VS loads the page, so after some period of time has elapsed I open the browser to be presented with an _Ooops_ page, and no idea why it's there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* Content: [F1 help no-match fallback - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(SolutionItemsProject)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/not-in-toc/default.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/not-in-toc/default.md)
* Product: **visual-studio**
* Technology: ****
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@liamlaverty I'm inclined to leave this as-is. The current heading "Oops! No F1 help match was found" implies that there's no help article available for your F1 click (although "no match" is a bit more accurate, since the article might exist, but is not hooked up properly). There's also a question early on in the doc asking if you were looking for F1 Help. We've been trying to keep the descriptive text here very short.
