### ISSUE TITLE
Installing VS22 Community on client from layout on (an no-internet) network share

### ISSUE THREAD

**Issue by rra88** [MicrosoftDocs/visualstudio-docs#7794]
I've followed [https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022#install-visual-studio-onto-a-client-machine-from-a-network-installation](url) to create a layout that I've xcopy'ed over to a network location on a network not connected to internet. I used `vs_Community.exe --layout C:\VSLayout --add Microsoft.VisualStudio.Component.CoreEditor --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.DataScience --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.Python --includeRecommended --includeOptional --lang en-US` to create the layout. On a client on the network, I want to install from the layout, so I ran `\\myServer\folder\vs_Community.exe --noweb`. I added the --noweb option here, and not in the command for creating the layout as the --noweb option was introduced in the chapter "Install Visual Studio onto a client machine from a network installation" in the documentation (after all the info about creating a layout). The installation quit after some minutes with an error message about not having internet connection. Did I read the documentation wrong? Should the --noweb option be added when creating the layout?

_Originally posted by @rra88 in https://github.com/MicrosoftDocs/visualstudio-docs/issues/1531#issuecomment-1068921532_

**Comment by christineruana** [comment]
@WilliamAntonRohm - how do I get the vs-installation/tech label added to this issue?

#reassign @christineruana

**Comment by christineruana** [comment]
Hi @rra88 - hmm.  It seems that you did everything right here.  When you create the layout, you need internet access so the bits can be downloaded from the internet into the layout.  However, when you install from the layout onto the client machine by invoking \\myServer\folder\vs_community.exe --noweb (on the client), you're basically telling the client to install from the layout and don't get any of the bits from the internet.  Regarding your very last question, if you add --noweb when creating the layout, then I think the layout will be empty.  

There's not enough information in your description above to diagnose exactly what is going wrong here, but from what you describe, you're doing everything right.  May I suggest that you fill out a problem report on our [developer community site](https://developercommunity.visualstudio.com/report?space=8&entry=problem).  Also, on the client machine, you'll need to collect and send us some diagnostic log files using http://aka.ms/vscollect tool and attach them to the bug report.  This will help us figure out where the problem is.  Note that the link I provided above to the Dev Community site requires you to be using VS.  If you can't get VS installed, you can file a bug report this back door way:  http://aka.ms/vs/admin/feedback.  

Hope this helps-   

Thanks,  Christine

**Comment by christineruana** [comment]
Hi @rra88 - I'm just checking in here.  Did you get the issue sorted out?  If not, did you open a ticket on the [developer community](https://developercommunity.visualstudio.com/report?space=8&entry=problem) site and attach the log files?  Note that ideally you'll provide log files from both the machine used to create the layout and a separate set of log files from the client that's having problems installing.  Can you please link to the dev community ticket here, as I haven't noticed it on that platform yet.

Thank you -  
 Christine

**Comment by rra88** [comment]
Hey Christine. I haven't been at it for a long while, but I just tried installing from the layout again and it worked! I'm not sure what I did differently this time, but it seems it was my error last time, so the issue can be closed. Thanks for the support.

**Comment by christineruana** [comment]
@rra88 I'm really glad it's working for you now.  Thank you for taking the time to provide feedback and we welcome any other suggestions you have for making layouts easier to deal with.  File them here: http://aka.ms/vs/admin/feedback.
