### ISSUE TITLE
Where is this Bootstrapper Manifest Generator???

### ISSUE THREAD

**Issue by miguelguzman** [MicrosoftDocs/visualstudio-docs#780]
I can't find the Bootstrapper Manifest Generator referred to by this article. Please, update!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f270d325-9120-a89e-2275-2486f95edbf5
* Version Independent ID: 59bd9a92-920d-be12-12cd-16877f410109
* Content: [Creating Bootstrapper Packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/creating-bootstrapper-packages)
* Content Source: [docs/deployment/creating-bootstrapper-packages.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/deployment/creating-bootstrapper-packages.md)
* Service: **unspecified**
* GitHub Login: @stevehoag
* Microsoft Alias: **shoag**

**Comment by Mikejo5000** [comment]
@miguelguzman Sorry for the slow response. I'm looking into it.

**Comment by Mikejo5000** [comment]
@miguelguzman So, the Bootstrapper Manifest Generator is a quite old legacy tool, and looks like it's no longer available. Instead, you need to manually create the bootstrapper manifest:
https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest
https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest

I'll update the docs.

**Comment by johnkellyjr** [comment]
This is useless. The Bootstrap Manifest Generator might be old, but Windows Installer needs it because you can't just copy any MS redist to a project without the public key. We don't need to know how to make a manifest file. We need to be able to use it to solve: https://social.msdn.microsoft.com/Forums/vstudio/en-US/ded089cc-a849-4dc6-a4ca-e85b75b301f6/bootstrapper-public-key-for-net-45-runtime-doesnt-match?forum=msbuild

**Comment by TroySchmidt** [comment]
The documentation currently recommended way is for us to be bundling Windows install packages directly into our installer projects.  Instead of having it reference them directly from the Windows site.  That leads to multiple sources of truth and install package bloat.  All we really need is instructions on how to generator or otherwise find the publickey given any ID like at https://www.microsoft.com/en-in/download/confirmation.aspx?id=53164... what is that publickey?

**Comment by Mikejo5000** [comment]
I'll ask about this.

**Comment by Mikejo5000** [comment]
If there's still a request to support the Bootstrap Manifest Generator (deprecated), please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

On the question of generating or finding the public key, it looks like  the reference post has a workaround (Darko's response): https://social.msdn.microsoft.com/Forums/vstudio/en-US/ded089cc-a849-4dc6-a4ca-e85b75b301f6/bootstrapper-public-key-for-net-45-runtime-doesnt-match?forum=msbuild.

If the workaround needs to be doc'ed, let me know. Otherwise, please use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) for this issue as well.
