### ISSUE TITLE
Unable to open Microsoft Docs page pointing to DirectX 11 FXC error codes, such as X3501. 

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/visualstudio-docs#7806]
I'm currently on Windows 10 Pro, Visual Studio 2022 Community (64-bit) Version 17.0.4.

I was following a DirectX 11 tutorial, when I suddenly get an error:

`FXC : error X3501: 'main': entrypoint not found`

Clicking on the error code, I get redirected to this URL page instead:

https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(keywords_removed)%26rd%3Dtrue&view=vs-2022

I'm assuming the new Microsoft Docs website didn't include FXC (Shader Effect Compiler) error codes documentations?

Here, I can only find this, which explains what "fxc.exe" is:

https://docs.microsoft.com/en-us/windows/win32/direct3dtools/fxc

But nothing related to error codes, linker errors, and `X####` error codes.

**Comment by stevewhims** [comment]
Hi, @tommai78101, when you say that you "click on the error code", are you clicking on that inside Visual Studio?

If this is to do with Visual Studio not taking you to the right page in the docs, then I would suggest that you try going to [Visual Studio developer community](https://developercommunity.visualstudio.com) and log a bug with them.

Thanks!
-Steve

**Comment by tommai78101** [comment]
I also couldn't find where X3501 error code doc page is at.

**Comment by stevewhims** [comment]
Thanks, @tommai78101! For the missing documentation, I'm investigating that internally. For the Visual Studio issue I think your issue was resolved in error (it certainly is a VS issue), so I've written to the engineer there to reconsider it as a VS issue.

Thanks!
-Steve

**Comment by tommai78101** [comment]
@stevewhims Thank you for looking into this issue.

**Comment by stevewhims** [comment]
For the missing documentation, the feature team is aware, and they've created an internal work item to track that. I've added to that work item a link to this GitHub issue.

Incidentally, I can't manage this GitHub issue (I can't close/reopen it). That's probably because it was opened in a repo (https://github.com/MicrosoftDocs/visualstudio-docs/) that I don't work in.

So I'll go ahead and unassign myself from this issue. But feel free to create a new issue (just about the missing documentation) in https://github.com/MicrosoftDocs/win32, if you like. That way I'll be able to close and reopen it, but it'll remain assigned to me. In any case be assured that fixing this is on our radar.

Thanks!
-Steve

**Comment by stevewhims** [comment]
@WilliamAntonRohm, please close this if you're able to. I can't close nor assign.

**Comment by tommai78101** [comment]
@stevewhims Unfortunately, I don't think that repository allows anyone to create an issue. I can't create an issue on the MicrosoftDocs/win32 repository. Nonetheless, it's great that it's being tracked internally. Thanks for the update.
