### ISSUE TITLE
Remote debug pythonon Raspberry 

### ISSUE THREAD

**Issue by gboysen** [MicrosoftDocs/visualstudio-docs#781]
Well I tried everything but couldn't get PTVS debugging to work I can connect vie SSL but no debugger and PTVS tools did not connect ! 
Given that c++ hasb plug-in and go tool I hope you can make this better soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904b359d-de5e-adf4-9966-e1ab5be204be
* Version Independent ID: 564c35dd-ac25-8db4-ea48-e76476c50f89
* Content: [Debugging Python code on remote Linux computers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines#feedback)
* Content Source: [docs/python/debugging-python-code-on-remote-linux-machines.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/debugging-python-code-on-remote-linux-machines.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the feedback. The best place for this issue https://github.com/Microsoft/PTVS/issues, as it may involve feature work. Check if your issue is already covered with https://github.com/Microsoft/PTVS/issues/763. In the meantime, I'm closing this doc issue with the expectation that you'll repost on the PTVS issues list.

**Comment by gboysen** [comment]
Thanks I will have a look later and keep you posted.
