### ISSUE TITLE
Outdated Documentation: "Enable full solution analysis" is not in Tools Options anymore

### ISSUE THREAD

**Issue by gmarbury** [MicrosoftDocs/visualstudio-docs#7830]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f7e6c9-3f47-4caa-b69f-ae6393bde555
* Version Independent ID: dc59c52a-163f-40fb-c84d-ba7b1b8118b4
* Content: [Tips to improve performance - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-performance-tips-and-tricks?view=vs-2022)
* Content Source: [docs/ide/visual-studio-performance-tips-and-tricks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/visual-studio-performance-tips-and-tricks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@gmarbury You're right, and thanks for bringing this to our attention. We've updated the page so that the Visual Studio 2022 and Visual Studio 2019 versions don't show that text (the option is still available in Visual Studio 2017). We'll close this issue now with our thanks to you for your help in improving the documentation!
