### ISSUE TITLE
Opera GX in Create an ASP.NET Core app with React - Visual Studio

### ISSUE THREAD

**Issue by Hantick** [MicrosoftDocs/visualstudio-docs#7885]
Hi!
Is there any option to launch an Opera GX browser instead of chrome or edge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Hantick -- Hantick, thank you for your question.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

This seems like a product-related issue rather than a documentation issue, ,so I am closing it now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @Mikejo5000 for awareness

**Comment by Mikejo5000** [comment]
@Hantick You may be able to switch to another browser using the drop-down next to the Start debugging button and choosing **Browse with...** and then adding your browser. Not sure what kind of debugging support you will get.

![image](https://user-images.githubusercontent.com/11948536/162786340-7edee7fe-03cb-4bee-ba42-4302357fd395.png)
