### ISSUE TITLE
"Advanced example for containers" installtion procedure doesn't work

### ISSUE THREAD

**Issue by JanWosnitza** [MicrosoftDocs/visualstudio-docs#7907]
I tried to install VS BuildTools in a container, but using the descriped method didn't work. The setup finishes without downloading or installing anything. (https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022)

This is the line in question:

    && (start /w C:\TEMP\Install.cmd vs_buildtools.exe --quiet --wait --norestart --nocache modify `

And this how I had to modify it to get it installing inside the `mcr.microsoft.com/windows/server:ltsc2022` image:

    && (start /w C:\TEMP\Install.cmd vs_buildtools.exe install --quiet --wait --norestart --nocache `

notice the location of `modify` seems to be wrong according to the help output of "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe". The dash-dash parameters are parsed by the method (`modify` in the original line) and are not global.
Also it should `install` as the VS Buildtools are not yet installed. (but didn't test if `modify` works in this case too)

Best
Jan Wosnitza

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by TimShererWithAquent** [comment]
@JanWosnitza Thanks for your input -

**Comment by anandmeg** [comment]
#reassign: @milarso81
similar to https://github.com/MicrosoftDocs/visualstudio-docs/issues/7278

**Comment by milarso81** [comment]
The issue here is that the image base used in the example docs does have build tools installed already so modify needs to be used in that case, while `mcr.microsoft.com/windows/server:ltsc2022` does not have build tools installed so you are correct the `install` command would be needed in that case. I think the example works when you use the same image base, is the request then we have an example for `mcr.microsoft.com/windows/server:ltsc2022`?

**Comment by milarso81** [comment]
The other issue with the install script, we are using start instead of call when running the script to try and collect logs if the install fails. That brings up anther command window that is waiting to be closed but does not when there are no errors because the script does not exit. It also does not output anything to stdout since it is running in a different console in the container. So we can fix by updating the example.

**Comment by milarso81** [comment]
The example docs will use servercore and install command and it should work going forward, update should be up later today. #please-close

**Comment by milarso81** [comment]
@JanWosnitza please create anther issue for the process isolation problem. Thanks!
