### ISSUE TITLE
Add version a certain feature or warning was added

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/visualstudio-docs#797]
Sometimes when looking at a warning or compiler flag it would be really useful if we could know when it was added to the compiler

**Comment by gewarren** [comment]
@tiagomacarios thanks for the feedback. Are you talking about any particular compiler, e.g. csc.exe?

**Comment by tiagomacarios** [comment]
cl.exe c++ compiler

**Comment by gewarren** [comment]
@corob-msft or @mikeblome can you look at this suggestion for the C++ compiler docs?

**Comment by corob-msft** [comment]
For very recent error additions and deletions, you may see an annotation in an individual error article such as "This error was introduced in Visual Studio 2017 version 15.3" or "This error is no longer reported starting in Visual Studio 2017." Unfortunately, there is no commonly available  source for when errors were introduced before about VS2015 update 3. In this case, your best clue may be when the error message appears in the documentation on MSDN. One caveat is that error documentation has sometimes lagged the compiler versions, in a few instances by quite a bit. 

Warnings, on the other hand, are super easy. Check out [Compiler warnings by compiler version](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version). It'll tell you everything you want to know about when a warning was introduced, all the way back to VS 2002.

All the compiler options introduced since about VS2015 should have a phrase in the option documentation such as "This option was introduced in Visual Studio 2017 version 15.1" or "This option is deprecated starting in Visual Studio 2017." For convenience, there's a list of the current [deprecated compiler options](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-by-category#deprecated-and-removed-compiler-options) available, but not a one-stop listing of new or updated options - you have to look at the individual options for that information. 

We're probably not going to add historical information to existing error messages,  because it's a huge data set with limited application, and would involve touching thousands of topics. Likewise, we probably won't add documentation for which pre-VS 2015 version of the compiler first supported a particular option. There is a limited work-around, because this is information you can find out by comparing the documentation by version.

That said, I'll take your suggestion for an easier way to find this information under advisement. I know it could be helpful when updating old projects to use the latest toolset, and we're interested in making that as simple and straightforward as we can.

**Comment by tiagomacarios** [comment]
@corob-msft It would be nice if you had that as a field, not just text. This way one knows where the information is.

I had this issue a couple of times. The last time was last week When I was looking for when C26438 was added and as you can see there is no mention in the help about when it was. I had to look around to figure out it was in 15.5.
https://docs.microsoft.com/en-us/visualstudio/code-quality/c26438
https://blogs.msdn.microsoft.com/vcblog/2017/11/15/c-core-check-improvements-in-visual-studio-2017-15-5/
