### ISSUE TITLE
wirklich eure Scheiss seiten sind ein WItz 

### ISSUE THREAD

**Issue by Daniel-Majunke** [MicrosoftDocs/visualstudio-docs#8117]
man kann die verfickte json genauso 1 zu 1 rauskopieren und der Compiler meckert, unglaublich ! Von euren Codebeispielen die nicht gerade nur 3 Zeilen lang sind funktikonieren 1 % . Fickt euch und eure Seiten.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68483bc8-45dc-fc2e-b289-2901a70461ff
* Version Independent ID: 5167502a-bd55-8927-5656-1c4f107884d7
* Content: [Create an ASP.NET Core app with TypeScript - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2022)
* Content Source: [docs/javascript/tutorial-aspnet-with-typescript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-aspnet-with-typescript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Daniel-Majunke -- Daniel, vielen Dank für Ihr klares und genaues Feedback.  Ich schließe dieses Problem jetzt.

**Comment by Mikejo5000** [comment]
@Daniel-Majunke I retested the first half of the article on VS 17.2.1 and followed the steps exactly (up to build/run). Everything worked just as described. However, I believe there could easily be confusion over choosing a project template in the **Create a new ASP.NET Core MVC project**. When you create a project, it is easy to choose **ASP.NET Core Web App** instead of **ASP.NET Core Web App (Model-View-Controller). The first is a Razor template, and won't work at all with the steps. I will add more clarity on this point.
