### ISSUE TITLE
References are mysteriously broken

### ISSUE THREAD

**Issue by IsaacSherman** [MicrosoftDocs/visualstudio-docs#8127]
This did not solve my problem.  The references are stored with relative paths in the project file, they haven't been moved or deleted, there is just a yellow triangle and the program refuses to build.  I added the reference path as suggested. It didn't work.  In the project file I added in an absolute Hint path to the dll in question.  It didn't change anything either.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f552234-e74f-1cfc-848c-ba15571b35c6
* Version Independent ID: 2c89a49a-0aac-15bf-fb17-e644dfd115cc
* Content: [Troubleshoot broken references - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/troubleshooting-broken-references?view=vs-2022)
* Content Source: [docs/ide/troubleshooting-broken-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/troubleshooting-broken-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@IsaacSherman -- Isaac, thank you for your feedback, and sorry to read of your difficulty.  It looks like you're having an issue with the product itself, rather than an issue with the documentation.  If Visual Studio is not taking into account the reference path nor the Hint path, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report this issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

Also, consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @TerryGLee for awareness
