### ISSUE TITLE
There should be a list of language/frameworks supported by v15

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#815]
Like c#7 features can be built with v15, or what versions of .net can bu built with it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb723883-dd62-0c53-8617-7bc867b9aaf3
* Version Independent ID: de1ff8ce-885c-9df0-077c-48c82f163c83
* Content: [What's New in MSBuild 15 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0)
* Content Source: [docs/msbuild/what-s-new-in-msbuild-15-0.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/what-s-new-in-msbuild-15-0.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by vasiliy-kuznetsov** [comment]
Absolutely, basically I came to this page to figure out which minimum version of MS Build can build .net standart 1.3 project.

**Comment by Mikejo5000** [comment]
Sounds like the request is for a matrix of features and language/frameworks. @rainersigwald for comment.

**Comment by CaryFan** [comment]
Agree. For example, by default, which C and C++ versions and runtimes are supported. It can become confusing because MS is not the owner of C and C++, unlike C#.

**Comment by rainersigwald** [comment]
Unfortunately, I don't think we can do this in a reasonable way. It's a very complicated question (despite being easy and reasonable to ask for!) because MSBuild is very general.

Even without getting into extreme edge cases (you can always call an executable from MSBuild, so you could theoretically use the first release of MSBuild from 10+ years ago to run the newest `csc.exe` on brand-new code), there's an additional dimension to the matrix which is "what Visual Studio workloads must be installed?"

To take a stab at the questions asked explicitly here:

* C# feature compatibility is dependent on the version of the C# compiler used. C# 7.0 was first supported with [Roslyn 2.0.0](https://github.com/dotnet/roslyn/releases/tag/Visual-Studio-2017), which shipped with Visual Studio 2017 (version 15.0). The version of MSBuild that shipped with that release was `15.1.548`. C# 7.0 can only be compiled with a Visual Studio (or Build Tools) installation newer than 15.0.
* Building an assembly targeting .NET Standard 1.3 requires the .NET Core SDK version 1.0.0 or higher. This could be downloaded as a standalone environment on Windows, macOS, and Linux, or installed as part of the ".NET Core Cross-Platform Development" workload in Visual Studio. In that release, no Build Tools installer supported .NET Core--that support was added in a later Build Tools release (I want to say 15.3 but I'm not totally sure).
* C and C++ support is determined by the C++ compiler, and is very complicated because the compiler can and does partially implement a specification, and has been improving in patch releases--for instance,  the compiler that shipped with Visual Studio 15.7 [announced C++17 standard conformance](https://blogs.msdn.microsoft.com/vcblog/2018/05/07/announcing-msvc-conforms-to-the-c-standard/). No MSBuild changes were required for that, but the end-to-end experience only works in Visual Studio 2017 15.7 and higher, which shipped with MSBuild 15.7.179.

In addition to languages and features supported by Microsoft as part of Visual Studio releases, MSBuild has a plug-in model that allows third parties to support arbitrary languages and runtimes. In those cases, it's the version of the SDK that matters, but that SDK may have a dependency on features of MSBuild introduced in a specific MSBuild version.

**Comment by StingyJack** [comment]
> * C# 7.0 can only be compiled with a Visual Studio (or Build Tools) installation newer than 15.0.

@rainersigwald - thats the general level of detail that I would have liked to have available via some simple matrix. I wan't looking for all the possibilities, just why I could not build a c# project that uses `$"{style}"` of string interpolation with a tfs 2015 build task (the task uses v14 unless you re-point it). The error message was less than helpful in figuring out what the problem was.
