### ISSUE TITLE
The docs do not show where to get the PythonConsoleApp template

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/visualstudio-docs#8242]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adec9eb-97b5-4f9f-77d6-a9eb9130ed10
* Version Independent ID: 90fb8ff4-4ccd-98c1-92c2-02a33252c681
* Content: [Python in Visual Studio tutorial step 1, create a project](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-01-create-project?view=vs-2022)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-01-create-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/tutorial-working-with-python-in-visual-studio-step-01-create-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
@kgreed -- Kirsten, thank you for your feedback.  Please try this section:
- [Step 1: Create a new Python project](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-01-create-project?view=vs-2022#step-1-create-a-new-python-project), and see its step 3.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by kgreed** [comment]
@WilliamAntonRohm Hi there.
I cannot follow step 3 because the template is not present.
https://stackoverflow.com/questions/72814021/missing-pythonconsoleapp-template

**Comment by WilliamAntonRohm** [comment]
@kgreed -- Kirsten, thank you for your follow-up.  This seems to be a product issue rather than a documentation issue.  Please report it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
