### ISSUE TITLE
Specify explicit version for "latest" component

### ISSUE THREAD

**Issue by danstur** [MicrosoftDocs/visualstudio-docs#8272]
It is not clear if there is any way to specify an explicit version for the - at the time - latest version of a component. 

This causes the following problem for me:
Currently `Microsoft.VisualStudio.Component.VC.ATLMFC` maps to `C++ MFC for latest v143 build tools (x86 & x64)` , but as soon as VS2023 (or similar) is released this could easily map to v144 build tools, which isn't what I want in a .vsconfig file that describes the required components for my solution (since I will still require the old 143 build tools until I update). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe411145-ff47-dfe5-1e57-db8d54671b58
* Version Independent ID: 4dac6d72-8c3c-dec8-d473-a2902e4e1fb9
* Content: [Visual Studio Professional workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022&preserve-view=true)
* Content Source: [docs/install/workload-component-id-vs-professional.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-professional.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@danstur -- Daniel, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@anandmeg -- Megha, please look into this issue.

**Comment by anandmeg** [comment]
@danstur - thanks for sharing your feedback!

The tools along with their versions are explicitly listed at the bottom of the page in the [Unaffiliated components](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022&preserve-view=true#unaffiliated-components) section. By using one of those explicit component names (instead of Microsoft.VisualStudio.Component.VC.ATLMFC), you can explicitly specify a particular version of the tools.

Hope this helps with your question. Please let us know if you have any other questions. Thanks!
