### ISSUE TITLE
missing most popular synchrnization seequence

### ISSUE THREAD

**Issue by alex4747-pub** [MicrosoftDocs/visualstudio-docs#8325]
[Enter feedback here]
It is so bad that I wondering how Microsoft survived that long.

Then normal local-remote sync sequence is

git commit
git fetch
git rebase origin/branch-name
git push --force-with-lease

It is not even listed as option. The proposed pull/push combination may easily create either unwanted changed or unnecessary or illogically ordered revisions when there are 1000s of software engineers working on the same project.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50dd5a2-e4da-2ed6-434a-b90c1c4bdf79
* Version Independent ID: f50dd5a2-e4da-2ed6-434a-b90c1c4bdf79
* Content: [git fetch, pull, push, & sync - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/version-control/git-fetch-pull-sync?view=vs-2022)
* Content Source: [docs/version-control/git-fetch-pull-sync.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-fetch-pull-sync.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TimShererWithAquent** [comment]
Thanks @alex4747-pub - We'll look into changes for the article.

**Comment by TimShererWithAquent** [comment]
@alex4747-pub 

It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our "Suggest a feature" option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

**Comment by alex4747-pub** [comment]
Interesting, the proper sequence of the git commands is doable from vs2019 no new features are required. The problem is that for whatever reason you recommend a far suboptimal may to synchronize a local repository with a remote.

**Comment by WilliamAntonRohm** [comment]
@alex4747-pub -- Alex, thank you for your follow-up.
