### ISSUE TITLE
Visual Studio 2022 for Mac - No extension manager

### ISSUE THREAD

**Issue by ademclk** [MicrosoftDocs/visualstudio-docs#8382]
How can I install extensions? Couldn't find anything IDE not recognizing .vsix files.

**Comment by TimShererWithAquent** [comment]
@ademclk Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 

-	[Visual Studio on Q&A](https://docs.microsoft.com/answers/products/vs) 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
