### ISSUE TITLE
vue.config.js doesn't have a "target" parameter

### ISSUE THREAD

**Issue by thobbsinteractive** [MicrosoftDocs/visualstudio-docs#8390]
The example completely falls down when looking at the vue.config.js portion of the documentation. Not only isn't there a "target" parameter in the default generate vue.config.js, you don't show us what it should look like at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@thobbsinteractive -- Tim, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@thobbsinteractive I tested this on 17.3.0 with both the JS and TS Standalone Vue template, and I see the `target: 'https://localhost:5001',` section in vue.config.js for both projects. What version of VS are you using?  Since I can't repro the issue, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
I will close this and we can re-open if there is something more for me to look at here. Thanks!
