### ISSUE TITLE
Support for COM/VSTO addins in O365

### ISSUE THREAD

**Issue by kapilkathuria** [MicrosoftDocs/visualstudio-docs#8394]
[Enter feedback here]
Hello,

This is not really a feedback, in-fact I wanted to ask a question. I didn't see any other option to comment/ask question on article & hence thought I can try asking here.

My Question: with Web Add-in available, what is Microsoft's roadmap for COM/VSTO addins in future? Are there any plan to stop supporting COM/VSTO add-in in roadmap or is Microsoft looking to keep supporting COM/VSTO add-ins as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2cccf4-e8b1-aa69-b3ae-50d27b2a4d50
* Version Independent ID: 9c3a644a-f267-4092-24be-2566788e7500
* Content: [Walkthrough: Create your first VSTO Add-in for Outlook - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook?view=vs-2022&tabs=csharp)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@kapilkathuria -- thank you for your questions.  This repo is solely for documentation issues, and this seems product-related.  Please add this issue here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

Also, consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

cc @John-Hart for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
