### ISSUE TITLE
The Merge Editor window doesn't appear

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/visualstudio-docs#8417]
[Enter feedback here]
My colleague has encountered a merge conflict when he pulled changes from the remote. He is using VS 2022 Professional. There is no "Open Merge Editor" when he selects one of the files under "Unmerged Changes". And double-clicking a file doesn't go into the merge editor.

Help, please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Version Independent ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Content: [Resolve merge conflicts in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022)
* Content Source: [docs/version-control/git-resolve-conflicts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-resolve-conflicts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@houghj16 FYI on this

**Comment by WilliamAntonRohm** [comment]
@Rod-in-NM -- Rod, thank you for your feedback.  This appears to be product-related rather than documentation-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Rod-in-NM** [comment]
OK, thank you @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@Rod-in-NM -- Rod, you're welcome!
