### ISSUE TITLE
When Using "Find All References", What Exactly is the "Clear All Filters" Button in the Results Pane

### ISSUE THREAD

**Issue by Kevin-Andrew** [MicrosoftDocs/visualstudio-docs#8492]
The documentation for **Find references in your code** https://learn.microsoft.com/en-us/visualstudio/ide/finding-references?view=vs-2022, has the following:

> * Remove any filters on the returned results by choosing the **Clear All Filters** button.

And then not another mention about it on the page.

How is that of any help? That's nothing more than what the tool tip says!

I now have a problem with Visual Studio 2022 where every time I use the **Find All References**, it's not showing all of the references, and the results pane shows the filter button as enabled. Yet, to my knowledge, I've never specified any filters. How could I? The documentation is incomplete and doesn't explain what they are, where they come from, or how to use them.

So now, every time I use the **Find All References**, I have to remember to click the **Clear All Filters** button to make sure I'm not missing anything.

![image](https://user-images.githubusercontent.com/22459191/191619672-fd5dfcdb-f387-4dd0-86cc-bcdf133d06d8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0ff86d8-c851-8bfa-3357-09350f76bd95
* Version Independent ID: af88c525-6027-4e0e-7417-23e16f386f21
* Content: [Finding references in your code - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/finding-references?view=vs-2022)
* Content Source: [docs/ide/finding-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/finding-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by Fjaler** [comment]
I see exactly the same problem. Without restarting PC or Visual studio This feature just stopped working over night. Now I press "Clear all filters" on EVERY search for all references. May even be deal breaker for VS. Kills workflow hard!

**Comment by WilliamAntonRohm** [comment]
@Fjaler -- thank you for clarifying.  Please add this as a product issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by Kevin-Andrew** [comment]
I would hope that the documentation for this can be created and included in some upcoming release. I would hope that this item isn't just closed due to inactivity. I would think and hope that you would want to offer complete documentation on your product.

**Comment by TerryGLee** [comment]
@Kevin-Andrew We've added some additional info to the page about the intent behind the **Clear All Filters** button, but the behavior you describe is a problem with the product itself rather than with the documentation. To get this product issue addressed, please consider reporting it by using a different venue. Specifically, the following:

- Report product issues to the engineering team via the [Report a problem](how-to-report-a-problem-with-visual-studio.md) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.
- Track product issues and engineering team responses in the [Visual Studio Developer Community](https://aka.ms/feedback/suggest?space=8).

Meanwhile, we'll close this issue here, with our thanks to you for your feedback.

**Comment by Kevin-Andrew** [comment]
Thanks.
