### ISSUE TITLE
misleading and potentially dangerous "Note" at the bottom

### ISSUE THREAD

**Issue by sbalderrama** [MicrosoftDocs/visualstudio-docs#8610]
The "NOTE" at the bottom explaining "Take Incoming" for keeping "all of your changes" doesn't mention that in the process you will lose all the changes from "current".   This should be clear so people don't make a mistake.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Version Independent ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Content: [Resolve merge conflicts in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022)
* Content Source: [docs/version-control/git-resolve-conflicts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-resolve-conflicts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@houghj16 FYI

**Comment by TerryGLee** [comment]
@sbalderrama Thanks for letting us know. Upon review, the Note at the bottom of the page doesn't say anything about “Take Incoming”—in fact, it expressly mentions only “Keep Current”—but the screenshot in the Note has “Take Incoming (Remote)” highlighted along with “Keep Current (Local)”. We edited the screenshot and its alt-text so that it highlights and mentions only “Keep Current (Local)”. We'll close this issue now with our thanks for your help in improving the documentation!
