### ISSUE TITLE
This article is effectively useless

### ISSUE THREAD

**Issue by jmarolf** [MicrosoftDocs/visualstudio-docs#863]
This article is effectively useless.  It tells be what the AppliesTo element does, but without a list of Capabilities there is no way for me to know how to author this correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177e2c60-627c-a81e-d8a4-906c360a7e53
* Version Independent ID: 449e778c-7ac8-e8a7-16cd-16ddaa2502d4
* Content: [AppliesTo Element (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/appliesto-element-visual-studio-templates)
* Content Source: [docs/extensibility/appliesto-element-visual-studio-templates.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/appliesto-element-visual-studio-templates.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
