### ISSUE TITLE
Just My Code is not disabled by Enable step into .NET Framework code

### ISSUE THREAD

**Issue by sebastienros** [MicrosoftDocs/visualstudio-docs#8648]
> If you had Just My Code enabled, a warning dialog box tells you that Just My Code is now disabled. Select OK.

I selected the option, but the dialog didn't show up, so the feature didn't work until I find this page and ensure the "Just My Code" option was disabled (it was not).

```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 6.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e04e717-61a6-99eb-60cd-34263fa597b5
* Version Independent ID: 3ee15675-d5bd-f3c9-fb85-1b65b3d71897
* Content: [Debug .NET Framework source - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2022)
* Content Source: [docs/debugger/how-to-debug-dotnet-framework-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-debug-dotnet-framework-source.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I test this on VS 2022 version 17.5 Preview 5, and the dialog box did appear. It may have been fixed in an upgrade. If you continue to experience the problem after upgrading, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
