### ISSUE TITLE
Sdk-style project locations?

### ISSUE THREAD

**Issue by chipplyman** [MicrosoftDocs/visualstudio-docs#8660]
All the templates under Common7\IDE\ProjectTemplates\CSharp appear to be for legacy-style projects.  Where can I find the templates for sdk-style projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08f8f1c1-ffab-4a28-28e0-01ab59f8f827
* Version Independent ID: fb87ecb9-aaf2-a693-a30b-f5a4aea01ba8
* Content: [Locate templates - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-locate-and-organize-project-and-item-templates?view=vs-2022)
* Content Source: [docs/ide/how-to-locate-and-organize-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-locate-and-organize-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@chipplyman Does the following page include the info you seek? 

     [.NET default templates](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates)

**Comment by chipplyman** [comment]
It does not.

Through further research and exploration, I was able to determine that these templates live within .nupkg files under %PROGRAMFILES%\dotnet\templates.

**Comment by TerryGLee** [comment]
@chipplyman We appreciate your response, and for taking the time to include the answer you identified so that others who might have a similar question can find the information, too. Meanwhile, we updated the page you referenced with further links to SDK-style template information, in hopes that it might also help those who are seeking similar information. We'll close this issue now along with our thanks to you for your help with improving the Visual Studio documentation!
