### ISSUE TITLE
Side by side Stable and Beta/Alpha channels

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/visualstudio-docs#871]
I think something has to be written about having different versions side by side, because it's not clear what happens when switching from stable to beta and vice versa, are the different channel versions still maintained side by side or downloading one channel version remove others?

As an example, suppose the developer is using Visual Studio for Mac with a Stable version on a Mac and a Visual Studio Preview on a Windows PC. When trying to pairing the PC to the Mac, a warning on the PC side ask the user to update the Mac with the same version of Xamarin that is installed on the PC, stating that this will overwrite the Xamarin.iOS version on the Mac.

Is this really true or it refers to the same channel installed in the PC that can be/is present in the Mac?

Because if it really replace the Mac version with the PC version, regardless of the channel, then using the Visual studio for Mac after pairing will put the developer in an unstable state where the iOS version is Beta (or Alpha, depending on what was actually used by Visual Studio Preview on the PC side) while the Android is still related to the Stable channel!

If true (and I don't think so and hope this is not the case) some urgent work has to be done to enable side by side coexistence of Stable / Beta / Alpha bits so that after pairing the Visual Studio Preview working on the PC can pair and use preview bits on Mac to successfully build while the Visual Studio for Mac can still use stable bits for her needs.

Otherwise, if things already works side by side (as I do believe) this page documentation shuld clearly explain it, and the warning message on Visual Studio (on the PC side) has to be changed to better explain it, opening a specific issue on Visual Studio feedback site.

### UPDATE
After pairing my PC to the Mac and then going back using the Mac, it asked me to reinstall stable bits for Xamarin.iOS, then going back to PC and trying again the pairing, it asked me to install the beta version. So it turns out that I was wrong assuming SxS coexistence. This is bad and I hope someone will fix it, soon or later (depending on how many developers are in my situation and really needs it).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f3608c-d434-e892-85db-032af35f919b
* Version Independent ID: d546284e-5cd8-6a41-790b-5302b628d357
* Content: [Updating Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/update)
* Content Source: [mac/update.md](https://github.com/Microsoft/visualstudio-docs/blob/master/mac/update.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
Hi @ncarandini, I think the best place for this to be addressed is actually in the Xamarin docs, rather than in the IDE documentation. While there is [this](https://docs.microsoft.com/xamarin/ios/get-started/installation/windows/connecting-to-mac/#xamarinios) content in the Pair to Mac docs, I've spoken to the team who have agreed that there could be more clarification and an internal issue has been created to track it. 

While it is possible to run two VSMac installs SxS, not all the dependencies (such as Mono) run SxS. Therefore we don't recommend SxS installs. I'd encourage you to give developer feedback on this issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html).

Thanks!
