### ISSUE TITLE
msbuild /t:publish does not behave as described

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#8853]
I think there are multiple issues with this page. It doesn't correspond to reality in several ways, as far as I can tell. But to keep things focussed I'll start with a single issue.

The page says _For .NET Core 3.1 and .NET 5 and later [...] you need to provide an additional property for the publish profile on the MSBuild command line._ This isn't true. you don't need to provide the ` /p:PublishProfile=` option. If you don't provide it, some kind of publish takes place anyway, but I'm not sure what configuration is used. This should be documented.

If you do provide the option, but give a profile name which doesn't exist, the build 'succeeds' anyway but with subtly different behaviour from if you hadn't given any profile name.

If you provide a publish profile name that _does_ exist, it seems like only some of the contents of that profile are respected and others are ignored. For example, `PublishDir` and `PublishUrl` are ignored, so it took me a long time to discover where the publish output was actually going.

I'm not sure if these should be considered bugs in `msbuild` or not, but at least the documentation should describe the current behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1672c325-b08a-dbc0-0e3e-31c832753613
* Version Independent ID: c479d585-37bb-795d-1e1c-4833c2262db6
* Content: [Building ClickOnce Applications from the Command Line - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022)
* Content Source: [docs/deployment/building-clickonce-applications-from-the-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/building-clickonce-applications-from-the-command-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Related to https://github.com/MicrosoftDocs/visualstudio-docs/issues/3708#issuecomment-1383086631

**Comment by Mikejo5000** [comment]
Looking at a possible edit based on new comments here:
https://developercommunity.visualstudio.com/t/Clickonce-for-NET-Core-copies-all-files/1500772#T-ND10253874

**Comment by Mikejo5000** [comment]
Doc update should be live by EOD today, 1/19/23

**Comment by sujitnayak** [comment]
The issue of publish not failing when PublishProfile is not provided or is invalid is being tracked here for a future .NET SDK release:
https://github.com/dotnet/sdk/issues/28370

With respect to the comment about PublishDir and PublishUrl, these 2 properties have different behaviors. When Publishing is started in VS IDE, it invokes msbuild to publish artifacts into the PublishDir location. After this msbuild step is completed, Visual Studio will then publish ClickOnce specific artifacts to the location pointed to by PublishUrl.  This second step runs inside the Visual Studio process.

Since PublishUrl property is not used in the msbuild step, it is expected that it will be ignored when you invoke msbuild directly to do the publish from the command line. The PublishDir value that msbuild uses as the destination for the publish should come from the PublishDir property in the .pubxml file but you can also override it on the msbuild command line with the /p switch. If you do that, the publish output will go into that overridden location.

**Comment by HughWarrington** [comment]
@sujitnayak thanks for the info! It would be really handy if this was in the docs too.

I would suggest that command-line publish is different enough between .NET Framework and .NET/Core that they should be separate pages. That would make it easier as a reader. At the moment the differences are sprinkled throughout the document.

**Comment by WilliamAntonRohm** [comment]
@sujitnayak, @HughWarrington -- Sujit, Hugh, thank you for your followup.

**Comment by Mikejo5000** [comment]
@HughWarrington It looks like most of Sujit's comments on the subject apply to .NET Framework as well. But in general there are a fair number of differences, yes. I will review the article.

**Comment by Mikejo5000** [comment]
Decided to refactor into two articles, per suggestion. New article:
https://learn.microsoft.com/en-us/visualstudio/deployment/building-dotnet-clickonce-applications-from-the-command-line?view=vs-2022
