### ISSUE TITLE
"AutoUnify=True" And "AppconfigFile is not empty" Can Be Met at the Same Time in ResolveAssemblyReference Task

### ISSUE THREAD

**Issue by Monrother** [MicrosoftDocs/visualstudio-docs#8855]
From the document in https://learn.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task?view=vs-2022, it says that `AutoUnify` must be `false` when `AppConfigFile` is specified. While, actually, when doing build, if this condition is not met (`AutoUnify` is `true` and `AppConfigFile` is specified), it works well and maybe this is what users sometimes expect (unify the conflicts and merge with the contents in App.config, especially when there's conflicts for unresolved assembly).

**Comment by ghogen** [comment]
@Monrother 
Thanks for submitting  your feedback.

MSBuild sources indicate that it's an error for AppConfigFile to be specified when AutoUnify is true.
See https://github.com/dotnet/msbuild/blob/bac7691b89aac9745564265e24158a25a36524b2/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L643
and
https://github.com/dotnet/msbuild/blob/bac7691b89aac9745564265e24158a25a36524b2/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L676

MSBuild is an open source project, so you can enter an issue at https://github.com/dotnet/msbuild with a suggestion to reconsider this, but the documentation should reflect the design intentions of MSBuild as reflected in those comments until someone decides otherwise.
