### ISSUE TITLE
The tools option does not appear when opening a new version of VS code.

### ISSUE THREAD

**Issue by Caleb-Joo** [MicrosoftDocs/visualstudio-docs#8877]
In the tutorial for how to open the developer command prompt it says to open tools in vs code. However, tools is not in the top bar when a new version of vs code is downloaded and launched.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 513f1e35-aba1-8b92-845e-1ed4ccad8e62
* Version Independent ID: 45eb46ce-a9b1-f141-5a97-c448b9349c48
* Content: [Command-line shells & prompt for developers - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022)
* Content Source: [docs/ide/reference/command-prompt-powershell.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/command-prompt-powershell.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Caleb-Joo We appreciate your feedback. The page you refer to is specifically for Visual Studio rather than VS Code. To make sure that that's move evident to all, we've added a Tip note to the page, which will be published later today, that says the following:

"This article describes how to use the command-line shells in [Visual Studio](https://visualstudio.microsoft.com/#vs-section). If you're looking for the equivalent in [Visual Studio Code](https://visualstudio.microsoft.com/#vscode-section)&mdash;also known as **VS Code**&mdash;see [Command Line Interface (CLI)](https://code.visualstudio.com/docs/editor/command-line)."

We'll close this issue now, with our thanks to you for your help with improving the Visual Studio documentation!
