### ISSUE TITLE
Type can more have values than the doco captures

### ISSUE THREAD

**Issue by VaclavK** [MicrosoftDocs/visualstudio-docs#889]
e.g. ProjectGroup

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae0aa369-2cc7-8452-dc52-e75f19ac6a5e
* Version Independent ID: 41e7734f-83ef-afa7-5e15-03b0a97929ab
* Content: [VSTemplate Element (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-ie/visualstudio/extensibility/vstemplate-element-visual-studio-templates)
* Content Source: [docs/extensibility/vstemplate-element-visual-studio-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vstemplate-element-visual-studio-templates.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by kadorken** [comment]
Ha. Just figured this out and was going to make same comment. Should have scrolled to bottom first.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
