### ISSUE TITLE
"remove unused packages" is not showing in visual studio <2019 16.11.23>

### ISSUE THREAD

**Issue by nasusonetrick** [MicrosoftDocs/visualstudio-docs#8893]
even by right clicking on project name or dependencies node in Solution Explorer in visual studio 2019 pro <16.11.23>
"remove unused References" is not showing  !

i also checked ( Tools -> Options -> Text Editor -> c# -> Advanced -> [Show "Remove Unused References .... "] )
and its enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2019)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/remove-unused-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@nasusonetrick -- thank you for your feedback.  This appears to be a product issue, rather than a documentation issue.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

Also, consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
