### ISSUE TITLE
Restore with local undo

### ISSUE THREAD

**Issue by JonnoWonno** [MicrosoftDocs/visualstudio-docs#8917]
It may be helpful to document how to revert a (pushed) commit and restore related files locally (under local git changes) from the particular erroneous/reverted commit.

In other words, how would I (through git, and especially VS) go about recovering from having, for instance, 10 files with (pending) changes, intending to only commit 2 - I accidentally "Commit All and Sync" (ie. forgot to stage) and need to revert to the previous status/scenario (remote and local), of having those 10 files with changes still pending showing locally under git changes (and the change undone remotely).

There may be an easier way to do it - but I had to resort to: 
1. Reverting change
2. Viewing initial erroneous commit 
3. Individually  manually copying and replacing content in local files. 
This method is prone to mistakes, since you may end up manually replacing content of an unintended file (ie. in the case of a similar filename or same filename in a different folder). 

I did not see an option to restore file locally (ie. make it changed/pending staged) from the initial erroneous commit, even when viewing that commit.

A kind of "Revert Remote and Restore Local".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Version Independent ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Content: [Manage Git repos in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/version-control/git-manage-repository?view=vs-2022)
* Content Source: [docs/version-control/git-manage-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-manage-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @houghj16
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@JonnoWonno -- Jonathan, thank you for your detailed feedback.  You're welcome to add this as a feature request:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@houghj16 -- Jessie, please look into this issue.

**Comment by TerryGLee** [comment]
@JonnoWonno I've checked in with the engineering dev team, and they've asked that if you're willing to do so, please submit this feedback by using the [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) tool directly in Visual Studio (from the menu bar, select **Help** > **Send Feedback** > **Suggest a Feature**). After you do so, you can then view its progress in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com), where others can also view and upvote it, too. We'll be sure to document any expanded functionality when it becomes available. Meanwhile, we'll close this issue here and extend our sincere thanks to you for your continued interest in Visual Studio!
