### ISSUE TITLE
codepage used for \x and \

### ISSUE THREAD

**Issue by j-veidt** [MicrosoftDocs/visualstudio-docs#8932]
It would be nice to mention that \x and \ (octal) also always target unicode characters like \u, independently of the codepage of the file where the search is applied. This is not obvious for values in the range 0x80-0xFF.
Character codes in range 0x90-0xff are identical in Unicode page 0 and windows-1252, but those in 0x80-0x9f are not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@j-veidt We appreciate your feedback. Because the content on this page is based on the logic that's set forth in .NET, we respectfully request that you create a PR for the [Regular Expression Language - Quick Reference](https://learn.microsoft.com/dotnet/standard/base-types/regular-expression-language-quick-reference) page on the .NET content set instead (and to which this Visual Studio page is linked). Meanwhile, we'll close this issue now with our thanks to you for your help with improving the documentation! And also, please know that this GitHub Issue that you filed will stay on record with the Visual Studio page, too.
