### ISSUE TITLE
Will there be documentation for ECMAScript 7 and beyond?

### ISSUE THREAD

**Issue by infinnie** [MicrosoftDocs/visualstudio-docs#894]
I want to see documentation for ES 7 features like `async` and `await` keywords. They have been supported by major browsers and non-browser environments like Node.js. Will there be any plans for that?

**Comment by gewarren** [comment]
@Mikejo5000 can you help with this question?

**Comment by Mikejo5000** [comment]
@liminzhu Limin, do you have any thoughts about this? Thanks.

**Comment by liminzhu** [comment]
Hey @infinnie . In general we're moving towards a direction that instead of keeping our own JS docs, we put effort into helping MDN better ([see blog](https://blogs.windows.com/msedgedev/2017/10/18/documenting-web-together-mdn-web-docs/#MCm7bpygMAFebh66.97)), so going forward you can find all the ES7 content there. We'll keep references to things specific to our implementation (mainly some legacy stuff like ActiveX, we want to interop with others).

**Comment by Mikejo5000** [comment]
Closing, since we won't be doc'ing this info here
