### ISSUE TITLE
Error "Illegal characters in path" - Standalone typescript angular project - (in Visual Studio 2022 17.4.4)

### ISSUE THREAD

**Issue by excellent-1** [MicrosoftDocs/visualstudio-docs#8949]
When adding a standalone typescript angular project to my solution (in Visual Studio 2022 17.4.4) I receive the error "Illegal characters in path" every time.

**Comment by Mikejo5000** [comment]
@excellent-1 I can run the standalone typescript angular project in VS 2022 17.5 Preview 5 without any errors. It sounds like this only happens when you add the project to an already existing solution? To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
