### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by mrbrijeshmishra** [MicrosoftDocs/visualstudio-docs#8997]
I am seeing that bootstrapper of visual studio community version is missing. Add it back I want to create offline installer and I am not able to do it because of your foolishness.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022#download-the-visual-studio-bootstrapper-to-create-the-network-layout)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@mrbrijeshmishra -- thank you for your feedback.  As this is a product issue rather than a documentation issue, please raise it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @anandmeg for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
