### ISSUE TITLE
"code element-level indicators" for Git configurable?

### ISSUE THREAD

**Issue by h-d2023** [MicrosoftDocs/visualstudio-docs#9065]
I consider "code element-level indicators" to be an extremely useful feature: for research, it is very helpful to be able to track only the changes made to a particular method. However, I have not found a way to change the default of 12 months when using Git. Is this configurable somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aeed9cef-8a01-ad6e-36a7-c858ac44c952
* Version Independent ID: 43948287-86e7-cf04-344f-48bb32592e1a
* Content: [Find code changes and other history with CodeLens - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/find-code-changes-and-other-history-with-codelens?view=vs-2022)
* Content Source: [docs/ide/find-code-changes-and-other-history-with-codelens.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/find-code-changes-and-other-history-with-codelens.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@h-d2023 -- thank you for your feedback and questions.  Please consider these resources, and let me know if they help answer:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

**Comment by WilliamAntonRohm** [comment]
@h-d2023 -- thank you for the followup, and my apologies for the delay in responding.  I'm not sure where the `1000` comes from.  If it is a fixed number, please add this issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@TerryGLee -- do you know if there is a settable parameter for the number of changes?

**Comment by TerryGLee** [comment]
@h-d2023 Thanks again for your patience; we are inquiring about this and hope to have an answer for you, soon.

**Comment by TerryGLee** [comment]
@h-d2023 I've checked in with the product team, and they'd like to encourage you to create a feature request that asks for a settable parameter for the number of Git changes. You can do so by using the [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) tool. 

Meanwhile, we'll close this GitHub Issue here, as this venue is meant strictly for documentation issues. We thank you though, for your continued interest in Visual Studio, and also for surfacing something that can help make the product even better, too.
