### ISSUE TITLE
"Group Into" changes positions and "Ungroup" is a bit hard to find

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#911]
I have two overlapping button for test purposes. When I group them, VS moves them to some other location. Is this intentional or a bug?
Ungrouping is a bit painful though. For some types right clicking on one of the elements is enough to see "Ungroup" in the menu. But for others like "ViewBox", I have to get to "Document Outline" and right click on ViewBox to see "UnGroup" menu item. I must ask, is this again intentional or a bug to report?

PS: Thanks, by the way, for replies. I will try editing simple typos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfd1636-a149-bcf7-823f-d2ecf0a0120f
* Version Independent ID: c65af203-fb57-0609-7f12-902bfb497fdd
* Content: [Working with elements in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/working-with-elements-in-xaml-designer#changing-the-an-elements-margins)
* Content Source: [docs/designers/working-with-elements-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/working-with-elements-in-xaml-designer.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz Thanks for this feedback. I'll find out whether it's a bug and let you know.

**Comment by gewarren** [comment]
@diverdan92 Could you comment on these two questions?

**Comment by diverdan92** [comment]
@LyalinDotCom - can you take a look?

@yilmazdurmaz  - can you provide more clear repro instructions for the first issue you mention? What layout element are you grouping the two buttons into? A Grid, StackPanel, Canvas, something else? Also, for these types of issues that appear to be product bugs, I encourage you to [file the issue report directly in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017).

**Comment by gewarren** [comment]
@yilmazdurmaz Thanks for this feedback - it sounds like a bug based on diverdan92's response. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.
