### ISSUE TITLE
Build process for Angular application showing .NET Framework dependency

### ISSUE THREAD

**Issue by ParallaxOW** [MicrosoftDocs/visualstudio-docs#9134]
Our build platform is a Linux container using .NET 6.0 SDK.  I am unable to build the solution created by this process in that platform due to a .NET Framework dependency in the Angular project--which I don't believe I added.  I see the scaffolding is still in Preview, so not sure if the .NET Framework dependency is still a WIP, or not.   Or am I doing something wrong, which is very possible.

**Comment by ParallaxOW** [comment]
This is the error message I receive from running 

dotnet publish -c Release --sc -r linux-musl-x64 . 

MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored /home/rlangel/_source/conaf/webapi/webapi.csproj (in 321 ms).
/usr/share/dotnet/sdk/6.0.403/Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/rlangel/_source/conaf/angularapp/angularapp.esproj]
/usr/share/dotnet/sdk/6.0.403/Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/rlangel/_source/conaf/angularapp/angularapp.esproj]

**Comment by ParallaxOW** [comment]
for clarity -- if needed, this is in reference to 
https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022

**Comment by WilliamAntonRohm** [comment]
@ParallaxOW -- Russ, thank you for your detailed feedback.  This issue appears to be implementation-related, rather than documentation-related.  Please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Mikejo5000** [comment]
@ParallaxOW @name Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
