### ISSUE TITLE
Support for shim of System.Windows.MessageBox

### ISSUE THREAD

**Issue by nhanqv** [MicrosoftDocs/visualstudio-docs#915]
I tried to create Fakes of System.Windows.MessageBox.
But It seems Microsoft Fakes not support System.Windows.MessageBox currently.
Can you tell me why Microsoft Fakes doens't support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b356f491-a828-65ee-915b-b1ccdf71024c
* Version Independent ID: 3fa9dddf-b328-8e2f-c7b2-016a38f71bf6
* Content: [Using shims to isolate your application for unit testing in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing#feedback)
* Content Source: [docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@nhanqv Apologies for the delay in providing you with a response. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

- [https://www.stackoverflow.com](https://www.stackoverflow.com) 

- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
