### ISSUE TITLE
Why no obvious Tools, Options item for using LF as the end of line marker? 

### ISSUE THREAD

**Issue by David-Noble-at-work** [MicrosoftDocs/visualstudio-docs#9152]
WTF? What is your obsession with CRLF? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2642c7f-04bb-56eb-0f26-d867703cf2f4
* Version Independent ID: 9c3f65b2-143b-8053-35ad-866152ea905e
* Content: [Encoding and line break characters - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2022)
* Content Source: [docs/ide/encodings-and-line-breaks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/encodings-and-line-breaks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@David-Noble-at-work -- David, thank you for your questions.  As this issue is product-related, rather than documentation-related, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
