### ISSUE TITLE
"Continue without code" does no longer exists in VS 2022

### ISSUE THREAD

**Issue by uguryuruk** [MicrosoftDocs/visualstudio-docs#9155]
[Enter feedback here]
In the start screen on Visual Studio 2022, I can't see "continue without coding" link. So this section is need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2022)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@uguryuruk -- Ugur, thank you for your feedback.  This behavior is a product issue, rather than a documentation issue.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
