### ISSUE TITLE
Immediate Window unexpected behavior

### ISSUE THREAD

**Issue by desidotnet** [MicrosoftDocs/visualstudio-docs#9194]
This is about Visual Studio 2022 Community edition. According to https://learn.microsoft.com/en-us/visualstudio/debugger/debugging-dll-projects?view=vs-2022 DLL can be debugged with Immediate Window without a calling app, I have been using it for a very long time all the way till using .net framework 4.8.x.  However, when I recently recreated a .net 4.8.6 based C# Class Library project (whole solution) to switch to using .NET 5.0, I started getting a popup window telling me that "A project with an Output Type of Class Library cannot be started directly" and it no longer works like it used to.  Is there a fix for this problem? This was such a handy/heavily used feature while programming a DLL, I need to upgrade to .NET 5.0 but due to the above referenced issue I may have to hold off and keep using .net framework 4.8.6. Please help if you have knowledge on this issue! (For now I have created a dummy calling app, but it takes significant amount of additional time to compile the blank GUI of that dummy project which is of absolutely no use to me, I rather not waste so much compiling time every time I have to make a small change, I have over 140 new DLL calls to implement).

**Comment by WilliamAntonRohm** [comment]
@desidotnet -- Desi, thank you for your thorough feedback.  This repo is solely for documentation, and this issue seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
