### ISSUE TITLE
Question Not Answered

### ISSUE THREAD

**Issue by J4ramos** [MicrosoftDocs/visualstudio-docs#9218]
[Enter feedback here]
The question googled for was "How to record vs code sessions". 
The answer given was for Visual Studio, even though the results link listed vs code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae8a631c-418e-5753-0332-3d24946ba593
* Version Independent ID: 413a5fa1-eecc-efde-381d-55dd78347d27
* Content: [Record Screen and Voice During Tests - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/how-to-include-recordings-of-the-screen-and-voice-during-tests?view=vs-2022)
* Content Source: [docs/test/how-to-include-recordings-of-the-screen-and-voice-during-tests.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/how-to-include-recordings-of-the-screen-and-voice-during-tests.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@J4ramos -- thank you for your feedback.  This issue is not with the documentation, but rather the search engine.  Please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
