### ISSUE TITLE
Advertised information is missing

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/visualstudio-docs#9299]
[Enter feedback here]

The 'parent' page (https://learn.microsoft.com/en-us/visualstudio/ide/user-permissions-and-visual-studio?view=vs-2022) has a link that says you can find out how to run the debugger in VS2022 with elevated privileges. When I click the link and go to the 'child' page (https://learn.microsoft.com/en-us/visualstudio/debugger/debugger-settings-and-preparation?view=vs-2022), I can't see anything about that.

Also, this document is for VS2022 but I searched for VS2017 information. I know this is a Google failing but thought you ought to know. It might be useful to include a link to the VS2017 information, assuming it can be done in VS2017.

- Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0974e6c8-6131-25f5-5837-411ba0d4c1e0
* Version Independent ID: d6c8c133-53b7-984a-cbc1-d5bf2baa1fcf
* Content: [Debugger Settings and Preparation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/debugger-settings-and-preparation?view=vs-2022)
* Content Source: [docs/debugger/debugger-settings-and-preparation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/debugger-settings-and-preparation.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@PatrickRyder -- Patrick, thank you for your feedback.  Please consider these resources, if you haven't already:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@PatrickRyder Thanks for the feedback! I checked some old versions of this page back to 2008 and none of talk about running the debugger with elevated privileges. We do have a remote debugger topic that provides related guidance:
https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging-errors-and-troubleshooting?view=vs-2022

BTW, the VS 2017 version of the page is here: 
https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/debugger/debugger-settings-and-preparation?view=vs-2017

I'll update the link.

**Comment by Mikejo5000** [comment]
There are also a few other scenarios that require running VS as an administrator to debug, such as [Debuggin on a local IIS server](https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2022).

The parent page, https://learn.microsoft.com/en-us/visualstudio/ide/user-permissions-and-visual-studio?view=vs-2022, is really only saying that you need to run VS as administrator when debugging an app with elevated privileges. There isn't really a good link to use here, since the parent page has already said what needs to be said, as far as I can tell. I'm closing this for now, but let me know if there is some specific information you need that is missing.
