### ISSUE TITLE
Dead link http://microsoft.com/piracy/activation.mspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#942]
Found in subscriptions//vs-license-terms.md
The link markdown is also malformed `[microsoft.com/piracy/activation.mspx.[(http://microsoft.com/piracy/activation.mspx)]` should be `[microsoft.com/piracy/activation.mspx](http://microsoft.com/piracy/activation.mspx)`

**Comment by TerryGLee** [comment]
@nschonni Thanks for reporting this; we have this in our queue to fix.
@evanwindom Is this something that you can attend to? It's on the [Visual Studio License Terms](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-license-terms) page. If so, please let us know whence it's fixed by commenting as such in this GitHub Issue.
@prrana FYI.

**Comment by nschonni** [comment]
Oops, fixed in #969 but forgot to link it properly in the commit message
Might be good to fix the redirect though, so I'll leave it open for now.

**Comment by TerryGLee** [comment]
@evanwindom @prrana If this doc is deprecated, we might consider removing it from the repo altogether...

**Comment by TerryGLee** [comment]
All: We've removed the deprecated doc and redirected to a current version of the information. Closing this issue accordingly.
