### ISSUE TITLE
Dead link https://www.microsoft.com/products/ceip/EN-US/privacypolicy.mspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#945]
Found in subscriptions//vs-license-terms.md

**Comment by TerryGLee** [comment]
@nschonni Thanks for reporting this; we have this in our queue to fix.
@evanwindom Is this something that you can attend to? It's on the [Visual Studio License Terms](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-license-terms) page. If so, please let us know whence it's fixed by commenting as such in this GitHub Issue.
@prrana FYI.

**Comment by evanwindom** [comment]
License Terms removed from resources in TOC.  Pending PR.

**Comment by TerryGLee** [comment]
@evanwindom @prrana If this doc is deprecated, we might consider removing it from the repo altogether...

**Comment by TerryGLee** [comment]
All: We've removed the deprecated doc and redirect to a current version of the information. Closing this issue accordingly.
