### ISSUE TITLE
Instruction page is missing instruction

### ISSUE THREAD

**Issue by EFEaglehouse** [MicrosoftDocs/visualstudio-docs#9472]
For the page labeled "Enable or install first-party .NET analyzers", you might want to actually include some instructions on how to enable or install first-party .NET analyzers. Saying only "it's in an SDK or NuGet package" isn't really very useful without those instructions.

The "legacy" code analyzers included with Visual Studio 2019 don't work and configuration is deprecated. All the important information presented about how to disable legacy analyzers or access the new analyzers is very vague.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04393392-f11e-4825-2d02-ba41e6c6d882
* Version Independent ID: c86598c1-1363-d11b-df15-ca32bf970de5
* Content: [Enable or install first-party .NET analyzers - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-net-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/code-quality/install-net-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@EFEaglehouse To clarify a bit, you'd like to see instructions on installing the SDK and on installing the NuGet package? Or a link to those instructions? Thanks!

**Comment by Mikejo5000** [comment]
Adding a sub-section with links to articles on migrating to the .NET analyzers from legacy FxCop and from FxCop. I'm not including steps to install the NuGet package since the SDK is recommended. I'm also adding a phrase indicating that Visual Studio includes the .NET SDK. Unless migration is needed, nothing needs to be done to enable .NET analyzers for .NET 5+ projects in VS 2019 version 16.8 and above.
