### ISSUE TITLE
Dead link https://www.microsoft.com/licensing/product-licensing/products.aspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#948]
Found in subscriptions//TOC.md

**Comment by TerryGLee** [comment]
@nschonni Thanks for reporting this; we have this in our queue to fix.
@evanwindom Is this something that you can attend to? It's the "Volume License and Product Use Rights (PUR)" link in the Resources section of the TOC. If so, please let us know whence it's fixed by commenting as such in this GitHub Issue.
@prrana FYI.

**Comment by evanwindom** [comment]
Changed link in TOC to point to a new licensing terms page.  Added to PR.
