### ISSUE TITLE
Section "Set a working directory" is a bit confusing

### ISSUE THREAD

**Issue by CarolinaB-visiba** [MicrosoftDocs/visualstudio-docs#9497]
Hi!

Just got started on this excellent introduction. thank you for publishing it!
I noticed some indiscrepancies regarding the "python3" folder instructions. I am using the provided tutorial material and there is no python3 folder. Also missing is matching settings in the json example provided on the page, setting the working folder to python3.

I am quite sure I get this anyway, but I wanted to highlight this for you in service of others that might find this confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfaa1bb6-20e0-dadf-7b12-30fa947c520e
* Version Independent ID: 87b861c0-0a08-f6fd-6fa2-9117e853dbbc
* Content: [Quickstart - Open a Python code folder - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/quickstart-05-python-visual-studio-open-folder?view=vs-2022)
* Content Source: [docs/python/quickstart-05-python-visual-studio-open-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/quickstart-05-python-visual-studio-open-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@CarolinaB-visiba -- Carolina, thank you for your kind words and suggestion.

@cwebster-99 -- Courtney, please look into this issue.

**Comment by cwebster-99** [comment]
Thank you for the feedback. It looks like the repo has changed and the python3 subfolder is no longer in the main branch. In this case, I edited the paragraph to read as a hypothetical scenario rather than one you should be actively recreating if you are following along with the given repo. The hope is that the scenario is specific enough for those who are in this situation and need to configure their working directory.  #please-close
