### ISSUE TITLE
rename/move instead of copy possible for None's?

### ISSUE THREAD

**Issue by pjljvandelaar** [MicrosoftDocs/visualstudio-docs#9565]
[Enter feedback here]
Test resources of analysers can confuse tools (e.g., a test.vsproj is discovered as a project within the solution instead of just being a resource).
A solution is to use changed extensions, like vsproj_.
We would like to change these extensions back to have the test case as similar to the real situation as possible.

The documentation is not clear enough whether that is possible or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97e663f7-3bac-61af-28bb-f0e471dcdca6
* Version Independent ID: 97985f56-e0ac-a03d-f651-b86cc2b85804
* Content: [Common MSBuild Project Items - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022)
* Content Source: [docs/msbuild/common-msbuild-project-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/common-msbuild-project-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@pjljvandelaar -- thank you for your feedback.  Please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
@pjljvandelaar 
Have you tried implementing your idea and run into problems?  In general, documentation can't cover all the possible scenarios, but if you can narrow your inquiry down to some details that we could either confirm or disconfirm, I could possibly update this document.

**Comment by ghogen** [comment]
@pjljvandelaar 
I think anything is possible, since MSBuild is very flexible.

I would imagine you could use the Copy or Move task in which the SourceFiles are given as an item group (could be @None or a custom group you define via ItemDefinitionGroup just for this purpose) and DestinationFiles, where the item group for Destination Files would be constructed by an item transform done by modifying the %Extension metadata of the None collection. If I have time, I might work up an example to test this idea.

Copy task - https://learn.microsoft.com/en-us/visualstudio/msbuild/item-definitions?view=vs-2022
Move task - https://learn.microsoft.com/en-us/visualstudio/msbuild/move-task?view=vs-2022
ItemDefinitionGroup - https://learn.microsoft.com/en-us/visualstudio/msbuild/item-definitions?view=vs-2022
MSBuild items - https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2022
Item metadata - https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2022
Transform item list using metadata - https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2022#BKMK_Transforming

**Comment by ghogen** [comment]
This code takes all the None items and copies them to the output folder, with an _ appended to the extension. Perhaps you can adapt it to your situation.

`	<Target Name="RenameNones" AfterTargets="Build">

		<ItemGroup>
			<SourceFile Include="@(None)" />
			<DestinationFile Include="@(SourceFile->'$(OutDir)\%(Filename)%(Extension)_')" />
		</ItemGroup>

		<Copy SourceFiles="@(SourceFile)"
			  DestinationFiles="@(DestinationFile)"
			  SkipUnchangedFiles="true" />
	</Target>
`

**Comment by ghogen** [comment]
I think it would be preferable to create a custom ItemDefinitionGroup for this purpose rather than reusing the 'None' item type which would enable you to set this as a Build Action in Visual Studio only for the project files you need this behavior on.  The way to get a custom item type to appear in VS is by using AvailableItemName - https://learn.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2022#additional-build-actions

**Comment by pjljvandelaar** [comment]
@ghogen 
Indeed, anything is possible, since MSBuild is more flexible than I was aware.

Your list with relevant pointers and the examples have helped tremendously.

It is always a challenge to get the right information and pointers in a document without overwhelming the reader with too much details. For me, some of the provided information could/should have been integrated in the documentation.

Thanks for your time!
