### ISSUE TITLE
Installing with commands produces error

### ISSUE THREAD

**Issue by nymbols** [MicrosoftDocs/visualstudio-docs#960]
Running the installation with all the commands in step 3 produces an error (At most one command parameter can be specified.) Running just the exe is sufficient to install ONLY what is in the layout folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nymbols Thanks for your feedback; we'll investigate this and make changes to the document as necessary.

**Comment by TerryGLee** [comment]
@nymbols Thanks again for your input. We've changed our site architecture since this GitHub Issue was originally posted, and so the page you referenced now redirects to [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017). On this page, we say the following in "Step 3: Install Visual Studio from the local cache" -- "To make sure that you install only the files that you've previously downloaded, use the same command-line options that you used to create the layout cache."

If you find still that running the command as per the example in Step 3 (or in any of the other steps) on the updated page still produces an error, please let us know via a new GitHub Issue. Meanwhile, we'll close this one as it refers to a page that's been deprecated.

Thanks,
~ Terry
