### ISSUE TITLE
Document does not include enough information

### ISSUE THREAD

**Issue by BSarmady** [MicrosoftDocs/visualstudio-docs#9642]
I want to create an offline layout that only includes X64 architecture en_US  language. after 26 hours of downloading, I have a 50GB 
that has all the languages and architectures (ARM, X86 and X64) that also includes professional, enterprise and community editions.

1- How do I choose which version of visual studio I want to create layout for?
2- How do I choose which architecture of visual studio I want to create layout for (ARM, X86, X64)?
3- How do I choose which product to download?
4- How do I remove a language from existing offline layout?
5- How do I update the existing offline layout?
6- What are command line parameters for the vs_setup.exe (no matter how I run it, it shows a download GUI, then a second console window and then immediately closes)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@BSarmady -- Bob, thank you for your feedback.  Please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@anandmeg -- Megha, please look into this issue.

**Comment by christineruana** [comment]
Hi @BSarmady  - Can you please look at this page for instructions for how to [create a layout](https://learn.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio)? I'm pretty sure that it will answer all the questions you posted above regarding syntax, language, version, product, etc. This page is similar to the "Create an offline install" page that you asked this question on, but it's more comprehensive.   I added an "Important Note" at the top of the "Create an offline installation page" that points to the create-a-network-layout page, but you may not have seen it. 

If you still have questions after reading above, please feel free to re-ask.  

Thanks,  Christine

**Comment by BSarmady** [comment]
Thank you @christineruana for the reply and help,.

Linked document answers 1,3 and 5 completely but still doesn't answer 2 and 4. and 6 is partially answered.

I have downloaded the Language again using the command line specifying the en_US but layout still includes more than 8 languages for some components. probably they do not follow specified parameter?

Also still ARM, X86 and X64 components are all downloaded, Document does not specify if I still require all architectures for installation even if installing system is X64.

for 6, running the executable from command line with /? doesn't show a help screen (just runs the setup). Rest of Microsoft applications will show a list of command option, which helps me to find my answers by searching through documents with name of command line parameter.

**Comment by anandmeg** [comment]
#reassign:@christineruana

**Comment by christineruana** [comment]
Hi @BSarmady,

For #2 - there's an --arch parameter you can use to create a layout and specify which binaries to include.  x64 is the default for VS 2022, and you can choose to add in ARM binaries for applicable workloads.  This is documented in the [command line online docs](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022).  

Regarding #4 - there are various way we handle localization within Visual Studio.  Some components implement localization in a single file, so all localized resources for all languages are packaged together.  Other components have a separate resource file per locale.  If you're noticing that some components have locales other than English, it's probably because all their localized resources are contained in one file.  Also, as a general rule, there's no way to "remove" anything from a layout.

Regarding #6 - our response to "setup.exe -?" could use some improvement.  Please feel free to open a [developer community problem report](https://aka.ms/vs/admin/feedback) about this and we'll get it on the backlog.  Hard to make changes like this until there's an official record of people asking for it.   Also, at best we would have this content point to the online documentation which I linked to above.  

Hope this additional information helps.  LMK if you have any further questions.

**Comment by j-martens** [comment]
Thank you for your question. We will not proceed to close the issue. #please-close
