### ISSUE TITLE
$if$

### ISSUE THREAD

**Issue by elchido** [MicrosoftDocs/visualstudio-docs#968]
Where is $if$ documented? I want to use something like:

$if$ ($targetframeworkversion$ >= 3.5)using System.Linq;  
$endif$using System.Text;  

but what kind of expression can be written in the $if$? What's the syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* Content: [How to: Use Wizards with Project Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates)
* Content Source: [docs/extensibility/how-to-use-wizards-with-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
