### ISSUE TITLE
No indication that \s does not work the same as in .NET regexes

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/visualstudio-docs#973]
https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio

In standard .NET regular expressions, `\s` matches any type of whitespace. Thus the following regex:

```
if\s*\((?<condition>.+)\)\s*Assert\.Fail\((?<message>".*")\);
```

matches:

```
if (someCondition)
    Assert.Fail("message");
```

But in Visual Studio 15.7.1 this matches nothing, while the following regex does work in VS (and in .NET):

```
if\s*\((?<condition>.+)\).*\r?\n.*Assert\.Fail\((?<message>".*")\);
```

However, that regex does *not* match the following, while the one with `\s` does:

```
if (someCondition)

    Assert.Fail("message");
```

It thus seems that `\s` in VS means "match whitespace **excluding line breaks**", and the documentation should be updated to reflect this, as well as explaining how to get the same effect.

**Comment by gewarren** [comment]
@iankemp I tried this out and agree it looks like there's a bug here. Can you log a bug at Developer Community? This is what I found:

In Visual Studio, `\s` seems to match carriage returns *only in certain cases*. Consider the following text:

```
            if (someCondition)
                5
Assert.Fail("message");

            if (someCondition)

                5

Assert.Fail("message");
```

This regex does not match either `if` statement: `if\s*\(someCondition\)\s*5\s*Assert\.Fail`

But this regex matches both: `if\s*\(someCondition\)\r\s*5\s*Assert\.Fail`

To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
