### ISSUE TITLE
Not Offline, 

### ISSUE THREAD

**Issue by syedrashid47** [MicrosoftDocs/visualstudio-docs#980]
vs_Enterprise.exe --layout c:\vs2017layout --lang en-US

this downloads the installer not the actual packages, 
only 67 mb downloaded,  and when you start install it requires internet access, 
I DO NOT HAVE INTERNET ACCESS AT MY HOME>
HOW CAN I INSTALL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network#feedback)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by xm574** [comment]
Hi, True.. please provide a solution as it is impossible to install the tool on a restricted network.
I have created the layout folder from a computer with internet access.. moved it to a computer with limited access and executed the installation.. then I had these message:
"Give us a minute...."
"Unable to download installation files. Check your internet connection and Try again".
It is supposed to be the OFFLINE installation!!

**Comment by speeder990** [comment]
Hi, Downloading the Community version right now, No problems seems to present. You did get your spaces right, right? As for the installation, install security certificates provided, then execute the installer inside the cache folder.  You may need Internet connection for Android SDKs though.  Microsoft please confirm this as I have not installed Android development since last year I guess.

**Comment by pcchannz** [comment]
The vs2017layout folder is not created upon running the command

vs_community.exe --layout c:\vs2017layout --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Component.GitHub.VisualStudio --includeOptional --lang en-US

Am I missing something? Thanks

**Comment by ciphernemo** [comment]
I just discovered a shortcut as well to include everything: --allWorkloads

Also, the examples use --includeOptional but they don't use --includeRecommended ... both should be used according to the installer's command options help.

**Comment by ciphernemo** [comment]
Wow, the vs installer is broken, or the help provided for it is broken. One of the two. Because...

--includeOptional does NOT include recommended as well and,
--includeRecommended does NOT include optional, yet,
both --includeOptional and --includeRecommended together do not work, and will pick the first option you use.

WTF, Microsoft? I'm going to have to experiment more with this myself, because this guide is wrong AND your official knowledge base articles are wrong. I will post a new top-level comment here when I find out exactly what does and doesn't work. Frustrating. On that note, I'm approaching this from a deployment perspective, trying to roll VS 2017 into an MDT deployment of Windows 10.

**Comment by ciphernemo** [comment]
One solved so far:

The -all option will install EVERYTHING, all workloads, all components

The -allWorkloads option will install all workloads and components, but NOT install any recommended or optional components.

So this article is correct: https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio

**Comment by ciphernemo** [comment]
It looks like there's no way to automatically install BOTH optional and recommended components of any workload through the command line options. Either you use -installOption to install optional and NOT recommend, -installRecommend to install recommended and NOT optional, or neither to perform the exact same function as -installRecommend. This seems broken.

The only workaround I see is to not include either option, then manually --add all optional components of each workload. That seems clunky and not-as-intended, but it's the only way that seems to work. Why did Microsoft screw this up so royally?

**Comment by TerryGLee** [comment]
@syedrashid47 Thanks for your feedback. And @ciphernemo, @speeder990 - Thanks for posting solutions. 👍
