### ISSUE TITLE
How can I download projects from TFS

### ISSUE THREAD

**Issue by sarmisen** [MicrosoftDocs/visualstudio-docs#981]
Hi

Just installed TFS addon for Visual Studio Community 2017 for mac.

I've already managed to connect to my remote TFS and to map it to a local folder. Already through the most difficult part.

However I don't see how to download last version from remote version to local workspace. In windows it would usually be right click and you'd see a contextual menu with all the version control features (Get latest version, view history...). But I can't find these options in my Mac. I've tried it all (Option + Click, cmd + click) with no luck. Can you help me?

Kind regards.

Sergio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by lclaytont** [comment]
I find the documentation about checking in changes to be lacking. I alter a file and it lists the pending change in the source control explorer under the file. To get an option to check that in I have to go to the exact file rather than the parent solution or project file. And when I do check in I get a checked in message in the VC pallet - but then it never updates in either TFS or in my version control explorer.
