### ISSUE TITLE
.NET 8 Method in example

### ISSUE THREAD

**Issue by KircMax** [MicrosoftDocs/visualstudio-docs#9829]
I was trying to search for an example on how to use a method and call that one easily in the Program.cs - that I could not find.
Because the Program.cs seems to only contain the 'plain code to be executed' - do I get that right?
Then of course that example wouldn't make sense.
Still then I don't think this example provides best practice code to just put everything into the Program.cs... I'd then prefer the code to really be moved into a class and call that one there, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Version Independent ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Content: [Tutorial: Create a simple C# console app  - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@KircMax, thanks for your feedback. The section [Revise the code](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022#revise-the-code) in the article revises the code to create two classes (Calculator and Program), rather than rely on the program class to handle all the code. The initial part of the article is introducing a new user to adding C# code for a basic app and then shows how to revise and restructure the code.
[Part 2: Extend C# console app](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022) of the tutorial, shows how to add an additional project and create methods.

Hope this helps! Please let us know if the above doesn't answer your question. Thanks!

**Comment by anandmeg** [comment]
@KircMax, thanks again for your feedback. Closing this issue now, but please reopen if the above response doesn't help or answer your question, or if have any additional questions. Thanks!
