### ISSUE TITLE
addedExtension and pathSegment Examples are Blank

### ISSUE THREAD

**Issue by emu7800** [MicrosoftDocs/visualstudio-docs#9836]
The code examples for addedExtension and pathSegment in .filenesting.json are blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by ghogen** [comment]
@emu7800 
The addedExtension element always appears empty because it always applies to all extensions, as the note in that section indicates. The pathSegment example is also empty here, because that is an example of applying to all cases, but the note gives an example where it's more specifically targeted.

I think we can close this issue, and I hope this clarifies the behavior and the reason for the apparently empty sections of code. Thanks for the question!
